pulp/pulp

- bindings/pulp/bindings/server_info.py
- common/pulp/common/constants.py
- docs/dev-guide/integration/rest-api/status.rst
- docs/user-guide/release-notes/2.6.x.rst
- server/pulp/server/async/scheduler.py
- server/pulp/server/async/worker_watcher.py
- server/pulp/server/managers/resources.py
- server/pulp/server/managers/status.py
- server/pulp/server/webservices/controllers/status.py
- server/test/unit/server/async/test_scheduler.py
- server/test/unit/server/async/test_worker_watcher.py
- server/test/unit/server/managers/test_resources.py
- server/test/unit/test_manager_factory.py
- server/test/unit/test_status_controller.py
- server/test/unit/test_status_manager.py
This patch returns additional data from the /status API call. Specifically, it
returns a worker list, the message broker connection status, the database
connection status, and the Pulp version (RHBZ #704184).
There is a small behavior change to include the resource manager and scheduler
as part of the worker heartbeat list. Previously, these were not included in
the list. These entries are filtered out when Pulp requests a free worker.
A few PEP8 fixes are included as well for files that were touched in this patch.
Additionally, the `ping()` method in ServerInfoAPI has been removed; this
called a URL that no longer exists.
> Updates to /status API

- deps/python-kombu/python-kombu.spec
Require python-unittest2 >= 0.8.0 when building on Fedora 21 or greater. This
is related to https://bugzilla.redhat.com/show_bug.cgi?id=1161166.
> Conditionally require python-unittest2 >= 0.8.0

- run-tests.py
This commit adds support for flake8 to run-tests.py. It currently only
checks the files that I've already made sure were PEP-8 to catch PEP-8
regressions.
> Run flake8 in run-tests.py.

- server/test/unit/test_status_manager.py
This test broke when qpid was not running, due to an improper mock.
> fix a broken unit test

- server/pulp/server/async/tasks.py
- server/test/unit/server/async/test_tasks.py
https://bugzilla.redhat.com/show_bug.cgi?id=1179463
The issue was that strip() treats the string passed into it as an iterator, which was stripping extra characters on hostnames that end in 'd', 'q', or '.'. The incorrect resultant queue name caused the task dispatched to not go to the correct worker.
> Fixes the mutation of queue name to get it right on all hostnames

- server/pulp/plugins/conduits/mixins.py
- server/test/unit/test_conduit_mixins.py
The fix for 1171278 in pulp_rpm needs to be able to find a unit based on the
unit key, regardless of which repo its in. This patch adds
`find_unit_by_unit_key` to the SearchUnitsMixin to facilitiate this.
> 1171278 - additional helper method for finding units

- deps/python-nectar/python-nectar.spec
[BZ-1174283](https://bugzilla.redhat.com/show_bug.cgi?id=1174283)
This change already [exists in nectar](https://github.com/pulp/nectar/blob/master/python-nectar.spec#L19), but it needs to be copied over to the pulp deps for building.
> 1174283 - bump python-requests to 2.4.3

- client_lib/pulp/client/extensions/exceptions.py
- client_lib/test/unit/client/extensions/test_exceptions.py
- server/pulp/server/managers/repo/distributor.py
- server/test/unit/test_repo_distributor_manager.py
Pulp caught exceptions (Exception) and then reraised as a PulpDataException. Additionally, errors are sometimes thown that contain other errors inside e.extra_data. This information was thrown away and could not be used.
Solution renders all error data recursively and allows the exception to bubble up rather than reraising as a different exception.
Reopened from https://github.com/pulp/pulp/pull/1392
This is necessary for the right information to get back to the user after we merge https://github.com/pulp/pulp_docker/pull/52
> do not throw exception information away

- server/etc/default/upstart_pulp_celerybeat
- server/etc/rc.d/init.d/pulp_celerybeat
- server/usr/lib/systemd/system/pulp_celerybeat.service
https://bugzilla.redhat.com/show_bug.cgi?id=1172745
Issue consisted in the fact that celerybeat was using the unconfigured
celery app. That's why the broker string was incorrect. By adding --app
option it will use the configured app and the startup info will be correct.
> 1172745 - celerybeat service incorrectly reports broker on startup.

- docs/conf.py
Backported from https://github.com/pulp/pulp/pull/1362.
This change uses the sphinx_rtd_theme if it is installed, otherwise it uses the default. This makes it simpler to make docs changes in 2.6.
The theme is available with pip:
pip install sphinx_rtd_theme
> add read the docs theme to sphinx

- docs/dev-guide/integration/rest-api/role/cud.rst
The permissions on roles are handled in a different API now. This doc change
points people to the correct doc if they are updating permissions.
> 1066022 - update role doc to remove mentions of permissions

- server/pulp/server/auth/authorization.py
- server/pulp/server/db/migrations/0012_role_schema_change.py
- server/pulp/server/managers/auth/role/cud.py
- server/pulp/server/webservices/controllers/roles.py
- server/test/unit/server/db/migrations/test_migration_0012.py
Allows the use of resources that contain a '.' in role permission definitions
[BZ-1099649](https://bugzilla.redhat.com/show_bug.cgi?id=1099649)
> 1099649 - Allow '.' in role resource permissions

- deps/gofer/dist_list.txt
This dep is provided by upstream Fedora (yay!)
> Remove fc21 from gofer builds

- .gitignore
Rope is a tool used by vim/emacs for refactoring and ensuring imports. I use this, and would like it in the gitignore.
> add ropeproject to gitignore

- server/test/unit/server/agent/test_context.py
This unused import causes run-tests.py to fail on master.
> Remove an unused import in a test.

- pulp.spec
- server/pulp/server/agent/direct/services.py
- server/test/unit/server/agent/direct/test_services.py
Fixes a variety of pulp 2.6 / gofer 2.4 integration issus:
- agent plugin not being installed in site-packages.
- pulp needs to explicitly declare the pulp.task queue (not longer implicitly created by gofer consumer)
- need to use the get_url() *workaround* when starting the reply consumer.  get_url() goes away in 3.0.
> Fix agent plugin packaging.

- server/etc/pulp/server.conf
https://bugzilla.redhat.com/show_bug.cgi?id=1165403
> 165403 - deprecated cacert and cakey settings from server.conf

- server/pulp/server/webservices/controllers/repositories.py
- server/test/unit/server/webservices/controllers/test_repositories.py
https://bugzilla.redhat.com/show_bug.cgi?id=1078833
Furthermore, deleting an importer now requires the
DELETE permission instead of the UPDATE permission.
> 1078833 - Updating and deleting importers now returns 404 when appropriate.

- server/etc/rc.d/init.d/pulp_celerybeat
- server/etc/rc.d/init.d/pulp_workers
The previous fix for RHBZ #1145723 did not work properly for freshly installed
systems with more than one Pulp worker. In these cases, only the last log file
would get its permissions set properly because the ``chown`` command was done
outside of the loop over each worker.
This patch moves the ``chown`` inside the loop. I also moved it above the log
file writing operation in a few other places to make the ``chown`` command more
obvious.
> 1145723 - touch and chown log file before writing to it

- deps/python-kombu/1182322.patch
- deps/python-kombu/python-kombu.spec
There is an error string we did not handle correctly when PLAIN sasl mech was
used, python-saslwrapper was installed, and cyrus-sasl-plain was *not*
installed.
This patch contains a patch to Pulp's python-kombu to handle this scenario.
> 1182322 - handle case where PLAIN is used with saslwrapper

- server/pulp/server/auth/authorization.py
- server/pulp/server/webservices/controllers/decorators.py
- server/test/unit/server/auth/test_authorization.py
- server/test/unit/server/webservices/views/base.py
This PR will allow auth_required statement able to easily have assertions made about them.
Docs on how to use this can be found here:  https://fedorahosted.org/pulp/wiki/ReplacewebpywithDjango#UnitTesting
> Make auth required easy to mock

- server/pulp/server/webservices/urls.py
- server/pulp/server/webservices/views/plugins.py
- server/test/unit/server/webservices/test_urls.py
- server/test/unit/server/webservices/views/test_plugins.py
Creates a skeleton for all of the plugin urls to be converted to django. Each url branch will branch from this to prevent merge conflicts.
> create base for plugins view module

- deps/external_deps.json
In the past we had to tag pulp-docker and python-crane in manually to the
correct koji tag. This is a step that was frequently forgotten.
Instead, use external-deps.json which automatically pulls the correct versions
into the specificed tag.
> update external deps file for docker and crane

- server/pulp/server/initialization.py
- server/pulp/server/maintenance/monthly.py
- server/test/unit/server/managers/schedule/test_utils.py
https://bugzilla.redhat.com/show_bug.cgi?id=1184187
**The Problem**
At test run time, unexpected calls to db.connection.initialize() will read the production database. This wasn't a problem before, but with commit 70274cf9be047708da930b25f93c9d3f4feb7f78 mongo starts to cache the most recent call to mongoengine.connect() as the working 'default' database. This effectively ties the tests to the production DB once one of these unexpected calls to db.connection.initialize() occurs. The unit tests liberally drop collections which causes the production database to be dropped.
**The Solution**
In the case of initialization.py, having the db.connection.initialize() call occur at the method level instead of the module level provides the connection when it is needed for production code while the …
> 1184187 - Causes all platform tests to use pulp_unittest

- pulp.spec
https://bugzilla.redhat.com/show_bug.cgi?id=1183700
This will cause pulp-server to overwrite the pulp_celerybeat, pulp_workers, and pulp_resource_manager Upstart scripts. I tested rebuild Pulp with this new spec file and the build worked.
> 1183700 - Update pulp.spec to overwrite Celery related init scripts

- server/test/unit/server/webservices/views/test_util.py
This test was skipped because the __init__.py was missing.
> create __init__.py in views and fix unit test

- agent/pulp/agent/gofer/pulpplugin.py
- agent/test/unit/test_agent.py
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1159303
In the past, the agent determined consumer registration based on the existence of a valid consumer certificated.  When unregistered from the consumer, the certificate is deleted which is detected by the agent.  When a consumer is unregistered from the server and the agent is running, the server sends the agent notification of the un-registration and the agent deletes the certificate.  Because were never deleting the agent queue, the agent would always get this notification.  However, in the sprint, we plan to have the server delete agent queues after un-registration.  This opens the door for the case that the agent is not running on un-registration so it never gets the notification.  When it starts, the certificate will still …
> agent validate registration using rest api.

- server/selinux/server/pulp-celery.te
https://bugzilla.redhat.com/show_bug.cgi?id=1186420
Gives read permissions to all cert_t certs. Usually certs are kept with cert_t anyway so Celery should be allowed to read them.
> 1186420 - reading cert_t for custom SSL config

- server/selinux/server/pulp-celery.te
This fixes my previous commit. I've tested this on RHEL6 and RHEL7. Modern
Fedoras should go well as well.
> 1186420 - fixed reading cert_t for custom SSL config

- server/etc/rc.d/init.d/pulp_celerybeat
- server/etc/rc.d/init.d/pulp_workers
https://bugzilla.redhat.com/show_bug.cgi?id=1183706
See [this comment](https://bugzilla.redhat.com/show_bug.cgi?id=1183706#c2) for the rationale behind removing the check.
> 1183706 - Remove permission check from upstart celery scripts

- server/pulp/plugins/util/publish_step.py
pre-existing unit metadata, and how to avoid that.
re #101 
https://pulp.plan.io/issues/101
> Documenting a quirk of this function that could lead to clobbering

- deps/external_deps.json
This way, they can be included in the 2.6 betas.
> Add the Python plugins to external deps.

- docs/user-guide/release-notes/2.6.x.rst
https://bugzilla.redhat.com/show_bug.cgi?id=1185937
> 1185937 - add release note for python-gofer-amqplib discontinued.

- pulp-dev.py
I missed this file during my testing of the repo-auth patch.
> fix broken pulp-dev.py

- docs/user-guide/release-notes/2.6.x.rst
https://bugzilla.redhat.com/show_bug.cgi?id=1190794
I manually rebuilt the docs with the RTD sphinx theme and it this change fixed it.
> 1190794 - Fixes release note formatting on 2.6.0 release note

- devel/pulp/devel/test_runner.py
- server/pulp/server/managers/auth/cert/certificate.py
Print messages before starting flake8 and the unit tests to make it easier to follow the jenkins log files
> Print helpful messages before starting the flake8

- server/pulp/server/db/connection.py
- server/test/unit/server/db/test_connection.py
This commit also fixes several unit tests that were assuming that the database was
local and unauthenticated.
> Do not log the length of the database password.

- server/pulp/server/webservices/views/util.py
- server/test/unit/server/webservices/views/test_util.py
https://pulp.plan.io/issues/149
> Create 1.4 compatible HttpResponseRedirect object.

- pulp-dev.py
The /var/cache/pulp directory is now owned by apache
> Fixed dev install script

- pulp.spec
- server/pulp/server/agent/direct/pulpagent.py
- server/pulp/server/managers/consumer/agent.py
- server/test/unit/server/agent/direct/test_agent.py
- server/test/unit/server/managers/consumer/test_agent_manager.py
https://bugzilla.redhat.com/show_bug.cgi?id=1159303
The NotFound exception is new in gofer 2.5 which contains support for amqp 1.0 (proton).  We can delay merging until that work is complete and gofer 2.5 is released.
> 1159303 - delete agent queues on consumer unregistration.

- server/pulp/plugins/conduits/unit_import.py
- server/test/unit/test_unit_import_conduit.py
do_get_repo_units() supports `as_generator` but previously we were unable to
pass this in via get_source_units.
> 1185868 - allow as_generator to be passed in to get_source_units 

- server/selinux/server/pulp-celery.te
Some puppet modules have symlinks.  celery_t context needs to have
permissions to manage creation and removal of symlinks.
> BZ1182760 - Add proper SELinux rules for PuppetInstallDistributor

- server/test/unit/server/managers/content/test_upload.py
I noticed after merging one of my PEP-8 PRs that due to other changes in master, my merge introduced a failure. I usually run the tests before pushing merges, but this time I forgot, and it bit me!
> Fix a failing PEP-8 test.

- server/pulp/server/webservices/controllers/consumer_groups.py
- server/pulp/server/webservices/controllers/contents.py
- server/pulp/server/webservices/urls.py
- server/pulp/server/webservices/views/consumer_groups.py
- server/pulp/server/webservices/views/content.py
- server/test/unit/server/webservices/test_urls.py
- server/test/unit/server/webservices/views/test_consumer_groups.py
- server/test/unit/server/webservices/views/test_content.py
- server/test/unit/test_contents_controller.py
GET /pulp/api/v2/consumer_groups/ http://fpaste.org/184316/67088614/
POST /pulp/api/v2/consumer_groups/ http://fpaste.org/184326/67157314/
POST missing required param /pulp/api/v2/consumer_groups/  http://fpaste.org/184318/36710061/
POST invalid param /pulp/api/v2/consumer_groups/  http://fpaste.org/184320/36711661/
GET /pulp/api/v2/content/uploads/ http://fpaste.org/184323/71301142/
POST /pulp/api/v2/content/uploads/ http://fpaste.org/184324/67144414/
> Adding back urls deleted because of compatibility issues.

- agent/setup.py
- bindings/setup.py
- client_admin/setup.py
- client_lib/setup.py
- common/setup.py
- comps.xml
- nodes/child/setup.py
- pulp.spec
- server/setup.py
This commit also removes some incorrect Requires lines in our spec file, and adds
python-gofer-qpid to our server qpid group.
https://pulp.plan.io/issues/278
re #278
This is necessary to satisfy Travis in https://github.com/pulp/pulp_python/pull/20
> Add install_requires arguments to our setup.py files.

- docs/dev-guide/integration/events/amqp.rst
- docs/dev-guide/integration/events/email.rst
- docs/dev-guide/integration/events/http.rst
- docs/dev-guide/integration/events/index.rst
- docs/dev-guide/integration/events/repo-action-events.rst
- docs/user-guide/release-notes/2.7.x.rst
- server/pulp/server/async/emit.py
- server/pulp/server/config.py
- server/pulp/server/db/model/base.py
- server/pulp/server/db/model/dispatch.py
- server/test/unit/server/async/test_emit.py
- server/test/unit/server/db/model/test_dispatch.py
This patch adds new functionality to emit event notifications when TaskStatus
objects are changed. This relies on mongoengine's ``signals`` library; when a
TaskStatus is updated we publish a message.
re #87
> Emit event notifications when TaskStatus is saved or updated.

- server/setup.py
Pulp_python unit tests were emitting error messages due to this dep being
missing. Blinker is needed for mongoengine signals to work.
> Add blinker dependency to setup.py

- docs/sphinx/dev-guide/contributing/branching.rst
- docs/sphinx/dev-guide/contributing/bugs.rst
- docs/sphinx/dev-guide/contributing/merging.rst
This PR will get merged forward to 2.5-release -> 2.5-testing -> 2.5-dev -> 2.6-dev -> master. I'm also manually going to merge this into 2.6-testing -> 2.6-dev -> master.
That will not introduce anything except this commit and its resolved conflicts into 2.6-dev because the parent of this commit is the merge-base for 2.5-release and 2.6-testing. That means it's the most recent commit that is in the history of both 2.5-release and 2.6-testing so any commits onto the branch (ie: this one) will only bring in the expected commit to both release streams.
> Updates bug docs to point users to Redmine

- server/selinux/server/uninstall.sh
The `uninstall.sh` script was removing two `.if` files which were also
controlled by RPM. These should only be cleaned up by RPM itself.
re #554
> Fix error during pulp-selinux uninstall

- docs/sphinx/user-guide/nodes.rst
[redmine-655](https://pulp.plan.io/issues/655)
> closes 655, fix typo in nodes auth

- server/pulp/server/logs.py
If `/dev/log` doesn't exist, don't try to use it. Instead, print a helpful message and exit.
Closes: https://pulp.plan.io/issues/639
> gracefully handle no dev log for pulp-manage-db, closes 639

- docs/dev-guide/contributing/dev_setup.rst
- playpen/dev-setup.sh
Since we now use flake8 in the tests, it is a dep for developers.
closes  https://pulp.plan.io/issues/300
> add flake8 to dev setup

- deps/external_deps.json
Plugins will be assembled via the ci tooling in pulp_packaging, no need for them to be listed in the external deps anymore
> Remove plugins that are part of pulp from the external deps

- client_lib/pulp/client/extensions/core.py
- client_lib/pulp/client/launcher.py
Using an ssh client to execute pulp-admin commands caused a traceback if `wrap_to_terminal` in  `/etc/pulp/admin/admin.conf` was set to `true`. There is no way to get the terminal size in this case because the command is being run without a tty device, so we should fall back to the `wrap_width` specified in `admin.conf`
> fallback to config wrap width when unable to access tty size, closes 335

- server/pulp/server/managers/content/upload.py
- server/test/unit/server/managers/content/test_upload.py
(as mentioned in docs)
closes [636] (https://pulp.plan.io/issues/636)
> 636 - API delete nonexisting upload_id now returns 404

- server/etc/rc.d/init.d/pulp_celerybeat
- server/etc/rc.d/init.d/pulp_workers
This commit updates our Upstart init scripts to call stop_workers and
then start_workers, instead of restart_workers(). There seems to be an
issue with Celery multi, restarting, and Pulp. This commit works around
that issue by fully stopping the workers instead of issuing a restart to
them.
https://pulp.plan.io/issues/686
closes #686
> Upstart use stop/start instead of restart_workers.

- agent/pulp/agent/gofer/pulpplugin.py
- agent/test/unit/test_agent.py
re:#734
The asynchronous attach (using a thread) was designed to prevent the pulp plugin *initializer* from blocking the loading of other plugins if the registration validation was blocked.  The problem with doing this is that - when there are pending requests, the gofer scheduler will attempt to dispatch to a plugin that has not completely loaded.  This fails.  So, this PR goes back the synchronous way of doing things (except the addition of making the API call.
This matches changes made to the Katello agent.
Gofer 2.6+ provides for more alternatives here but for now, we need to do this.
If gofer survives the chopping block, I will suggest a few things to clean up the pulp agent:
- Refactor the pulpplugin.py into several modules (something like):
- plugin.py (remote API)
- auth.py …
> Synchronous agent attach to prevent race conditions.

- pulp.spec
- server/etc/default/upstart_pulp_celerybeat
- server/etc/rc.d/init.d/pulp_workers
- server/pulp/server/async/manage_workers.py
- server/selinux/server/pulp-celery.fc
- server/selinux/server/pulp-celery.te
- server/usr/lib/systemd/system/pulp_celerybeat.service
- server/usr/lib/systemd/system/pulp_resource_manager.service
- server/usr/lib/systemd/system/pulp_workers.service
This patch also adds back some lines of pulp.spec file that were
accidently removed in
https://github.com/pulp/pulp/commit/f4d2de05d58f71e9baccd18e0ce8020c3e80d6fb
> Added SELinux rules to restrict pid and tmp file management

- repoauth/pulp/repoauth/oid_validation.py
- repoauth/test/test_oid_validation.py
Putting plugin specific values here is a total hack but reworking how repo-auth works is outside the scope of this pr.
> refs #99 - add ostree web prefix.

- pulp.spec
- server/selinux/server/relabel.sh
This patch enhances the pulp-selinux RPM install process. The version of the
pulp-server SELinux policy is recorded in /var/lib/rpm-state/pulp before the new
policy is installed. Then that version is passed as an argument to relabel.sh.
The relabel script then only relabels the files that have not been properly labeled
in the previously installed version. If no version is passed in, all files
are relabeled.
Fixes #540
> 540 - Check previous version of pulp-server SELinux policy at ugrade

- docs/user-guide/release-notes/2.6.x.rst
Because of a redmine change, the query needs to be updated to show 2.6.0 in platform.
> Fixes release notes link for 2.6.0

- server/pulp/plugins/util/publish_step.py
- server/test/unit/plugins/util/test_publish_step.py
For large numbers of available packages this step breaks with an assertion in
mongodb (assertion 13385 combinatorial limit of $in partitioning of result set
exceeded).  I fixed it with running the database query multiple times for
smaller subsets of our available units.
> split database query in publish_step into multiple smaller ones

- server/pulp/server/db/connection.py
- server/test/unit/server/db/test_connection.py
MongoDB allows passwordless logins. However, Pulp was checking that both the
username *and* password were set before attempting a login.
This patch alters the user/pass check to fail only if a password is set sans
username. If a username is set sans password, a MongoDB connection will be
attempted.
Note that all of the auth still happens in Mongo. This was just a "pre-check"
that Pulp was doing to give a clear error message.
fixes #708
> Allow passwordless mongodb connections to be configured

- pulp.spec
I forgot the `:` somehow in a previous commit.
> Fix broken spec file

- docs/user-guide/nodes.rst
If `oauth_key` is used instead of `key` under `[parent_oauth]`, users will get
a confusing error during node sync.
fixes #528
> Add warning in nodes setup to not copy/paste values

- docs/dev-guide/contributing/bugs.rst
These tags are no longer available on Redmine so they need to not be recommended in the docs.
> Removes docs on Reopened and Security tags since they are deleted

- docs/user-guide/qpid.rst
- server/bin/pulp-qpid-ssl-cfg
Remote hosts are more likely to be connecting to qpidd using the fully
qualified hostname, especially in complex environments where not all
machines share the same domain/search suffix.
Sometimes the fqdn is not properly set up, and the hostname contains the
entire fqdn. This change addresses this, while also allowing the user to
specify in case a DNS alias or IP address is preferred.
It also fills the example configs out with the hostname used as the CN
in the cert, as that is the only string that will actually work due to
server certificate verification.
Support relative paths for INST_DIR
Previously relative path usage was not supported for INST_DIR due to the
script cding to the temp directory. Use readlink to make it an absolute
path.
> pulp-qpid-ssl-cfg - More robust hostname default, prompt for input, support relative paths for INST_DIR

- server/pulp/server/logs.py
- server/test/unit/server/test_logs.py
More complete and symmetrical with start_logging().  Also, fixes issue with unit tests.
> clear log handlers in stop_logging().

- server/pulp/server/logs.py
- server/test/unit/server/test_logs.py
Already reviewed on PR #1769 and just needed to be re-issued against 2.6-testing.
More complete and symmetrical with start_logging(). Also, fixes issue with unit tests.
>   clear log handlers in stop_logging()

- client_lib/pulp/client/commands/repo/sync_publish.py
- client_lib/test/unit/client/commands/repo/test_sync_publish.py
- playpen/dev-setup.sh
- pulp.spec
- server/pulp/server/async/tasks.py
- server/pulp/server/managers/repo/sync.py
- server/test/unit/server/async/test_tasks.py
This goes along with additional changes to plugins so they can take advantage
of smarter error reporting. This includes the use of the unittest2 module for
testing that error reporting.
refs #652
refs #702
https://pulp.plan.io/issues/652
https://pulp.plan.io/issues/702
> Task failures of known types no longer log tracebacks.

- server/pulp/server/managers/content/upload.py
- server/test/unit/test_content_managers.py
The upload delete method used inode data to determine if a file
exists before deleting it. On filesystems with cached or slow-to-
respond inode data like NFS this was causing issues. The new
implementation always tries to remove a file and silences
only the error in the case where the file does not exist.
Also some small flake8 fixes.
closes #480
https://pulp.plan.io/issues/480
> Adjusts the upload delete API implementation

- server/etc/default/upstart_pulp_resource_manager
- server/etc/default/upstart_pulp_workers
- server/pulp/server/async/manage_workers.py
- server/usr/lib/systemd/system/pulp_resource_manager.service
The heartbeat interval for celery was previously set to the default of 2
seconds. This caused the workers collection to be updated in mongo every two
seconds as well, even on an idle system.
Instead, set the heartbeat interval to 30 seconds. This should be sufficient
for worker status updates.
fixes #808
> set heartbeat interval to 30s

- pulp-dev.py
- pulp.spec
- server/etc/rc.d/init.d/pulp_celerybeat
- server/etc/rc.d/init.d/pulp_workers
- server/selinux/server/pulp-celery.te
- server/selinux/server/relabel.sh
- server/usr/lib/tmpfiles.d/pulp.conf
This patch provides a fix for both systemd and upstart. A configuration file for
systemd-tmpfiles helps ensure that /var/run/pulp is recreated at boot time. The
upstart script already created the directory if it was missing. The same script
now restores the context on the newly created directory. The relabel.sh script
now contains a statement to restore context of /var/run/pulp also.
Fixes #719
> Added persistence of /var/run/pulp

- deps/python-kombu/1195361.patch
- deps/python-kombu/1212200.patch
- deps/python-kombu/README
- deps/python-kombu/python-kombu.spec
Removes ordereddict from Kombu Python setuptools dependencies.
The spec file still includes it.
Also backports two fixes that were already included in
python-kombu-6.pulp
Fixes a SASL negotiation issue when PLAIN is not available
and the python-saslwrapper is installed
Fixes a connection close issue that was already included
in python-kombu-6.pulp. Included here so that multiple
versions of Pulp can use the same version. They should be
able to safely.
closes #896
https://pulp.plan.io/issues/896
> Kombu SASL connection, connection closing, and python dep fixes

- docs/user-guide/troubleshooting.rst
Replace rsyslog.conf examples with reference to rsyslog.com and suggestion to use tail and grep.
> refs:654 - remove rsyslog examples.

- docs/dev-guide/integration/rest-api/status.rst
- docs/user-guide/scaling.rst
* A section on clustered monitoring which identifies issues and
workarounds for the /status/ API in clustered environments.
* A section on pulp-admin configuration for clustered
environments.
* Generalizes the load balancer docs to include DNS based load
balancing in addition to TCP based load balancing.
re #915
re #282
https://pulp.plan.io/issues/915
https://pulp.plan.io/issues/282
> Adds three updates to the clustering documentation.

- docs/dev-guide/integration/events/index.rst
- server/etc/pulp/server.conf
The previous docs were not suitable for someone who wanted to integrate with
Pulp but was not already familiar with TaskStatus objects.
This patch adds some examples and further explanation on task notifications and
how to use them.
> Update docs for task notification messages

- client_lib/pulp/client/commands/repo/importer_config.py
- client_lib/test/unit/test_commands_importer_config.py
- common/pulp/common/plugins/importer_constants.py
- docs/dev-guide/integration/rest-api/repo/cud.rst
- docs/user-guide/content-sources.rst
- docs/user-guide/release-notes/2.7.x.rst
- server/pulp/plugins/util/importer_config.py
- server/pulp/plugins/util/nectar_config.py
- server/pulp/server/content/sources/constants.py
- server/pulp/server/content/sources/descriptor.py
- server/pulp/server/managers/repo/importer.py
- server/test/unit/plugins/util/test_importer_config.py
- server/test/unit/plugins/util/test_nectar_config.py
- server/test/unit/server/content/sources/test_descriptor.py
- server/test/unit/server/managers/repo/test_importer.py
Nectar already has support for basic auth when downloading files. However, Pulp
did not have an option to set this on the importer.
This commit adds a `basic_auth_username` and `basic_auth_password` to importer
configs to allow for basic auth. Options to `pulp-admin` have also been added.
Plugins will not automatically be able to use basic auth, and will have to set
`include_basic_auth=True` when using the *ImporterConfigMixin* mixin.
This commit contains an additional security-related change to obfuscate
`basic_auth_password` and `proxy_password` in importer configs when returned
via the REST api.
re #163
> Allow basic auth when syncing from repos

- docs/dev-guide/integration/rest-api/repo/retrieval.rst
- docs/user-guide/release-notes/2.7.x.rst
- server/pulp/server/db/migrations/0017_distributor_last_published.py
- server/pulp/server/managers/repo/distributor.py
- server/pulp/server/managers/repo/publish.py
- server/pulp/server/webservices/urls.py
- server/pulp/server/webservices/views/repositories.py
- server/test/unit/plugins/conduits/test_repo_publish.py
- server/test/unit/server/db/migrations/test_0017_distributor_list_published.py
- server/test/unit/server/managers/repo/test_distributor.py
- server/test/unit/server/managers/repo/test_publish.py
- server/test/unit/server/webservices/views/test_repositories.py
Contained in the PR:
- Change storage of *last_publish* on distributors from iso8601 string to native date object in mongo.  This is needed to support date range searches.  The API will continue to return this field as an ios8601 string so backwards compatibility is maintained.
- The distributor  *last_publish* only updated on successful publish.
- Added /v2/distributors/seach/ endpoint to support search.
> ref #214, support distributor search.

- docs/user-guide/server.rst
This patch adds a label to the importer config section. This label is needed so that other projects can reference this section.
> Added a label for importer config

- docs/dev-guide/contributing/bugs.rst
The Redmine custom field 'Tags' at pulp.plan.io no longer has
the 'Groomed' or 'Sprint Candidate' options. Those have been
removed so this removes references from the bug filing docs
to match.
> Updates bug filing docs with changes to Tags

- client_lib/pulp/client/commands/consumer/query.py
- client_lib/test/unit/test_commands_consumer_query.py
- nodes/extensions/admin/pulp_node/extensions/admin/commands.py
- nodes/test/unit/test_admin_extensions.py
https://pulp.plan.io/issues/666
This is just a display issue.
For the *consumer list* command - de-duplicate the list of repositories.
For the *node list* command - only include nodes distributors.
> ref #666, fix dups in binding list.

- server/pulp/server/managers/schedule/utils.py
- server/test/unit/server/managers/schedule/test_utils.py
closes #768
This issue also was present in update/delete methods in schedule sync/publish and in
consumer schedule content install/update/uninstall.
Manual testing for:
scheduled sync http://fpaste.org/215722/43012388/
scheduled publish http://fpaste.org/215721/43012374/
scheduled consumer content install http://fpaste.org/215723/24126143/ (skipped update/uninstall - they are the same)
> API call to Update a scheduled publish returns 400 with invalid schedule_id

- server/setup.py
web.py is not available on "fresh" 2.7 installs from RPM, which causes
pulp-manage-db to not run.
fixes #959
https://pulp.plan.io/issues/959
> Remove web.py reference from setup.py

- rel-eng/fedora-pulp.repo
- rel-eng/rhel-pulp.repo
This commit removes older entries, and fixes some gpg parameters to make them
match what's on fedorahosted.
> Update .repo files to remove older entries

- Vagrantfile
- docs/dev-guide/contributing/dev_setup.rst
- playpen/vagrant-setup.sh
This commit adds documentation of our new Vagrant setup, as well as
configuring it to use NFS to share the code rather than rsync which was
very slow.
> Configure Vagrant for NFS shares and document it.

- deps/python-kombu/476.patch
- deps/python-kombu/README
- deps/python-kombu/python-kombu.spec
I did a tito test build of the RPM and the patch applied cleanly. I did not bump the release because release 7 has not yet been built on koji.
This is a fix for upstream issue 476.
https://github.com/celery/kombu/issues/476
fixes #470
https://pulp.plan.io/issues/470
> Fixes a file descriptor leak in python-kombu

- docs/dev-guide/conventions/criteria.rst
- docs/user-guide/release-notes/2.7.x.rst
- server/pulp/server/db/model/criteria.py
- server/test/unit/server/db/model/test_criteria.py
https://pulp.plan.io/issues/214
To completely support the use case in #214, pulp *criteria* needs to support filters on fields stored in the DB as mongo *ISODate*.  Since filters are passed to pymongo, the value of filters on fields stored as ISODate need to be parsed and converted into python *datetime* before being passed to mongo.
This approach attempts to follow the *operator* pattern already established by mongo for expressing queries.  It introduces an operator extension named ``$date`` which coverts the iso-8601 string value into a python *datetime* object before it is handed to pymongo.
> Add  criteria search operator.

- server/pulp/server/managers/schedule/utils.py
- server/test/unit/server/managers/schedule/test_utils.py
The schedule field was being updated, but next_run and
first_run were not being updated. These values are used
to determine if a schedued task should be run so updating
them is necessary.
fixes #922
https://pulp.plan.io/issues/922
> Updates to schedules are now respected by celerybeat

- pulp.spec
This was already being performed as a macro.
fixes #980
https://pulp.plan.io/issues/980
> Removes duplicate calling of systemctl daemon reload

- pulp-dev.py
Not all distributions put the systemctl executable in the same location.
pulp-dev.py had been calling it as /sbin/systemctl, but Fedora 21 keeps
that executable in /usr/bin/systemctl. This commit calls the executable
as just systemctl and allows the PATH variable to be used to locate it.
https://pulp.plan.io/issues/991
fixes #991
> Don't use full path to systemctl in pulp-dev.py.

- Vagrantfile
- playpen/vagrant-setup.sh
This commit speeds up vagrant provision in two ways:
* Turn off the mongo journal.
* Use dnf instead of yum.
> Speed up the vagrant provisioning.

- server/pulp/server/managers/consumer/applicability.py
According to mongo documentation [0] the cursor will initially return about 101
documents or slightly more than 1 megabyte of data. The subsequent fetches return
4 times as much data. The default timeout of mongo cursor (version 2.4) is 600
seconds. This timeout cannot be adjusted until mongodb 2.6. If 400 applicability
calculations need to be performed in 600 seconds, each calculation cannot take
any longer than 1.5 seconds. In my testing I found the calculations to take 12 to
13 seconds. Limiting the batch size to 25 ensures that calculations can take up
to 24 seconds each before the cursor times out.
[0] http://docs.mongodb.org/v2.4/core/cursors/#cursor-batches
https://pulp.plan.io/issues/998
fixes #998
> Adds batch size to cursor used to iterate repo profile applicabilities

- server/pulp/server/async/app.py
- server/pulp/server/async/tasks.py
- server/test/unit/server/async/test_app.py
- server/test/unit/server/async/test_tasks.py
We had two different Celery startup signal handlers registered, and it
seemed that the second was no longer being sent. This commit ensures
that all worker startup code happens in the same signal handler, and
that it occurs in the correct order.
https://pulp.plan.io/issues/988
fixed #988
> Perform all Worker setup in the same signal.

- server/pulp/server/async/app.py
We had used the undocumented worker_init signal, which turns out to send
unknown arguments to initialize_worker(). This commit switches us to the
well documented celeryd_after_setup signal instead:
http://celery.readthedocs.org/en/latest/userguide/signals.html#celeryd-after-setup
> Use the documented celeryd_after_setup signal.

- docs/user-guide/troubleshooting.rst
Qpid has unfortunately moved the qpidtoollibs Python package from the
python-qpid-qmf package to the qpid-tools package. This commit adds the
qpid-tools package to the troubleshooting guide in addition to the
python-qpid-qmf. We need to mention both for now since we do not know if
our users will be using the newer or older version of qpid.
> Update our troubleshooting for qpid-tools.

- bindings/pulp/bindings/responses.py
- client_admin/pulp/client/admin/admin_auth.py
- client_admin/pulp/client/admin/auth.py
- client_admin/pulp/client/admin/tasks.py
- client_lib/pulp/client/commands/polling.py
- client_lib/pulp/client/commands/repo/status.py
- client_lib/pulp/client/commands/repo/upload.py
- client_lib/pulp/client/launcher.py
- client_lib/test/unit/client/commands/test_polling.py
- common/pulp/common/plugins/progress.py
- docs/dev-guide/integration/rest-api/tasks.rst
- docs/user-guide/admin-client/tasks.rst
- docs/user-guide/server.rst
- nodes/child/pulp_node/handlers/model.py
- nodes/common/pulp_node/reports.py
- nodes/extensions/admin/pulp_node/extensions/admin/rendering.py
I also changed all the docs and messages not to confuse the users. I did not touch any variables' or methods' name.
closes #966
https://pulp.plan.io/issues/966
these PRs should be merged together:
https://github.com/pulp/pulp_rpm/pull/694
https://github.com/pulp/pulp_docker/pull/71
> Fixing discrepancy "canceled" vs. "cancelled

- playpen/vagrant-setup.sh
The Vagrant box's sudoers file did not allow the -u flag to be used
without a password. This commit edits the sudoers file so that it does
allow this.
> Allow the vagrant users to sudo as other users.

- server/pulp/server/async/tasks.py
- server/test/unit/server/async/test_tasks.py
fixes #1011 
https://pulp.plan.io/issues/1011
> Add support for parsing TaskStatus objects to the TaskResult object

- docs/user-guide/release-notes/2.6.x.rst
The notes mention that Fedora 22 is supported, and Fedora 20 is dropped.
> Release notes for 2.6.3

- server/pulp/server/managers/consumer/applicability.py
- server/test/unit/server/managers/consumer/test_applicability.py
25 was still causing timeouts for some users. 10 worked, so 5 seems
like a safe bet.
https://pulp.plan.io/issues/998
fixes #998
> This reduces the batch size to 5

- playpen/vagrant-motd.txt
- playpen/vagrant-setup.sh
This commit adds some useful bash functions to the Vagrant provisioned
.bashrc file that will start, stop, restart, and display the status of
all the Pulp services. The functions are called pstart, pstop, prestart,
and pstatus, respectively.
> Add prestart and friends to Vagrant provisioning.

- deps/python-kombu/1195361.patch
- deps/python-kombu/README
- deps/python-kombu/python-kombu.spec
https://pulp.plan.io/issues/917
https://pulp.plan.io/issues/1006
fixes #917
fixes #1006
re #711
I also did a `tito build --test --rpm` where all unit tests in python-kombu were run and passed, and it successfully built python-kombu-3.0.24-8.pulp.
> Fixes 917 and 1006 by stopping an thread that should have exited

- docs/user-guide/admin-client/tasks.rst
- docs/user-guide/release-notes/2.7.x.rst
- nodes/test/unit/base.py
- server/etc/pulp/server.conf
- server/pulp/server/config.py
- server/pulp/server/db/migrations/0018_remove_archived_calls.py
- server/pulp/server/db/model/dispatch.py
- server/pulp/server/db/reaper.py
- server/test/unit/server/db/migrations/test_0018_remove_archived_calls.py
- server/test/unit/server/db/test_reaper.py
https://pulp.plan.io/issues/952
Closes #952
Reviewed under master #1903. Created against 2.7-dev.
> Task 952: Delete unused models from server.db.models.dispatch

- docs/user-guide/release-notes/2.7.x.rst
- server/bin/pulp-gen-ca-certificate
- server/etc/pulp/server.conf
- server/pulp/server/config.py
The server_name and the CN in certificates generated by pulp-gen-ca-certificate is
the fully qualified domain name (FQDN).
https://pulp.plan.io/issues/926
fixes #926
> Set server_name to FQDN for default server config

- server/pulp/server/db/model/__init__.py
The pre-save handler did not save the full path to the
file_path set with set_content in the case where
file_path is a file.
re #862
> Set storage path in ContentUnit.pre_save handler correctly.

- server/pulp/server/async/manage_workers.py
- server/setup.py
- server/usr/lib/systemd/system/pulp_workers.service
The lastest version of setuptools does not support '/' character in name of
install scripts. This patch removes the entry point which lived in
/usr/libexec/pulp-manage-workers. The unit file now uses the
'pulp.server.asynch.manage_workers' as a python module.
> Removed pulp-manage-workers entry point from setup.py

- playpen/ansible/roles/pulp_server/tasks/main.yml
- playpen/vagrant-setup.sh
Our Vagrant provisioning didn't do anything for Crane. This commit
creates basic support for creating a virtualenv and installing Crane's
dependencies.
In order to avoid copying the RPM dependency information, I determined
how to query Crane's spec file for the RPMs that Crane depends on.
Since this line was also useful for our other projects, I converted our
dependencies to all be installed this way. By
doing this, I also solved #990 and so this commit also fixes that issue.
https://pulp.plan.io/issues/990
fixes #990
> Provision a virtualenv for Crane if present.

- docs/dev-guide/contributing/dev_setup.rst
Adds documentation about how to configure Vagrant to use libvirt's
unsafe cache mode, which allows developers to trade data safety for I/O
performance.
> Document how to configure Vagrant for unsafe cache

- docs/dev-guide/contentauth.rst
- repoauth/pulp/repoauth/wsgi.py
- repoauth/test/test_wsgi.py
- server/etc/pulp/repo_auth.conf
Previously in Pulp 2.7, repo authenticator plugins were controlled only via the
plugin's entry points. This meant that if a plugin was installed by default, we
were not able to disable it.
A new config value has been added to repo_auth.conf to disable specific
plugins. This lets us turn plugins on and off at will, without having to
uninstall any default plugins.
fixes #1055
https://pulp.plan.io/issues/1055
> Allow disabling specific repo auth plugins

- server/pulp/server/db/model/__init__.py
The task status model incorrectly generated 2 indexes for task_id. I believe that this will fix https://pulp.plan.io/issues/1092 but I have been unable to replicate the failure of the migration.
Regardless, this extra index must be dropped in 2.7.0 (where it first appears) so that we do not need to write a migration to remove it.
@dkliban, I would appreciate if you could try this on your system to see if it solves your issue.
> index task_status.task_id only once

- docs/dev-guide/policies/style.rst
Our style guide was pretty thin on how we do doc blocks. Particularly since it is done differently in old and new code, it is valuable to make our expectations clear, and more valuable to have an example.
This also fixes a broken link to the Sphinx docs.
> Update style guide for in-code documentation and add an example

- devel/pulp/devel/test_runner.py
- run-tests.py
Sets the django settings environment in the test runner rather than in run-tests.py so the plugin tests can make use of it also.
> move django settings environment variable to test runner

- server/pulp/server/async/tasks.py
- server/pulp/server/managers/consumer/agent.py
- server/pulp/server/webservices/views/tasks.py
- server/test/unit/server/async/test_tasks.py
- server/test/unit/server/managers/consumer/test_agent.py
The upgrade to mongoengine 0.9.0 revealed that parts of the
Pulp codebase which used mongoengine models did not specify
kwargs. This raises an exception (as it should) in mongoengine
0.9.0.
I audited the existing models on 2.7-testing, fixed those, and
I updated the tests to match.
re #934
https://pulp.plan.io/issues/934
> Fixes mongoengine model usage that did not have kwargs

- common/pulp/common/constants.py
- docs/user-guide/installation.rst
- docs/user-guide/release-notes/master.rst
- docs/user-guide/scaling.rst
- docs/user-guide/server.rst
- server/pulp/server/async/scheduler.py
- server/pulp/server/db/manage.py
- server/pulp/server/db/model/__init__.py
- server/test/unit/server/async/test_scheduler.py
- server/test/unit/server/db/test_model.py
https://pulp/plan.io/issues/1060
closes #1060
> Pulp with multiple celeryBeat instances

- common/pulp/common/compat.py
- server/test/unit/base.py
- server/test/unit/plugins/loader/test_manager.py
- server/test/unit/server/controllers/test_repository.py
- server/test/unit/server/controllers/test_units.py
- server/test/unit/server/db/test_model.py
- server/test/unit/server/webservices/views/serializers/test_serializers.py
In order to use new things like `self.assertDictEqual`, we are increasingly using unittest2 in older versions of python. By moving this import to the compat module, we can avoid doing this same import magic in every test module.
> import unittest2 in compat module

- server/pulp/server/webservices/views/repositories.py
- server/test/unit/server/managers/repo/test_cud.py
- server/test/unit/server/webservices/views/test_repositories.py
closes #750
https://pulp.plan.io/issues/750
All this three calls behave the same:
if a non_exitent_importer provided in the call, but the repo itself exists a 404 missing_resource *repo_id* will be raised, though the repo exists.
Now with the fix it will return 404 missing_resource *importer_id*
> Fixing get, update, delete call when non existent importer is provided.

- playpen/vagrant-motd.txt
- playpen/vagrant-setup.sh
This commit adds a new ptests bash function to the development
environment. This function loops over all the Pulp projects that you
have installed and runs each test suite.
This commit also removes the tests from the initial provisioning so that
we can save some time on vagrant up.
> Add a ptests command to the dev environment.

- test_requirements.txt
Pulp uses Mock in a way that is now broken[0] with the new version that was
recently released. This commit pins us to use Mock<1.1 to avoid the
problem for now. In the end, we should update our tests to use the new
Mock API as part of the work on issue #1135.
[0] https://github.com/testing-cabal/mock/issues/263
re #1135
> Pin the version of Mock that we use.

- server/pulp/server/content/storage.py
- server/pulp/server/db/model/__init__.py
- server/test/unit/server/content/test_storage.py
- server/test/unit/server/db/test_model.py
The ContentUnit remodeled to have (2) derived classes: FileContentUnit and SharedContentUnit.  All plugins currently subclassing ContentUnit will need to be changed to subclass FileContentUnit instead.
Content (bits) storage is delegated to ContentStorage classes.  These classes are focused on how content is stored.  They are not meant to address subjects like *Object Storage* but ARE modeled in such a way as to not be orthogonal.
> ref #865 - mongoengine modeling for shared storage.

- common/pulp/common/constants.py
- server/pulp/server/async/scheduler.py
- server/test/unit/server/async/test_scheduler.py
https://pulp.plan.io/issues/1115
closes 1115
> Adds logging if Pulp is missing critical Celery services

- Vagrantfile
- playpen/vagrant-setup.sh
For some reason, the -e started causing provisioning failures recently.
I suspect that a Fedora update might have changed the behavior of that
flag, but I have not confirmed this. Since we are slowly switching from
the shell provisioner to Ansible I believe it is best to disable this
flag for now to get around the immediate issue.
> Remove the -e from the bash provisioner.

- docs/user-guide/broker-settings.rst
- docs/user-guide/qpid.rst
- docs/user-guide/release-notes/2.6.x.rst
- server/bin/pulp-qpid-ssl-cfg
- server/etc/pulp/server.conf
- server/pulp/server/async/celery_instance.py
- server/pulp/server/config.py
- server/test/unit/server/async/test_celery_instance.py
Adds login_method options to [tasks] section of server.conf
If login_method is set, the value is used to configure the BROKER_LOGIN_METHOD Celery option. login_method defaults to '' which allows Celery to use its default values.
This change includes docs updates on practical usage of the new setting and a release note.
closes #1168
https://pulp.plan.io/issues/1168
> Adds login_method options to [tasks] section of server.conf

- .gitignore
- Vagrantfile.example
- docs/dev-guide/contributing/dev_setup.rst
- playpen/ansible/roles/core/tasks/main.yml
This commit splits the Vagrant "getting started" documentation into
required steps and optional steps. This makes getting started with
Vagrant simpler, and allows the user to go back and learn about
the more advanced options separately.
> Split Vagrant docs into required and optional.

- server/pulp/server/async/task_status_manager.py
- server/pulp/server/async/tasks.py
- server/test/unit/server/async/test_task_status_manager.py
- server/test/unit/server/async/test_tasks.py
https://pulp.plan.io/issues/1136
During the migration to celery, the agent task cancellation did not get wired up.
> ref #1136 - support agent task cancellation.

- server/pulp/plugins/model.py
- server/pulp/server/db/model/__init__.py
- server/test/unit/server/db/test_model.py
Being able to access the repo object is a prereq for versioned repos.
@barnabycourt
> add repository object to repo tranfer unit

- server/pulp/server/db/model/__init__.py
- server/test/unit/server/db/test_model.py
This platform changes causes validation to happen earlier
before mongoengine begins its init. This causes a coded
exception to be raised earlier in the case that the model
definition is invalid.
> Moves post_init functionality to attach_signals.

- client_lib/pulp/client/commands/repo/cudl.py
- client_lib/test/unit/client/commands/repo/test_cudl.py
- docs/dev-guide/integration/rest-api/repo/retrieval.rst
- server/pulp/server/webservices/views/serializers/__init__.py
- server/test/unit/server/webservices/views/serializers/test_serializers.py
https://pulp.plan.io/issues/1172
The scratchpad is used by plugins to store additional repository properties.
> Expose scratchpad in detailed repository serialization.

- server/pulp/server/managers/repo/unit_association_query.py
- server/test/unit/server/managers/repo/test_unit_association_query.py
I confirmed that this doesn't get called anywhere in the platform or in our plugins.
> removing a function that was deprecated 3.5 years ago

- server/selinux/server/pulp-celery.te
This patch adds an additional SELinux allow rule so pulp-ostree can invoke the
gpg binary.
> update pulp-selinux for ostree gpg-related perms

- server/pulp/server/content/storage.py
- server/pulp/server/db/model/__init__.py
- server/test/unit/server/content/test_storage.py
- server/test/unit/server/db/test_model.py
https://pulp.plan.io/issues/1233
Add provider to shared storage and include it in the path.  This needed to be propagated to the shared content unit class.
> Add provider to shared storage location.

- server/pulp/server/controllers/units.py
- server/pulp/server/managers/content/orphan.py
- server/pulp/server/managers/repo/unit_association.py
- server/pulp/server/webservices/views/content.py
- server/test/unit/server/controllers/test_units.py
- server/test/unit/server/managers/content/test_orphan.py
- server/test/unit/server/webservices/views/test_content.py
https://pulp.plan.io/issues/1215
Several places in the code, only two of which I touched here, need to know the
unit key fields for a given type ID. I created a new controller function that
takes care of finding that information regardless of whether the type is
defined the new way (mongonengine) or old way. The next step will be to use
that controller function in additional places, but that is beyond the scope of
this bug fix.
fixes #1215
> fixed orphan removal by type when the type uses mongoengine

- server/pulp/plugins/conduits/mixins.py
- server/test/unit/plugins/conduits/test_mixins.py
https://pulp.plan.io/issues/1239
This bug affected the "get_units" method of at least two conduit mixins.
fixes #1239
> a repo unit association query now works for types defined with mongoengine

- server/pulp/plugins/file/distributor.py
- server/test/unit/plugins/file/test_distributor.py
Write the exception and its traceback to the log at error level
when FileDistributor publish has an error.
https://pulp.plan.io/issues/1248
closes #1248
> Adds error logging to platform base FileDistributor exceptions

- Vagrantfile.example
I learned in a bug report I filed against vagrant-libvirt that the Fedora 22 Vagrant box we use has moved
locations[0]. This commit updates the example Vagrantfile to use the new location. There are 301 redirects in place
for the old location, so there is no immediate urgency for developers to adopt this change.
[0] https://github.com/pradels/vagrant-libvirt/issues/452#issuecomment-137332077
> Adjust the example Vagrantfile for the new F22 box location.

- server/selinux/server/pulp-celery.te
My previous PR (https://github.com/pulp/pulp/pull/2024) did not build on RHEL 6
due to the "gpg_exec" directive not existing. The ostree plugin is not
currently built for RHEL 6 anyway, so we can conditionalize both.
> Fix pulp-selinux on RHEL 6

- common/pulp/common/error_codes.py
- docs/user-guide/release-notes/2.7.x.rst
- server/etc/pulp/server.conf
- server/pulp/server/db/connection.py
- server/test/unit/server/db/test_connection.py
This patch enables pulp to iterate over a list of seeds until a connection
is made. When more than one seed is present, an exception is raised if no
'replica_set' config is specified. An exception is also raised if an empty
string is passed in as value for 'seeds'.
re #1012
https://pulp.plan.io/issues/1012
> Properly handles ['database']['seeds'] config

- server/pulp/server/managers/repo/publish.py
- server/pulp/server/managers/repo/sync.py
fixes #1043 
Original PR: https://github.com/pulp/pulp/pull/1965, reopened against 2.6-dev so it won't hold up the release.
> sort sync and publish history by an indexed key

- server/pulp/plugins/file/distributor.py
- server/pulp/plugins/file/model_distributor.py
- server/test/unit/plugins/file/test_model_distributor.py
https://pulp.plan.io/issues/1250
There are two commits in this PR. The first just makes a straight copy of the original distributor, and the second modifies it. Keeping both commits makes it clear what I had to change.
> created fork of FileDistributor that works with models

- server/pulp/server/managers/repo/unit_association_query.py
This prevented us from long delays in association units
> sort with _id in every unit association query (prevents mongo from freeze)

- server/etc/pulp/server.conf
- server/pulp/server/config.py
- server/pulp/server/lazy/alias.py
- server/pulp/server/lazy/url.py
- server/pulp/server/webservices/urls.py
- server/pulp/server/webservices/views/lazy.py
- server/test/functional/test_lazy_url.py
- server/test/unit/server/lazy/test_alias.py
- server/test/unit/server/lazy/test_url.py
- server/test/unit/server/webservices/views/test_lazy.py
https://pulp.plan.io/issues/1180
Create the RedirectView which is used to redirect content GET requests that 404 to the streamer using a signed URL.
After researching signed URLs,  I have concluded that they are a concept for which there is no standard.  Without a standard, it appears that providers such as Amazon have invented there own.  As a result, there are no standard python libs for dealing with signed URLs.  I have included a collection of classes that provide URL signing and validation based on Amazon signed URLs for EC2.  I have included functional tests but have not yet finished the unit tests .. which will follow.  For now, I just wanted to get this work onto the feature branch.
The auth handler looks like this:
```
from pulp.server.config import config
from …
```
> ref #1180 - add redirect view and url signing.

- docs/dev-guide/contributing/dev_setup.rst
The Vagrant environment requires Fedora, so we should instruct Vagrant
developers to use dnf instead of yum.
> Tell Vagrant devs to use dnf instead of yum.

- server/pulp/server/webservices/views/search.py
- server/test/unit/server/webservices/views/test_search.py
https://pulp.plan.io/issues/312
The BZ originally led me to believe that the problem was with the `filters` field. In actuality, all fields will be passed as strings and need to be loaded from json. The `limit` and `skip` fields do not need to be included because they are cast to integers elsewhere.
> load data structures from GET json

- server/pulp/server/async/tasks.py
- server/test/unit/server/async/test_tasks.py
closes #1222
The worker may not be on the same machine as the scheduler, and this
cleanup will occur on worker startup anyway.
> Do not delete worker if unresponsive.

- common/pulp/common/dateutils.py
- common/test/unit/test_dateutils.py
- server/pulp/plugins/conduits/repo_publish.py
- server/pulp/server/managers/repo/_common.py
- server/test/unit/plugins/conduits/test_repo_publish.py
- server/test/unit/server/managers/repo/test_common.py
closes https://pulp.plan.io/issues/1254
When saving datetimes to Mongo, tz information is stripped. We have to reconstruct the tzinfo (assuming UTC) so it can be compared with other datetimes.
> ensure datetimes on distributors

- server/pulp/server/webservices/middleware/postponed.py
- server/test/unit/server/webservices/middleware/test_postponed.py
If there are Mongoengine documents in an async call report, they must be serialized using the serializer found on the object's model.
https://pulp.plan.io/issues/1259
> serialize ME documents in a call report

- common/pulp/common/dateutils.py
- common/test/unit/test_dateutils.py
- server/pulp/plugins/conduits/repo_publish.py
- server/pulp/plugins/model.py
- server/test/unit/plugins/conduits/test_repo_publish.py
- server/test/unit/plugins/test_model.py
I moved _ensure_tz_specified to the Repository class in master here: https://github.com/pulp/pulp/pull/1931.
This functionality needed to be used more generally, and I moved it to common: https://github.com/pulp/pulp/pull/2067
The merge forward required some changes that warrant another review.
> 2067 merge forward

- server/pulp/plugins/importer.py
- server/test/unit/plugins/test_importer.py
https://pulp.plan.io/issues/1281
I'm not 100% sold on this approach but seems reasonable.  Even for the docker importer which needs to make an API call to get a session key which it adds a a header to the downloader .. this will work.  The streamer would use it (something) like this:
```
entry = LazyCatalogEntry.objects.get(relative_path=<path with /var/lib/pulp/content stripped>)
config, plugin =  plugin_api.get_importe_by_id(entry.plugin_id)
downloader = plugin.get_downloader(config, entry.url, **entry.data)
```
> Add get_downloader() to base importer.

- server/pulp/server/event/data.py
- server/test/unit/server/event/test_email.py
- server/test/unit/server/event/test_http.py
- server/test/unit/server/managers/event/test_crud.py
https://pulp.plan.io/issues/1255
2.7.0 includes the mongoengine conversion for TaskStatus. The TaskStatus serializer needs to be used in before a TaskStatus object can be dumped to json.
> serialize tasks for emails

- server/pulp/server/webservices/views/lazy.py
- server/test/unit/server/webservices/views/test_lazy.py
If the URL that mapped to the Lazy RedirectView was queried
directly rather than being the result of an internal redirect
via Apache's ErrorDocument, the client would get a 500.
A 404 felt like the best response to me, but I would welcome other suggestions.
> Lazy RedirectView no longer returns HTTP 500.

- server/pulp/plugins/util/publish_step.py
closes #1269 
I did not change move--> copy when
1) move was performed from /var/lib/pulp/ to /var/lib/pulp/
2) move was performed from /var/cache/pulp to /var/cache/pulp
3) in tests where it was not testing the code itself
4) under rel-eng directory
I did not change copytree in case where only symlinks were copied and param symlinks  was set to True https://docs.python.org/2/library/shutil.html#shutil.copytree for more info read 2nd paragraph
> Removing shutil.move and copytree where /var/cache/pulp is involved.

- deps/python-kombu/1245.patch
- deps/python-kombu/python-kombu.spec
Includes fix that allows kombu to connect on localhost
This was scratch built successfully on koji. See the [build results here](http://koji.katello.org/koji/taskinfo?taskID=353399).
closes #1245
https://pulp.plan.io/issues/1245
> Upgrades kombu to 3.0.24-10

- server/pulp/server/lazy/alias.py
The translated alias was not resolving the symlinks properly and returning `/var/lib/pulp/published/...` paths instead of `/var/lib/pulp/content/...` paths.
Basically simplified in a way the ensures the os.path.realpath() is called on the returned path.
> Fix alias translation.

- server/etc/httpd/conf.d/pulp_apache_24.conf
In Apache 2.4 when an 'Include' command fails to match any file
Apache will fail to start. This is avoided by using the
'IncludeOptional' command. In 2.2 the 'Include' command acts in a
similar fashion to the 'IncludeOptional' command in 2.4, so that
configuration remains unchanged.
Closes #293
> Apache 2.4 now starts without a conf file in /etc/pulp/vhost80/

- server/pulp/server/webservices/views/repositories.py
- server/test/unit/server/webservices/views/test_repositories.py
Adds repo validation for RepoUnassociate
closes [#1073](https://pulp.plan.io/issues/1073)
> Fix error message on repo remove command

- server/pulp/server/db/model/__init__.py
- server/test/unit/server/db/test_model.py
Here is some pseudocode to illustrate the undesirable behavior
```
unit = FileContentUnit()
unit.set_content('/the/source/file/path/')
unit.save() # automatically moves the file into place
unit.save() # the second call to save moves the same file again
```
With this change, only a second call to `set_content` would
cause a save to copy files around.
> Causes a single set_content() call to only save files once

- common/pulp/common/error_codes.py
- docs/user-guide/release-notes/2.7.x.rst
- pulp.spec
- server/etc/pulp/server.conf
- server/pulp/server/config.py
- server/pulp/server/db/connection.py
- server/test/unit/server/db/test_connection.py
Pulp now accepts a write concern for the MongoDB connection. All writes
to the database are now acknowledged. For replica sets, 'majority' or 'all'
members can be asked to acknowledge the write.
> Adds support for write concern

- server/pulp/server/controllers/content.py
`apply_async_with_reservation` requires the arguments for the
task be passed as a list and Nectar's `download_one` requires
events to be explicitly turned on.
> Two small modifications to the lazy download task.

- pulp-dev.py
- server/etc/default/upstart_pulp_streamer
- server/etc/pulp/server.conf
- server/etc/rc.d/init.d/pulp_streamer
- server/pulp/server/config.py
- server/pulp/server/lazy/streamer.py
- server/srv/pulp/streamer.tac
- server/srv/pulp/streamer_auth.wsgi
- server/test/unit/server/lazy/test_streamer.py
- server/usr/lib/systemd/system/pulp_streamer.service
This commit adds the 'lazy' module inside of pulp.server.
It also adds streamer settings to Pulp's server.conf.
> ref #1195 - Implement the pulp-streamer.

- server/pulp/server/constants.py
- server/pulp/server/controllers/content.py
- server/pulp/server/lazy/streamer.py
- server/test/unit/server/lazy/test_streamer.py
This also updates the streamer to check for a special HTTP header to
determine whether or not it should dispatch a task and changes the
streamer to use the new LazyCatalogEntry model.
I'm hesitant to write tests for the task just yet, since we may end up changing it quite a bit depending on whether we download entire content units or not.
> Update the download_one task to use the streamer.

- docs/user-guide/installation.rst
As of https://fedorahosted.org/epel/ticket/8 it is easier to install the epel-release RPM. Update our documentation to reflect this.
> doc: improve epel-release instructions

- server/pulp/server/async/tasks.py
- server/pulp/server/db/model/__init__.py
- server/pulp/server/webservices/views/tasks.py
- server/test/unit/server/async/test_tasks.py
- server/test/unit/server/webservices/views/test_tasks.py
TaskStatus has a group_id field. The group_id is used to group a set
of tasks together. The TaskStatus view selects only TaskStatus documents
that don't have a group_id set. The task_id field should only be set
when performing parallelized work.
https://pulp.plan.io/issues/1204
closes #1204
> Adds group_id to TaskStatus model

- playpen/ansible/roles/dev/tasks/main.yml
I noticed recently that vagrant up has issues when starting Pulp due to having the wrong version of Gofer.
It turns out that we had been installing Gofer before enabling the beta repository. This commit enables the
repository before installing Gofer to resolve that issue.
> Enable the beta repo before installing Pulp packages.

- server/pulp/server/db/model/__init__.py
- server/test/unit/server/db/test_model.py
- server/test/unit/server/webservices/test_urls.py
The first-pass implementation of ContentUnit for mongoengine
used an attribute name of 'user_metadata' to model the database
field named 'pulp_user_metadata'. This is a nice chance, but it
forces multiple plugins to handle name translation for both
Criteria objects and serializers.
By modeling the attribute as the actual database name everything
becomes simpler. We can rename pulp_user_metadata to
user_metadata in a future X release.
> ContentUnit now models pulp_user_metadata as pulp_user_metadata

- server/pulp/server/db/model/__init__.py
- server/test/unit/server/db/test_model.py
The first-pass implementation of ContentUnit for mongoengine
used an attribute name of 'last_updated' to model the database
field named '_last_updated'. This is a nice chance, but it
forces multiple plugins to handle name translation for both
Criteria objects and serializers.
By modeling the attribute as the actual database name everything
becomes simpler. We can rename _last_updated to last_updated in
a future X release.
> Renames last_updated to _last_updated on ContentUnit

- server/pulp/plugins/file/distributor.py
- server/pulp/plugins/util/publish_step.py
- server/pulp/server/db/model/__init__.py
- server/pulp/server/util.py
- server/test/unit/server/test_util.py
Implements copytree method without use of copy2() and copystat() to prevent
copying of metadata. This ensures files have proper selinux security context
based on the new location.
https://pulp.plan.io/issues/1253
re: 1253
https://pulp.plan.io/issues/1312
re: 1312
> Adds pulp.common.util.copytree method

- nodes/child/pulp_node/importers/download.py
- nodes/child/pulp_node/importers/strategies.py
- nodes/test/nodes_tests/test_importer_strategies.py
- server/pulp/server/content/sources/container.py
- server/pulp/server/content/sources/event.py
- server/pulp/server/content/sources/model.py
- server/test/functional/test_content_sources.py
- server/test/unit/server/content/sources/test_container.py
- server/test/unit/server/content/sources/test_event.py
- server/test/unit/server/content/sources/test_model.py
Added non-threaded API for use within reactor frameworks such as Twisted.
Usage:
```
container = ContentContainer()
container.threaded = False
...
```
Simplified code with better Listener/Event model.
Removed cancel logic.
> Content sources container API safe to be used within Twisted.

- server/pulp/server/content/web/views.py
- server/pulp/server/lazy/url.py
- server/srv/pulp/streamer_auth.wsgi
- server/test/functional/test_lazy_url.py
- server/test/unit/server/content/web/test_views.py
Add support for policy extensions.  Then, update the usage of signed urls in pulp to include the remote_ip in the policy extensions.  This ensures that when the signed url is used as part of the redirect, only the client getting redirected can use that url.
Does this seem valuable?
Also, 10 seconds seemed too short by default so changed it to 90 seconds.
> Add policy extensions.

- pulp.spec
Since the streamer is a Python package, its RPM package name should have the
'python-' prefix.
> Update the streamer rpm package name.

- server/pulp/server/content/sources/model.py
- server/test/unit/server/content/sources/test_model.py
fixes #1278 
https://pulp.plan.io/issues/1278
> log a warning when a content source config file cannot be read

- playpen/vagrant-setup.sh
Previously, the /var/lib/pulp/published/docker/v{1,2}/app folders were owned by root instead of apache, which
caused some problems during publishing. This commit fixes them to be owned by apache for Vagrant
installations.
> This commit fixes the permissions on the Docker publish folder.

- server/pulp/server/db/model/__init__.py
- server/test/unit/server/db/test_model.py
Deferred downloads is used by the passive lazy workflow to queue up
downloads processed by the streamer. A celerybeat task will use this
queue to download the units later.
> Adds a new MongoEngine model for deferred downloads.

- server/pulp/server/db/manage.py
- server/pulp/server/db/model/__init__.py
- server/test/unit/server/db/test_model.py
This commit also adds the call to ``ensure_indexes`` in the
pulp-manage-db script.
> Update the lazy models to use AutoRetryDocument.

- Vagrantfile.example
- playpen/ansible/roles/dev/files/flower.service
- playpen/ansible/roles/dev/tasks/main.yml
Flower is a web-based tool for monitoring and administrating Celery
clusters. This adds Flower to the Ansible dev playbook and includes a
systemd unit for the service. It is configured to run on port 5555.
This also adds hostname management to the example Vagrantfile. If this
is enabled, it is possible to access the Flower dashboard from your host
machine at http://dev.example.com:5555/.
> Add Celery Flower to the Vagrant dev box.

- common/pulp/common/error_codes.py
- server/pulp/server/content/storage.py
- server/pulp/server/controllers/repository.py
- server/pulp/server/db/model/__init__.py
- server/test/unit/server/content/test_storage.py
- server/test/unit/server/controllers/test_repository.py
- server/test/unit/server/db/test_model.py
https://pulp.plan.io/issues/1302
Mainly added the *downloaded* field to content unit.  Added *downloaded* to ContentUnit.  Replaced *set_content()* with *import_content()* and change behavior to *import* the content when it's called instead of setting _source_path and copying when the unit is saved.  Support for importing directories has been removed.  The *path* passed to import_content() must be an existing file.  Importers (rpm, puppet, docker) will be updated to call import_content() for each file downloaded instead of with the entire directory after it has all been downloaded.  This should not be an issue as both the puppet and rpm plugins are in the process of conversion to mongoengine on master.
I decided to leave *_storage_path* on ContentUnit.  After looking at orphan clean up, I …
> Add downloaded field to file content unit.

- server/pulp/server/webservices/views/search.py
- server/test/unit/server/webservices/views/test_search.py
The base class for search was originally implemented for POST searches only and expanded to also apply to GET searches. This resulted in some mess and some bugs which are corrected here.
https://pulp.plan.io/issues/312
closes: #312
> refactor the search class to simplify use of GET and POST searches

- server/pulp/server/controllers/repository.py
- server/test/unit/server/controllers/test_repository.py
Fixing:
```
Nov 05 14:45:01 localhost.localdomain pulp[11129]: celery.worker.job:ERROR: (11129-90976) Traceback (most recent call last):
Nov 05 14:45:01 localhost.localdomain pulp[11129]: celery.worker.job:ERROR: (11129-90976)   File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
Nov 05 14:45:01 localhost.localdomain pulp[11129]: celery.worker.job:ERROR: (11129-90976)     R = retval = fun(*args, **kwargs)
Nov 05 14:45:01 localhost.localdomain pulp[11129]: celery.worker.job:ERROR: (11129-90976)   File "/home/jortel/git/pulp/server/pulp/server/async/tasks.py", line 400, in __call__
Nov 05 14:45:01 localhost.localdomain pulp[11129]: celery.worker.job:ERROR: (11129-90976)     return super(Task, self).__call__(*args, **kwargs)
Nov 05 14:45:01 …
```
> Fix setting last_sync in repo controller.

- playpen/vagrant-setup.sh
There is a Docker migration that moves any files that are present in /var/lib/pulp/published/docker, which
caused the Crane setup to not be correct after a Vagrant up. This commit adds the needed Crane symlinks after
that migration so that the symlinks don't get moved.
> Configure the crane metadata after the migrations during dev setup.

- docs/dev-guide/integration/rest-api/repo/cud.rst
While working on the mongoengine conversion, I noticed that these docs were difficult to use, so I added a bit of clarification.
> add param docs to distributor update

- server/pulp/server/config.py
The default path used in the Apache configuration[0] uses the path 'streamer'. The default config value for server.conf should match.
[0] https://github.com/pulp/pulp/blob/lazy-content/streamer/etc/httpd/conf.d/pulp_streamer.conf
> Updated lazy redirect_path default to match Apache conf.

- playpen/ansible/roles/dev/files/bashrc
Add a function to the Vagrant default bashrc to run the pulp-smash tests.
> Add "psmash"  to the Vagrant bashrc

- server/pulp/server/db/querysets.py
- server/pulp/server/webservices/views/search.py
- server/pulp/server/webservices/views/serializers/__init__.py
- server/test/unit/server/db/test_querysets.py
- server/test/unit/server/webservices/views/serializers/test_serializers.py
- server/test/unit/server/webservices/views/test_search.py
Using a criteria search by string representations of an ObjectId was broken in master for collections that have been converted to mongoengine. There is not a redmine issue for this because though this code exists in 2.7, no collections are affected, thus there has never been a release with this issue.
Thanks to @Ichimonji10 for smashing up my search code :)
> Translate _id field specially to allow for ObjectIds

- Vagrantfile.example
By default, the fedora-22 base box we use is built with a 40G disk. The partition table accurately reflects this size, but the filesystem is only using 5G of it. This change fixes that, by growing the filesystem to match the partition size:
```
==> dev: meta-data=/dev/vda3              isize=256    agcount=4, agsize=321792 blks
==> dev:          =                       sectsz=512   attr=2, projid32bit=1
==> dev:          =                       crc=0        finobt=0
==> dev: data     =                       bsize=4096   blocks=1287168, imaxpct=25
==> dev:          =                       sunit=0      swidth=0 blks
==> dev: naming   =version 2              bsize=4096   ascii-ci=0 ftype=0
==> dev: log      =internal               bsize=4096   blocks=2560, version=2
==> dev:          = …
```
> vagrant resizes the root volume when provisioning

- server/pulp/server/controllers/importer.py
- server/test/unit/server/controllers/test_importer.py
A small change made right before merge of https://github.com/pulp/pulp/pull/2114 led to an incorrect type.
> fix type error for set importer

- .gitignore
In the process of messing around with python optimize settings today,
I managed to make a ton of pyo files, which should be ignored just like
pyc files
> ignore pyo files in addition to pyc

- server/pulp/server/db/model/__init__.py
- server/test/unit/server/db/test_model.py
This commit adds a ``pre_delete`` signal to the Importer model which
handles the removal of catalog entries.
closes #1327
> The lazy catalog is now purged when an importer is deleted.

- server/pulp/server/async/scheduler.py
- server/pulp/server/db/fields.py
- server/pulp/server/db/model/__init__.py
- server/test/unit/server/db/test_fields.py
re #1254
re #1267
https://www.redhat.com/archives/pulp-list/2015-November/msg00044.html
> adding UTCDateTimeField, which always returns datetimes with timezone UTC

- playpen/ansible/roles/dev/files/bashrc
The various systemd commands accept multiple arguments. Why use a for loop if
a simpler expression suffices?
> Trim down `pstatus` function in .bashrc

- deps/external_deps.json
Our build script is failing right now because it is looking for the wrong version of python kombu. It was built in koji using the .pulp suffix after the version.
> Changes version of python-kombu in exteral_deps.json

- docs/dev-guide/integration/rest-api/repo/retrieval.rst
- server/pulp/server/controllers/repository.py
- server/pulp/server/webservices/views/repositories.py
- server/test/unit/server/controllers/test_repository.py
- server/test/unit/server/webservices/views/test_repositories.py
This adds the following fields to the repository object returned from
the API ``v2/repositories/<repo-id>/?details=true``:
``total_content_units`` and ``total_units_downloaded``.
closes #1354
> Add total/downloaded units to repository view.

- playpen/vagrant-setup.sh
The development environment installs dependencies from the spec file. It had been installing them by name
only, ignoring any version specific requirements. This commit converts it to also consider the version
requirements so that the development environment matches the spec file more closely.
> Use REQUIRENEVRS instead of REQUIRENAME for development dependencies.

- server/pulp/plugins/util/publish_step.py
- server/test/unit/plugins/util/test_publish_step.py
Some types are a mixture of Units and Metadata, and need to be treated separately. The GetLocalUnitsStep did
not allow developers to specify what data structure would contain the iterable of available Units. This
commit adds the ability for developers to give a pointer to that data structure while maintaining the
previous behavior if it is not specified for backwards compatibility.
This is needed for the Docker plugin Mongoengine conversion as it reduces the number of steps that are needed
in its importer's code.
https://pulp.plan.io/issues/863
re #863
> Allow developers to override the GetLocalUnitsStep's available_units.

- server/pulp/plugins/types/database.py
- server/test/unit/server/db/migrations/test_0015_load_content_types.py
- server/test/unit/server/db/test_manage.py
The upgrade to fedora 23 revealed that the 'dropDups' property of mongo
indices was deprecated in 2.6 and removed in 2.7[0].
The removed 'dropDups' assertions weren't stricly necessary, since the
test is checking that the uniqueness contraint is applied, which it is.
dropDups only comes into play if it's explicitly requested, which we
never do.
https://pulp.plan.io/issues/1393
fixes #1393
> drop checks for dropDups

- server/pulp/server/managers/content/orphan.py
- server/test/unit/server/managers/content/test_orphan.py
This change appears in both the mongoegine version and the
non-mongoengine version of the "delete orphan by type" method because
although lazy is only supported by mongoengine types, the
``delete_orphan_by_id`` method works with mongoengine types and calls
the non-mongoegine version of "delete orphan by type".
It also updates the mongoengine version of "delete by type" to match the
signature of the non-mongoengine version.
closes #1339
> The lazy catalog is purged during an orphan purge.

- client_lib/pulp/client/commands/repo/importer_config.py
- client_lib/pulp/client/validators.py
- client_lib/test/unit/test_commands_importer_config.py
- client_lib/test/unit/test_validators.py
- common/pulp/common/plugins/importer_constants.py
- server/pulp/plugins/util/importer_config.py
- server/test/unit/plugins/util/test_importer_config.py
https://pulp.plan.io/issues/1201
I'm thinking we should revisit the branding on this feature.  The term *lazy* is fine for an informal reference to the feature (or internal code) but thinking we should use something better for CLI and API as it pertains to repositories. 
Perhaps something like:
CLI:
```
--download-policy=(immediate | background | on_demand)
```
API (importer configuration):
```
download_policy=(immediate | background | on_demand)
```
Thoughts?
> Add lazy option to pulp admin.

- nodes/test/nodes_tests/test_plugins.py
- server/pulp/plugins/conduits/repo_sync.py
- server/pulp/server/controllers/repository.py
- server/test/unit/plugins/conduits/test_repo_sync.py
- server/test/unit/server/controllers/test_repository.py
Conduits are going away someday, but in the mean time the importer
ObjectId is needed during sync so the lazy catalog can be built and this
seems the best place to stash it.
> Add the importer ObjectId to the RepoSyncConduit.

- server/etc/httpd/conf.d/pulp_content.conf
- server/pulp/server/content/web/views.py
The reason 'path_info' is used rather than 'path' is because 'path' is the SCRIPT_NAME/PATH_INFO where the script name would be something like '/pulp/content' and path info is '/var/www/pub/pulp/....'. Interestingly, the script name is being derived as 'http:' or 'https:'. That's clearly not correct, but it doesn't affect us.
I also removed the SSLRequireSSL directive from the Apache
config, as both HTTP and HTTPS requests should be lazy.
> Update the /pulp/content WSGI app to use 'path_info'.

- playpen/ansible/roles/dev/files/bashrc
The quotes are needed because without them bash will attempt to expand the asterisk that precedes which can
cause trouble depending on which folder your cwd is.
> Quote the rm py[co] statements in the bashrc.

- docs/user-guide/installation.rst
qpid-cpp-linearstore is available in all supported distributions now
(woot), so we can remove the note about how you might want to install it
instead of the -store package in favor of installing the -linearstore
package everywhere.
There are also some minor docs fixes:
- Indentations fixed so autonumbering works correctly in the 'Server'
installation steps
- Added subsections to the Repositories section of the install guide,
and made the brokers subsection call out that the guide expects qpid
to be installed
https://pulp.plan.io/issues/1341
fixes #1341
https://pulp.plan.io/issues/842
refs #842
> docs no longer mention qpid-cpp-store

- server/pulp/server/async/scheduler.py
- server/pulp/server/async/worker_watcher.py
- server/test/unit/server/async/test_scheduler.py
- server/test/unit/server/async/test_worker_watcher.py
Pulp had been using the timestamp attribute of Celery's Events to determine when the workers were most
recently available. Due to a bug in Celery, this cause an off-by-one-hour bug for users who live in a locale
that does daylight savings time that is not currently observing daylight savings time (such as New York in
the winter):
https://github.com/celery/celery/issues/1802#issuecomment-161916587
This fixes the issue by using the local_received time which is computed in the receiver by Celery with
time.time() without any timezone shifting attempts.
https://pulp.plan.io/issues/1380
fixes #1380
> Use Celery's local_received time for worker availability.

- pulp.spec
- server/etc/rc.d/init.d/pulp_celerybeat
- server/etc/rc.d/init.d/pulp_workers
Pulp logs to /var/log/pulp/ until logging is set up on systems using the
init scripts. This ensures the directory and the files within are not
world readable.
https://pulp.plan.io/issues/252
> Update the spec file and init scripts so logs aren't 755.

- playpen/ansible/roles/dev/files/bashrc
Removing the py[co] files causes the next Pulp startup to take a long time. The preset command also removes
the py[co] files, and is already an otherwise destructive command. Since this removal makes prestart take a
long time and prestart is a heavily used command during development, it was decided that dropping the
behavior from prestart and leaving it only in preset was favorable.
> Do not rm py[co]'s during prestart.

- devel/pulp/devel/unit/server/base.py
- devel/test/unit/server/test_base.py
- nodes/test/nodes_tests/__init__.py
- server/pulp/server/config.py
- server/test/unit/plugins/util/test_publish_step.py
- server/test/unit/server/test_config.py
pulp.server.config would load /etc/pulp/server.conf unconditionally at
import time. Converting this to lazily loading the config file allows
for the config object to be instantiated without immediately trying
to read the conf. This also allows changing the config files before
loading them, which makes pulp.server.config testable.
fixes #607
https://pulp.plan.io/issues/607
> server.conf is lazily loaded

- server/pulp/plugins/util/publish_step.py
- server/pulp/server/controllers/repository.py
- server/pulp/server/db/model/__init__.py
- server/pulp/server/db/querysets.py
- server/test/unit/plugins/util/test_publish_step.py
- server/test/unit/server/async/test_tasks.py
- server/test/unit/server/controllers/test_repository.py
- server/test/unit/server/db/model/test_dispatch.py
- server/test/unit/server/db/test_model.py
- server/test/unit/server/db/test_querysets.py
In order to not cache query results by default, all models must
use QuerySet objects that are subclasses of QuerySetNoCache. This
modifies all our models that don't have custom QuerySet objects to
use the QuerySetNoCache by default (by inheriting from
AutoRetryDocument) and introduces a superclass for all custom QuerySet
classes to use which derives from QuerySetNoCache.
closes #1395
> Change all QuerySet objects to be QuerySetNoCache objects.

- common/pulp/common/error_codes.py
- server/pulp/plugins/util/verification.py
- server/test/unit/plugins/util/test_verification.py
* The checksum_type now validates while being sanitized
* If its invalid a coded exception is raised
* A coded exception for checksum not being correct is introduced
> Two improvements related to checksum_type validation

- playpen/ansible/dev-playbook.yml
- playpen/ansible/roles/dev/files/bashrc
- playpen/ansible/roles/lazy/files/squid.conf
- playpen/ansible/roles/lazy/tasks/main.yml
- playpen/ansible/vagrant-playbook.yml
This doesn't enable or start the pulp streamer since that gets set up in the vagrant-setup.sh file which happens after the ansible run. When that changes, we can enable the streamer and start it in the lazy role.
> Add lazy to the ansible playbook

- server/pulp/server/managers/repo/unit_association.py
- server/test/unit/server/managers/repo/test_unit_association.py
There was a bug in at least one plugin (and probably more) that forgot to
account for the unit counts during mongoengine conversion. This appears to be a
relatively inexpensive call, and I think is a fine and robust approach instead
of the previous one, where pulp tracked unit count deltas for each operation.
> adding a call to rebuild unit counts at the end of every associate_from_repo call

- server/pulp/server/managers/repo/unit_association.py
- server/test/unit/server/managers/repo/test_unit_association.py
This bug would not have been noticed for plugins with only one unit type.
This fixes the bug and also pulls the criteria-to-units logic out to a separate
function, so it can more easily be reasoned about and tested.
> the associate function failed to limit by unit type ID

- devel/pulp/devel/unit/server/base.py
- devel/test/unit/server/test_base.py
start_logging() is called in _load_test_config, which triggers conf load,
but fails, because loading the config sets defaults, which is blocked by
overridden config attrs.
https://i.imgur.com/KJyc4gz.gifv
restoring the config setters for the duration of _load_test_config
safely prevents that explosion. I also added more/better tests to
confirm expectations of the config override/restore mechanism
fixes #1409
https://pulp.plan.io/issues/1409
> Reorder config attr overrides to prevent explosions

- playpen/all_26.sh
- playpen/all_27.sh
- playpen/all_master.sh
~~These need to be used with caution. Note that the 2.6 script also drops the db. I can remove the db drop and migrations part of it if people think that is a safer option.~~
I have removed the database stuff. Users will still need to migrate (and drop if rolling backwards), but this should not be a part of the script.
> add scripts to switch branches

- server/pulp/server/db/model/__init__.py
I somehow messed up this morning when I merged master into lazy-content. I thought I kept BooleanField in the import list, but apparently I did not.
> Add missing BooleanField import.

- server/pulp/server/async/celery_instance.py
- server/pulp/server/async/tasks.py
- server/pulp/server/controllers/content.py
- server/pulp/server/controllers/distributor.py
- server/pulp/server/controllers/repository.py
- server/pulp/server/db/model/criteria.py
- server/pulp/server/db/reaper.py
- server/pulp/server/maintenance/monthly.py
- server/pulp/server/managers/repo/unit_association.py
- server/pulp/server/webservices/views/repositories.py
- server/test/unit/server/async/test_celery_instance.py
- server/test/unit/server/async/test_tasks.py
- server/test/unit/server/db/model/test_criteria.py
- server/test/unit/server/managers/repo/test_unit_association.py
- server/test/unit/server/webservices/views/test_repositories.py
https://pulp.plan.io/issues/23
> As a user, I can rest easy in the knowledge that Pulp's Celery tasks are not serialized dangerously

- playpen/ansible/roles/dev/files/bashrc
- playpen/ansible/roles/dev/files/motd
I can see this being useful if, for example, you could provide a PID to pdebug and immediately begin debugging that process via SIGTRAP. Maybe it's not the best implementation, though.
> Add a function to the Vagrant bashrc to print Pulp PIDs.

- playpen/dev-setup.sh
python-dnf is a prerequisite for Ansible's dnf module to work, and is not included in Fedora 23 by default.
> Add python-dnf to the dev-setup.sh script.

- server/pulp/server/controllers/distributor.py
- server/pulp/server/controllers/importer.py
- server/pulp/server/controllers/repository.py
- server/test/unit/plugins/conduits/test_repo_sync.py
- server/test/unit/server/controllers/test_distributor.py
- server/test/unit/server/controllers/test_importer.py
- server/test/unit/server/controllers/test_repository.py
- server/test/unit/server/managers/content/test_upload.py
- server/test/unit/server/managers/repo/test_unit_association.py
Distributors/importers conversion mixed with recent serialization work caused some problems. This removes passing importer objects through the tasking system. Additionally, recent changes to the distributor controller mean that it should be passing a model.Repository object to the plugin instead of a repo transfer unit.
> remove importer objects from tasks

- devel/pulp/devel/mock_config.py
- nodes/test/nodes_tests/test_plugins.py
The `mock_config.patch` decorator only worked when code that imported the `config` module and used like `config.config.get()`.  I needed to be fixed to work when imported like:
```
from pulp.server.config import config as pulp_conf
```
Various fixes in test_plugins related to changes in master.
> Fix config patcher; fix nodes tests.

- server/pulp/plugins/util/misc.py
- server/test/unit/plugins/util/test_misc.py
Previously, pulp.plugins.util.misc.create_symlink would not allow
creating a symlink to a file that did not exist. This is now possible.
This change was introduced because the lazy workflow creates symlinks
that are initially broken.
closes #1421
> create_symlink now allows the creation of broken symlinks.

- playpen/ansible/roles/dev/files/bashrc
The recent move of the Crane building from the vagrant-setup.sh to the development .bashrc file caused some
permissions in the resulting environment to disallow pulp_docker from publishing into Crane. This commit fixes that
issue.
> Fix the crane permissions in the preset command.

- playpen/ansible/roles/dev/files/bashrc
- playpen/ansible/roles/dev/files/motd
This currently just uses telnet to connect to localhost port 4444. When
rpdb is updated, it could be used to send a SIGTRAP to a specified
process and attach to it.
> Add pdebug to the Vagrant bashrc.

- server/pulp/server/event/http.py
- server/test/unit/server/event/test_http.py
This addresses two problems: firstly, the listener would
not validate the signature on the server's x509 certificate. Secondly,
it was willing to perform SSLv2 and SSLv3. python-requests validates
certificates by default. On EL6+ and Fedora, it uses the system trust
store to perform this validation.
The protocols supported by requests is determined by urllib3. As of
Fedora 23, SSLv2 and SSLv3 is not supported.
closes #581
> Update the HTTP callback event publish to use requests.

- server/pulp/server/controllers/distributor.py
- server/test/unit/server/controllers/test_distributor.py
I changed this line to fix a smash test yesterday. The iso distributor was expecting a repo object, not a transfer object. However, it turned out to be that the iso plugin was incorrect, not core.
> distributors should be passed a transfer repo, not a repo_obj

- playpen/ansible/roles/dev/files/bashrc
Several files were going missing after preset, including the server's
public RSA key in /var/lib/pulp/static. This ensures everything is
re-linked and re-installed when resetting Pulp.
> Vagrant's `preset` now makes use of pulp-dev.py

- playpen/ansible/library/pulp_facts.py
- playpen/ansible/roles/dev/tasks/main.yml
Each night Jenkies re-builds Pulp and the dependencies we carry. Our
vagrant environment should pull from these (rather than a beta repo)
when on master.
> Update Vagrant to use the nightly repository.

- client_lib/pulp/client/commands/repo/importer_config.py
- streamer/test/unit/streamer/test_config.py
- streamer/test/unit/streamer/test_server.py
Several unit tests are failing on lazy-content due to features missing
from Python 2.4 or 2.6.
> Fix unit test failures on EL5/6 for lazy-content.

- pulp.spec
Modifying mod_xsendfile required version 
closes #[1465](https://pulp.plan.io/issues/1465)
> Changing mod_xsendfile required version

- run-tests.py
Unit tests for the streamer are failing because one or more unit tests
in `server` are making use of OpenSSL and failing to clean the error
stack. This is probably a bug in M2Crypto. This commit simply ensures
the streamer tests run before the server tests.
> Fix 'Unknown OpenSSL error' unit test failure on F23.

- common/pulp/common/error_codes.py
- common/pulp/common/plugins/reporting_constants.py
- common/pulp/common/tags.py
- playpen/ansible/roles/lazy/files/squid.conf
- server/etc/pulp/server.conf
- server/pulp/plugins/conduits/mixins.py
- server/pulp/server/async/app.py
- server/pulp/server/async/celery_instance.py
- server/pulp/server/config.py
- server/pulp/server/controllers/content.py
- server/pulp/server/db/model/__init__.py
- server/test/unit/server/async/test_celery_instance.py
- server/test/unit/server/controllers/test_content.py
- server/test/unit/server/db/test_model.py
- streamer/pulp/streamer/server.py
- streamer/srv/pulp/streamer_auth.wsgi
- streamer/test/unit/streamer/test_server.py
This introduces two new tasks, one to download deferred content units,
and one to download a repository using the lazy catalog.
closes #1199
> Create tasks to download lazy repository content.

- server/pulp/server/controllers/repository.py
- server/pulp/server/managers/content/upload.py
- server/test/unit/server/controllers/test_repository.py
- server/test/unit/server/managers/content/test_upload.py
Updating repository units from platform, due to them
not being reliably updated by plugins.  The code to do
this lives in platform, so we should be able to utilize it
from there
https://pulp.plan.io/issues/1467
re #[1467](https://pulp.plan.io/issues/1467)
> Update Repository Units from platform

- bindings/pulp/bindings/repository.py
- bindings/test/unit/test_repository.py
- client_admin/pulp/client/admin/repo.py
- client_lib/pulp/client/commands/repo/sync_publish.py
- client_lib/test/unit/client/commands/repo/test_sync_publish.py
- docs/dev-guide/integration/rest-api/repo/sync.rst
- server/pulp/server/controllers/content.py
- server/pulp/server/webservices/urls.py
- server/pulp/server/webservices/views/repositories.py
- server/test/unit/server/controllers/test_content.py
- server/test/unit/server/webservices/test_urls.py
- server/test/unit/server/webservices/views/test_repositories.py
This new API is located at ``v2/repositories/<repo-id>/actions/download/``.
This commit also adds support for this API in pulp-admin.
closes #1355
> Add a new REST API endpoint to download lazy repositories.

- server/pulp/plugins/util/publish_step.py
- server/test/unit/plugins/util/test_publish_step.py
If the available_units list passed in were empty at the time process_main()
gets called, which would happen if no units were available remotely, then the
step would try to use self.parent.available_units. This is not the desired
behavior.
> fixed theoretical bug where wrong available_units list could get used

- playpen/cleanup/remove_orphaned_dirs.py
- server/pulp/server/managers/content/orphan.py
- server/test/unit/server/managers/content/test_orphan.py
https://pulp.plan.io/issues/1238
This also adds a script into playpen that can be run to manually clean up any remaining directories that were left behind by orphan cleanup in pulp < 2.8.0
> fix regex to remove content and empty directories on orphan cleanup

- server/pulp/plugins/file/distributor.py
- server/test/unit/plugins/file/test_distributor.py
This is a partial fix for issue 1480. In pulp 2.8, following the mongoengine
refactor, the working directory for plugins is obtained in a different way.
This code didn't get converted until now.
re #1480
https://pulp.plan.io/issues/1480
> file distributor no longer fails to get working directory

- server/pulp/server/db/model/__init__.py
- server/pulp/server/db/model/dispatch.py
- server/pulp/server/managers/auth/principal.py
- server/test/unit/server/db/model/test_dispatch.py
https://pulp.plan.io/issues/1381
`ScheduledCall` model uses `as_dict` to serialize in preparation for a pymongo insert which cannot handle Mongoengine objects.
The `SystemUser` is such a basic object that the simplest path was just to have it inherit from dict (via the old base model) instead of writing a serializer for it. Treating it as a dict has always worked before, this is the most obvious way to ensure that the behavior doesn't change.
> Ensure all values in ScheduledCall are serialized

- devel/pulp/devel/skip.py
- server/pulp/server/managers/repo/unit_association.py
- server/test/unit/plugins/conduits/test_repo_sync.py
- server/test/unit/server/managers/repo/test_unit_association.py
The Docker Importer implements the remove_units() method, but the
platform was still passing the old RepoAssociation objects instead
of the proper Mongoengine units. This commit detects converted
plugins and passes them the new units.
https://pulp.plan.io/issues/1375
re #1375 
This commit might also fix https://pulp.plan.io/issues/1479 but my dev box didn't have the pulp_rpm developer install (to save time during preset) so I haven't had time to check it or not. If it doesn't, I'll just mark that bug unassigned anyway, but thought it was worth mentioning here.
> Pass the updated Mongoengine units to Importer.remove_units().

- nodes/parent/pulp_node/distributors/http/distributor.py
- server/pulp/server/controllers/importer.py
- server/pulp/server/db/model/__init__.py
- server/pulp/server/db/model/dispatch.py
- server/pulp/server/db/querysets.py
- server/pulp/server/webservices/middleware/postponed.py
- server/pulp/server/webservices/views/repositories.py
- server/pulp/server/webservices/views/search.py
- server/pulp/server/webservices/views/serializers/__init__.py
- server/pulp/server/webservices/views/serializers/content.py
- server/pulp/server/webservices/views/users.py
- server/test/unit/server/controllers/test_importer.py
- server/test/unit/server/db/model/test_dispatch.py
- server/test/unit/server/db/test_model.py
- server/test/unit/server/db/test_querysets.py
- server/test/unit/server/webservices/middleware/test_postponed.py
- server/test/unit/server/webservices/views/serializers/test_content.py
- server/test/unit/server/webservices/views/serializers/test_serializers.py
- server/test/unit/server/webservices/views/test_repositories.py
- server/test/unit/server/webservices/views/test_search.py
- server/test/unit/server/webservices/views/test_users.py
Recent changes in the pymongo > mongoengine conversion have resulted in
different ways to represent mongo documents in the REST api views; the
correct way is to use the mongoengine Document serializers wherever
possible. When that isn't possible, remap_fields_with_serializer exists
to use the information in a mongoengine serializer to modify serialized
results properly.
Anything that is using the serialization functions in
pulp.server.webservices.views.serializers.content should automaticaly
benefit from this change, which implicitly fixes redmine #1490.
These changes can also be used to benefit views that don't call the
existing serialization functions by explicitly using the new
remap_fields_with_serializer function as-needed, such as RepoUnitSearch,
which will help (but not fix) …
> content unit search views use content unit serializers

- server/pulp/server/webservices/views/repositories.py
The reproducer in #1478 will still fail, but with a problem that appears
to be specific to the distribution type in pulp_rpm. That problem is being
tracked in https://pulp.plan.io/issues/1505
https://pulp.plan.io/issues/1478
fixes #1478
re #1505
> RepoUnitSearch remaps unit fields using legacy field remapper

- pulp.spec
- server/pulp/server/controllers/repository.py
- server/test/unit/server/controllers/test_repository.py
Prior to this commit, the ``download_started`` method attempted to raise
an exception to stop downloading a file that already existed on disk.
This assumes that https://github.com/pulp/nectar/pull/38 is part of the 1.4.3 release of Nectar.
> Update the lazy download tasks to correctly skip existing files.

- server/pulp/server/controllers/repository.py
- server/test/unit/server/controllers/test_repository.py
This is because not all units have a downloaded flag anymore, and we
don't want them for lazy-related queries.
> Add flag to filter for units inheriting from FileContentUnit.

- server/pulp/server/controllers/importer.py
- server/test/unit/server/controllers/test_importer.py
The importer conversion introduced a regression where when you
update an importer it saved a reference to the new importer
itself in the TaskStatus instead of a serializer verison of it.
When that TaskStatus was fetched, it could not be serialized
by the webservices layer and caused a 500 exception.
https://pulp.plan.io/issues/1483
closes #1483
> Ensures setting an importer serializes into the task result

- nodes/common/pulp_node/conduit.py
https://pulp.plan.io/issues/1487
This conduit was written long before the platform provided generator based methods for fetching content units.  Also, the conduit manipulates the data a little.  And, the `UnitIterator` implements `__len__` which is used to reporting progress.  Long term, I would advocate that nodes use the `SingleRepoUnitsMixin` and find a way to deal with the lack of `__len__()` support.  But, given the future of nodes, I'm just fixing what's here.
I also added some missing docstrings and renamed some variables to make the code clearer.
> ref #1487 - update node conduit to handle both legacy and mongoengine units.

- server/test/unit/server/db/model/test_dispatch.py
Unit tests had invalid ISO8601 date string, causing
tests to fail under mongoengine-0.10
fixes #[1495](https://pulp.plan.io/issues/1495)
https://pulp.plan.io/issues/1495
> Fix unit test to use ISO8601 date string

- server/pulp/server/db/model/__init__.py
- server/test/unit/server/db/test_model.py
Previously, the query used to get catalog revisions would retrieve all
entries for all files in a multi-file content unit. This ensures that
only catalog entries for a single file are retrieved. In combination
with a pulp_rpm PR, this closes issue 1539.
> Update save_revision to work with multi-file units.

- server/pulp/server/controllers/repository.py
`_storage_path` is required when saving the unit. The reason this
already worked with single file units is that `set_storage_path` is
called on them and regenerates the _storage_path. This is required for
multi-file units.
closes #1545
> Load `_storage_path` when reloading the content unit.

- docs/user-guide/deferred-download.rst
- playpen/ansible/roles/lazy/files/squid.conf
Kickstart uses the Range header, which the streamer does not handle.
Furthermore, we will always want to fetch the entire file since Pulp is
going to download the cached file later.
> Update the recommended Squid configuration for Kickstart.

- server/pulp/server/managers/repo/unit_association_query.py
- server/pulp/server/webservices/views/serializers/__init__.py
When building mongo queries, UnitAssociationQuery wasn't translating the
incoming fields to their proper mongo fields via the model serializer.
To start, this change makes "public" the serializer translate methods that
provide useful functionality when incoming criteria get broken down into
their actual mongo queries.
Then, those public methods are used by UnitAssociationQuery to translate
model fields before building queries to mongo.
https://pulp.plan.io/issues/1527
fixes #1527
> unit association query uses model serializers

- docs/user-guide/release-notes/master.rst
- pulp.spec
- server/pulp/plugins/types/database.py
- server/pulp/server/controllers/repository.py
- server/pulp/server/db/connection.py
- server/pulp/server/db/migrations/0007_scheduled_task_conversion.py
- server/pulp/server/db/migrations/lib/managers.py
- server/pulp/server/managers/consumer/applicability.py
- server/pulp/server/managers/consumer/cud.py
- server/pulp/server/managers/consumer/profile.py
- server/pulp/server/managers/content/orphan.py
- server/pulp/server/managers/content/query.py
- server/pulp/server/managers/repo/unit_association_query.py
- server/setup.py
- server/test/unit/server/controllers/test_repository.py
- server/test/unit/server/db/migrations/lib/test_managers.py
- server/test/unit/server/db/test_connection.py
- server/test/unit/server/managers/content/test_query.py
https://pulp.plan.io/issues/1528
fixes #1528 
This pull request does not include the effort needed to provide pymongo >= 3.0.0 in the Pulp RPM repository. That will be done in a separate effort. Until that is done, this pull request will not pass in Jenkies.
https://github.com/pulp/pulp_rpm/pull/775 must be merged before this is merged.
> Update Pulp to work with the pymongo 3.0.0 API.

- server/test/unit/plugins/util/test_publish_step.py
This test started failing because of https://github.com/pulp/nectar/pull/40
> Fix the publish_steps unit test proxy url

- nodes/child/pulp_node/importers/strategies.py
- nodes/test/unit/test_plugins.py
- pulp-dev.py
https://pulp.plan.io/issues/1463
Basically the logic needed to be updated to detect that an updated unit has an associated file that needs to be downloaded.  When this is detected, we need to use the same approach as a newly added unit.  The conduit logic does the right thing depending on whether it's a new unit or an updated one.
I also noticed during testing that pulp-dev needed to be fixed to properly deal with changes introduced as part of: https://github.com/pulp/pulp/pull/2239.
The unit tests (white box) for nodes were stripped down a while back because they were broken as part of a platform change and never fixed/replaced.  This functionality (change) is covered by the remaining (black box) tests.
> Better support updated units with associated files.

- server/pulp/server/controllers/repository.py
- server/pulp/server/controllers/units.py
- server/pulp/server/managers/repo/unit_association.py
- server/pulp/server/managers/repo/unit_association_query.py
- server/pulp/server/webservices/views/content.py
- server/pulp/server/webservices/views/serializers/__init__.py
- server/pulp/server/webservices/views/serializers/content.py
- server/test/unit/server/controllers/test_units.py
- server/test/unit/server/webservices/views/serializers/test_content.py
- server/test/unit/server/webservices/views/serializers/test_serializers.py
When breaking a criteria down into its raw mongo queries, use the
model serializers for a given content type to adjust the unit search
spec as-needed for each content type in the criteria.
https://pulp.plan.io/issues/1479
fixes #1479
https://pulp.plan.io/issues/1533
fixes #1533
https://pulp.plan.io/issues/1535
fixes #1535
https://pulp.plan.io/issues/1563
fixes #1563
> Use model serializers when searching mongoengine content units

- nodes/child/pulp_node/importers/strategies.py
- nodes/test/nodes_tests/test_plugins.py
This fixes a couple of broken tests on master. Looks like the changes were made in 2.6 where they obviously worked, and now break after the merge forward.
https://github.com/pulp/pulp/pull/2340/
@jortel, does this change seem reasonable?
> fix some broken tests

- server/pulp/server/controllers/repository.py
- server/pulp/server/db/fields.py
- server/test/unit/plugins/conduits/test_repo_publish.py
- server/test/unit/server/db/test_fields.py
Due to a bug in datetime utils, we can't rely on mongonegine to
convert a string representation of a timestamp with timezone represented
as Z on end. As a result we now require the date to be supplied as
a datetime object with tzinfo set.
https://pulp.plan.io/issues/1565
closes #1565
> Adds validation to the UTCDateTimeField for mongoengine

- streamer/etc/httpd/conf.d/pulp_streamer.conf
In Apache's default proxy configuration, workers do not use HTTP Keep-Alive or connection pooling. The TCP connections to the origin server will instead be opened and closed for each request[0]. This is *very* inefficient, especially since we know that we're always connection to localhost:3128. This configures a worker (which does use pooling) and sets a connection timeout of one minute.
[0] https://httpd.apache.org/docs/2.2/mod/mod_proxy.html#workers
> Create a proxy worker that pools TCP connections.

- deps/external_deps.json
- deps/python-kombu/1564.patch
- deps/python-kombu/python-kombu.spec
- rel-eng/packages/python-kombu
Adds a patch to python-kombu which uses UUIDs for delivery_tag instead of integers generated by `count()`. This fixes the acks_late issue in python-kombu.
This has been built on EL6, F22, and F23. The EL7 build is blocked, but will get unblocked and built later today. I propose we merge this asap, so downstream can be unblocked.
> Adds patch to have Qpid transport ack all processed messages

- server/pulp/server/async/celery_instance.py
- server/test/unit/server/async/test_celery_instance.py
This removes a scary, multiline warning from celery workers when
they start up
https://pulp.plan.io/issues/23
re #23
> Disables all other celery serializers except JSON

- server/pulp/server/webservices/views/task_groups.py
- server/test/unit/server/webservices/views/test_task_groups.py
Originally we wanted to return  a 404 when querying for a task group that has no tasks
associated with it. However, we always return a task group id when kicking off the
applicability regeneration task. User should be able to see that 0 tasks were dispatched
as part of that task group.
https://pulp.plan.io/issues/1582
closes #1582
> Sends back a group call report for summary of task group with 0 tasks

- server/pulp/server/content/web/wsgi.py
Firstly, the content application does not use the database, so it
shouldn't be initializing a connection to the database. Secondly, this
implementation breaks with pymongo-3.x because it was creating a
connection in a parent process (pre-WSGI forking, I believe) which is
not safe (see https://jira.mongodb.org/browse/PYTHON-961).
Without this, it is not possible to download content from Pulp.
> Remove database initialization from content.wsgi.

- streamer/pulp/streamer/server.py
- streamer/test/unit/streamer/test_server.py
Forwarding incorrect headers was causing Squid to fail to pool TCP
connections. This stops the streamer from forwarding hop-by-hop HTTP
headers (defined in RFC 2069).
This is part of issue #1524
> pulp_streamer no longer forwards hop-by-hop HTTP headers.

- docs/dev-guide/integration/rest-api/consumer/applicability.rst
- server/pulp/server/managers/consumer/applicability.py
- server/pulp/server/webservices/views/repositories.py
- server/test/unit/server/managers/consumer/test_applicability.py
- server/test/unit/server/webservices/views/test_repositories.py
This adds a parameter called 'parallel' to the API call for regenerating applicability
for a repository. When specified and True, the work is done in parallel. When not specified
or False, the work is done as one long running task.
https://pulp.plan.io/issues/1448
closes #1448
> Adds back the API for generating applicability for a repo

- bindings/test/unit/test_search.py
- server/pulp/server/webservices/views/repositories.py
- server/pulp/server/webservices/views/search.py
- server/pulp/server/webservices/views/serializers/__init__.py
- server/test/unit/server/webservices/views/test_search.py
Remove unspecified, nonrequired key value pairs from serialized results
when searching by a criteria object that specifies `fields`.
Working on https://pulp.plan.io/issues/1332 I noticed 500s when specifying invalid fields. Fixing https://pulp.plan.io/issues/1417 made 1332 simpler to fix.
> Allow restriction of fields on Mongoengine documents

- server/pulp/server/content/web/views.py
- server/test/unit/server/content/web/test_views.py
Requests for directories or files that don't exist in the repository
should not be forwared to the streamer. This PR updates the view for the
content WSGI app to check for the link in the published repository
before forwarding a request.
closes #1551
> Don't forward requests for files that don't exist to the streamer.

- pulp.spec
- streamer/setup.py
- streamer/usr/lib/systemd/system/pulp_streamer.service
This is to pave the way for the SELinux work (issue #1459).
> Launch the streamer with its own script in /usr/bin/

- docs/user-guide/deferred-download.rst
It's not clear in the documentation where the squid configuration file is. Also, there are multiple configuration files for squid.
> Specify where the squid configuration file is

- playpen/vagrant-setup.sh
Quite hypocritically I hardcoded a hostname into our development environment. This is a commit of shame.
> Use the hostname in crane.conf

- docs/user-guide/deferred-download.rst
Looking at the server.conf file, it seems like this should be lazy and not
deferred_downloads.
https://github.com/pulp/pulp/blob/1360d5d5c8f9b4f2d959970ca920990f33277022/server/etc/pulp/server.conf#L389
> Fixing a reference to the lazy sync section

- playpen/ansible/roles/dev/files/bashrc
- playpen/vagrant-setup.sh
The vagrant-setup.sh script had been installing, uninstalling,
and reinstalling the plugins which took a long time. This was done
for the DRY principle so that some code could be shared with preset
and vagrant-setup.sh, but it cost a few more minutes on each
vagrant up. This commit reworks preset() so that the more complex
operations are split into a common function that vagrant-setup.sh
can still use, which allows it not to call preset.
> Rework the vagrant-setup.sh script to only install once.

- server/pulp/server/managers/content/orphan.py
- server/test/unit/server/managers/content/test_orphan.py
https://pulp.plan.io/issues/1586
Skip file deletion when unit storage path does not exist.
> Fix orphan purge to not fail when content not downloaded.

- streamer/pulp/streamer/server.py
- streamer/test/unit/streamer/test_server.py
- streamer/usr/share/pulp/wsgi/streamer.tac
Alternate content sources is now supported for repositories using
download policies other than `immediate`.
closes #1451
> Implement alternate content sources in the streamer.

- streamer/setup.py
Twisted's Python packages in EL6 and EL7 are named differently than in
Fedora and other newer distributions. This wasn't a large problem until
we started to use setuputils to make a binary entry, which checks the
installed Python packages.
> Update the dependencies for the streamer for EL.

- deps/external_deps.json
- deps/python-requests-toolbelt/dist_list.txt
Since requests-toolbelt still needs to go through testing
repositories, it will be carried by us for those systems
as well until they make it into stable.
> Adding requests-toolbelt to el6, el7, fc23

- server/pulp/server/controllers/repository.py
- server/test/unit/server/controllers/test_repository.py
It seems this existed to handle a bug elsewhere and is no longer
necessary.
> No longer set the _storage_path when lazy downloading.

- server/pulp/server/event/http.py
- server/test/unit/server/event/test_http.py
By default requests form-encodes post requests. However, there is
a json kwarg that will dump the provided dictionary to JSON and POST
it with the correct content type.
See http://docs.python-requests.org/en/latest/user/quickstart/#more-complicated-post-requests
> Ensure the HTTP event notifier sends JSON-encoded bodies.

- playpen/all_27.sh
Rewrite `playpen/all_27.sh`:
* Make the script behave more safely by adding `set -euo pipefail`.
* Make the script iterate through all directories named `pulp*` in the `~/devel` directory and either install the correct version of that plugin (if we know what that version is), or uninstall the plugin otherwise.
* Make the script disable the pulp-nightlies repo, enable the pulp-2.7-beta repo, and downgrade the python-{mongoengine,pymongo} packages as appropriate.
* Make the script delete the `/etc/httpd/conf.d/pulp_{content,streamer}` symlinks. These links are broken, and if left in place, they prevent httpd from starting.
* Make the script advise the user on how to drop and recreate the mongo database, and how to restart the Pulp services.
> Rewrite script for rolling back to Pulp 2.7

- server/pulp/server/content/storage.py
- server/pulp/server/db/model/__init__.py
- server/test/unit/server/content/test_storage.py
- server/test/unit/server/db/test_model.py
https://pulp.plan.io/issues/1600
Changed `ContentUnit.unit_key_str()` because it did not produce unique results based on unit key.  The problem is that it created a string representation of - a list of sorted *values* that are not associated with their keys.
For example:
```
key_a = {
'a':1,
'b':2,
'c':3,
'd':3,
'e':4
}
key_b = {
'a':3,
'b':2,
'c':1,
'd':4,
'e':3
}
```
**both** *key_a* and *key_b*  produced the same string '[1, 2, 3, 3, 4]'
> Unit storage path based on sha256 of unit key instead of using UUID.

- playpen/all_27.sh
Make the script install Docker from the 1.0-dev branch. Why this branch? I
followed the following procedure for choosing it:
1. Go to https://repos.fedorapeople.org/repos/pulp/pulp/fedora-pulp.repo, follow
the link to the "Version 2.7 Beta Builds" directory, and note the plugin's
version number there. In this case, `pulp-docker-*-1.0.2-1.fc22.noarch.rpm`
packages are listed, which means that the plugin's version number as used in
the last 2.7 beta build is 1.0.2.
2. Find the plugin source code repository, and view that plugin's branches.
3. Choose the branch whose name best matches the beta build version number.
For further context on this process, see https://pulp.plan.io/issues/1351#note-5
and the following discussion.
> Add support for the Docker plugin to all_27.sh

- docs/dev-guide/design/deferred-download.rst
The numbering was a bit off, which made it confusing to follow.
> Re-order the sequence diagram description

- server/etc/httpd/conf.d/pulp_apache_22.conf
- server/etc/httpd/conf.d/pulp_apache_24.conf
By default, Apache allows 100 HTTP requests per TCP connection before
resetting it. Since it is not uncommon for Pulp to serve thousands or
tens of thousands of requests from a single client, it makes sense to
not use the default. This is especially noticeable when performing
Pulp-to-Pulp syncs.
This is related to issue #1629.
> Set Apache to allow unlimited requests per TCP connection.

- server/pulp/server/content/web/views.py
- server/test/unit/server/content/web/test_views.py
This is mostly for the benefit of browsers, since the default MIME
type Django uses is text/html which causes the browser to attempt to
render RPMs and such instead of downloading them.
closes #1627
> Attempt to guess the MIME type of content served with xsendfile.

- deps/python-kombu/569.patch
- deps/python-kombu/python-kombu.spec
- rel-eng/packages/python-kombu
Adding kombu patch for reconnect issue.
Patch is from https://github.com/celery/kombu/pull/569
re #[1635](https://pulp.plan.io/issues/1635)
https://pulp.plan.io/issues/1635
[Scratch](http://koji.katello.org/koji/taskinfo?taskID=419513)
[Fedora 23](http://koji.katello.org/koji/taskinfo?taskID=419515)
[Fedora 22](http://koji.katello.org/koji/taskinfo?taskID=419519)
[RHEL 7](http://koji.katello.org/koji/taskinfo?taskID=419529)
[RHEL 6](http://koji.katello.org/koji/taskinfo?taskID=419533)
> Adding kombu patch for reconnect issue.

- server/etc/pulp/server.conf
- server/pulp/server/config.py
- server/pulp/server/content/web/views.py
- server/test/unit/server/content/web/test_views.py
This setting didn't do anything beyond stopping the content WSGI
application from redirecting the client. If the lazy services haven't
been setup, the client will receive a HTTP 503 or HTTP 404.
closes #1649
> Remove the `enabled` setting for lazy.

- pulp-dev.py
- pulp.spec
- server/pulp/server/content/web/settings.py
- server/pulp/server/content/web/views.py
- server/setup.py
- server/test/unit/server/content/web/test_views.py
- server/usr/share/pulp/templates/404.html
- server/usr/share/pulp/templates/500.html
- server/usr/share/pulp/templates/directory_index.html
In the past we were able to use Apache's directory index feature.
However, for lazy content we pass the request through to the content
WSGI application and are unable to use this feature. This introduces a
simply template that lists the directories and files within a requested
directory, as well as clear HTTP 404 and HTTP 500 error pages.
closes #1512
> Create a simple directory index for the content.wsgi app.

- server/pulp/server/db/model/__init__.py
- server/test/unit/server/db/test_model.py
The query needs to match the catalog index when determining the next revision number.  When a  unit already exists and a plugin is generating catalog entries for a new that I **intends** to add causes duplicate key errors.
Needed for: https://pulp.plan.io/issues/1643
> Query needs to match the catalog unique index.

- server/selinux/server/pulp-celery.te
The old statement whitelisted explicit permissions and was not
fully complete. It worked on most distributions but not all.
This Refpol version will use a superset which is maintained in
Refpol and is appropriate for use anywhere Refpol is available.
closes #1484
https://pulp.plan.io/issues/1484
> Switches SELinux netlink_route_socket to use a Refpol macro

- server/pulp/plugins/util/publish_step.py
- server/test/unit/plugins/util/test_publish_step.py
DownloadStep.cancel() had unconditionally called
self.downloader.cancel(), which caused an AttributeError if
cancel() was called before intialize(). This would happen, for
example, if a pulp-docker sync were canceled during metadata
fetching.
https://pulp.plan.io/issues/1645
fixes #1645
> Return gracefully when DownloadStep.cancel() is called before init.

- docs/user-guide/deferred-download.rst
- streamer/etc/httpd/conf.d/pulp_streamer.conf
We do not actually require Squid to be used as the caching proxy. Many
users may be interested in using a different caching proxy for numerous
reasons (performance, familiarity, ease of configuration etc). This just 
makes it clear that the services are interchangeable with other services.
As a side note, Varnish looks very nice. It'd be worth performance testing it side-by-side with Squid.
> Rework deferred download guide to include Varnish.

- server/pulp/server/content/web/views.py
- server/test/unit/server/content/web/test_views.py
When I initially tested the directory index, I used lazy and links
resolved to /var/lib/pulp/published/.../. However, if the content
exists, os.path.realpath follows it into /var/lib/pulp/content/.
This is one of the issues blocking issue 1654.
> Allow xsendfile to serve /var/lib/pulp/content.

- playpen/all_27.sh
The `all_27.sh` script walks through each repository in `~/devel/pulp*`, checks
out an appropriate branch, and either installs or uninstalls the code in that
branch using the `pulp-dev.py` script. This works so long as all of the
repositories found are, in fact, either Pulp or one of its plugins. pulp-smash
is neither. Refine the script to make it more precisely find correct
repositories.
> Refine playpen/all_27.sh script

- server/pulp/server/managers/repo/unit_association.py
- server/test/unit/server/managers/repo/test_unit_association.py
pulp.server.managers.repo.unit_association.RepoUnitAssociationManager._units_from_criteria()
was not passing the criteria's unit_fields list along to the next
callee. This caused significant memory usage in certian Pulp
operations. This commit corrects that oversight.
https://pulp.plan.io/issues/1662
fixes #1662
> Use the unit_fields from criteria in unit_association.

- docs/user-guide/deferred-download.rst
RHEL6 and its derivatives ship with Squid 3.1. This version of Squid
does not define the access control lists used in the documented
configuration by default. This commit adds the necessary definitions
commented out by default with a note about when to uncomment them.
See the default values for each version:
3.1: http://www.squid-cache.org/Versions/v3/3.1/cfgman/acl.html
3.2: http://www.squid-cache.org/Versions/v3/3.2/cfgman/acl.html
> Update the documented Squid configuration.

- server/pulp/server/content/web/views.py
- server/test/unit/server/content/web/test_views.py
This commit ensures the content.wsgi application only performs repo auth
when the request arrived via HTTPS. Client certificates won't arrive
over HTTP and this was causing access denied errors on unprotected
repositories.
closes #1666
> Only perform repo auth on HTTPS requests.

- playpen/ansible/roles/dev/files/bashrc
- playpen/ansible/roles/dev/files/motd
We'd talked about renaming `preset`, so I started off with that (I renamed it to `pclean`). I also wanted a handy command for easily interacting with the journal for all pulp-related units, but wasn't willing to make yet another copy of the services list, so I converted some repeated lists to arrays and *then* implemented `pjournal`. The `ps ax| grep foo | grep -v grep` is a reimplementation of pgrep`, so I refactored `pprocs`, and now we have so many functions I thought it'd be good to put in a (relatively) easy way to autogenerate a help summary for all the functions in our bashrc.
This PR is broken up into 5 commits so each idea can be reviewed and accepted/rejected. The commits are mostly interdependent, so breaking it up into multiple PRs would probably be tedious for everyone …
> bashrc: I went overboard

- server/selinux/server/build.sh
- server/selinux/server/enable.sh
- server/selinux/server/install.sh
- server/selinux/server/pulp-celery.te
- server/selinux/server/pulp-server.fc
- server/selinux/server/pulp-streamer.fc
- server/selinux/server/pulp-streamer.if
- server/selinux/server/pulp-streamer.te
- server/selinux/server/relabel.sh
I tested this by having lazy installed and all the services running. It compiles on EL6, EL6, and Fedora 22+. Lazy performed correctly on all systems.
If you want to see for yourself, you need to compile the policy and then install it on top of pulp-selinux on a 2.8.0 nightly. You can put SELinux into Enforcing mode and then checkout this PR on the rpm machine.
0. Install and update the `selinux-policy-devel` package on your rpm installation.
1. Set SELinux to Enforcing, or Permissive and monitor for denials `sudo journalctl -f -l | grep denied`. I usually do the Permissive
2. Get the code:  `git fetch`, `git reset --hard origin/1459-Dortmunder-Export`
3. Compile the policy:
```
make NAME=pulp-streamer -f /usr/share/selinux/devel/Makefile DISTRO=rhel7 clean
make NAME=pulp-streamer -f …
```
> Adds pulp-streamer SELinux policy

- docs/user-guide/troubleshooting.rst
- nodes/child/pulp_node/importers/http/importer.py
- nodes/test/nodes_tests/test_plugins.py
- server/pulp/plugins/util/nectar_config.py
- server/pulp/server/controllers/repository.py
- server/test/unit/plugins/util/test_nectar_config.py
- server/test/unit/plugins/util/test_publish_step.py
- server/test/unit/server/controllers/test_repository.py
closes #1626
https://pulp.plan.io/issues/1626
1)This commit fixes the yum repo sync cancellation.
Now cancel_repo_sync() base class  cancels the yum repo sync via calling sys.exit()
2)Some dead code is also removed.
3)Since DownloadConfig.finalize() is not called anymore, nectar config was changed
to use temporary space that tasks use and not use the /tmp for writing temporary files.
I also need to fix tests and celery traceback in the logs
We decided to put the celery traceback into "common issues " in docs.
Another 2 PR should be merged
https://github.com/pulp/pulp_rpm/pull/810
https://github.com/pulp/nectar/pull/44
> 1626 - Fix yum repo sync cancellation.

- server/selinux/server/pulp-streamer.te
re #1459
https://pulp.plan.io/issues/1459
> Restricts squid SELinux workaround to Fedora 23 only

- server/pulp/server/controllers/content.py
- server/test/unit/server/content/sources/test_content.py
https://pulp.plan.io/issues/1692
The bug was introduced here: https://github.com/pulp/pulp/pull/2116/files#diff-4e345a77fb83e6a3dbcb29e9e12b7808R65
... without a corresponding change to the calling code.
fixes #1692
> Fixed a simple argument mismatch bug in content sources code.

- playpen/mongoengine/README
- playpen/mongoengine/dockerimage/Dockerfile
- playpen/mongoengine/dockerimage/rhel-pulp.repo
- playpen/mongoengine/dockerimage/run.sh
- playpen/mongoengine/dockerimage/server.conf
- playpen/mongoengine/dockerimage/validation_check.py
- playpen/mongoengine/run.sh
https://pulp.plan.io/issues/1416
re #1416
This can be tested now. I'm building from this branch into the correct docker hub repository, so you can follow the instructions in the README exactly.
> Dockerizing the 2.8 upgrade validation checker

- docs/user-guide/release-notes/master.rst
This bugfix needs a release note:
https://pulp.plan.io/issues/1610
https://github.com/pulp/pulp/pull/2389
> add release note for sync task change

- server/pulp/server/controllers/repository.py
- server/test/unit/server/controllers/test_repository.py
Returning dictionaries instead of document objects reduces the elapsed time by 30x.  For example: An RPM repository containing 12k units - the time for `get_associated_unit_ids()` is reduced from ~3 seconds to ~100 milliseconds.
> Fix performance regression in associated unit queries.

- streamer/etc/rc.d/init.d/pulp_streamer
This change is required because there is a log statement above the
function definition.
> Move the log function definition up in the init script.

- server/pulp/server/content/web/views.py
- server/test/unit/server/content/web/test_views.py
`REQUEST_SCHEME` is not a variable that must be present in the environ
dictionary, and in fact is _not_ present in EL6's version of Apache
httpd.
> Make use of `wsgi.url_scheme`, a PEP333 required variable.

- docs/user-guide/deferred-download.rst
Squid 3.1 requires a `defaultsite` option on the `http_port` directive,
but this is not required for newer versions of Squid. The recommended
configuration has been updated with a commented out version for RHEL 6
users.
> Update the squid configuration to work with Squid 3.1.

- playpen/ansible/roles/core/tasks/main.yml
This CLI tool automatically inspects your box for packages that were installed from the updates-testing repository, and then prompts you for Bodhi
feedback. It's a handy way for us to participate in the updates that are coming our way.
> Add fedora-easy-karma to the dev environment.

- playpen/ansible/roles/dev/files/bashrc
This commit adjusts psmash to re-activate the developer's
virtualenv when psmash is done if there was one.
> Maintain the dev's activated virtualenv.

- server/pulp/server/webservices/views/serializers/__init__.py
- server/test/unit/server/webservices/views/serializers/test_serializers.py
As mentioned in the referenced issue, these serializer methods are
generally useful and have been exposed as "public" in a previous commit.
This makes that change formal by updating serializer internal references
and tests to use the public methods.
fixes #1555
https://pulp.plan.io/issues/1555
> publicize useful serializer methods 

- server/selinux/server/pulp-streamer.te
This commit adds an SELinux rule to allow the streamer to access
/dev/urandom.
https://pulp.plan.io/issues/1711
fixes #1711
> Add dev_read_urand to the pulp_streamer_t policy.

- server/pulp/server/webservices/views/repositories.py
- server/test/unit/server/webservices/views/test_repositories.py
The mongoengine conversion removed this validation from the manager, it
can now be done with the controller for importers and directly with
Mongoengine for distributors.
closes https://pulp.plan.io/issues/1717
> Fix importer/distributor validation for schedules

- deps/external_deps.json
closes #1635
https://pulp.plan.io/issues/1635
This PR should not be merged until these 3 packages are all present in `stable`.
https://bodhi.fedoraproject.org/updates/FEDORA-2016-5d43aca906
https://bodhi.fedoraproject.org/updates/FEDORA-2016-a172eb2efe
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-cd64dcfc3c
The EL6 Copr repo already has the package and doesn't require any karma promotion or delay. Also Rawhide already has the package; I manually verified that.
> python-kombu-3.0.33-4.pulp is now included via external_deps.json

- playpen/ansible/dev-playbook.yml
- playpen/ansible/roles/pulp_ca/tasks/main.yml
- playpen/ansible/vagrant-playbook.yml
- playpen/vagrant-setup.sh
For too long we have lived with `verify_ssl: False` and `curl -k`. No longer. This sets up a CA and certificate for Apache as part of the Ansible setup.
This is just a first pass. A good next step would be to set up all our other services with certificates from this CA.
> Set up a CA and a cert for Apache in Vagrant.

- playpen/coverage/coverage_hook
I made this nifty thing that'll install all the deps for coverage for
you if you want, but then threw an 'import coverage' up in the
module-level imports, so you can only use that thing if coverage is
already installed.
Woops. Fixed it!
> Can now install coverage without coverage being installed first

- playpen/ansible/dev-playbook.yml
- playpen/ansible/vagrant-playbook.yml
Specifically, replace the refs to "sudo:" with "become:",
and explicitly configure it as described in the docs for that
mechanism: https://docs.ansible.com/ansible/become.html
> address new deprecation warnings seen in ansible2

- deps/external_deps.json
https://pulp.plan.io/issues/1730
> gofer 2.7.5 loads pam libs on demand.

- server/selinux/server/pulp-streamer.te
Also removes inappropriate semicolons behind Refpol statements
re #1459
closes #1726
https://pulp.plan.io/issues/1726
I tested that this compiles as far back as on EL6. I also installed the policy and verified that any tmp directories created by the streamer receive the expected `pulp_streamer_tmp_t` context. Files have the same statements and should work the same. See the output below.
```
[cloud-user@bmbouter-selinux server]$ ls -laZ /tmp/asdfasdf/
drwxr-xr-x. apache apache unconfined_u:object_r:pulp_streamer_tmp_t:s0 .
drwxrwxrwt. root   root   system_u:object_r:tmp_t:s0       ..
```
> Adds pulp_streamer_tmp_t to the pulp-streamer SELinux policy

- server/pulp/plugins/loader/api.py
- server/pulp/plugins/types/database.py
- server/test/unit/plugins/types/test_database.py
Fixes a bug that broke upgrades due to the fact that indexes were being
generated for newly renamed fields before the migrations were run
populating the indexes with 'null' and breaking upgrades if there are
uniqueness contstraints.
closes https://pulp.plan.io/issues/1738
> Create mongoengine indexes only after migrations

- server/pulp/server/db/model/__init__.py
- server/test/unit/server/db/test_model.py
Move the `list_files()` method definition to ContentUnit. This is
convenient when receiving a list of ContentUnit derivatives that may or
may not have inherited from FileContentUnit. The default implementation
on ContentUnit returns an empty list unless `_storage_path` is defined,
so a user can call `list_files` on any ContentUnit subclass when dealing
with content files.
closes #1735
> Move `list_files()` from FileContentUnit to ContentUnit.

- server/pulp/server/content/web/settings.py
- server/pulp/server/content/web/views.py
This commit configures loggers for the content.wsgi application. This
ensures unhandled exceptions are logged to syslog and that logging is
configured so messages can be sent from the views.
closes #1739
> Enable logging for the content.wsgi application.

- server/pulp/server/controllers/repository.py
In commit cb99aa95 the task named sync_with_auto_publish was
deleted and was intented to have all usage switch to
queue_sync_with_auto_publish. This works for everything except
saved scheduled call database records which expect to call the
original task by name.
This updates the task name so when the old records call the task
by name it will still work. All other usage dispatches using the
object queue_sync_with_auto_publish and not by name so this
will continue to work with the existing new code. Also new
scheduled calls save into the db by looking up the task name,
so newly created schedule calls will save into the db just like
the old ones did with this change also.
https://pulp.plan.io/issues/1742
closes #1742
> Specifies the queue_sync_with_auto_publish celery task name

- server/test/unit/server/content/web/test_views.py
Apparently logging calls `os.path.exists`. I have removed the offending
assertion which was not particularly useful in any case.
> Update failing unit test for the content views.

- server/selinux/server/pulp-celery.te
Fedora Rawhide restricts access to /etc/resolv.conf. This commit
adds the sysnet_dns_name_resolve policy to the celery_t context
which allows it to resolve hostnames.
https://pulp.plan.io/issues/1764
fixes #1764
> Allow the Celery process to resolve domain names.

- playpen/ansible/roles/dev/tasks/main.yml
Without this `make html` will fail so you can't build docs in an environment setup by ansible. This issue is so small that I didn't make a PR for it.
> Adds plantuml to ansible dev role so that docs can be built

- server/pulp/server/event/http.py
We make use of the BSON serializer, so we can't let requests do the
serializing for us. Therefore we need to use the `data` kwarg rather
than the `json` kwarg and just set the content type ourselves.
closes #1776
> Don't have requests re-serialize the http event data.

- streamer/test/unit/streamer/test_server.py
This was causing code to execute that required a database connection,
but the tests themselves never used the database.
closes #1494
> Do not use autospec with the mock MongoEngine objects

- streamer/pulp/streamer/server.py
- streamer/test/unit/streamer/test_server.py
If a non-HTTP error occurs in Nectar the streamer would fail to return a
reasonable status code. An example of this is if the domain name is
unresolvable or the host is not accepting connections. This resulted in
an HTTP 200 from the streamer. It is now a HTTP 503.
closes #1734
> Ensure a proper HTTP status code in the streamer on failure

- server/usr/lib/systemd/system/pulp_celerybeat.service
- server/usr/lib/systemd/system/pulp_resource_manager.service
- server/usr/lib/systemd/system/pulp_workers.service
- streamer/usr/lib/systemd/system/pulp_streamer.service
On Fedora 24, the /etc/resolv.conf symlink is not set up when the
network.target starts. This causes a race condition during boot,
and our Celery workers often read the /etc/resolv.conf symlink
before it points at its final destination. This causes our workers
to be unable to resolve domain names.
This commit adjusts our unit files so they wait for the
network-online.target which occurs once the network is ready to
use.
> All Pulp services should wait until the network is online to start.

- server/test/unit/server/event/test_http.py
This commit of shame contains fixes for the unit tests I broke in the
commit a6f8f83514fb7255d540a61028a842860a8fb422.
> Fix the HTTP event notifier unit tests.

- server/pulp/plugins/importer.py
- server/pulp/plugins/util/nectar_config.py
- server/pulp/server/controllers/repository.py
- server/pulp/server/db/model/__init__.py
- server/test/unit/plugins/test_importer.py
- server/test/unit/plugins/util/test_nectar_config.py
- server/test/unit/server/controllers/test_repository.py
- server/test/unit/server/db/test_model.py
- streamer/pulp/streamer/server.py
- streamer/test/unit/streamer/test_server.py
This commit begins a shift towards storing repository PEM data (CA
certificates, client certificates, and client keys) on the
filesystem, and passing paths to those certs to Nectar rather than
allowing nectar to write them in temporary files.
This commit provides the infrastructure for this change, but only
converts the streamer to using it. All other downloads in Pulp
still take the old, now deprecated path.
https://pulp.plan.io/issues/1771
fixes #1771
> Streamer download requests use permanently stored pem files.

- server/selinux/server/pulp-streamer.te
re #1771
https://pulp.plan.io/issues/1771
This was compiled and installed on the machine where the SELinux denial was encountered. After being applied no more SELinux denials were shown. The original denial was:
```
type=SYSCALL msg=audit(1459639923.760:2537): arch=c000003e syscall=21 success=no exit=-13 a0=7fe61c00e3d0 a1=4 a2=7fe644bc0fa8 a3=3 items=0 ppid=1 pid=25805 auid=4294967295 uid=48 gid=48 euid=48 suid=48 fsuid=48 egid=48 sgid=48 fsgid=48 tty=(none) ses=4294967295 comm="pulp_streamer" exe="/usr/bin/python2.7" subj=system_u:system_r:streamer_t:s0 key=(null)
type=AVC msg=audit(1459639923.760:2537): avc:  denied  { search } for pid=25805 comm="pulp_streamer" name="pulp" dev="dm-0" ino=68703432 scontext=system_u:system_r:streamer_t:s0 …
```
> Adds apache_manage_sys_content_rw to pulp-streamer SELinux policy

- streamer/pulp/streamer/server.py
- streamer/test/unit/streamer/test_server.py
The commit ensures that failures to find a catalog entry and failures to
find the content unit referenced by a catalog entry are logged much more
clearly.
I ran across a case where the content unit referenced by a catalog entry was missing from the database. That's bad, and I still don't know how it happened, but this ensures the logging is much clearer. Previously it would complain that the catalog entry was missing even when it was, in fact, the content unit. Both these cases shouldn't happen unless the database is very wrong, so I've made them both error-level.
> Ensure streamer logging is clear about database lookup failures

- docs/user-guide/installation.rst
- server/pulp/server/content/web/views.py
- server/test/unit/server/content/web/test_views.py
Users sometimes make /var/lib/pulp a symbolic link. This worked fine
until we introduced the content wsgi application for lazy syncing. This
modifies it to account for symbolic links when deciding whether or not
it's safe to serve a file. It also documents the necessary Apache
changes that need to take place to make symbolic links work.
closes #1791
> Modify the content web view to account for symbolic links

- server/pulp/server/webservices/views/serializers/__init__.py
- server/test/unit/server/webservices/views/serializers/test_serializers.py
Do not attempt to objectidify `_id`s if `_id` is not a remapped field.
> Translate _id only if it is in remapped fields

- server/pulp/server/db/migrations/0023_importer_tls_storage.py
- server/test/unit/server/db/migrations/test_0023_importer_tls_storage.py
https://pulp.plan.io/issues/1771
fixes #1771
> Add a migration that writes Importer TLS files to local storage.

- docs/user-guide/release-notes/2.8.x.rst
The previous instructions were too destructive. We should only recommend that the user remove pulp-semantic-version package.
> Fixes upgrade instructions

- client_consumer/pulp/client/consumer/cli.py
Prior to this commit, consumers wrote the certificate and private key
issued by the Pulp server's registration process to
/etc/pki/pulp/consumer/consumer-cert.pem with 644 permissions, which
allowed anyone on the host to read the private key. This ensures the
file is written with 600 permissions.
https://pulp.plan.io/issues/1834
fixes #1834
> Create consumer private keys with 600 permissions (CVE-2016-3112)

- pulp.spec
During installation, the RSA key pairs used to validate messages between
the pulp server and pulp consumers were generated in a directory that is
world-readable with a umask of 002. After it was written, the permissions
were modified to protect the key. For a brief moment, the RSA keys were
world-readable. This commit explicitly sets the umask in the %post
scriptlet to be 077 so it is only readable to the owner.
https://pulp.plan.io/issues/1837
fixes #1837
> pulp.spec now generate RSA keys with umask 077 (CVE-2016-3111)

- docs/dev-guide/contributing/bugs.rst
This is going directly into the docs so this PR is against 2.8-release and then will be merged:
PR -> 2.8-release -> 2.8-dev -> master
> Adds IRC Triage process to docs

- common/pulp/common/error_codes.py
- server/pulp/plugins/distributor.py
- server/test/unit/plugins/test_distributor.py
A follow-up PR in pulp_rpm will call the new methods from actual distributors.
https://pulp.plan.io/issues/1835
re #1835
> added distributor methods to ensure all units in a repo have been downloaded

- docs/dev-guide/contributing/bugs.rst
This will be merged to `2.8-release` then to `2.8-dev` then to `master`
> Adds note to docs that triage meeting should be announced in #pulp

- nodes/common/bin/pulp-gen-nodes-certificate
This commit fixes two CVEs.
CVE-2016-3107
=============
Install Node certificate with 640, apache owned (CVE-2016-3107).
Prior to this commit, the Node certificate had been installed
world-readable:
$ ls -lah /etc/pki/pulp/nodes/
total 4.0K
drwxr-xr-x. 2 root root   21 Apr  8 16:37 .
drwxr-xr-x. 4 root root   90 Apr  8 16:37 ..
-rw-r--r--. 1 root root 3.2K Apr  8 16:37 node.crt
This commit adjusts the generation script to limit the permissions
to 0640, and to adjust the group ownership to the apache group.
Credit also goes to Jeremy Cline (Red Hat) for independently
discovering and reporting this issue.
https://pulp.plan.io/issues/1833
fixes #1833
CVE-2016-3108
=============
Safely create tmp dir for the Nodes certificate (CVE-2016-3108).
Security researcher Sander Bos contacted the Pulp …
> CVE-2016-3107 & CVE-2016-3108: Safely generate Nodes certificate.

- server/pulp/plugins/conduits/repo_publish.py
The value of last publish is set upon success https://github.com/pulp/pulp/blob/master/server/pulp/server/controllers/repository.py#L1053
> Fix misleading comment about last_publish date.

- docs/dev-guide/integration/rest-api/repo/cud.rst
This looks like an accidental copy/paste and does not belong.
> Remove inaccurate param from docs

- server/pulp/server/util.py
- server/test/unit/server/test_util.py
https://github.com/pulp/pulp_rpm/blob/pulp-rpm-2.8.2-1/plugins/pulp_rpm/plugins/importers/yum/listener.py#L172
Many plugins could benefit from using this. I have a use for it right now in
pulp_puppet. One this is merged, a follow-up PR will remove it from pulp_rpm.
> moving "deleting" context manager into platform (from pulp_rpm)

- server/bin/pulp-qpid-ssl-cfg
Sander Bos reported that the pulp-qpid-ssl-cfg script creates
certificate files and NSS database files in world-readable unsafe
temporary directory $DIR, from which is than the content copied to
permanent installation directory $INST_DIR with wrongly assigned
permissions, which are corrected only after the copying process is
done. This bug gives attacker a time frame for stealing sensitive
data.
This commit reworks the script to use safe practices to create the
secrets so that they begin their lives in a protected state.
https://pulp.plan.io/issues/1854
fixes #1854
> CVE-2016-3696: Safely generate qpid TLS keys.

- server/bin/pulp-qpid-ssl-cfg
Pulp's pulp-qpid-ssl-cfg script used bash's $RANDOM in unsafe
ways:
0) The default NSS DB password was a single value from $RANDOM,
limiting it to the strings from 0 to 32768.
1) The certutil -z flag receives a "noise file". The script
used $RANDOM to populate a file with numbers to generate this
file. Since $RANDOM was used in this way, the seed file
had low diversity since only 11 possible bytes appeared in the
file (ASCII 0-9 and newline).
This commit alters the script to use /dev/urandom as the source
for generating the DB password and the seed.
https://pulp.plan.io/issues/1858
> CVE-2016-3704: Use stronger seed and DB password.

- server/etc/rc.d/init.d/pulp_celerybeat
Thanks to Sander Bos for pointing out the spelling error.
> Fix a typo in an init script.

- client_lib/pulp/client/launcher.py
- client_lib/test/unit/client/test_launcher.py
https://pulp.plan.io/issues/1844
The config contains api_prefix, but it was not being utilized when
initializing a PulpConnection.
> Use the api_prefix option from config

- docs/user-guide/release-notes/2.3.x.rst
This was recently intorduced when the 2.3 release notes were
adjusted during the 2.8.3 release.
re #950
https://pulp.plan.io/issues/950
> Fixes formatting error in 2.3 release notes

- docs/conf.py
The plugins refer to platform using the intersphinx keyword
'platform'. As the plugin content will start being  built as
one sphinx project, the platform sphinx must also support
the 'platform' keyword.
re #950
https://pulp.plan.io/issues/950
> Adds intersphinx name for 'platform' to sphinx config

- AUTHORS
- common/pulp/common/constants.py
- server/pulp/server/async/scheduler.py
- server/test/unit/server/async/test_scheduler.py
- server/test/unit/server/async/test_tasks.py
Fixes a bug wherein duplicate celerybeat instances will see one or the other going offline as a worker going offline and treats them as such.  Hence, it will try to delete the scheduler's work queue and prints a misleading error message.
https://pulp.plan.io/issues/1113
> Issue #1113: If an instance of pulp_celerybeat dies unexpectedly, Pulp incorrectly tries to "cancel all tasks in its queue"

- server/pulp/plugins/util/metadata_writer.py
- server/test/unit/plugins/util/test_metadata_writer.py
This appears to have been copied over to pulp_rpm at some point
and subsequently modified to have yum-specific behavior. Behaviors
that were not yum-specific and the related tests have been pushed
back to platform.
> Refactor MetadataFileContext to DRY things up

- server/pulp/plugins/util/metadata_writer.py
- server/pulp/plugins/util/verification.py
- server/pulp/server/controllers/repository.py
- server/pulp/server/util.py
- server/test/unit/plugins/util/test_metadata_writer.py
- server/test/unit/plugins/util/test_verification.py
- server/test/unit/server/test_util.py
Calculation of checksums was moved out of the "verification"
module, because it is useful in many more cases than just in
the process of verification. The only plugin using the moved
code is pulp_rpm, and corresponding changes to that plugin
will be in a separate PR.
re #1618
https://pulp.plan.io/issues/1618
> Adds a function to calculate checksums of multiple types at once.

- playpen/vagrant-setup.sh
As of Pulp Smash version 2016.05.05, the various
`pulp_smash.config.ServerConfig` methods default to working with a
configuration file section named "pulp" In earlier versions, the
defaulted to working with a configuration file section named "default."
This change was made so that Pulp Smash can more sanely adapt to the
case where not all Pulp components are on the same host. If the various
components are on different hosts, then the configuration file might
have sections named "pulp," "pulp agent," etc.
No breakage has occurred because Pulp Smash has logic for backwards
compatibility. It's a good idea to update, regardless.
> Update Pulp Smash settings file

- playpen/ansible/roles/dev/tasks/main.yml
- playpen/dev-setup.sh
This change allows the vagrant user to use mock without sudo and checks
out the packaging repository so users can build RPMs inside Vagrant.
> Configure vagrant and dev setup for packaging

- playpen/ansible/roles/dev/tasks/main.yml
These two deps make installing the Jekyll environment easier.
The Jekyll environment itself is done manually with docs
that will be kept in the pulpproject.org directory.
https://pulp.plan.io/issues/1862
re # 1862
> Adds two deps to Vagrant environment

- agent/setup.py
- bindings/setup.py
- client_lib/setup.py
- devel/setup.py
- server/setup.py
As far as I know, the only place we install these libraries from pip is
in dev environments and in the PR tester. So, I think this change
therefore only affects developers working on environments running python
2.4, like el5, and our ability to test our pull requests on environments
running python 2.4, like el5. :)
> deal with libs dropping py2.4 support breaking PR tests

- docs/user-guide/release-notes/2.8.x.rst
We actually had 2.8.4 release notes in there twice due to the 2.8.4
hotfix preempting what became the 2.8.5 release. This pulls the
original 2.8.4 release notes up and labels them as 2.8.5.
> 2.8.5 release notes

- server/test/unit/server/webservices/views/test_repositories.py
I don't know why the jenkins flake8 runs are complaining about this while my
vagrant environment is not, but it does appear to be a valid complaint.
> trying to make flake8 happy by fixing an import statement

- server/pulp/plugins/util/saxwriter.py
- server/test/unit/plugins/util/test_saxwriter.py
fixes #2015 
https://pulp.plan.io/issues/2015
> saxwriter attributes and values can have utf-8 non-ascii chars

- pulp.spec
Sometimes on EL6 boxes, the services can fail to stop in time which
during an upgrade can lead to the packages not getting updated.
> Fixes #1948: Prevent RPM install error when services fail

- docs/Makefile
- docs/conf.py
- docs/dev-guide/contributing/dev_setup.rst
- docs/dev-guide/contributing/documenting.rst
- docs/user-guide/installation/v1_upgrade.rst
- docs/user-guide/release-notes/2.1.x.rst
- docs/user-guide/release-notes/2.4.x.rst
- docs/user-guide/release-notes/2.5.x.rst
This removes intersphinx and removes all content which used
intersphinx.
URLs are also updated to use docs.pulpproject.org instead of
readthedocs.io
Finally, the docs guide is updated to match the current state
of things for contributors.
Also, one really tiny formatting fix I saw while I was editing.
https://pulp.plan.io/issues/2034
fixes #2034
> Removes intersphinx, updates urls, adds doc guide

- Vagrantfile.example
- playpen/ansible/roles/dev/tasks/main.yml
Since all our dependencies are in F24 we don't need to enable external repositories to get a working development environment.
> Update Vagrant and Ansible to work with Fedora 24

- server/pulp/plugins/migration/standard_storage_path.py
- server/test/unit/plugins/migration/test_standard_storage_path.py
https://pulp.plan.io/issues/2056
The platform migration needed to use a stricter comparison when matching the target path to one of the files listed by the unit as contained within the storage_path.
The unit test was pretty hard to understand (even though I wrote it).  Updated the data sets and made the functionality more explicit.
> Fix distribution storage path migration incorrect re-linking of .treeinfo files.

- server/pulp/server/lazy/url.py
- server/test/unit/server/lazy/test_url.py
- server/test/unit/server/webservices/views/test_repositories.py
The lazy URL parser does not work with url-safe base64-encoded queries containing
padding ('='). It's worth investigating why the standard library parser
isn't used, but this is an easy fix for the immediate future.
closes #2031
> Handle queries containing base64 padding gracefully

- docs/dev-guide/integration/rest-api/status.rst
- docs/user-guide/installation/f23-.rst
- docs/user-guide/installation/f24+.rst
- docs/user-guide/release-notes/2.10.x.rst
- docs/user-guide/release-notes/index.rst
- docs/user-guide/scaling.rst
- docs/user-guide/troubleshooting.rst
- server/pulp/server/async/app.py
- server/pulp/server/async/scheduler.py
- server/pulp/server/async/tasks.py
- server/pulp/server/db/manage.py
- server/pulp/server/db/model/__init__.py
- server/test/unit/server/async/test_app.py
Adds a mechanism to enforce that only one resource manager can be executing at a time. Duplicate copies of the resource manager will wait until the original one dies off.
closes #898
https://pulp.plan.io/issues/898
> Prevent more than one resource manager from operating in parallel - #898

- AUTHORS
- oid_validation/pulp/oid_validation/oid_validation.py
- oid_validation/test/test_oid_validation.py
The prefix stripping method used in the oid_validator failed if the
prefix was _not_ found in the path. This fixes that particular issue,
improves readability, and adds a unit test.
fixes #2065
> Update the prefix-stripping method in oid_validator

- server/pulp/server/async/tasks.py
- server/test/unit/server/async/test_tasks.py
If a child Celery process is killed, Celery would recover
but the TaskStatus would stay at running forever. This adds
an additional check when the resource lock is removed which
handles cleanup for any worker being killed.
Because the _release_resource is being run, we know the task
itself has exited, yet if the TaskStatus is not at a final state,
the worker certainly errored.
https://pulp.plan.io/issues/1673
fixes #1673
> _release_resource cleans up killed worker tasks
