pulp/pulp

server/test/unit/server/async/test_tasks.py
This fixes the currently failing tests on master.
=> Fix some failed mocks.

client_admin/pulp/client/admin/auth.py, client_admin/test/unit/test_auth.py
[BZ-1111591](https://bugzilla.redhat.com/show_bug.cgi?id=1111591)
Okaara cannot recognize an empty string as a password, so we should not allow the user to get into a broken state.
Reopened from https://github.com/pulp/pulp/pull/1367
=> 1111591 - require passwords to not be empty strings

server/etc/pulp/server.conf
https://bugzilla.redhat.com/show_bug.cgi?id=1123509
=> 1123509 - deprecated ssl_ca_certificate setting in server.conf

agent/etc/gofer/plugins/pulpplugin.conf, agent/pulp/agent/gofer/pulpplugin.py, agent/test/unit/test_agent.py, docs/user-guide/broker-settings.rst, docs/user-guide/installation.rst, pulp-dev.py, pulp.spec, server/pulp/server/agent/auth.py, server/pulp/server/agent/context.py, server/pulp/server/agent/direct/pulpagent.py, server/pulp/server/agent/direct/services.py, server/pulp/server/db/migrations/0009_qpid_queues.py, server/test/unit/server/agent/direct/test_agent.py, server/test/unit/server/agent/direct/test_services.py, server/test/unit/server/agent/test_auth.py, server/test/unit/server/agent/test_context.py, server/test/unit/server/db/migrations/test_migration_0009.py
Same as PR #1447 (already reviewed) but merging against 2.6-testing instead.
=> port to gofer 2.4

common/pulp/common/error_codes.py, server/pulp/server/managers/repo/importer.py, server/pulp/server/webservices/controllers/repositories.py, server/test/unit/server/managers/repo/test_cud.py, server/test/unit/server/webservices/controllers/test_repositories.py, server/test/unit/test_repo_importer_manager.py
https://bugzilla.redhat.com/show_bug.cgi?id=1084064
=> 1084064 - adding an importer now returns 404 and 400 when appropriate.

server/pulp/server/db/connection.py, server/test/unit/server/db/test_connection.py
https://bugzilla.redhat.com/show_bug.cgi?id=1182335
The way we did username and password auth would have worked if all of our code uses mongoengine, but because some of the code uses PyMongo directly the auth wasn't working. It really should have worked with how it was written IMHO, but it doesn't because of a strange mongoengine behavior. I've filed an [upstream bug with mongoengine](https://github.com/MongoEngine/mongoengine/issues/851) on that.
I've hand tested this also to verify that Pulp works correctly with username and password auth for MongoDB.
I also ensured that all tests pass on all platforms using [Jenkins job 89](https://pulp-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/unittest-pulp/89/). There was one test failure on EL5, but that is unrelated to this PR.
=> 1182335 - Fixes username and password auth for mongoDB connection

server/pulp/server/webservices/application.py, server/test/unit/server/webservices/test_application.py
https://bugzilla.redhat.com/show_bug.cgi?id=1177018
=> 1177018 - raise an exception when wsgi application fails to start

deps/python-nectar/python-nectar.spec
Backported from 2.6-dev. https://github.com/pulp/pulp/pull/1482
=> 1174283 - bump python-requests to 2.4.3

docs/dev-guide/integration/rest-api/content/index.rst, docs/dev-guide/integration/rest-api/content/units.rst, docs/dev-guide/integration/rest-api/repo/content.rst, docs/user-guide/release-notes/master.rst, server/pulp/plugins/model.py, server/pulp/server/constants.py, server/pulp/server/db/migrations/0014_pulp_user_metadata.py, server/pulp/server/webservices/controllers/contents.py, server/test/unit/plugins/test_model.py, server/test/unit/server/agent/test_context.py, server/test/unit/server/db/migrations/test_0014_pulp_user_metadata.py, server/test/unit/server/webservices/controllers/test_contents.py, server/test/unit/test_conduit_mixins.py
https://pulp.plan.io/issues/86
closes #86
=> Add an API for storing custom Unit metadata.

server/pulp/server/webservices/urls.py, server/pulp/server/webservices/views/repo_groups.py, server/test/unit/server/webservices/test_urls.py, server/test/unit/server/webservices/views/test_repo_groups.py
Creates a skeleton for the django conversion of all repo_groups urls.
=> create base for repo_groups django conversion

server/pulp/server/webservices/views/plugins.py, server/test/unit/server/webservices/test_urls.py, server/test/unit/server/webservices/views/test_plugins.py, server/test/unit/server/webservices/views/test_util.py
I will rebase when ready to merge.
=> django conversion /plugins/types/

server/pulp/server/webservices/urls.py, server/pulp/server/webservices/views/root_actions.py, server/test/unit/server/webservices/test_urls.py, server/test/unit/server/webservices/views/test_root_actions.py
This will affect /v2/actions/login URL
link to the manual testing http://ur1.ca/jihzh
=> Introducing Login view.

server/pulp/server/webservices/urls.py, server/pulp/server/webservices/views/consumer_groups.py, server/test/unit/server/webservices/test_urls.py, server/test/unit/server/webservices/views/test_consumer_groups.py
~~1 tests should be added( test_urls.py + test_consumer_group.py)~~
~~2 docs for every class and method should be added~~
~~3 add manual testing fpaste~~
=> Introducing Consumer group view

server/pulp/server/webservices/urls.py, server/pulp/server/webservices/views/content.py, server/test/unit/server/webservices/test_urls.py, server/test/unit/server/webservices/views/test_content.py
Combination of all PRs that were open for /content/*
Hand testing will follow.
Nice to have: replace href building with `reverse()` where possible
=> django conversion /v2/content/

server/pulp/server/webservices/urls.py, server/pulp/server/webservices/views/content.py, server/test/unit/server/webservices/test_urls.py, server/test/unit/server/webservices/views/test_content.py
Hand testing:
http://fpaste.org/178382/26274381/
=> django conversion content/units/<type_id>/<unit_id>/pulp_user_metadata

server/pulp/server/webservices/settings.py, server/pulp/server/webservices/urls.py, server/pulp/server/webservices/views/consumer_groups.py, server/pulp/server/webservices/views/content.py, server/test/unit/server/webservices/test_urls.py, server/test/unit/server/webservices/views/test_consumer_groups.py, server/test/unit/server/webservices/views/test_content.py
=> Add default database definition so EL6 tests are happy

server/pulp/server/managers/repo/publish.py, server/pulp/server/managers/repo/sync.py, server/pulp/server/tasks/repository.py, server/pulp/server/webservices/controllers/repositories.py, server/test/unit/server/managers/repo/test_publish.py, server/test/unit/server/managers/repo/test_sync.py, server/test/unit/server/tasks/test_repository.py
I also rearranged some code to make the sync workflow consistent with the way
other "itineraries" work.
https://bugzilla.redhat.com/show_bug.cgi?id=1120671
=> 1120671 - scheduled tasks show correct resources in task list

server/pulp/server/db/connection.py, server/test/unit/server/db/test_connection.py
https://bugzilla.redhat.com/show_bug.cgi?id=1182279
reference to existing pr https://github.com/pulp/pulp/pull/1603
=> 1182279 - DEBUG level logs database password.

docs/dev-guide/contributing/dev_setup.rst, playpen/dev-setup.sh
This PR adds support for RHEL 7 to our dev-detup.sh, as well as a whole lot of new features:
* checking out pull requests through git
* virtualenvs for each of our projects
* differentiating between upstream and origin in git checkouts
* Custom code checkout path
* The zoo repo is automatically created and sync'd for you
=> Support RHEL 7 in dev-setup.sh.

run-tests.py, server/pulp/plugins/conduits/__init__.py, server/pulp/plugins/conduits/_common.py, server/pulp/plugins/conduits/cataloger.py, server/pulp/plugins/conduits/dependency.py, server/pulp/plugins/conduits/mixins.py, server/pulp/plugins/conduits/profiler.py, server/pulp/plugins/conduits/repo_publish.py, server/pulp/plugins/conduits/repo_sync.py, server/pulp/plugins/conduits/unit_import.py, server/pulp/plugins/conduits/upload.py
This PR cannot be merged until these are merged:
https://github.com/pulp/pulp_docker/pull/53
https://github.com/pulp/pulp_openstack/pull/17
https://github.com/pulp/pulp_puppet/pull/158
https://github.com/pulp/pulp_rpm/pull/641
=> PEP-8 pulp.plugins.conduits.

docs/dev-guide/integration/rest-api/repo/publish.rst, docs/dev-guide/integration/rest-api/repo/sync.rst, server/pulp/server/managers/schedule/utils.py, server/test/unit/server/managers/schedule/test_utils.py, server/test/unit/server/webservices/controllers/test_repositories.py
https://bugzilla.redhat.com/show_bug.cgi?id=1185011
=> 1185011 - pulp-admin says sync schedule deleted succesfully for non-existing schedule id

playpen/dev-setup.sh
Since the dev-script.sh sets apache rights for the home directory the publickey authentication for ssh doesn't work anymore. I also enable the services at boot.
Example: after running dev-script on a vagrant machine i'm not able to log in the machine anymore.
Tell me if i need to prompt for authorization to the user and i will edit the PR
=> Disable StrictMode for ssh

server/pulp/server/async/manage_workers.py, server/usr/lib/systemd/system/pulp_workers.service
https://bugzilla.redhat.com/show_bug.cgi?id=1190756
=> 1190756 - Send SIGQUIT to the workers instead of the proxy.

server/test/unit/server/managers/consumer/test_agent.py
This fixes https://gist.github.com/jortel/16aead622b49e9a1c0f1
=> Fixed incorrectly mocked TaskStatus in consumer agent unit tests

server/pulp/server/managers/repo/group/cud.py
This is a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1192177
=> Removes working directory cleanup from repo group delete

server/pulp/server/webservices/middleware/exception.py
These fields were included in webpy so we should include them in django as well.
=> add traceback and exception to django exception handler

server/pulp/server/webservices/middleware/exception.py
Webpy did this, so should django.
=> handle all 500s with traceback, not just unhandled 500s

server/pulp/server/webservices/middleware/exception.py
=> Revert "add traceback and exception to django exception handler"

server/pulp/server/managers/content/upload.py, server/pulp/server/managers/repo/dependency.py, server/pulp/server/managers/repo/distributor.py, server/pulp/server/managers/repo/group/distributor.py, server/pulp/server/managers/repo/importer.py, server/pulp/server/managers/repo/unit_association.py, server/test/unit/server/managers/repo/test_cud.py, server/test/unit/server/managers/repo/test_dependency.py, server/test/unit/server/managers/repo/test_unit_association.py, server/test/unit/server/webservices/controllers/test_consumers.py, server/test/unit/test_repo_distributor_manager.py, server/test/unit/test_repo_group_controller.py, server/test/unit/test_repo_group_distributor_manager.py, server/test/unit/test_repo_group_manager.py, server/test/unit/test_repo_importer_manager.py, server/test/unit/test_repo_publish_conduit.py, server/test/unit/test_repo_sync_conduit.py, server/test/unit/test_server_managers_content_upload.py
https://bugzilla.redhat.com/show_bug.cgi?id=1193689
=> BZ1193689 - Removed getting of working directories where they are not used

pulp.spec
Bringing this snippet back after it was removed from a merge conflict.
https://github.com/pulp/pulp/commit/f4d2de05d58f71e9baccd18e0ce8020c3e80d6fb#diff-d478c192eb97a80291504e709a4172b3L302
=> Adds back Django to spec file

deps/python-kombu/1195361.patch, deps/python-kombu/python-kombu.spec
https://bugzilla.redhat.com/show_bug.cgi?id=1195361
Adds in a patch from upstream kombu. It was tested up there.
=> 1195361 - Fixes close issue with a backport from upstream Kombu

server/pulp/server/managers/consumer/group/cud.py, server/test/unit/server/managers/consumer/group/test_cud.py
closes [668] (https://pulp.plan.io/issues/668)
=> 668 - 500 error is raised when attempting to create consumer group with already existing id

client_admin/pulp/client/admin/auth.py, client_lib/pulp/client/commands/consumer/query.py, client_lib/pulp/client/commands/criteria.py, client_lib/pulp/client/commands/repo/cudl.py, client_lib/pulp/client/commands/repo/group.py, docs/user-guide/admin-client/consumer.rst
closes [582] (https://pulp.plan.io/issues/582)
=> 582 - Added to --field option some helpful info.

nodes/parent/pulp_node/distributors/http/distributor.py, nodes/parent/pulp_node/distributors/http/publisher.py, nodes/parent/pulp_node/distributors/publisher.py, nodes/test/unit/test_plugins.py, nodes/test/unit/test_publishers.py
re #681
https://pulp.plan.io/issues/681
=> Node distributor removal now deletes published data.

docs/user-guide/release-notes/2.6.x.rst
Add agent related release notes.
=> Agent related 2.6.0 release notes.

docs/user-guide/release-notes/2.6.x.rst
to find the contributors:
```bash
diff <(git shortlog origin/2.5-release origin/2.6-testing -s | cut -f2) \
<( git shortlog origin/2.5-release -s | cut -f2) \
--unchanged-group-format='' --changed-group-format='%<'
```
=> add thank you note for new contributors

playpen/dev-setup.sh
This also installs bash completion.
=> Use epel-release in dev-setup.sh if the OS is CentOS.

server/pulp/server/initialization.py
https://pulp.plan.io/issues/114
closes #114
=> Remove an unnecessary import.

docs/user-guide/server.rst
Closes [157] (https://pulp.plan.io/issues/157)
=> Updated the failure and recovery scenarios in docs.

server/pulp/server/webservices/views/consumers.py
A previous commit introduced some flake8 failures in this file.
=> fix some pep8/flake8 failures

playpen/images/circular-pulp-sticker.svg
This is what was sent to the sticker printer. I removed the "juicy" tagline and got the web address better aligned.
=> adjusting text

bindings/pulp/bindings/auth.py, bindings/test/unit/test_auth.py, docs/user-guide/release-notes/2.7.x.rst
fixes #760
https://pulp.plan.io/issues/760
=> Fixed a bindings bug that caused user creation to fail.

docs/conf.py, docs/dev-guide/contributing/bugs.rst, docs/dev-guide/contributing/building.rst, docs/dev-guide/contributing/documenting.rst, docs/user-guide/release-notes/2.1.x.rst, docs/user-guide/release-notes/2.2.x.rst, docs/user-guide/release-notes/2.3.x.rst, docs/user-guide/release-notes/2.4.x.rst, docs/user-guide/release-notes/2.6.x.rst, docs/user-guide/tuning.rst
=> Updates extlinks and its usage for redmine. Also bug triage docs.

docs/dev-guide/integration/rest-api/permission/actions.rst
=> 400 should be returned if any of the parameters are invalid in permissions

server/pulp/server/managers/consumer/agent.py, server/pulp/server/managers/consumer/group/cud.py, server/pulp/server/managers/consumer/profile.py, server/test/unit/server/managers/consumer/group/test_cud.py, server/test/unit/server/managers/consumer/test_agent.py, server/test/unit/server/managers/consumer/test_bind.py, server/test/unit/server/managers/consumer/test_profile.py
Closes # 829
https://pulp.plan.io/issues/829
=> Some consumer history event types are not implemented

client_admin/pulp/client/admin/auth.py, client_lib/pulp/client/commands/consumer/query.py, client_lib/pulp/client/commands/criteria.py, client_lib/pulp/client/commands/repo/cudl.py, client_lib/pulp/client/commands/repo/group.py, docs/user-guide/admin-client/consumer.rst, docs/user-guide/admin-client/nodes.rst, docs/user-guide/general-reference.rst
Closes  #582 
https://pulp.plan.io/issues/582
=> Updated docs with --field option.

docs/sphinx/user-guide/release-notes/2.5.x.rst
=> Adds 2.5.3 release notes

server/selinux/server/pulp-server.te
=> Removes dontaudit rules from pulp-server SELinux policy

server/pulp/server/managers/auth/permission/cud.py, server/pulp/server/managers/auth/role/cud.py, server/pulp/server/webservices/views/permissions.py, server/test/unit/server/managers/auth/permission/test_cud.py, server/test/unit/server/managers/auth/role/test_cud.py, server/test/unit/server/webservices/views/test_permissions.py
Closes #400
Now with missing required params MissingValue is raised (http://fpaste.org/206023/14279081/)  and
with invalid/nonexistent param passed in the data IvalidValue is raised. http://fpaste.org/206021/08006142/
=> Wrong response code in Grant/Revoke permissions section.

docs/user-guide/index.rst, docs/user-guide/installation.rst, docs/user-guide/release-notes/2.6.x.rst, docs/user-guide/scaling.rst, docs/user-guide/tuning.rst
=> Adds a clustering requirements docs and a release note

server/pulp/server/logs.py, server/test/unit/server/test_logs.py
=> Revert "clear log handlers in stop_logging()."

docs/user-guide/installation.rst
Fix formatting of database line in server.conf description to be more in line with the other examples.
=> Update installation.rst - Formatting fix

server/pulp/server/db/manage.py, server/test/unit/server/db/test_manage.py
https://pulp.plan.io/issues/888
=> Apply indexes to platform models

client_lib/pulp/client/commands/repo/sync_publish.py, client_lib/test/unit/client/commands/repo/test_sync_publish.py, server/pulp/server/async/tasks.py, server/pulp/server/managers/repo/sync.py, server/test/unit/server/async/test_tasks.py
This reverts commit d5d540a3f774e5d27683d73cd111683ea36f4498, reversing
changes made to 253650ce0f405b9776ae2f80aafbfa7eb2e2266c.
=> Revert "Merge branch 'less-logging' into 2.7-dev"

docs/user-guide/scaling.rst
=> Adds logging section to clustering docs

server/pulp/server/webservices/views/search.py, server/test/unit/server/webservices/views/test_search.py
https://pulp.plan.io/issues/312
Moved from https://github.com/pulp/pulp/pull/1778 so this can be merged into 2.7-dev
closes #312
=> fix filters field so GET searches work

docs/user-guide/release-notes/2.7.x.rst, nodes/child/pulp_node/importers/strategies.py, nodes/common/pulp_node/conduit.py, nodes/test/unit/test_conduit.py, nodes/test/unit/test_plugins.py, server/pulp/plugins/conduits/_common.py, server/pulp/plugins/conduits/mixins.py, server/pulp/plugins/conduits/repo_sync.py, server/pulp/plugins/conduits/unit_import.py, server/pulp/plugins/conduits/upload.py, server/pulp/plugins/model.py, server/pulp/server/db/migrations/0016_remove_repo_content_unit_owner_type_and_id.py, server/pulp/server/db/model/repository.py, server/pulp/server/managers/content/upload.py, server/pulp/server/managers/repo/sync.py, server/pulp/server/managers/repo/unit_association.py, server/pulp/server/managers/repo/unit_association_query.py, server/test/unit/plugins/conduits/test_mixins.py, server/test/unit/plugins/conduits/test_profiler.py, server/test/unit/plugins/conduits/test_repo_sync.py, server/test/unit/plugins/conduits/test_unit_import.py, server/test/unit/server/db/migrations/test_0016_remvoe_repo_content_unit_owner_type_and_id.py, server/test/unit/server/db/model/test_repository.py, server/test/unit/server/managers/content/test_orphan.py, server/test/unit/server/managers/content/test_upload.py, server/test/unit/server/managers/repo/test_dependency.py, server/test/unit/server/managers/repo/test_unit_association.py, server/test/unit/server/managers/repo/test_unit_association_query.py, server/test/unit/server/webservices/controllers/test_repositories.py
https://pulp.plan.io/issues/849
=> Remove owner type and and owner_id from repo_content_units

server/pulp/server/async/tasks.py, server/pulp/server/db/manage.py, server/pulp/server/db/model/resources.py, server/test/unit/base.py, server/test/unit/server/async/test_tasks.py, server/test/unit/server/db/model/test_resources.py, server/test/unit/server/db/test_manage.py
closes #727
https://pulp.plan.io/issues/727
=> convert "reserved_resources" collection to mongoengine .

server/pulp/server/db/manage.py, server/pulp/server/db/model/__init__.py, server/test/unit/server/db/test_manage.py, server/test/unit/server/db/test_model.py
Depends on https://github.com/pulp/pulp/pull/1783
https://pulp.plan.io/issues/779
=> Add initial model for repo_content_units

server/pulp/server/managers/content/query.py, server/test/unit/server/managers/content/test_query.py
=> Added OSError 17 exception handling during race condition

server/pulp/server/async/tasks.py, server/test/unit/server/async/test_tasks.py
https://pulp.plan.io/issues/907
closes #907
=> Resource reservations now release properly

server/etc/rc.d/init.d/pulp_celerybeat
=> Fixes typo in init script for pulp_celerybeat

server/pulp/server/webservices/urls.py, server/pulp/server/webservices/views/content.py, server/test/unit/server/webservices/test_urls.py, server/test/unit/server/webservices/views/test_content.py
closes #776
https://pulp.plan.io/issues/776
=> Delete the /content/types api endpoint.

bindings/pulp/bindings/tasks.py, client_admin/pulp/client/admin/tasks.py, client_admin/test/unit/test_pulp_tasks_extension.py
closes #851
https://pulp.plan.io/issues/851
Also fixes https://pulp.plan.io/issues/906
=> As a user, I can see tasks in particular states.

server/pulp/server/db/manage.py, server/pulp/server/db/model/__init__.py, server/test/unit/server/db/test_manage.py, server/test/unit/server/db/test_model.py
closes: [#785](https://pulp.plan.io/issues/785)
=> add a mongoengine model for repositories

docs/user-guide/installation.rst, server/pulp/server/webservices/settings.py
=> Turned off DEBUG in django settings.py

docs/user-guide/release-notes/2.6.x.rst
=> Added proper link to fixed bugs for 2.6.1

docs/user-guide/general-reference.rst
=> Mention in docs that Resource ID value can contain periods.

common/pulp/common/error_codes.py, server/pulp/server/db/model/__init__.py, server/test/unit/server/db/test_model.py
https://pulp.plan.io/issues/847
=> Initial content unit model

client_lib/test/unit/test_commands_importer_config.py
This line was too long and broke flake8 when I merged it forward. Apologies!
=> Fix line that is too long

client_lib/pulp/client/commands/repo/status.py, client_lib/test/unit/client/commands/repo/test_status.py
As described here: https://pulp.plan.io/issues/889
=> Fix for issue 889.

common/pulp/common/error_codes.py, server/pulp/plugins/loader/api.py, server/pulp/plugins/loader/manager.py, server/pulp/server/db/manage.py, server/pulp/server/db/model/__init__.py, server/test/unit/plugins/loader/test_api.py, server/test/unit/plugins/loader/test_manager.py, server/test/unit/server/db/test_manage.py, server/test/unit/server/db/test_model.py
refs: #853
https://pulp.plan.io/issues/853
=> Create entry point to load unit models

docs/dev-guide/integration/rest-api/status.rst
=> The status API return body example in docs is not formatted correctly.

server/pulp/plugins/loader/manager.py, server/pulp/server/db/manage.py, server/test/unit/server/db/test_manage.py
https://pulp.plan.io/issues/916
=> Ensure index fails on mongoengine 0.7.10

docs/user-guide/installation.rst
closes #935
https://pulp.plan.io/issues/935
=> Updates docs. Pulp requires CentOS or RHEL Server

common/pulp/common/error_codes.py
https://pulp.plan.io/issues/947
=> Fix error code PLP0008

pulp-dev.py, pulp.spec
=> 742 - Reload systemctl daemon after install

Vagrantfile, playpen/vagrant-setup.sh, test_requirements.txt
This cannot be merged until all the following pull requests are merged:
https://github.com/pulp/pulp_deb/pull/10
https://github.com/pulp/pulp_docker/pull/68
https://github.com/pulp/pulp_openstack/pull/20
https://github.com/pulp/pulp_ostree/pull/29
https://github.com/pulp/pulp_puppet/pull/182
https://github.com/pulp/pulp_python/pull/41
https://github.com/pulp/pulp_rpm/pull/684
=> Add some dependencies in the vagrant provisioning.

common/pulp/common/plugins/reporting_constants.py, server/pulp/plugins/util/manifest_writer.py, server/pulp/plugins/util/publish_step.py, server/test/unit/plugins/util/test_manifest_writer.py, server/test/unit/plugins/util/test_publish_step.py
https://pulp.plan.io/issues/304
=> Adding a publish step that creates a PULP_MANIFEST

common/pulp/common/error_codes.py
fixes #997 
https://pulp.plan.io/issues/997
=> Fix malformed error strings

server/pulp/server/webservices/views/repositories.py, server/test/unit/server/webservices/views/test_repositories.py
Fixes #1009
https://pulp.plan.io/issues/1009
=> Fix malformed call to unassociate_by_criteria

client_lib/pulp/client/commands/unit.py, docs/user-guide/admin-client/repositories.rst
https://pulp.plan.io/issues/662
fixes #662
=> Minor Change in Documentation

docs/user-guide/admin-client/consumer-group.rst, docs/user-guide/admin-client/index.rst
closes #722
https://pulp.plan.io/issues/722
=> issue #722 - Consumer Groups CLI is not documented

bindings/pulp/bindings/server.py, bindings/pulp/bindings/upload.py
fixes #705
https://pulp.plan.io/issues/705
Ugly to not have unittests on this but the log messages are not currently being confirmed in unit tests
=> Don't print out the file contents when using the uploads api

docs/dev-guide/integration/rest-api/content/orphan.rst, server/pulp/server/managers/content/orphan.py, server/pulp/server/webservices/views/content.py, server/test/unit/server/managers/content/test_orphan.py, server/test/unit/server/webservices/views/test_content.py
closes #667
closes #1035
https://pulp.plan.io/issues/667
https://pulp.plan.io/issues/1035
=> Fixing behaviour of individual orphan removal and orphan removal by type

Vagrantfile, docs/dev-guide/contributing/dev_setup.rst, playpen/ansible/playbook.yml, playpen/ansible/roles/common/tasks/main.yml, playpen/ansible/roles/pulp_server/tasks/main.yml, playpen/vagrant-setup.sh
This commit converts the first few provisioning steps from bash to
Ansible. Additionally, it formally defines a "dev" box in our
Vagrantfile. This will make it easier for us to later split out the
database to its own environment.
=> Convert a few provisioning steps to Ansible.

server/pulp/server/webservices/views/consumers.py, server/pulp/server/webservices/views/content.py, server/pulp/server/webservices/views/repositories.py, server/pulp/server/webservices/views/search.py, server/test/unit/server/webservices/views/test_consumer_groups.py, server/test/unit/server/webservices/views/test_consumers.py, server/test/unit/server/webservices/views/test_content.py, server/test/unit/server/webservices/views/test_repositories.py, server/test/unit/server/webservices/views/test_search.py
fixes #1038 
https://pulp.plan.io/issues/1038
=> unit search works again with the "include_repos" argument

docs/user-guide/content-sources.rst
https://pulp.plan.io/issues/1047
=> Use paths property instead of url property in the example.

server/pulp/server/webservices/views/search.py, server/test/unit/server/webservices/views/test_search.py
fixes: 1040
https://pulp.plan.io/issues/1040
=> only parse json filters if they are present

client_admin/pulp/client/admin/auth.py, client_admin/test/unit/test_auth.py
closes #1058
https://pulp.plan.io/issues/1058
=> Fixed failure during pulp-admin user update.

docs/dev-guide/integration/rest-api/consumer/bind.rst
closes #318
https://pulp.plan.io/issues/318
=> Updating repo and consumer names in the examples.

client_lib/pulp/client/extensions/core.py, client_lib/test/unit/test_client_framework_core.py
closes #1062
https://pulp.plan.io/issues/1062
=> Fixing omit_hidden option in render_document_list

bindings/pulp/bindings/base.py, bindings/pulp/bindings/bindings.py, bindings/pulp/bindings/server_info.py, bindings/test/unit/test_server_info.py, client_admin/pulp/client/admin/admin_status.py, client_admin/pulp/client/admin/cli.py, client_admin/test/unit/test_admin_status.py
closes #1034
https://pulp.plan.io/issues/1034
=> As a pulp-admin user, I can see the results of the /status/ API call

docs/dev-guide/contributing/bugs.rst
closes #977
https://pulp.plan.io/issues/977
=> Update docs about target release.

server/pulp/server/async/tasks.py, server/pulp/server/managers/consumer/agent.py, server/pulp/server/webservices/views/tasks.py, server/test/unit/server/async/test_tasks.py, server/test/unit/server/managers/consumer/test_agent.py, server/test/unit/server/managers/repo/test_cud.py
Had to add some pep8 fix on top of @bmbouter original PR.
=> Fix mongoengine

server/pulp/server/managers/auth/role/cud.py, server/test/unit/server/managers/auth/role/test_cud.py
https://pulp.plan.io/issues/1078
closes #1078
=> Fixed: Unable to remove a user from super-user role

server/pulp/server/webservices/middleware/exception.py, server/pulp/server/webservices/middleware/postponed.py, server/pulp/server/webservices/views/util.py, server/test/unit/server/managers/repo/test_cud.py, server/test/unit/server/webservices/views/test_root_actions.py, server/test/unit/server/webservices/views/test_util.py
https://pulp.plan.io/issues/963
=> fix http header responses

server/pulp/server/controllers/repository.py, server/pulp/server/managers/schedule/repo.py
https://pulp.plan.io/issues/1116
=> schedulers should use queue_syncs and publishs rather than run

client_admin/pulp/client/admin/tasks.py, client_admin/test/unit/test_pulp_tasks_extension.py
closes #851
https://pulp.plan.io/issues/851
=> Adding temporary fix for task state discrepancies.

server/pulp/server/content/sources/model.py
https://pulp.plan.io/issues/1071
fixes #1071
=> Added a check on name of config file for alternate content sources

server/pulp/server/managers/auth/cert/cert_generator.py
Poking around in the auth stuff as part of a story, I saw this scary looking code and realized that it hasn't been used in any pulp release.
=> remove some code that was never used

common/pulp/common/error_codes.py, docs/dev-guide/integration/rest-api/tasks.rst, docs/user-guide/release-notes/master.rst, server/pulp/server/exceptions.py, server/pulp/server/webservices/views/tasks.py, server/test/unit/server/webservices/views/test_tasks.py
https://pulp.plan.io/issues/1111
closes #1111
=> Story 1111: Purge completed task status records

server/test/unit/server/db/test_model.py
@asmacdo Here is the patch for the issue. Thanks for pointing this out.
=> Fix in Unit test for CeleryBeatLock

server/pulp/server/webservices/middleware/exception.py, server/pulp/server/webservices/urls.py, server/pulp/server/webservices/views/util.py, server/test/unit/server/webservices/test_urls.py, server/test/unit/server/webservices/views/test_util.py
https://pulp.plan.io/issues/1140
closes #1140
=> Adds a 404 handler for Django which responds with JSON

common/pulp/common/constants.py, common/pulp/common/error_codes.py, docs/dev-guide/integration/rest-api/tasks.rst
https://pulp.plan.io/issues/1148
closes #1148
=> Refactor 1148: Removing 'timed out' state from Pulp's task state list

bindings/pulp/bindings/server.py, bindings/pulp/bindings/tasks.py, bindings/test/unit/test_tasks.py, client_admin/pulp/client/admin/tasks.py, client_admin/test/unit/test_pulp_tasks_extension.py, common/pulp/common/error_codes.py, docs/user-guide/admin-client/tasks.rst, docs/user-guide/release-notes/master.rst
https://pulp.plan.io/issues/228
closes #228
=> Story 228: Purge Completed task records by pulp-admin user

Vagrantfile
This commit adjusts the video in the guest to use Spice/QXL for
better performance.
=> Configure the Vagrant box to use qxl/spice

nodes/parent/pulp_node/distributors/http/distributor.py
https://pulp.plan.io/issues/1097
closes #1097
=> Issue 1097: Cancelling a task while sync

playpen/ansible/roles/dev/tasks/main.yml
This commit adds dstat, fpaste, iotop, jnettop and python-ipdb to the
development environment.
=> Install some useful development tools.

deps/python-kombu/1168.patch, deps/python-kombu/python-kombu.spec
This does not bump the release because the -9 version has not
yet been built in Koji so it can still be edited.
re #1168
https://pulp.plan.io/issues/1168
=> Patches downstream Kombu with login_method support

playpen/catalog.py
Used to troubleshoot alternate content sources related issues.
=> Diagnostic tool used to inspect the content catalog.

run-tests.py, server/pulp/server/async/celery_instance.py, server/pulp/server/constants.py, server/pulp/server/webservices/wsgi.py, server/test/unit/server/async/test_celery_instance.py
re #1216
https://pulp.plan.io/issues/1216
=> Adds django settings environment variable to all celery processes

common/pulp/common/pic.py
closes #1228
https://pulp.plan.io/issues/1228
=> Adds verify_ssl as an option to pic.common.connect()

server/pulp/plugins/conduits/_common.py, server/pulp/plugins/conduits/mixins.py, server/pulp/server/db/model/__init__.py, server/pulp/server/managers/repo/unit_association.py
fixes #1212 
https://pulp.plan.io/issues/1212
=> Fixed the unit unassociate workflow to work with mongoengine models and filters

docs/user-guide/release-notes/2.7.x.rst, docs/user-guide/scaling.rst, server/etc/pulp/server.conf, server/pulp/server/async/scheduler.py, server/pulp/server/config.py, server/pulp/server/db/connection.py, server/pulp/server/db/model/__init__.py, server/test/unit/server/db/test_connection.py, server/test/unit/server/db/test_model.py
re #1
https://pulp.plan.io/issues/1
Reopened against 2.7-testing from https://github.com/pulp/pulp/pull/2042
=> Introduce unsafe_autoretry setting

bindings/pulp/bindings/bindings.py, bindings/pulp/bindings/consumer.py, bindings/pulp/bindings/server.py, bindings/pulp/bindings/static.py, bindings/test/unit/test_static.py, client_consumer/pulp/client/consumer/cli.py, client_consumer/test/unit/test_cli.py
The recommit of double-shame :)
Originally https://github.com/pulp/pulp/pull/2031, but this was negative commited because it was branched from 2.6-dev rather than the merge-base of 2.7-testing and 2.6-dev.
=> convert consumer register to bindings

client_consumer/pulp/client/consumer/cli.py, server/pulp/server/webservices/views/repositories.py, server/test/unit/server/webservices/views/test_repositories.py
Since I this has been refactored in master, this change is going into a different file. 
Small change, but since it is a different file and an unit test changed, I thought it would be better to open a PR for this merge.
=> 2033 merge forward

docs/dev-guide/integration/rest-api/index.rst, docs/dev-guide/integration/rest-api/server_plugins.rst
closes #1121
https://pulp.plan.io/issues/1121
=> Adding documetation for /v2/plugins/* API

server/pulp/server/async/app.py, server/pulp/server/async/tasks.py, server/test/unit/server/async/test_app.py
This code moved between 2.7 and 2.8.
https://github.com/pulp/pulp/pull/2063
=> merge forward for PR #2063

server/pulp/server/webservices/middleware/exception.py
Incorrect syntax in a new PLP error resulted in `str(e) = None` and was not obvious to fix.
=> Improve custom pulp exception incorrect syntax error

server/pulp/server/db/fields.py, server/pulp/server/db/model/__init__.py, server/test/unit/server/db/test_fields.py
https://pulp.plan.io/issues/1231
=> Lazy content catalog model object.

common/pulp/common/plugins/importer_constants.py, server/pulp/plugins/util/importer_config.py, server/test/unit/plugins/util/test_importer_config.py
https://pulp.plan.io/issues/1200
=> Add lazy properties to import configuration.

server/pulp/server/async/tasks.py, server/test/unit/server/async/test_tasks.py
https://pulp.plan.io/issues/1244
=> check that schedule exists before attempting to use it

playpen/dev-setup.sh
Add prose comments to script at `playpen/dev-setup.sh`.
=> Add comments to dev-setup.sh script

server/pulp/server/controllers/content.py, server/pulp/server/controllers/repository.py, server/pulp/server/db/fields.py, server/pulp/server/db/model/__init__.py, server/test/unit/server/controllers/test_repository.py, server/test/unit/server/db/test_fields.py
https://pulp.plan.io/issues/1181
Still needs unit tests but wanted to get some pre-review.
=> Add content download task.

server/pulp/server/managers/content/query.py, server/pulp/server/managers/repo/unit_association_query.py, server/test/unit/server/managers/content/test_query.py
deprecates a redundant manager function
=> fixes usages of the obsolete "content_types_db"

server/pulp/server/db/model/__init__.py
Changes:
- Flatten embedded documents.  Mainly because they won't be supported by postgres in the future.
- Renamed: `plugin_id` => `importer_id`.  More accurate.
- Renamed `relative_path` => `path`.  The value is an absolute path.
At @jeremycline request, the referencing code has not be fixed to match these changes.  He will make the necessary changes in subsequent PR.
=> flatten the catalog model.

client_consumer/pulp/client/consumer/cli.py
Delete imported server public key
Fixes [#1260](https://pulp.plan.io/issues/1260)
=> Delete server public key as well

deps/external_deps.json
closes #922
https://pulp.plan.io/issues/992
=> Adding saslwrapper to the external deps list.

server/pulp/server/managers/repo/unit_association_query.py
This change was not merged forward correctly:
https://github.com/pulp/pulp/commit/b54816cf9f68dc099425b33e5027a82d16e1570d
This also fixes https://pulp.plan.io/issues/1322
=> fix a merge forward issue that broke unit association

server/pulp/server/webservices/views/search.py, server/test/unit/server/webservices/views/test_search.py
https://pulp.plan.io/issues/981
closes: #981
=> wrap the use of criteria to catch invalid criteria objects

nodes/extensions/admin/pulp_node/extensions/admin/commands.py, nodes/extensions/consumer/pulp_node/extensions/consumer/commands.py, nodes/test/unit/test_admin_extensions.py, nodes/test/unit/test_consumer_extensions.py
closes #1286
https://pulp.plan.io/issues/1286
=> Improving pulp nodes bind/unbind behaviour

streamer/pulp/streamer/server.py, streamer/test/unit/streamer/test_server.py
Rather than dispatching a task, the lazy streamer now adds an entry to
the deferred_download collection.
=> Modify the lazy streamer to make deferred_download entries.

server/pulp/server/lazy/url.py, server/test/unit/server/lazy/test_url.py
Functional tests already exist: https://github.com/pulp/pulp/blob/lazy-content/server/test/functional/test_lazy_url.py.  Just needed to add the unit tests.
=> add signed url unit tests.

common/pulp/common/error_codes.py, server/pulp/plugins/file/model_distributor.py, server/pulp/plugins/loader/manager.py, server/pulp/server/content/storage.py, server/pulp/server/db/manage.py, server/pulp/server/db/model/__init__.py, server/pulp/server/managers/content/orphan.py, server/test/unit/plugins/file/test_model_distributor.py, server/test/unit/plugins/loader/test_manager.py, server/test/unit/plugins/util/test_publish_step.py, server/test/unit/server/content/test_storage.py, server/test/unit/server/db/test_model.py, server/test/unit/server/managers/content/test_orphan.py
* renames source_location to _source_location
* renames unit_type_id to _content_type_id
* adds validation to AutoRetryDocument for the _ns field definition
* adds on-startup validation of subclasses of ContentUnit
* adds tests for new code and fixes other tests
=> Udates ContentUnit and adjusts platform code to match

docs/dev-guide/integration/rest-api/tasks.rst, server/pulp/server/webservices/urls.py, server/pulp/server/webservices/views/task_groups.py, server/test/unit/server/webservices/views/test_task_groups.py
https://pulp.plan.io/issues/1206
closes #1206
=> Adds task groups status API endpoint

docs/dev-guide/contributing/dev_setup.rst, docs/dev-guide/integration/rest-api/server_plugins.rst
Also some small docs formatting fixes
=> Adding instructions on configuring PyCharm w/ Vagrant

server/pulp/server/db/model/__init__.py, server/test/unit/server/db/test_model.py
There are publishers and other components that expect the unit.storage_path to include the file name for single file units.  On master, `set_content()` updates the storage path when single files are copied to include the file name.  To support `lazy`, we need to provide a way for the plugin to be more involved in setting the storage path to include the file name.  This is hacky and I don't really care for it much but it get's the job done until we can fix unit/file modeling.  Unfortunately, we'll need to live with this unitl 3.0.
Importers will need to do the following for single file units:
```
unit = MyUnit()
unit.set_storage_path('dog.rpm')
unit.save()
if not lazy:
unit.import_content(path_to_downloaded_file)
```
Publishers can work like they do currently.
=> Provide means for including the file name in storage path

playpen/ansible/roles/dev/files/flower.service, playpen/ansible/roles/dev/tasks/main.yml
=> Remove flower from the vagrant environment.

deps/external_deps.json
* python-amqp
* python-billiard
* python-celery
* python-kombu
=> Adds external_deps entries for 4 deps

deps/README
* python-amqp
* python-billiard
* python-celery
* python-kombu
=> Adds updates to dependency READMEs for 4 dependencies

playpen/ansible/roles/dev/files/bashrc, playpen/ansible/roles/dev/files/drop_database.js, playpen/ansible/roles/dev/tasks/main.yml
This command stops Pulp, erases the Pulp database, /var/lib/pulp, reruns the migrations, and then starts Pulp.
=> Add a preset command to the dev environment.

deps/external_deps.json, rel-eng/packages/python-mongoengine
* Updates tito tag to 0.9.0-1 for python-mongoengine
* Adds python-mongoengine and python-pymongo to external_deps.json
=> pymongo and mongoengine changes

deps/external_deps.json
https://pulp.plan.io/issues/1340
re #1340
=> Removes qpid 0.26 stack from external_deps.json

deps/external_deps.json
Update platforms fc22 and fc23.
=> updated platforms

playpen/ansible/roles/dev/files/bashrc
This also restarts Pulp before running the tests.
=> Remove any pyc files before running pulp-smash.

server/pulp/server/webservices/views/serializers/__init__.py, server/test/unit/server/webservices/views/serializers/test_serializers.py
https://pulp.plan.io/issues/1384
=> serializer should not fail if masked or removed field is None

playpen/ansible/roles/qpidd/tasks/main.yml
=> ansible install newer qpidd in fc23

comps.xml
https://pulp.plan.io/issues/1061
closes #1061
=> Updates comps.xml to use qpid-tools instead of python-qpid-qmf

docs/dev-guide/contributing/building.rst
https://pulp.plan.io/issues/1311
closes #1311
=> Updated build docs

server/pulp/server/controllers/repository.py, server/pulp/server/db/model/__init__.py, server/test/unit/server/controllers/test_repository.py, server/test/unit/server/db/test_model.py
General fixes and changes needed to better support plugins.
- The repository controller: `find_repo_content_units()` is called on repositories containing multiple types.  The query is not always valid for all types and raises `InvalidQueryError`.  Not sure if this is a good way to deal with this but seemed like the only option.
- For backwards compatibility we need the `storage_path` on single-file units to include the file name.  To facilitate this, the FileContentUnit needs to provide a way for plugins to specify what the file name is.  The semantics were challenging here.  A `set_filename()` method would suggest that it sets a `filename` attribute on the unit (which is does not).  So, don't love it but went with a *setter* instead.  Long term, when we can change file unit modeling, we …
=> ref #1373 - changes needed to support plugins.

playpen/ansible/roles/dev/tasks/main.yml
I recently added rpdb to the development environment, but it is not very useful without telnet ☺
=> Add telnet to the development environment.

server/pulp/server/controllers/repository.py, server/test/unit/server/controllers/test_repository.py
Here are the docs to confirm: http://docs.mongoengine.org/apireference.html#mongoengine.queryset.QuerySet.only
=> fixing use of mongoengine .only() function

nodes/child/pulp_node/importers/strategies.py, nodes/common/pulp_node/constants.py, nodes/parent/etc/httpd/conf.d/pulp_nodes.conf, nodes/parent/pulp_node/distributors/publisher.py, nodes/test/unit/test_plugins.py, nodes/test/unit/test_publishers.py, pulp-dev.py, pulp.spec
https://pulp.plan.io/issues/1337
See details ^^.
=> ref #1337 - Discontinue linking files for each unit during node publish.

server/pulp/server/db/model/__init__.py, server/test/unit/server/db/test_model.py
`ContentUnit.NAMED_TUPLE` doesn't require a call to
`ContentUnit.attach_signals` to be populated. It is accessible
immediately after defining a `ContentUnit` model class.
=> ContentUnit.NAMED_TUPLE implemented as a descriptor

client_admin/pulp/client/admin/tasks.py, client_admin/test/unit/test_pulp_tasks_extension.py
https://pulp.plan.io/issues/1418
closes #1418
=> Adds a filter to the search query used by pulp-admin to query for tasks

docs/dev-guide/integration/rest-api/repo/cud.rst
https://pulp.plan.io/issues/1362
=> update distributor_config docs to be clearer

server/pulp/server/webservices/views/decorators.py, server/test/unit/server/webservices/views/test_decorators.py
It also no longer causes a 404 for missing users, which is an incorrect
behaviour since this decorator is used on all views.
closes #1399
=> The auth decorator no longer causes a 404s for consumers.

server/pulp/server/db/model/__init__.py, server/test/unit/server/db/test_model.py
Setting the _storage_path in `__init__()` was causing the calculated _storage_path to be used instead of values pulled from the db.
After using the `storage_path =` in the importers, I decided the more explicit `set_storage_path()` would be more explicit and intuitive.
=> Better semantics.

server/pulp/server/controllers/repository.py, server/test/unit/server/controllers/test_repository.py
Discussed with @bmbouter and decided this would be best fixed by having the caller further qualify the query by including type_ids.
=> Revert catching query exception fix.

playpen/mongoengine/validation_check.py
Validation check script to run existing objects through the validation logic.
closes #[1415](https://pulp.plan.io/issues/1415)
=> 1415 - Validation Check Script

pulp.spec, server/etc/httpd/conf.d/pulp_content.conf, server/pulp/server/content/web/views.py, server/pulp/server/controllers/repository.py, server/pulp/server/db/model/__init__.py, server/test/unit/server/content/web/test_views.py, streamer/etc/httpd/conf.d/pulp_streamer.conf, streamer/etc/pulp/streamer.conf, streamer/pulp/streamer/server.py, streamer/test/unit/streamer/test_server.py
This commit addresses some of the issues brought up during the
lazy-content branch review. Others have been fixed in a separate PR,
while some have been written as tasks for the future.
=> Update the lazy-content branch based on the PR review.

server/pulp/plugins/importer.py, server/pulp/server/content/sources/event.py, server/pulp/server/db/model/__init__.py
Addressing *some* comments on lazy-content branch review.
=> Fixes to lazy-content branch.

server/pulp/plugins/util/publish_step.py, server/test/unit/plugins/util/test_publish_step.py
https://pulp.plan.io/issues/1453
related to https://github.com/pulp/pulp/pull/2289
=> fixing doc blocks, and passing correct Repository object to controller

deps/external_deps.json
https://pulp.plan.io/issues/1408
=> Adding python-semantic_version to the external deps list.

server/pulp/server/controllers/distributor.py, server/test/unit/server/controllers/test_distributor.py
=> Serialize distributor before passing to task

playpen/mongoengine/validation_check.py
Updates the validation check script to take advantage
of the entry points that plugins are supposed to set up.
This way we don't have to modify the check script for
every possible plugin.
https://pulp.plan.io/issues/1415
re #[1415](https://pulp.plan.io/issues/1415)
=> Update validation_check to use entry points

nodes/test/nodes_tests/test_admin_extensions.py, nodes/test/nodes_tests/test_plugins.py, pulp-dev.py, server/pulp/server/webservices/wsgi.py
New flake8 update has some issues.  This patch fixes latest
issues.
https://pulp.plan.io/issues/1517
closes #1517
=> Fix flake8 errors on build

server/pulp/server/webservices/views/consumer_groups.py, server/pulp/server/webservices/views/consumers.py
closes #1541
https://pulp.plan.io/issues/1541
=> 1541 - Retrieve bindings by consumer and repository call fails

server/pulp/server/db/model/__init__.py, server/test/unit/server/db/test_model.py
Plugins save then call import_content on FileContentUnit objects.
This ensures that if an error happens on import_content, we also
clean up after ourselves.
re #[1457](https://pulp.plan.io/issues/1457)
https://pulp.plan.io/issues/1457
=> Ensure file objects are cleaned up on error

nodes/child/pulp_node/importers/strategies.py
This issue is not caught by 2.7 flake8 check and only shows up after the merge forward.
=> fix pep 8 issue

server/pulp/server/webservices/views/content.py, server/test/unit/server/webservices/views/test_content.py
=> check for fields before translating them

server/pulp/server/db/migrations/0022_distributor_collection_trim.py
I haven't tested this, but I did confirm the problem in mongo so I expect this to fix the problem. Posting to unblock @mhrivnak 
https://pulp.plan.io/issues/1577
=> index must be dropped before fieldname can change

streamer/pulp/streamer/server.py
=> The streamer now pools connections.

server/pulp/server/content/sources/container.py, server/pulp/server/content/sources/model.py, server/test/unit/server/content/sources/test_container.py, server/test/unit/server/content/sources/test_model.py
https://pulp.plan.io/issues/1579
Mainly to support reusing http sessions when used with the streamer.
=> Share http sessions in content sources.

server/pulp/server/webservices/views/consumer_groups.py, server/test/unit/server/webservices/views/test_consumer_groups.py
closes #1542
https://pulp.plan.io/issues/1542
=> 1542 - Repository (un)binding for consumer_groups fails

docs/user-guide/admin-client/authentication.rst, docs/user-guide/admin-client/repositories.rst
Updating the docs at few places.
=> Fixed: Update the command line help text in docs

docs/dev-guide/conventions/criteria.rst
fixes #1575
https://pulp.plan.io/issues/1575
=> Extremely nitpicky docs tweak

devel/pulp/devel/unit/server/base.py, devel/test/unit/server/test_base.py
The code to shake an angry fist when the server conf is modified during
testing has been in place for a while, but it seems like my recent
tinkering in this area has resulted in exceptions being thrown when
modifying the conf where they weren't before.
I think other commits (mostly bef25c08bd65f4bf1bd149ed037ccf816f33c04e)
have done a good job of making that code reliable; all this does is make
the exception that gets raised return a (hopefully) useful error message,
indicating what config modifying function was called, and with what
args/kwargs.
c7afae1a78f911c48d634325b9658c53e3d60d78 is a good example of properly
mocking the config during a test run, rather than altering it.
=> A kindler, gentler config modification exception

server/pulp/server/controllers/repository.py, server/pulp/server/db/model/__init__.py, server/pulp/server/db/querysets.py, server/test/unit/server/controllers/test_repository.py
closes #1610 
https://pulp.plan.io/issues/1610
=> fix added, updated, and removed counts for mongoengine converted plugins

playpen/all_27.sh
@Ichimonji10, weird. I think this is a dnf docs bug.
=> change dnf syntax to enable/disable repos

deps/external_deps.json, deps/python-kombu/1212200.patch, deps/python-kombu/python-kombu.spec, rel-eng/packages/python-kombu
Add kombu patch 1212200
scratch:
http://koji.katello.org/koji/taskinfo?taskID=419105
Builds
[fedora23](http://koji.katello.org/koji/taskinfo?taskID=419107)
[fedora22](http://koji.katello.org/koji/taskinfo?taskID=419114)
[rhel7](http://koji.katello.org/koji/taskinfo?taskID=419131)
[rhel6](http://koji.katello.org/koji/taskinfo?taskID=419205)
=> Add patch back to kombu

server/pulp/server/db/manage.py, server/test/unit/server/db/test_manage.py
https://pulp.plan.io/issues/1477
closes #1477
=> Adds unit-key uniqueness constraint for all unit types

server/pulp/server/managers/consumer/applicability.py, server/test/unit/server/managers/consumer/test_applicability.py
closes #1625
https://pulp.plan.io/issues/1625
=> Fix applicability calculation for repos if parallel flag is set to true.

client_admin/pulp/client/admin/tasks.py
closes #1664
https://pulp.plan.io/issues/1664
=> Handle empty tags in task

oid_validation/pulp/oid_validation/oid_validation.py, oid_validation/test/test_oid_validation.py
Depending on how a request arrives and who is performing the
authentication, `mod_ssl.var_lookup` may not be present and
`SSL_CLIENT_CERT` is. This commit causes the authenticator to look in
both locations for the certificate and if neither can be found, it
returns `False`. Previously, it would cause an HTTP 500 by raising a
KeyError.
closes #1667
=> Use SSL_CLIENT_CERT and fall back to mod_ssl.var_lookup.

deps/python-kombu/571.patch, deps/python-kombu/python-kombu.spec, rel-eng/packages/python-kombu
Adding patch to update qpid transport with the new names in qpid
=> Qpid transport patch

AUTHORS, common/pulp/common/error_codes.py, server/pulp/plugins/loader/manager.py, server/pulp/server/controllers/repository.py, server/pulp/server/db/model/__init__.py, server/pulp/server/managers/repo/_common.py, server/pulp/server/managers/repo/unit_association.py, server/test/unit/plugins/loader/test_manager.py, server/test/unit/server/db/test_model.py
https://pulp.plan.io/issues/1636
closes #1636
=> Issue 1636: Developer oriented error messages added as coded exceptions

playpen/vagrant-setup.sh
This fixes this bug:
https://github.com/PulpQE/pulp-smash/issues/99
=> Fix the linter with psmash.

server/pulp/server/controllers/repository.py, server/pulp/server/event/http.py, server/pulp/server/managers/event/fire.py, server/test/unit/server/controllers/test_repository.py, server/test/unit/server/event/test_http.py
https://pulp.plan.io/issues/1657
=> Use pulp serializer to handle ObjectIds

pulp.spec
re #1459
https://pulp.plan.io/issues/1459
=> Adds the pulp-streamer SELinux policy the spec file

server/selinux/server/pulp-celery.te, server/selinux/server/pulp-server.te
closes #1688
https://pulp.plan.io/issues/1688
=> Adds pulp_cert_t manage files and dirs to pulp-celery SELinux policy

server/pulp/plugins/importer.py, server/pulp/plugins/util/nectar_config.py, server/test/unit/plugins/test_importer.py, streamer/pulp/streamer/server.py, streamer/test/unit/streamer/test_server.py
I added to a commit from @ipanova.
=> 1705 - Streamer code explicitly sets /tmp as the temp folder

server/pulp/server/async/celery_instance.py, server/pulp/server/controllers/repository.py, server/test/unit/server/async/test_celery_instance.py
closes #1697
https://pulp.plan.io/issues/1697
=> Celerybeat uses queue_deferred_download to dispatch deferred_download

server/pulp/server/db/migrations/0019_repo_collection_id.py, server/test/unit/server/db/migrations/test_0019_repo_collection_id.py
https://pulp.plan.io/issues/1707
=> fix repository migration

docs/dev-guide/integration/rest-api/tasks.rst, docs/user-guide/release-notes/master.rst, server/pulp/server/webservices/views/task_groups.py, server/test/unit/server/webservices/views/test_task_groups.py
https://pulp.plan.io/issues/1581
closes #1581
=> Story 1581: Cancel tasks in a task group

server/selinux/server/pulp-celery.te
closes #1731
https://pulp.plan.io/issues/1731
=> Allows { setrlimit } on celery_t:process for F23 in pulp-celery

server/pulp/server/webservices/views/search.py
re #1733
https://pulp.plan.io/issues/1733
All credits to @goosemania as she found the spot.
=> Pulp search call raising serialization issues

playpen/ansible/roles/dev/files/bashrc
https://pulp.plan.io/issues/1613
closes #1613
=> Separate v1 and v2 busybox repositories in dev env.

docs/user-guide/release-notes/2.8.x.rst
This fixes an inconsistency that shows up on the index page. This will be merged forward to master also.
=> Fixes title of 2.8.0 release notes section for consistency

playpen/mongoengine/dockerimage/rhel-pulp.repo
I built and ran it locally, which all worked.
=> updating 2.8 upgrade test script to use stable pulp repo

server/pulp/server/db/model/__init__.py
closes https://pulp.plan.io/issues/1809
=> Fix string format for python 2.6 compat

deps/external_deps.json, deps/python-kombu/577.patch, deps/python-kombu/python-kombu.spec, rel-eng/packages/python-kombu
closes #1801
https://pulp.plan.io/issues/1801
=> Adds patch to python-kombu to fix pulp_celerybeat deadlock

server/pulp/server/webservices/views/serializers/__init__.py, server/test/unit/server/webservices/views/serializers/test_serializers.py
https://pulp.plan.io/issues/1784
=> Make translate recursive to handle nested queries

common/pulp/common/error_codes.py
This PR fixes a typo in the error codes.
=> Typo fix in error codes.

server/pulp/plugins/migration/standard_storage_path.py, server/test/unit/plugins/migration/test_standard_storage_path.py
=> Support standard storage path migration used by plugins.

server/pulp/server/util.py, server/test/unit/server/test_util.py
https://pulp.plan.io/issues/1808
fixes #1808
=> copytree no longer accumulates an unbounded number of errors

server/pulp/plugins/file/distributor.py, server/test/unit/plugins/file/test_distributor.py
https://pulp.plan.io/issues/1824
fixes #1824
=> FileDistributor now works with files that have to be in subdirectories.

client_lib/pulp/client/commands/repo/sync_publish.py, client_lib/test/unit/client/commands/repo/test_sync_publish.py
re #1158
https://pulp.plan.io/issues/1158
=> Add --force-full flag to publish command

playpen/mongoengine/dockerimage/validation_check.py
Updating validation script to handle the FieldDoesNotExist case
=> Updating validation script for FieldDoesNotExist

common/pulp/common/error_codes.py, server/pulp/server/controllers/repository.py, server/pulp/server/managers/content/upload.py, server/test/unit/server/controllers/test_repository.py, server/test/unit/server/managers/content/test_upload.py
https://pulp.plan.io/issues/1747
closes #1747
=> Raise an exception if upload report indicates failure

docs/user-guide/release-notes/2.8.x.rst
re #1827
re #1830
re #1833
re #1834
re #1837
=> Add release notes for the upcoming 2.8.3.

docs/dev-guide/integration/rest-api/repo/cud.rst, docs/user-guide/release-notes/2.9.x.rst, docs/user-guide/release-notes/index.rst, server/pulp/server/controllers/repository.py, server/pulp/server/db/migrations/0024_distributor_last_updated.py, server/pulp/server/db/model/__init__.py, server/pulp/server/db/model/repository.py, server/test/unit/server/controllers/test_repository.py, server/test/unit/server/db/migrations/test_0024_distributor_last_updated.py, server/test/unit/server/db/test_model.py
closes #1724
https://pulp.plan.io/issues/1724
=> Publish should be a no-op if nothing changed since the last publish

server/pulp/plugins/conduits/repo_sync.py
re #1775
https://pulp.plan.io/issues/1775
=> Make last_sync date available from sync conduit

docs/dev-guide/contributing/bugs.rst, docs/user-guide/release-notes/2.9.x.rst
I built the docs and inspected them; they built correctly and looked correct.
=> Adds revised security disclosure process to the docs.

server/pulp/server/db/migrations/0023_importer_tls_storage.py, server/test/unit/server/db/migrations/test_0023_importer_tls_storage.py
https://pulp.plan.io/issues/1929
fixes #1929
=> Change migration 23 to not assume that Importers have configs.

server/pulp/server/controllers/repository.py
closes #1928
https://pulp.plan.io/issues/1928
Another corner case.
=> Publish should be operational if override config values were specified

pulp.spec
https://pulp.plan.io/issues/1712
fixes #1712
=> pulp-server depends on pulp-selinux.

common/pulp/common/error_codes.py
I'm using this error code in ``pulp_rpm`` for https://pulp.plan.io/issues/1618
=> adding a new error code for missing unit file

server/pulp/plugins/util/saxwriter.py, server/test/unit/plugins/util/test_saxwriter.py
re #1716
https://pulp.plan.io/issues/1716
=> Add SAX writer to generate XML without etree

server/pulp/plugins/migration/standard_storage_path.py, server/test/unit/plugins/migration/test_standard_storage_path.py
To support unit types like *distributions*, the migration in the platform needs to support specialized units that can specify the paths to files stored within the directory referenced by `_storage_path`.  This is needed to migrate all of the possible symlinks created during publishing.
Need for: https://pulp.plan.io/issues/1972
=> Support specialized unit classes in storage-path migration

server/test/unit/server/managers/schedule/test_utils.py
Fix test assertion based on timing.
=> Fix temperamental unit test.

server/bin/pulp-qpid-ssl-cfg
https://pulp.plan.io/issues/1890
=> NSS DB password no longer printed.

Vagrantfile.example, docs/dev-guide/contributing/dev_setup.rst, playpen/ansible/roles/dev/tasks/main.yml, playpen/vagrant-reset-user.sh
Let the developer choose between libvirt or docker for the Vagrant provider.
=> dev env: add support for Vagrant docker provider

server/pulp/server/controllers/importer.py, server/test/unit/server/controllers/test_importer.py
closes #2030
https://pulp.plan.io/issues/2030
=> Importer config is not validated during the update.

server/pulp/server/controllers/importer.py, server/test/unit/server/controllers/test_importer.py
Main issue was in the validation of importer config in the update call. In validate_importer_config() was passed and checked just the current specified values of the update call and values of importer config stored in db where not considered.
https://pulp.plan.io/issues/2039
=> Fix importer validation logic.

server/pulp/server/controllers/repository.py
closes #2081
https://pulp.plan.io/issues/2081
=> Updates a particular distributor's last published timestamp

pulp.spec, server/pulp/plugins/rsync/configuration.py, server/pulp/plugins/rsync/publish.py, server/pulp/plugins/util/publish_step.py, server/pulp/server/db/model/__init__.py
This adds shared rsync distributor code. The classes provided need to be extended in each plugin that implements the rsync distributor.
=> Adds rsync distributor publish steps to platform

test_requirements.txt
https://pulp.plan.io/issues/2106
=> pin to flake8-2.6.2 for py2.6 support

server/pulp/server/controllers/importer.py, server/pulp/server/webservices/views/repositories.py, server/test/unit/server/controllers/test_importer.py
closes #2082
https://pulp.plan.io/issues/2082
=> Cannot add importer to the repository.

server/pulp/plugins/rsync/publish.py
re #2115
https://pulp.plan.io/issues/2115
=> Renames skip_fast_forward to force_full

client_lib/pulp/client/commands/unit.py, server/pulp/server/managers/repo/unit_association.py
=> As a user, units which don't pass the signature check are not imported

server/pulp/server/db/model/criteria.py, server/test/unit/server/db/model/test_criteria.py
closes #1863
https://pulp.plan.io/issues/1863
=> Fix regex handling for the `$not` operator in filters

streamer/pulp/streamer/adapters.py, streamer/pulp/streamer/server.py
This PR is only here as a rebase to get the commit merge-able back to 2.8-dev.
The original PR is here:  https://github.com/pulp/pulp/pull/2639
=> Backport proposed requests HTTPAdapter

pulp.spec, server/pulp/plugins/rsync/configuration.py, server/pulp/plugins/rsync/publish.py
re #1887
https://pulp.plan.io/issues/1887
re #1963
https://pulp.plan.io/issues/1963
re #1759
https://pulp.plan.io/issues/1759
=> Removes ability to use password authentication when rsync-ing

server/pulp/server/webservices/templatetags/__init__.py, server/pulp/server/webservices/templatetags/templatetags.py
re #2077
https://pulp.plan.io/issues/2077
=> Backport verbatim tag from Django 1.5

server/pulp/server/content/web/settings.py, server/pulp/server/webservices/settings.py
Reopened against 2.10
https://pulp.plan.io/issues/2049
old Pr:
https://github.com/pulp/pulp/pull/2676
=> build templates compatible with Django 1.4-1.10

pulp.spec
This reverts commit 8c152a681ecd1e577c1ef6b7b56d3e5bf506a899.
re #2121
https://pulp.plan.io/issues/2121#note-8
=> Revert "Fixes selinux-policy spec file macro"

client_lib/pulp/client/extensions/exceptions.py, client_lib/test/unit/client/extensions/test_exceptions.py
closes #752
https://pulp.plan.io/issues/752
=> 752 - Fixed: Suggestion to add -v remains even if you use -v

.mention-bot
I can't actually turn this on since I can't modify the repository settings.
=> Add a simple mention-bot config

docs/user-guide/admin-client/authentication.rst
=> Update roles docs to use /v2/repositories/ in examples

streamer/pulp/streamer/server.py
=> Instantiate the PulpHTTPAdapter

streamer/pulp/streamer/adapters.py
The problem with the first backport was that it was not entirely
compatible with requests-2.6 and urllib3-1.10, which is what el6 and el7
ship.
For this backport I started with requests-2.6.2, applied the proposed patch, and then resolved all the conflicts.
I'll admit I'm a bit nervous of this approach, but the alternative is to carry requests and urllib3 for el6-f24 which I really don't want to do.
=> Second attempt at backporting the fix for requests issue #2863

docs/dev-guide/contributing/branching.rst
re #2043
https://pulp.plan.io/issues/2043
=> adding docs about marking branches as protected on github

platform/pulp/platform/models/generic.py, platform/pulp/platform/tests/models/test_generic.py
I also wrote some unittests to make sure the mapping interface behaves as
expected when writing the to database (`python manage.py test platform/`)
This is based on some ideas tossed around last Friday in a chat with @jortel
=> GenericKeyValueMapping raises KeyError instead of Django exceptions

docs/user-guide/consumer-client/bind.rst
=> Remove extra task ID from bind documentation example

docs/dev-guide/contributing/dev_setup.rst
=> Correct the URL for the dev-setup.sh script in the docs.

server/pulp/server/controllers/repository.py
closes #2187
https://pulp.plan.io/issues/2187
=> Fixes publish with predistributor logic

server/selinux/server/pulp-celery.te
closes #2199
https://pulp.plan.io/issues/2199
=> Adds an optional selinux boolean needed for using the rsync distributor

docs/dev-guide/3.0-development/data-modeling.rst, docs/dev-guide/3.0-development/dev-setup.rst, docs/dev-guide/3.0-development/index.rst, docs/dev-guide/3.0-development/plugin-api.rst, docs/dev-guide/3.0-development/rest-planning.rst, docs/dev-guide/index.rst
If people like the skeleton, I will put the 3.0 guide docs we already have in here.
=> Add skeleton for 3.0 development docs

platform/pulp/platform/models/__init__.py, platform/pulp/platform/models/progress.py
This creates three new models: ProgressBar, ProgressReport,
and ProgressSpinner. These can be used to create progress reports.
https://pulp.plan.io/issues/2092
closes #2092
=> Adds Progress Reporting models into pulp.platform.models.

platform/pulp/platform/models/base.py, platform/pulp/platform/models/repository.py
- removes lingering unique_together
- removes MasterModelQuerySet
- removes MasterModelManager
- fixes typo
=> Small Django models fixes

docs/conf.py
closes #2097
https://pulp.plan.io/issues/2097
=> Changed copyright year to current year

platform/pulp/platform/tests/fields/test_jsonfield.py
Create tests for JSONField
re #[2087](https://pulp.plan.io/issues/2087)
=> Create tests for JSONField

.travis.yml, flake8.cfg, platform/pulp/platform/logs.py, platform/pulp/platform/models/progress.py, platform/pulp/platform/settings.py, platform/pulp/platform/tests/models/test_content.py, platform/pulp/platform/tests/models/test_repository.py, platform/setup.py, test_requirements.txt
This includes some re-arrangement of code as well as the necessary updates to the .travis.yml file. This is because I don't want install pulp.server and its dependencies.
=> Add travis configuration for Pulp 3

server/pulp/plugins/util/publish_step.py, server/test/unit/plugins/util/test_publish_step.py
https://pulp.plan.io/issues/2237
=> Move working-directory to master location when permitted.

bindings/setup.py, client_admin/setup.py, client_lib/setup.py, oid_validation/setup.py, run-tests.py, server/test/unit/server/managers/auth/cert/test_cert_generator.py
closes #2262
https://pulp.plan.io/issues/2262
=> Rewrite shebangs to python3

app/pulp/app/models/task.py, server/pulp/server/async/scheduler.py, server/pulp/server/async/worker_watcher.py, server/test/unit/server/async/test_app.py, server/test/unit/server/async/test_scheduler.py, server/test/unit/server/async/test_tasks.py, tasking/pulp/tasking/__init__.py, tasking/pulp/tasking/base.py, tasking/pulp/tasking/celery_app.py, tasking/pulp/tasking/constants.py
closes #2156
https://pulp.plan.io/issues/2156
This PR have to be merged into code created by https://github.com/pulp/pulp/pull/2771.
=> Convert pulp_resource_manager to use a django lock model

app/pulp/app/serializers/__init__.py, app/pulp/app/serializers/generic.py, app/pulp/app/serializers/repository.py, app/pulp/app/viewsets/repository.py, docs/dev-guide/3.0-development/rest-api.rst
Add remaining fields and move fiter_fields back to ViewSet.
closes #2298
=> Finish Repository serializer

app/pulp/app/serializers/repository.py, app/pulp/app/viewsets/custom_filters.py, app/pulp/app/viewsets/repository.py
Finish the Repository ViewSet by implementing a FilterSet and creating
some custom filters.
https://pulp.plan.io/issues/2307
=> Add Repository Filters

streamer/pulp/streamer/adapters.py
https://pulp.plan.io/issues/2344
The `ProxyManager` IsA `PoolManager` and the code needs to update the SSL settings on either pool manager when retrieving a connection.
=> Fix SSLError resulting in http 503 when using proxy and SSL.

app/pulp/app/serializers/__init__.py, app/pulp/app/serializers/task.py
=> Add Task Serializer

app/pulp/app/serializers/consumer.py
Add consumer serializer
closes #[2306](https://pulp.plan.io/issues/2306)
=> Add consumer serializer

app/pulp/app/serializers/__init__.py, app/pulp/app/serializers/task.py
=> Add worker serializer

app/pulp/app/serializers/__init__.py
Add ConsumerSerializer to serializer init
=> Add ConsumerSerializer to serializer init

app/pulp/app/viewsets/repository.py
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/filters.py#L42-L46
=> Pull filter/filterset bases from django-filter

docs/user-guide/release-notes/2.11.x.rst, docs/user-guide/troubleshooting.rst, docs/user-guide/tuning.rst, server/etc/default/systemd_pulp_workers, server/etc/default/upstart_pulp_workers, server/etc/rc.d/init.d/pulp_workers, server/pulp/server/async/manage_workers.py, server/test/unit/server/async/test_manage_workers.py
- updates the configs for upstart and systemd
- updates the systemd unit manager
- updates the upstart script
- adds a release note
- adds docs on the feature
- adds a troubleshooting note
I hand tested these against systemd and upstart so I
expect them to work.
https://pulp.plan.io/issues/2172
closes 2172
=> Fixes to the process recycling feature

app/pulp/app/serializers/__init__.py, app/pulp/app/serializers/content.py, app/pulp/app/serializers/fields.py
closes #2299
https://pulp.plan.io/issues/2299
=> Finish content serializer and add one for artifact

server/pulp/server/controllers/importer.py, server/test/unit/server/controllers/test_importer.py
https://pulp.plan.io/issues/2372
=> Fix unset of property not set in the configuration.

app/pulp/app/apps.py, app/pulp/app/db-reset.sh, app/pulp/app/models/__init__.py, app/pulp/app/models/auth.py, app/pulp/app/settings.py
closes #2243
https://pulp.plan.io/issues/2243
=> Adds a custom User model to pulp.app

app/pulp/app/serializers/user.py
closes #2356
https://pulp.plan.io/issues/2356
=> Adds serializer for the PulpUser model

app/pulp/app/serializers/__init__.py, app/pulp/app/serializers/user.py, app/pulp/app/viewsets/__init__.py, app/pulp/app/viewsets/user.py
Adds ability to:
GET, POST to /api/v3/users/
PUT, PATCH, DELETE to /api/v3/users/<username>/
closes #2357
https://pulp.plan.io/issues/2357
=> Adds ViewSet for User model

app/pulp/app/serializers/__init__.py, app/pulp/app/serializers/generic.py, app/pulp/app/serializers/repository.py
re #2298
https://pulp.plan.io/issues/2298
=> Add RepositoryGroup serializer

app/pulp/app/response.py, app/pulp/app/viewsets/__init__.py, app/pulp/app/viewsets/task.py, tasking/pulp/tasking/base.py
=> Add task and worker viewsets

app/pulp/app/serializers/__init__.py, app/pulp/app/serializers/repository.py, app/pulp/app/viewsets/__init__.py, app/pulp/app/viewsets/repository.py
re #2298
https://pulp.plan.io/issues/2298
=> Add Publisher serializer

server/pulp/plugins/util/verification.py, server/pulp/server/content/storage.py, server/test/unit/server/content/test_storage.py
re #1823
https://pulp.plan.io/issues/1823
=> Verify size of a file at its final location

server/pulp/plugins/util/publish_step.py
closes #2387
https://pulp.plan.io/issues/2387
=> Handles exception when restorecon is called with SELinux disabled.

docs/dev-guide/contributing/bugs.rst, docs/dev-guide/contributing/building.rst
Also tweaked the bug reporting steps to better reflect our actually
current workflow.
=> Update bugs guide to use "Blocks Release" field.

app/pulp/app/models/base.py, app/pulp/app/serializers/repository.py, app/pulp/app/viewsets/__init__.py, app/pulp/app/viewsets/repository.py
closes #2308
https://pulp.plan.io/issues/2308
=> Add a RepositoryGroup ViewSet.

app/pulp/app/models/__init__.py, app/pulp/app/serializers/__init__.py, app/pulp/app/serializers/progress.py
closes #2302
https://pulp.plan.io/issues/2302
=> Add serializer for the progress models.

app/pulp/app/models/auth.py
I had to look in the django source to confirm which parameter this was setting.
=> making a positional argument named so it's clear which parameter it sets

app/pulp/app/serializers/__init__.py, app/pulp/app/serializers/repository.py, app/pulp/app/viewsets/__init__.py, app/pulp/app/viewsets/repository.py
closes #2311
https://pulp.plan.io/issues/2311
=> Add RepositoryContent Serializer and Viewset

server/usr/lib/systemd/system/pulp_celerybeat.service, server/usr/lib/systemd/system/pulp_workers.service, tasking/pulp/tasking/base.py, tasking/pulp/tasking/scheduler.py
One can also dispatch a task as a bonus
=> Various minor fixes to get workers/celerybeat/resource_manager run

app/pulp/app/viewsets/repository.py
closes #2310
https://pulp.plan.io/issues/2310
=> Add Publisher filter class

app/pulp/app/viewsets/content.py, app/pulp/app/viewsets/repository.py
=> Fix bullet lists in docstrings for filter classes

server/pulp/server/managers/repo/unit_association.py, server/test/unit/server/managers/repo/test_unit_association.py
closes #2264
https://pulp.plan.io/issues/2264
=> pulp reports details about import failure

app/pulp/app/serializers/__init__.py, app/pulp/app/serializers/catalog.py
closes #2301
https://pulp.plan.io/issues/2301
=> Add catalog serializer

docs/user-guide/troubleshooting.rst, server/pulp/server/db/manage.py, server/test/unit/server/db/test_manage.py
closes #2469
https://pulp.plan.io/issues/2469
=> Add --ignore-running-workers option to pulp-manage-db

app/pulp/app/tasks/__init__.py, app/pulp/app/tasks/repository.py, server/pulp/server/controllers/repository.py
closes #2407
https://pulp.plan.io/issues/2407
=> Convert celery task repository.delete

app/pulp/app/models/progress.py, app/pulp/app/serializers/progress.py
closes #2319
https://pulp.plan.io/issues/2319
=> Add a suffix attribute to the ProgressReport model.

docs/user-guide/release-notes/2.11.x.rst, docs/user-guide/troubleshooting.rst, server/pulp/server/async/scheduler.py, server/pulp/server/db/manage.py, server/test/unit/server/async/test_scheduler.py, server/test/unit/server/db/test_manage.py
re #2469 #2186
https://pulp.plan.io/issues/2469
https://pulp.plan.io/issues/2186
=> Revert "Prompt user of running workers/tasks on migration"

app/pulp/app/tasks/tags.py, app/pulp/app/viewsets/repository.py
closes #2475
https://pulp.plan.io/issues/2475
=> As a user, I can use REST API to remove a repository.

app/pulp/app/serializers/repository.py
Part of https://pulp.plan.io/issues/2298, but does not close the issue.
I chose to do just this one because I want someone else ( @goosemania ) to write the Publisher Serializer to ~make sure that using the nested routing is clear.`~
=> Add remaining fields to Importer Serializer

server/pulp/plugins/util/publish_step.py
Solution: Explicitly check if SELinux is enabled before calling restorecon
closes #2476
https://pulp.plan.io/issues/2476
=> Problem: Publish fails when SELinux is disabled

server/pulp/plugins/util/metadata_writer.py
re #2096
https://pulp.plan.io/issues/2096
=> Check the search_tag before attempting to fast forward file

server/pulp/server/controllers/importer.py, server/test/unit/server/controllers/test_importer.py
fixes #2520
https://pulp.plan.io/issues/2520
=> URL unquote escaped credentials in feed URL

server/pulp/server/controllers/repository.py, server/pulp/server/managers/content/upload.py, server/test/unit/server/managers/content/test_upload.py
closes #1847
https://pulp.plan.io/issues/1847
=> Update last_unit_added when unit is imported to repo.

docs/user-guide/release-notes/2.12.x.rst
refs #1268
https://pulp.plan.io/issues/1268
=> Adding release note for orphan removal feature

server/pulp/plugins/util/publish_step.py
Solution: Enable RSyncFastForwardUnitPublishStep to publish the same type of units into different
directories by extracting the publish path of a unit from it's symlink location.
This problem was introduced when the yum distributor was modified to publish repositories with a
new layout. This patch makes the RPM rsync distributor consistent with the yum distributor.
re #1976
https://pulp.plan.io/issues/1976
=> Problem: RSyncFastForwardUnitPublishStep publishes incorrectly

docs/user-guide/release-notes/2.12.x.rst, server/pulp/server/async/app.py, server/pulp/server/async/scheduler.py
Failover events are now logged as such
at the WARNING level
closes #2525
=> Explictly log failovers

docs/user-guide/release-notes/2.12.x.rst
Brought over from the 2.11 release notes and adapted for 2.12
=> el6 support changes for 2.12 release notes

docs/dev-guide/contributing/bugs.rst
Solution: Add documentation about "Work In Progress" pull requests
=> Problem: developer docs are out of date

docs/user-guide/introduction.rst
closes #2533
https://pulp.plan.io/issues/2533
=> Update support policy to reflect dropping of el6 support

server/pulp/server/logs.py, server/test/unit/server/test_logs.py
closes #2004
https://pulp.plan.io/issues/2004
=> Ensure DeprecationWarning is ignored when setting up logging

server/pulp/server/controllers/repository.py
https://pulp.plan.io/issues/2458
=> Log VerificationException at INFO.

docs/user-guide/release-notes/2.13.x.rst, nodes/test/nodes_tests/base.py, pulp.spec, server/etc/pulp/server.conf, server/pulp/server/config.py, server/pulp/server/managers/auth/cert/cert_generator.py, server/test/unit/base.py, server/test/unit/server/managers/auth/cert/test_cert_generator.py
closes #1839
https://pulp.plan.io/issues/1839
=> Remove sn.dat for serial number storage

docs/user-guide/scaling.rst
fixes #2563
https://pulp.plan.io/issues/2563
=> Fixing mongodb deployment link

server/pulp/server/db/manage.py
closes #1594
https://pulp.plan.io/issues/1594
=> Suppress DeprecationWarnings when running pulp-manage-db

docs/dev-guide/contributing/building.rst
re #2565
https://pulp.plan.io/issues/2565
=> Update build docs to mention "Verification Required" report

pulp.spec
closes #2583
https://pulp.plan.io/issues/2583
=> Adjust conditional to work correctly on fedora

docs/dev-guide/contributing/branching.rst, docs/dev-guide/contributing/bugs.rst, docs/dev-guide/contributing/dev_setup.rst, docs/dev-guide/contributing/documenting.rst, docs/dev-guide/contributing/index.rst, docs/dev-guide/contributing/merging.rst, docs/dev-guide/glossary.rst, docs/dev-guide/policies/style.rst, docs/dev-guide/policies/testing.rst, docs/user-guide/glossary.rst
re #1988
https://pulp.plan.io/issues/1988
=> Story 1988 - documentation improvement  for new developers

docs/dev-guide/contributing/dev_setup.rst
Fixes a line length issue
Fixes a block escaping issue
=> Two small fixes in dev_setup guide

streamer/pulp/streamer/server.py, streamer/test/unit/streamer/test_server.py
https://pulp.plan.io/issues/2587
Looks like moving the header management to a later stage caused squid to not cache.  Makes sense that the headers would need to be manipulated before streaming the bits.
Tested w/ smash tests mentioned in the issue:
```
[jortel@f23d ~]$ python3 -m unittest pulp_smash.tests.rpm.api_v2.test_download_policies.OnDemandTestCase.test_rpm_cache_control_header pulp_smash.tests.rpm.api_v2.test_download_policies.OnDemandTestCase.test_same_rpm_cache_header pulp_smash.tests.rpm.api_v2.test_download_policies.SwitchPoliciesTestCase.test_background_to_on_demand pulp_smash.tests.rpm.api_v2.test_download_policies.SwitchPoliciesTestCase.test_immediate_to_on_demand
/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: …
```
=> Fix streamer header forwarding.

server/pulp/server/managers/repo/unit_association.py, server/test/unit/server/managers/repo/test_unit_association.py
closes #2577
https://pulp.plan.io/issues/2577
=> update last_unit_added when units are copied

common/pulp/common/error_codes.py, server/pulp/server/async/tasks.py, server/pulp/server/managers/repo/unit_association.py, server/test/unit/server/managers/repo/test_unit_association.py
https://pulp.plan.io/issues/2551
=> Improved logging of worker abnormal termination.

docs/conf.py, docs/dev-guide/contributing/documenting.rst, docs/user-guide/release-notes/2.10.x.rst, docs/user-guide/release-notes/2.11.x.rst, docs/user-guide/release-notes/2.12.x.rst, docs/user-guide/release-notes/2.6.x.rst, docs/user-guide/release-notes/2.7.x.rst, docs/user-guide/release-notes/2.8.x.rst, docs/user-guide/release-notes/2.9.x.rst
closes #2585
https://pulp.plan.io/issues/2585
=> Create extlinks for all the plugins in sphinx config on a platform.

pulp.spec, server/pulp/server/async/app.py, server/pulp/server/async/celery_instance.py, server/pulp/server/async/tasks.py, server/pulp/server/db/model/dispatch.py, server/pulp/server/managers/repo/unit_association.py, server/setup.py
Make Pulp compatible with both Celery 3.1.z and Celery 4.0.z
closes #2527
=> Update Pulp to support Celery 4.0.z.

server/pulp/server/controllers/repository.py, server/test/unit/server/controllers/test_repository.py
closes #2630
https://pulp.plan.io/issues/2630
=> Only update last_unit_removed when units are removed

docs/dev-guide/contributing/dev_setup.rst
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
=> Minor typo in dev_setup page

tasking/pulp/tasking/tasks.py
=> Revert "Fix the arguments being passed to celery.apply_async"

deps/external_deps.json, pulp.spec
closes #2589
https://pulp.plan.io/issues/2589
=> Update spec file and external deps to use newer celery version

server/pulp/server/db/migrations/0028_distributor_last_updated_fix.py, server/test/unit/server/db/migrations/test_0028_distributor_last_updated_fix.py
closes #2240
https://pulp.plan.io/issues/2240
=> Set last_updated for distributor if it is absent or None

app/pulp/app/viewsets/repository.py
closes #2447
https://pulp.plan.io/issues/2447
=> Add publisher removal route to the REST API

app/pulp/app/entry_points.py, app/setup.py, docs/integration_guide/rest_api/index.rst
closes #2421
https://pulp.plan.io/issues/2421
=> As a user I can manage Pulp using a systemwide command

app/etc/pulp/server.yaml, app/pulp/app/settings.py
closes #2275
https://pulp.plan.io/issues/2275
Have to be yet tested in some real life scenario.
=> Set celery logger to pulp logger

app/pulp/app/models/progress.py
closes #2316
https://pulp.plan.io/issues/2316
=> Batch save() calls to ProgressReport

app/pulp/app/pagination.py, app/pulp/app/viewsets/repository.py
We're probably going have a bunch of things with a 'name' field,
so I made RepositoryPagination a little more generic.
=> Replace RepositoryPagination with generic paginator

server/pulp/plugins/rsync/publish.py
closes #2666
https://pulp.plan.io/issues/2666
=> Fix fast forward mode for rsync publish.

server/pulp/server/controllers/repository.py
Fix several cases where variables defined behind conditionals
are referenced elsewhere in the code from an upper scope.
closes #2722
https://pulp.plan.io/issues/2722
=> Fix 'referenced before assignment' errors

server/pulp/server/async/scheduler.py, server/test/unit/server/async/test_scheduler.py
fixes #2726
https://pulp.plan.io/issues/2726
=> Fix pulp_resource_mananger typo

docs/user-guide/installation/index.rst
Solution: add a note about disabling Transparent Huge Pages
closes #2746
=> Problem: install guide ommits THP recommendation

common/pulp/common/config.py, docs/user-guide/content-sources.rst, docs/user-guide/release-notes/2.14.x.rst, server/pulp/server/content/sources/constants.py, server/pulp/server/content/sources/descriptor.py, server/test/unit/server/content/sources/test_descriptor.py
closes #1282
https://pulp.plan.io/issues/1282
=> Add headers as an optional alternate content source descriptor

platform/pulp/app/models/progress.py
Fix:
```
psycopg2.ProgrammingError: can't adapt type 'Task'
```
=> Fix progress bar.

common/pulp/common/config.py, server/test/unit/server/content/sources/test_descriptor.py
re #1282
https://pulp.plan.io/issues/1282
=> Allow = in alternate content source header value

server/pulp/server/async/tasks.py
For both apply_async() and apply_async_with_reservation() if the task
fails to dispatch due to an error the task status record is updated to
show 'error'.
https://pulp.plan.io/issues/2770
closes #2770
=> TaskStatus records now error correctly

server/pulp/server/content/web/urls.py, server/pulp/server/webservices/settings.py, server/pulp/server/webservices/urls.py
fixes #2741
https://pulp.plan.io/issues/2741
=> Supporting django 1.6-1.11

platform/pulp/app/viewsets/task.py
closes #2755
https://pulp.plan.io/issues/2755
=> Update worker viewset to handle the . character

server/pulp/plugins/conduits/repo_config.py
Distributor configuration has never really been standardized and some plugins (namely ostree) use `relative_path` instead of `relative_url` for the relative publishing path.  This fix is hacky but this check is flawed and will need to be rewritten in pulp3 anyway.  Admittedly, just touching this code as little as possible.
Needed for fix: https://pulp.plan.io/issues/2769
=> Support passing the field name to get_repo_distributors_by_relative_url().

pulp.spec
Add obsoletes to spec files
refs #[2649](https://pulp.plan.io/issues/2639)
=> Add obsoletes to spec files

server/pulp/server/db/connection.py, server/test/unit/server/db/test_connection.py
closes #2728
https://pulp.plan.io/issues/2728
=> Make Pulp compatible with mongoengine 0.10+

server/pulp/plugins/rsync/configuration.py, server/pulp/plugins/rsync/publish.py
As user I want to be able to provide custom rsync arguments to rsync …
closes #2730
=> custom arguments for rsync distributor

platform/pulp/app/models/task.py, platform/pulp/app/serializers/task.py, platform/pulp/tasking/celery_app.py, platform/pulp/tasking/services/scheduler.py, platform/pulp/tasking/services/worker_watcher.py
closes #2430
https://pulp.plan.io/issues/2430
=> Keep workers records when they gone offline

server/pulp/server/webservices/views/consumers.py
All kudos go to Chris (@cduryee).
closes #2797
https://pulp.plan.io/issues/2797
=> Fix criteria obj for consumer in applicability regeneration view

platform/pulpcore/tasking/tasks.py
Ensure the worker field on the Task model gets populated.
closes #2768
https://pulp.plan.io/issues/2768
=> Associate worker foreign key with task

.travis.yml, docs/index.rst, docs/installation.rst, platform/etc/pulp/server.yaml, platform/pulpcore/app/settings.py
closes #2416
https://pulp.plan.io/issues/2416
=> Remove SECRET_KEY from Django settings

platform/pulpcore/app/tasks/repository.py, platform/pulpcore/app/viewsets/repository.py, server/pulp/server/controllers/repository.py
closes #2756
https://pulp.plan.io/issues/2756
=> Add repository update task

platform/pulpcore/app/serializers/repository.py
fixes #2824
https://pulp.plan.io/issues/2824
=> Return name for repositories in the api

server/pulp/plugins/rsync/publish.py
Fixes an issue where fastforward publishes were not
when they should have been.
closes #2844
https://pulp.plan.io/issues/2844
=> Fix fastforward rsync publishes.

platform/pulpcore/app/serializers/repository.py, platform/pulpcore/app/tasks/publisher.py, platform/pulpcore/app/viewsets/repository.py
=> Dispatch a task to update a publisher.

docs/index.rst, docs/installation/configuration-files.rst, docs/installation/distributed-installation.rst, docs/installation/index.rst, docs/installation/instructions.rst, docs/installation/migration.rst
closes #2857
https://pulp.plan.io/issues/2857
=> Refactor and stub out pages for the installation section in docs

docs/conf.py
re #2819
https://pulp.plan.io/issues/2819
=> Pulp2: set DJANGO_SETTINGS_MODULE env variable

docs/conf.py
re #2819
https://pulp.plan.io/issues/2819
=> Pulp3: set DJANGO_SETTINGS_MODULE env variable

platform/pulpcore/app/serializers/__init__.py, platform/pulpcore/app/serializers/base.py, platform/pulpcore/app/serializers/fields.py, platform/pulpcore/app/serializers/repository.py, platform/pulpcore/app/tests/serializers/test_base.py, platform/pulpcore/app/tests/test_urls.py, platform/pulpcore/app/tests/viewsets/test_base.py, platform/pulpcore/app/urls.py, platform/pulpcore/app/viewsets/base.py, platform/pulpcore/app/viewsets/repository.py, platform/setup.py
https://pulp.plan.io/issues/2823
closes #2823
=> Nests importer and publisher REST API paths under repositories

platform/pulpcore/app/response.py, platform/pulpcore/app/viewsets/repository.py
fixes #2864
https://pulp.plan.io/issues/2864
=> Convert relative url to full url in 202 responses

server/pulp/server/content/web/urls.py
https://pulp.plan.io/issues/2898
fixes #2898
=> Removes a stray import that was incompatible with django >= 1.10

.pep8speaks.yml
refs #2870
https://pulp.plan.io/issues/2870
=> Adding pep8speaks config file

server/pulp/server/content/web/settings.py, server/pulp/server/logs.py
I added some polish to https://github.com/pulp/pulp/pull/3041
https://pulp.plan.io/issues/2786
=> Allow content application to use console logging

plugin/pulpcore/plugin/download/factory.py
https://pulp.plan.io/issues/2911
=> Fix passing SSL settings.

docs/dev-guide/conventions/criteria.rst, docs/dev-guide/integration/rest-api/repo/content.rst
Thanks to @kersommoura for noticing this!
=> Removes docs for two fields that were removed in 2.7.0.

docs/contributing/style_guide.rst, docs/plugins/plugin-writer/basics.rst
closes #2760
https://pulp.plan.io/issues/2760
=> Add error handling section to docs

server/pulp/server/event/http.py
These came up in the time between when I opened my flake8 PR fix and when it got merged.
=> Fix flake8 unused import error and bare exception

server/pulp/server/managers/consumer/applicability.py
Race condition was possible when applicability generation was running
in parallel for the same consumer profiles.
closes #2874
https://pulp.plan.io/issues/2874
=> Resolve race condition during applicability generation

server/pulp/server/util.py, server/test/unit/server/test_util.py
closes #2783
https://pulp.plan.io/issues/2783
=> Copy mtime for copytree operation

deps/external_deps.json, deps/python-debpkgr/dist_list.txt, dist_list.txt
Updates for f26 building
re #2904
=> Updates for f26 building

docs/installation/instructions.rst, platform/pulpcore/app/settings.py
closes #2833
https://pulp.plan.io/issues/2833
=> Get location of server.yaml from environmental variable

platform/pulpcore/tasking/services/scheduler.py
=> removes an import of logging code that no longer exists

platform/pulpcore/app/models/progress.py, platform/pulpcore/app/serializers/task.py
closes #2969
https://pulp.plan.io/issues/2969
=> Update task to serialize progress_report

platform/pulpcore/app/models/repository.py
https://pulp.plan.io/issues/2986
=> Add unique constraint to repository-content.

server/pulp/server/async/tasks.py
Fixes an issue where tasks which go through apply_async()
directly fail to be associated with a worker, and thus
are not properly cancelled when the worker is restarted
mid-execution and performs cleanup.
closes #2734
https://pulp.plan.io/issues/2734
=> Fix some tasks failing to cancel after pulp restart

platform/pulpcore/tasking/celery_instance.py
Changed celery.conf settings to lowercase name identified in [Celery 4.1 docs](http://docs.celeryproject.org/en/latest/userguide/configuration.html#configuration)
[Reference Issue](https://pulp.plan.io/issues/2963?issue_count=48&issue_position=3&next_issue_id=2919&prev_issue_id=2977)
=> updated celery conf names

plugin/pulpcore/plugin/changeset/model.py, plugin/pulpcore/plugin/download/monitor.py
=> Renamed To Facts

deps/external_deps.json, deps/python-kombu/2927.patch, deps/python-kombu/python-kombu.spec
Fixing problem where messages in qpid were being lost when qpid gets
restarted.
fixes #2927
https://pulp.plan.io/issues/2927
Successful koji build: http://koji.katello.org/koji/taskinfo?taskID=21835
=> Adding patch to kombu to make messages durable

platform/pulpcore/download/batch.py, platform/pulpcore/download/ftp.py, platform/pulpcore/download/http.py, plugin/pulpcore/plugin/changeset/model.py, plugin/pulpcore/plugin/changeset/report.py
https://pulp.plan.io/issues/2917
=> Add additional keyword arguments.

plugin/pulpcore/plugin/changeset/model.py
Fixes infinite recursion in PendingArtifact.settled:
```
Sep 12 15:03:06 f25b.redhat.com celery[31197]:   File "/home/jortel/git/pulp/platform/pulpcore/app/tasks/importer.py", line 81, in sync
Sep 12 15:03:06 f25b.redhat.com celery[31197]:     importer.sync()
Sep 12 15:03:06 f25b.redhat.com celery[31197]:   File "/usr/lib64/python3.5/contextlib.py", line 77, in __exit__
Sep 12 15:03:06 f25b.redhat.com celery[31197]:     self.gen.throw(type, value, traceback)
Sep 12 15:03:06 f25b.redhat.com celery[31197]:   File "/home/jortel/git/pulp/platform/pulpcore/tasking/services/storage.py", line 150, in working_dir_context
Sep 12 15:03:06 f25b.redhat.com celery[31197]:     yield working_dir
Sep 12 15:03:06 f25b.redhat.com celery[31197]:   File …
```
=> Fix recursion in PendingArtifact.settled.

plugin/pulpcore/plugin/download/futures/event.py, plugin/pulpcore/plugin/download/futures/single.py
Few minor API changes: better naming; cloning to better support mirror lists.
=> minor enhancements.

platform/pulpcore/app/apps.py, platform/pulpcore/app/serializers/__init__.py, platform/pulpcore/app/serializers/base.py, platform/pulpcore/app/serializers/repository.py, platform/pulpcore/app/settings.py, platform/pulpcore/app/viewsets/__init__.py, platform/pulpcore/app/viewsets/base.py, platform/pulpcore/app/viewsets/repository.py
Add nesting functionality to base classes to simplify inheritance hierarchy.
=> Squash nest classes

platform/pulpcore/app/models/storage.py
=> Use hard links when possible.

plugin/pulpcore/plugin/changeset/model.py, plugin/pulpcore/plugin/models/importer.py
https://pulp.plan.io/issues/3008
=> Importer.get_download renamed to get_futures_downloader.

platform/pulpcore/app/models/storage.py
There can be (rare) race conditions where an artifact is copied into storage when it already exists.  This is because the file is stored before the DB commit can raise the constraint violation.  Storing artifacts is a concurrent operation.  In all cases, an existing file will not be overwritten.  The atomic copy prevents partial files from being stored.
=> Storage refined.

docs/installation/instructions.rst
closes #2840
https://pulp.plan.io/issues/2840
=> Add ansible galaxy installation guide.

AUTHORS, docs/user-guide/content-storage-faq.rst, docs/user-guide/index.rst
Added an FAQ section to the User Guide to address
some pulp storage logic queries.
closes #2758
https://pulp.plan.io/issues/2758
=> Documentation on Pulp's storage logic

server/pulp/server/controllers/repository.py, server/test/unit/server/controllers/test_repository.py
=> Silence aggregation warning with mongo 3.4 and newer.

platform/pulpcore/app/serializers/base.py
closes #3019
https://pulp.plan.io/issues/3019
=> to_internal_value should not process href_writable field if being called from task

docs/plugins/plugin-api/futures.rst, plugin/pulpcore/plugin/download/futures/__init__.py
Add documentation to support _futures_ downloader customization and extension.
=> Updated futures download documentation.

server/bin/pulp-gen-ca-certificate, server/selinux/server/pulp-celery.te
closes #2961
https://pulp.plan.io/issues/2961
=> Fix SELinux and cert gen permissions

platform/pulpcore/app/serializers/fields.py
Solution: stop trying to manually set artifactfield.context
=> Problem: content creation API throws 500 error

docs/plugins/plugin-api/asyncio.rst, plugin/pulpcore/plugin/download/asyncio/base.py, plugin/pulpcore/plugin/download/asyncio/factory.py, plugin/pulpcore/plugin/download/asyncio/group.py, plugin/pulpcore/plugin/download/asyncio/http.py, plugin/pulpcore/plugin/models/importer.py
- add the fetch() interface
- Docs improvements for asyncio downloaders
- fix some examples that were wrong
=> Add fetch() interface and docs

server/pulp/server/async/tasks.py, server/test/unit/server/async/test_tasks.py
A task might have completed or failed by the time apply_async attempts
to upsert a TaskStatus record.  We have to avoid touching the fields
set on success/failure (such as finish_time, result) during update,
otherwise we'll overwrite them with empty values.
closes #2959
https://pulp.plan.io/issues/2959
=> Fix task results lost due to race condition

platform/pulpcore/app/viewsets/repository.py
closes #3011
https://pulp.plan.io/issues/3011
=> Fix the traceback during publisher deletion.

docs/plugins/plugin-writer/first-plugin.rst, docs/plugins/plugin-writer/index.rst
re #2859
https://pulp.plan.io/issues/2859
=> Link to plugin_template repo from plugin wirter's guide

docs/installation/instructions.rst
Also, fix numbering in ordered list.
See: https://github.com/pulp/devel/pull/95
=> Require Ansible 2.3.2+

platform/pulpcore/app/viewsets/task.py
https://pulp.plan.io/issues/3054
=> fix task cancel

server/selinux/server/pulp-streamer.te
closes #3036
https://pulp.plan.io/issues/3036
=> Fixed selinux permissions for pulp-streamer on F26

platform/pulpcore/app/settings.py, platform/pulpcore/app/urls.py
Solution: stop using features that had been deprecated in 3.5
closes #3057
https://pulp.plan.io/issues/3057
=> Problem: not compatible with DRF 3.7.0

docs/plugins/plugin-writer/first-plugin.rst, platform/pulpcore/app/models/content.py, plugin/pulpcore/plugin/changeset/__init__.py, plugin/pulpcore/plugin/changeset/iterator.py, plugin/pulpcore/plugin/changeset/model.py
refs #3025
https://pulp.plan.io/issues/3025
=> Removing natural key fields attribute

docs/contributing/3.0-development/index.rst
https://pulp.plan.io/issues/2897
re #2897
=> Updating the Python runtime to 3.5 in one place

platform/pulpcore/app/serializers/repository.py
fixes #3073
https://pulp.plan.io/issues/3073
=> Return the repository content href so they can be deleted

platform/pulpcore/app/serializers/repository.py
closes #3059
https://pulp.plan.io/issues/3059
=> Added 'content_summary' field to repository detail view

platform/pulpcore/app/serializers/task.py
closes #3103
https://pulp.plan.io/issues/3103
=> Added 'spawned_tasks' field to task detail view

docs/workflows/index.rst, docs/workflows/scheduling-tasks.rst
closes #3077
https://pulp.plan.io/issues/3077
=> Added a new 'Scheduling Tasks' section to the 'Workflows' page

docs/dev-guide/contributing/building.rst
Rename pulp_packaging to pulp-ci
=> Rename pulp_packaging to pulp-ci

docs/installation/configuration-files.rst, docs/integration_guide/rest_api/authentication.rst, platform/pulpcore/app/settings.py, platform/pulpcore/etc/pulp/server.yaml
fixes #3107
https://pulp.plan.io/issues/3107
=> Change the default header prefix for jwt requests

agent/pulp/agent/lib/container.py, bindings/pulp/bindings/server.py, bindings/test/unit/test_server.py, client_lib/test/unit/test_client_framework_core.py, common/pulp/common/lock.py, common/pulp/common/pic.py, pulp-dev.py, repoauth/pulp/repoauth/repo_cert_utils.py, server/pulp/server/auth/ldap_connection.py, server/pulp/server/content/storage.py, server/pulp/server/db/migrations/0027_importer_schema_change.py, server/pulp/server/managers/auth/cert/certificate.py, server/pulp/server/managers/consumer/cud.py, server/pulp/server/managers/status.py, server/pulp/server/webservices/views/consumers.py, server/test/unit/server/managers/consumer/group/test_cud.py, server/test/unit/server/managers/content/test_orphan.py, server/test/unit/server/managers/repo/group/test_cud.py, server/test/unit/server/test_logs.py
closes #3106
https://pulp.plan.io/issues/3106
=> Fixed new flake8 errors

docs/dev-guide/integration/rest-api/consumer/applicability.rst
=> Fix repo applicability json example

plugin/pulpcore/plugin/download/futures/batch.py, plugin/pulpcore/plugin/download/futures/single.py
The `Batch` greatly simplified.
Fixed Download._repair logging stack trace for DownloadError (like 404s)
=> Simpler batch implementation.

platform/pulpcore/app/models/task.py, platform/pulpcore/app/views/status.py
closes #2659
https://pulp.plan.io/issues/2659
=> Show only the online workers in the status API

platform/pulpcore/app/models/fields.py, plugin/pulpcore/plugin/changeset/model.py
closes #3113
https://pulp.plan.io/issues/3113
=> Specify a path instead of an open file for Artifact instantiation

server/pulp/server/controllers/repository.py
closes #3119
https://pulp.plan.io/issues/3119
=> Log scenarios where a full sync or publish is being forced

server/pulp/server/managers/content/upload.py
https://pulp.plan.io/issues/3090
=> Propagate coded exceptions raised during upload.

pulpcore/pulpcore/app/viewsets/user.py
fixes #3123
https://pulp.plan.io/issues/3123
=> Fix jwt reset response

docs/installation/configuration-files.rst, pulpcore/pulpcore/app/settings.py, pulpcore/pulpcore/app/views/content.py, pulpcore/pulpcore/etc/pulp/server.yaml
https://pulp.plan.io/issues/2914
=> Support apache and nginx.

manage.py
Update symlink to manage.py that broke with platform->pulpcore rename
=> Add __init__.py to pulpcore/apidocs to make it a discoverable package.

server/selinux/server/pulp-celery.te
re #3159
https://pulp.plan.io/issues/3159
=> Update selinux definitions for qpid so it runs on f27

pulpcore/pulpcore/etc/pulp/server.yaml
Missed this during the review of #3225.
=> Fixed content.web_server default.

pulpcore/pulpcore/app/models/content.py, pulpcore/pulpcore/app/viewsets/content.py
closes #3016
https://pulp.plan.io/issues/3016
=> Delete an Artifact only if it is not associated with any Content

docs/contributing/3.0-development/rest-api.rst, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/serializers/task.py, pulpcore/pulpcore/app/serializers/user.py, pulpcore/pulpcore/app/viewsets/repository.py, pulpcore/pulpcore/app/viewsets/task.py, pulpcore/pulpcore/app/viewsets/user.py
fixes #3125
https://pulp.plan.io/issues/3125
=> Using UUIDs in URLs for users, publishers, importers, distros, and workers

pulpcore/pulpcore/app/models/__init__.py, pulpcore/pulpcore/app/models/progress.py, pulpcore/pulpcore/app/models/publication.py, pulpcore/pulpcore/app/models/task.py, pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/serializers/task.py, pulpcore/pulpcore/app/tasks/publisher.py, pulpcore/pulpcore/app/viewsets/__init__.py, pulpcore/pulpcore/app/viewsets/repository.py
Easier to combine the implementation of these 2 tasks.
Example publish:  
```
$ http POST http://f25a.redhat.com:8000/api/v3/publications/ \
publisher='http://f25a.redhat.com:8000/api/v3/publishers/file/main/'
```
https://pulp.plan.io/issues/3102
https://pulp.plan.io/issues/3033
=> Publishing updates.

pulpcore/pulpcore/app/serializers/repository.py
Found this while testing but somehow did not get committed.
=> Removed lookup_field on publication serialzer.

pulpcore/pulpcore/app/models/auth.py
fixes #3174
https://pulp.plan.io/issues/3174
=> Update user model to have a UUID

pulpcore/pulpcore/app/viewsets/repository.py
fixes #3080
https://pulp.plan.io/issues/3080
=> Add importer filters

pulpcore/pulpcore/app/viewsets/user.py
fixes #3142
https://pulp.plan.io/issues/3142
=> Add username filters for user list endpoint

server/selinux/server/pulp-server.te
closes #3159
https://pulp.plan.io/issues/3159
=> Allow httpd access to amqp and mongo ports

server/pulp/server/controllers/importer.py, server/test/unit/server/controllers/test_importer.py
MongoDB does not allow to change keys of the DictField
and values of the same DictField simultaneously thus we need
to save importer config twice.
closes #3210
https://pulp.plan.io/issues/3210
=> Save importer config in a proper way for MongoDB DictField

server/selinux/server/pulp-streamer.te
re #3159
https://pulp.plan.io/issues/3159
=> Update selinux policies to allow httpd access to squid port

pulpcore/pulpcore/app/tasks/repository.py
Repo version squash logic is implemented according to this design:
https://github.com/pulp/pulp/pull/3228#issuecomment-347659974
fixes #3233
https://pulp.plan.io/issues/3233
=> Update repo version squash logic to deal with readded content

pulpcore/pulpcore/app/viewsets/base.py
fixes #3230
https://pulp.plan.io/issues/3230
=> Add a check to see if parent object exists for nested viewsets

pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/tasks/repository.py
fixes #3219
https://pulp.plan.io/issues/3219
This goes with https://github.com/pulp/pulp_file/pull/25.
=> Allow users to delete the latest repo version

pulpcore/pulpcore/app/serializers/task.py
closes #3277
https://pulp.plan.io/issues/3277
=> Serialize deleted resources as null

pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/tasks/publisher.py, pulpcore/pulpcore/app/viewsets/repository.py
closes #3222
https://pulp.plan.io/issues/3222
=> Add complete field

pulpcore/pulpcore/app/viewsets/repository.py
fixes #3218
https://pulp.plan.io/issues/3218
=> Changed routes and added docs for added/removed content

pulpcore/pulpcore/app/models/publication.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/tasks/publisher.py
closes #3312
https://pulp.plan.io/issues/3312
=> Serialize RepositoryVersion on Publication

docs/plugins/plugin-api/index.rst, docs/plugins/plugin-api/tasking.rst, docs/plugins/plugin-api/tasks.rst, plugin/pulpcore/plugin/tasking.py, plugin/pulpcore/plugin/tasks.py, pulpcore/pulpcore/tasking/services/storage.py
https://pulp.plan.io/issues/3280
Also, refactored the services.storage functions into a WorkingDirectory class (context manager).
File plugin: https://github.com/pulp/pulp_file/pull/30
=> Consolidated tasking modules in pluign API.

pulpcore/pulpcore/tasking/celery_app.py, pulpcore/pulpcore/tasking/services/storage.py
Missed a spot where one of the working directory functions was being used.
=> Fix task init deleting the previous working directories.

plugin/pulpcore/plugin/repository.py
Removed RepositoryVersion._created_resource.
A few docstring corrections.
=> Removed RepositoryVersion._created_resource

pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/serializers/task.py, pulpcore/pulpcore/tasking/util.py
https://pulp.plan.io/issues/3226
Also fixed a few issues with `RepositoryVersion`.
=> Clean up incomplete created-resources.

pulpcore/pulpcore/app/models/publication.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/viewsets/repository.py
Only complete Publications can be distributed.
closes: #3184
https://pulp.plan.io/issues/3184
=> Add complete field to Publication

pulpcore/pulpcore/app/models/publication.py
https://pulp.plan.io/issues/3295
I originally added `add_artifact()` and `add_metadata()` as defined by the issue but after writing them they did not seem to provide much value.  Perhaps more discussion is needed.
=> Publishing context manager.

pulpcore/pulpcore/app/viewsets/base.py, pulpcore/pulpcore/app/viewsets/repository.py
Provides a generic way for a `ViewSet` to resolve resource URIs passed in the request _body_ to an instance of the resource (model).
=> Support generic URI resolution to resource instance.

pulpcore/pulpcore/app/viewsets/custom_filters.py, pulpcore/pulpcore/app/viewsets/repository.py
fixes #3238
https://pulp.plan.io/issues/3238
=> Add RepositoryVersion Filter

plugin/pulpcore/plugin/changeset/main.py, pulpcore/pulpcore/app/models/publication.py, pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/tests/viewsets/test_base.py, pulpcore/pulpcore/app/viewsets/repository.py
closes #3341
https://pulp.plan.io/issues/3341
=> Remove relationship between publishers/importers and repos

pulpcore/pulpcore/app/models/publication.py, pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/serializers/repository.py
For importer and publisher, the `name` is the natural key and must be unique.
=> Importer and publisher names must be unique.

pulpcore/pulpcore/app/models/__init__.py, pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/viewsets/repository.py
https://pulp.plan.io/issues/2894
=> Support Exporters.

pulpcore/pulpcore/app/serializers/repository.py
Found two parameters that were missing from the api docs.
=> Fixing missing repository version create parameters

pulpcore/pulpcore/app/models/base.py, pulpcore/pulpcore/app/models/repository.py
Using the `Content` model directly adds clarity and removes complexity.
=> RepositoryVersion.content() property improvements.

pulpcore/pulpcore/app/serializers/base.py
closes #3355
https://pulp.plan.io/issues/3355
=> Add docstring to fix Sphinx 1.7 doc breakage

pulpcore/pulpcore/app/models/publication.py
fixes #3354
https://pulp.plan.io/issues/3354
=> Fix publication deletion

server/pulp/server/async/scheduler.py, server/test/unit/server/async/test_tasks.py, server/test/unit/server/db/test_model.py
Not yet complete, just for testing purposes.
=> Fix broken unit tests on celery 4

pulpcore/pulpcore/app/models/task.py, pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/viewsets/base.py, pulpcore/pulpcore/app/viewsets/repository.py, pulpcore/pulpcore/tasking/tasks.py, pulpcore/pulpcore/tasking/util.py
fixes #3186
https://pulp.plan.io/issues/3186
=> Support the locking of multiple resources

plugin/pulpcore/plugin/models/importer.py
re: #3074
https://pulp.plan.io/issues/3074
=> Clean up plugin API Importer docstring

docs/plugins/plugin-writer/basics.rst, docs/plugins/plugin-writer/checklist.rst, docs/plugins/plugin-writer/first-plugin.rst, docs/plugins/plugin-writer/index.rst
fixes #3364
https://pulp.plan.io/issues/3364
=> Point users to pulp_file instead of pulp_example

.travis.yml, pulpcore/pulpcore/app/settings.py, pulpcore/pulpcore/etc/pulp/server.yaml
https://pulp.plan.io/issues/3359
closes #3359
=> Switch Pulp to use sqlite3 as default

pulpcore/pulpcore/app/serializers/fields.py, pulpcore/pulpcore/app/viewsets/base.py
For more info see https://git.io/vAKBA
=> Namespace DRF's ValidationError under serializers

pulpcore/pulpcore/app/serializers/repository.py
fixes #3394
https://pulp.plan.io/issues/3394
=> Updating distribution validation

pulpcore/pulpcore/app/models/task.py
Task models do not have a ```self.request``` attribute
WIP, trying to reproduce anpther issue I had.
=> Fix referencing attribute that does not exist

docs/user-guide/consumer-client/introduction.rst
refs #1875
https://pulp.plan.io/issues/1875
=> Add section about DNF to consumer docs

plugin/pulpcore/plugin/fields.py
closes #3434
https://pulp.plan.io/issues/3434
=> Expose pulpcore.app.fields.JSONField to plugins

common/pulpcore/common/tags.py, plugin/pulpcore/plugin/viewsets.py, pulpcore/pulpcore/app/models/__init__.py, pulpcore/pulpcore/app/models/task.py, pulpcore/pulpcore/app/serializers/task.py, pulpcore/pulpcore/app/viewsets/task.py, pulpcore/pulpcore/tasking/tasks.py
fixes #3426
https://pulp.plan.io/issues/3426
=> Remove unused task code

pulpcore/pulpcore/app/models/publication.py, pulpcore/pulpcore/app/serializers/repository.py
fixes #3451
https://pulp.plan.io/issues/3451
=> Remove http and https options from distributions

pulpcore/pulpcore/app/serializers/repository.py
fixes #3448
https://pulp.plan.io/issues/3448
=> Add warning about overlapping distribution base paths

pulpcore/pulpcore/app/settings.py, pulpcore/pulpcore/app/views/status.py
closes #2867
https://pulp.plan.io/issues/2867
=> Added version information for Pulp plugins to Status API

.gitignore, pulpcore/pulpcore/app/serializers/base.py, pulpcore/pulpcore/app/serializers/repository.py
fixes #3412
https://pulp.plan.io/issues/3412
=> Validate distribution base paths

pulpcore/pulpcore/app/viewsets/custom_filters.py, pulpcore/pulpcore/app/viewsets/repository.py, pulpcore/pulpcore/app/viewsets/task.py
fixes #3144
https://pulp.plan.io/issues/3144
=> Allow users to filter by tasks

plugin/pulpcore/plugin/changeset/iterator.py
closes #3499
https://pulp.plan.io/issues/3499
=> Set batch size to 800 to resolve sqlite issues

pulpcore/pulpcore/app/models/content.py
fixes #3508
https://pulp.plan.io/issues/3508
=> Clean up file on Artifact deletion

pulpcore/pulpcore/app/viewsets/base.py
closes #3093
https://pulp.plan.io/issues/3093
=> Include filter fields into schema for read actions only

pulpcore/pulpcore/app/viewsets/base.py
closes #3466
https://pulp.plan.io/issues/3466
=> Fixes publishing any repository version

.travis/server.sqlite.yaml, pulpcore/pulpcore/etc/pulp/server.yaml
Increase the sqlite timeout from 20 to 120 seconds
re: 3456
https://pulp.plan.io/issues/3456
=> Increase sqlite timeout

pulpcore/pulpcore/app/viewsets/task.py
closes #3143
https://pulp.plan.io/issues/3143
=> Add worker filtering

pulpcore/pulpcore/app/viewsets/repository.py, pulpcore/pulpcore/app/viewsets/task.py
closes #3536
https://pulp.plan.io/issues/3536
=> Fix date filtering on tasks and repository versions

pulpcore/pulpcore/app/tasks/__init__.py, pulpcore/pulpcore/app/tasks/orphan.py, pulpcore/pulpcore/app/urls.py, pulpcore/pulpcore/app/views/__init__.py, pulpcore/pulpcore/app/views/orphans.py, pulpcore/pulpcore/tasking/tasks.py
fixes #3442
https://pulp.plan.io/issues/3442
=> As a user, I can cleanup orphan content and artifacts

pulpcore/pulpcore/app/models/task.py
closes #3554
https://pulp.plan.io/issues/3554
=> Don't run tasks on the resource manager

.travis/install.sh, docs/contributing/3.0-development/app-layout.rst, docs/contributing/3.0-development/data-modeling.rst, docs/contributing/3.0-development/rest-api.rst, docs/contributing/language_guide.rst, docs/plugins/plugin-api/download.rst, docs/plugins/plugin-writer/basics.rst, docs/plugins/plugin-writer/checklist.rst, docs/plugins/plugin-writer/first-plugin.rst, plugin/pulpcore/plugin/changeset/__init__.py, plugin/pulpcore/plugin/changeset/main.py, plugin/pulpcore/plugin/changeset/model.py, plugin/pulpcore/plugin/download/factory.py, plugin/pulpcore/plugin/download/group.py, plugin/pulpcore/plugin/models/__init__.py, plugin/pulpcore/plugin/models/remote.py, plugin/pulpcore/plugin/serializers.py, plugin/pulpcore/plugin/viewsets.py, pulpcore/pulpcore/app/models/__init__.py, pulpcore/pulpcore/app/models/base.py, pulpcore/pulpcore/app/models/content.py, pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/urls.py, pulpcore/pulpcore/app/viewsets/__init__.py, pulpcore/pulpcore/app/viewsets/repository.py, pulpcore/tests/viewsets/test_base.py, test_requirements.txt
closes #3488
https://pulp.plan.io/issues/3488
=> Renames Importer to Remote

pulpcore/pulpcore/app/viewsets/content.py, pulpcore/pulpcore/app/viewsets/repository.py
Create provides more than just the ```create()``` method, too.
=> Added back two mixins removed earlier

pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/serializers/repository.py
Requires PR: PulpQE/pulp-smash#930
Requires PR: pulp/pulp_file#64
closes #3453
https://pulp.plan.io/issues/3543
=> Rename Remote.feed_url to Remote.url

pulpcore/pulpcore/app/viewsets/repository.py
fixes #3081
https://pulp.plan.io/issues/3081
=> Add name_in_list filter to publisher endpoint

.travis/pulp-smash-config.json
https://pulp.plan.io/issues/3563
=> closes #3563

pulpcore/pulpcore/app/serializers/base.py, pulpcore/pulpcore/app/viewsets/base.py, pulpcore/pulpcore/app/viewsets/custom_filters.py, pulpcore/pulpcore/app/viewsets/repository.py, pulpcore/pulpcore/app/viewsets/task.py, pulpcore/pulpcore/app/viewsets/user.py
Fixes 
* https://pulp.plan.io/issues/3082
* https://pulp.plan.io/issues/3557
* https://pulp.plan.io/issues/3558
=> Filtering overhaul

pulpcore/pulpcore/app/viewsets/base.py
closes #3567
https://pulp.plan.io/issues/3567
=> get_resource() shouldn't accept a non-specific URI

pulpcore/pulpcore/app/viewsets/base.py, pulpcore/tests/viewsets/test_base.py
closes #3567
https://pulp.plan.io/issues/3568
=> Add more unit tests around NamedModelViewSet

pulpcore/pulpcore/app/serializers/repository.py, pulpcore/tests/serializers/test_repository.py
fixes #2987
https://pulp.plan.io/issues/2987
=> Validate overlapping distribution paths

pulpcore/pulpcore/app/models/__init__.py, pulpcore/pulpcore/app/models/task.py, pulpcore/tests/models/test_task.py
closes #3509
https://pulp.plan.io/issues/3509
=> Prevent task deletion with locked resources

.coveragerc, .travis/script.sh, README.md, test_requirements.txt
VVV This is expected since there are no prior codecov data. VVV
=> Switch to codecov

pulpcore/pulpcore/app/apps.py, pulpcore/pulpcore/app/views/content.py, pulpcore/pulpcore/app/viewsets/__init__.py, pulpcore/pulpcore/app/viewsets/base.py, pulpcore/pulpcore/app/viewsets/content.py, pulpcore/pulpcore/tasking/celery_instance.py, pulpcore/pulpcore/tasking/services/manage_workers.py
* Added some comments
* Converted some comments to google-style
* Moved some filters around for clarity
* Deleted an old reference to Scheduler
* Added Exporter to the ViewSets __init__.py
* Removed filters from "retrieve" action in the DefaultSchema
(this actually does not change the generated schema at all, I checked)
=> General cleanup

pulpcore/pulpcore/etc/pulp/server.yaml
fixes #3588
https://pulp.plan.io/issues/3588
=> Add documentation for MEDIA_ROOT setting

docs/plugins/index.rst
closes #3600
https://pulp.plan.io/issues/3600
=> Add python to the table of available plugins

pulpcore/pulpcore/app/serializers/base.py
fixes #3633
https://pulp.plan.io/issues/3633
=> Exposing pk in responses for resources

docs/installation/instructions.rst
https://pulp.plan.io/issues/3612
=> Update migration doc.

.travis.yml, .travis/deploy.sh
POC that pushed to test.pypi.org: https://travis-ci.org/werwty/pulp/builds/377874762
Instructions on how to use this: https://pulp.plan.io/projects/pulp/wiki/Pulp3_Release_Guide
closes #3614
https://pulp.plan.io/issues/3614
=> Have Travis push packages to pypi whenever a pulp3 tags are created

pulpcore/pulpcore/app/viewsets/task.py
closes #3586
https://pulp.plan.io/issues/3586
=> Fix indeterministic worker filtering

pulpcore/pulpcore/app/settings.py
closes #3685
https://pulp.plan.io/issues/3685
=> Update MIDDLEWARE_CLASSES to MIDDLEWARE in settings.py

server/pulp/server/managers/auth/cert/cert_generator.py
closes #3676
https://pulp.plan.io/issues/3676
=> Fixes login API on FIPS enabled machines

pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/serializers/base.py, pulpcore/pulpcore/app/serializers/task.py, pulpcore/pulpcore/app/viewsets/base.py, pulpcore/pulpcore/app/viewsets/task.py, pulpcore/tests/viewsets/test_base.py
closes #3587
https://pulp.plan.io/issues/3587
=> Fixes using multiple serializers on derived viewsets

pulpcore/pulpcore/app/models/__init__.py, pulpcore/pulpcore/app/models/task.py
TaskLock should have been removed with the RQ transition. It is no
longer used.
=> Removes TaskLock

server/pulp/server/db/model/__init__.py
closes #3687
https://pulp.plan.io/issues/3687
=> Fixes Pulp w/ Mongoengine v0.14.1+

README.md, codecov.yml, common/README.rst, docs/contributing/continuous-integration.rst, docs/contributing/dev-setup/source.rst, docs/contributing/git.rst, docs/installation/instructions.rst, docs/plugins/plugin-writer/planning-guide.rst, plugin/README.rst, pulpcore/README.rst
fixes #3713,#3710
https://pulp.plan.io/issues/3713
https://pulp.plan.io/issues/3710
=> Updating docs and configs to use master instead of 3.0-dev

server/pulp/server/db/model/__init__.py, server/test/unit/server/db/test_model.py
https://pulp.plan.io/issues/3663
=> Fix orphan delete performance by adding missing index.

.travis/install.sh, docs/installation/instructions.rst, pulpcore/setup.py
RQ v0.11.0 contains the changes we need.
=> Remove installation step for installing RQ by git commit

pulpcore/pulpcore/app/serializers/repository.py
fixes #3748
https://pulp.plan.io/issues/3748
=> Updating distribution name help text to mention uniqueness

pulpcore/pulpcore/etc/pulp/server.yaml
https://pulp.plan.io/issues/3702
=> Comment DATABASE.

plugin/pulpcore/plugin/serializers.py, pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/tests/serializers/test_repository.py
https://pulp.plan.io/issues/3617
fixes #3617
=> Add Sync and Publish serializers

client_admin/pulp/client/admin/event.py, client_admin/test/unit/test_event.py, docs/dev-guide/integration/events/http.rst, docs/user-guide/release-notes/2.17.x.rst, docs/user-guide/release-notes/index.rst, server/pulp/server/event/http.py, server/test/unit/server/event/test_http.py
https://pulp.plan.io/issues/3780
=> Support ca_path passed in configuration for http notifier.

pulpcore/pulpcore/app/pagination.py
fixes #3790
https://pulp.plan.io/issues/3790
Note: This is up for discussion on pulp-dev. Recommend waiting a bit before merging.
=> Allow users to override page size

docs/bugs-features.rst, docs/index.rst, docs/overview/from-pulp-2.rst
Added new irc channels for content types.
Fix few typos & broken hyperlinks.
=> Minor Documentation fixes: Add new content type irc channels and typo/hyperlink fixes

docs/contributing/architecture/rest-api.rst, pulpcore/pulpcore/app/serializers/base.py, pulpcore/pulpcore/app/viewsets/content.py, pulpcore/pulpcore/app/viewsets/custom_filters.py, pulpcore/pulpcore/app/viewsets/repository.py, pulpcore/pulpcore/app/viewsets/task.py, pulpcore/pulpcore/app/viewsets/user.py
fixes #3852
https://pulp.plan.io/issues/3852
Required PR: PulpQE/pulp-smash#1105
=> Update code for new release of django-filter 2.0

pulpcore/pulpcore/app/urls.py
Per https://github.com/encode/django-rest-framework/blob/master/rest_framework/urls.py#L2-L12
=> Add login functionality to the browseable api

docs/Makefile, docs/contributing/architecture/app-layout.rst, docs/contributing/architecture/rest-api.rst, pulpcore/pulpcore/app/models/__init__.py, pulpcore/pulpcore/app/models/content.py, pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/urls.py, pulpcore/pulpcore/app/viewsets/__init__.py
Also did a little bit of formatting - because it didn't conform to what the docs said it should be
=> Fix a bunch of bad references in ReST docs

docs/user-guide/release-notes/2.16.x.rst, server/bin/pulp-gen-ca-certificate
=> 2.16.4 Picks

pulpcore/pulpcore/app/viewsets/__init__.py, pulpcore/pulpcore/app/viewsets/base.py, pulpcore/pulpcore/app/viewsets/content.py, pulpcore/pulpcore/app/viewsets/repository.py, pulpcore/pulpcore/app/viewsets/task.py, pulpcore/pulpcore/app/viewsets/user.py
Creating a BaseFilterSet class that will automatically set help_text for filters in our REST API schema.
fixes #3635
https://pulp.plan.io/issues/3635
=> Adding help text for FilterSet fields

server/pulp/server/managers/consumer/applicability.py
closes #3886
https://pulp.plan.io/issues/3886
=> Add batch_size for querying applicability profiles

pulpcore/pulpcore/app/pagination.py
fixes #3801
https://pulp.plan.io/issues/3801
=> Changing from cursor to page number pagination

plugin/pulpcore/plugin/viewsets.py
re #3827, #3897, #3898
https://pulp.plan.io/issues/3827
https://pulp.plan.io/issues/3897
https://pulp.plan.io/issues/3898
=> Exposes BaseFilterSet for plugins

plugin/pulpcore/plugin/stages/declarative_version.py
re #3844
https://pulp.plan.io/issues/3844
=> Fixes string comparison

plugin/pulpcore/plugin/download/factory.py, plugin/pulpcore/plugin/download/http.py, plugin/pulpcore/plugin/stages/artifact_stages.py, plugin/pulpcore/plugin/stages/declarative_version.py
https://pulp.plan.io/issues/3907
closes #3907
=> Add auto_decompress option everywhere

docs/user-guide/installation/extra_configuration.rst
https://pulp.plan.io/issues/3887
re #3887
=> Use the correct command for maintenance dispatch

server/pulp/server/managers/consumer/applicability.py
Results are written into a separate collection which is reused
every time hte cleanup is run.
If there are millions of orphaned applicability profiles,
it's easy to exceed 16MB.
closes #3893
https://pulp.plan.io/issues/3893
=> Use aggregation pipeline to avoid BSON 16MB size limit

docs/user-guide/installation/extra_configuration.rst
https://pulp.plan.io/issues/3908
closes #3908
=> Adds docs about pulp-maintenance package

plugin/pulpcore/plugin/download/factory.py, plugin/pulpcore/plugin/download/http.py, plugin/pulpcore/plugin/stages/artifact_stages.py, plugin/pulpcore/plugin/stages/declarative_version.py
=> Revert "Add auto_decompress option everywhere"

server/selinux/server/pulp-celery.te, server/selinux/server/pulp-streamer.te
This PR is currently disorganized and pending cleanup, but it should be functional.
=> Update SELinux policy

pulpcore/pulpcore/app/settings.py, pulpcore/pulpcore/app/views/content.py, pulpcore/pulpcore/etc/pulp/server.yaml
https://pulp.plan.io/issues/3696
https://pulp.plan.io/issues/3697
Support redirect to the streamer.  This includes adding REDIRECT settings to the CONTENT section.
I doubt the defaults are correct but we can change them later.
=> Support redirect in the content application.

pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/tasks/repository.py, pulpcore/pulpcore/app/viewsets/repository.py
fixes #3360
https://pulp.plan.io/issues/3360
=> Allow users to specify a base_version when creating a repo version

plugin/pulpcore/plugin/stages/api.py, pulpcore/pulpcore/app/models/progress.py
Up to now, if a stage raises an exception the asyncio.gather() call for all
stages will return directly and raise the exception.  This does not terminate
the other stages and they will remain scheduled (typically waiting for
input), as can be seen in the task report:
```
"progress_reports": [
{
"done": 0,
"message": "Associating Content",
"state": "running",
"suffix": "",
"task": "http://localhost:8000/pulp/api/v3/tasks/8084f037-bc11-4201-83bd-7c74dd18513b/",
"total": null
},
...
{
"done": 1,
"message": "Downloading Metadata",
"state": "completed",
"suffix": "",
"task": "http://localhost:8000/pulp/api/v3/tasks/8084f037-bc11-4201-83bd-7c74dd18513b/",
"total": 1
},
...
{
"done": 1,
"message": "Parsing Metadata",
"state": "failed",
"suffix": "",
"task": …
```
=> DeclarativeVersion: Cancel all remaining stages if one stage fails with an exception

common/pulp/common/plugins/importer_constants.py, docs/user-guide/server.rst, server/pulp/plugins/util/nectar_config.py
fixes #1758
https://pulp.plan.io/issues/1758
=> Exposing config options for read_timeout and connect_timeout

plugin/pulpcore/plugin/stages/declarative_version.py
re #3944
https://pulp.plan.io/issues/3944
=> Fix docstring of DeclarativeVersion

.travis.yml, common/setup.py, docs/contributing/dev-setup/quickstart.rst, docs/contributing/style-guide.rst, docs/installation/instructions.rst, plugin/setup.py, pulpcore/setup.py
closes #3984
https://pulp.plan.io/issues/3984
=> Remove Python 3.5 support

docs/plugins/index.rst
=> adds plugin writers guide link to the menu on left

.travis/install.sh
=> Pin version of sphinx to 1.7.9 while 1.8 has a bug with search

docs/release-notes/plugin_api/0.1.z.rst, docs/release-notes/pulpcore/3.0.x.rst, plugin/setup.py, pulpcore/setup.py
=> Release notes and release bump for beta 8

pulpcore/setup.py
=> Bumps pulpcore release so nightly docs reflect the correct version

docs/conf.py
re: #4027
https://pulp.plan.io/issues/4027
=> Reverts sphinx config to work with 1.7.9

.travis/script.sh, plugin/pulpcore/plugin/stages/api.py, plugin/pulpcore/plugin/stages/artifact_stages.py, plugin/pulpcore/plugin/stages/association_stages.py, plugin/pulpcore/plugin/stages/content_unit_stages.py, plugin/tests/unit/stages/test_stages.py, test_requirements.txt
Implementation of batches iterator and refactoring of existing stages. Changes to ArtifactDownloader  (https://pulp.plan.io/issues/4018) will be a separate PR..
=> Add async batches iterator

pulpcore/pulpcore/app/models/content.py
=> Artifact is compatible with bulk_create()

docs/bugs-features.rst, docs/contributing/continuous-integration.rst
Add info about functional tests, and the use of Pulp smash to write functional tests.
=> Update documentation section related to tests

pulpcore/pulpcore/app/views/content.py, pulpcore/pulpcore/tasking/util.py
One of the issues noticed by LGTM integration. MissingResource doesn't
take any args, only kwargs.
[noissue]
=> Fix MissingResource arguments

plugin/pulpcore/plugin/stages/declarative_version.py
For most custom pipelines it should be sufficient to override
`DeclarativeVersion.pipeline_stages()` now.
fixes #3935
https://pulp.plan.io/issues/3935
=> Allow simpler pipeline customization in DeclarativeVersion

plugin/pulpcore/plugin/models/__init__.py, plugin/pulpcore/plugin/serializers.py, plugin/pulpcore/plugin/viewsets.py, pulpcore/pulpcore/app/models/__init__.py, pulpcore/pulpcore/app/models/content.py, pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/serializers/content.py, pulpcore/pulpcore/app/viewsets/__init__.py, pulpcore/pulpcore/app/viewsets/content.py
https://pulp.plan.io/issues/3969
=> Add ContentGuard model, serializer and viewset.

README.md
=> Add links to issue tracker and mailing lists to README

docs/installation/configuration.rst, docs/plugins/plugin-api/overview.rst, docs/plugins/plugin-api/profiling.rst, plugin/pulpcore/plugin/stages/__init__.py, plugin/pulpcore/plugin/stages/api.py, plugin/pulpcore/plugin/stages/artifact_stages.py, plugin/pulpcore/plugin/stages/models.py, plugin/pulpcore/plugin/stages/profiler.py, pulpcore/pulpcore/app/management/commands/stage-profile-summary.py, pulpcore/pulpcore/app/settings.py
- adds docs for it
- adds the PROFILE_STAGES_API setting
- adds a management command to summarize the statistics
- adds an extra_data field to DeclarativeContent and DeclarativeArtifact
https://pulp.plan.io/issues/4021
closes #4021
=> Adds a performance profiler for the Stages API

docs/release-notes/plugin_api/0.1.z.rst, docs/release-notes/pulpcore/3.0.x.rst, plugin/setup.py
=> docs for beta 9

pulpcore/pulpcore/app/serializers/base.py
=> Fixes the operation postponed serializer

docs/release-notes/plugin_api/0.1.z.rst, docs/release-notes/pulpcore/3.0.x.rst, plugin/setup.py, pulpcore/setup.py
=> release notes and release number bump for beta 10

pulpcore/pulpcore/app/models/publication.py
[noissue]
here:
fix them and update your pull request.
Thank you so much for contributing to Pulp!
=> Make publisher optional

plugin/pulpcore/plugin/viewsets.py, pulpcore/pulpcore/app/urls.py
[noissue]
here:
fix them and update your pull request.
Thank you so much for contributing to Pulp!
=> Expose NamedModelViewSet to plugins

docs/release-notes/plugin_api/0.1.z.rst, docs/release-notes/pulpcore/3.0.x.rst, plugin/setup.py, pulpcore/setup.py
here:
fix them and update your pull request.
Thank you so much for contributing to Pulp!
=> Releasing new plugin and pulpcore versions

plugin/pulpcore/plugin/viewsets.py, pulpcore/pulpcore/app/viewsets/__init__.py
re #3783
https://pulp.plan.io/issues/3783
=> Exposes ContentFilter for plugins

.travis/install.sh
fixes #4037
https://pulp.plan.io/issues/4037
=> Allow commits to require pulp-smash PRs

pulpcore/pulpcore/app/models/publication.py, pulpcore/pulpcore/app/serializers/repository.py
https://pulp.plan.io/issues/3970
=> Associate content-guard with a distribution.

server/pulp/server/db/manage.py
closes #4055
https://pulp.plan.io/issues/4055
=> Create indexes before running any migration

pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
Test whether `base_version` can be used in conjunction with `add_content_unit`
and `remove_content_unit`.
See: https://pulp.plan.io/issues/3360
'[noissue]'
=> Expand base_version test case

pulpcore/pulpcore/app/models/publication.py
=> Explicitly references ContentGuard with a class name

plugin/pulpcore/plugin/download/http.py
closes #4036
https://pulp.plan.io/issues/4036
=> Retry in case of some 5XX errors

docs/release-notes/plugin_api/0.1.z.rst, docs/release-notes/pulpcore/3.0.x.rst, plugin/setup.py, pulpcore/setup.py
=> Release notes and release bump for beta 12

.travis/2.17-release.yaml
=> Bump version to 2.17.1

docs/user-guide/release-notes/2.17.x.rst
=> Release notes for 2.17.1

docs/user-guide/release-notes/2.17.x.rst
(cherry picked from commit 55e0cf9395669585c8ffe1050f92d91ee584ee76)
=> 2.17.1 release notes cherry-pick

pulpcore/pulpcore/app/views/content.py
https://pulp.plan.io/issues/4043
=> Set Content-Disposition header properly.

pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
Remove `created` field to avoid assertions related to time. Refactor the tests
to reflect this change.
'[noissue]'
=> Refactor base_version tests

pulpcore/tests/functional/api/test_auth.py
Remove JWT tests, and functions related to it.
See: https://pulp.plan.io/issues/3248
'[noissue]'
=> Remove JWT tests

pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/templatetags/pulp_urls.py, pulpcore/pulpcore/app/views/content.py, pulpcore/pulpcore/app/viewsets/base.py
pylint catches a lot of errors if it's ok to fix all errors I can send more patches.
=> Fix some pylint errors

pulpcore/tests/functional/api/test_auth.py
Update tests for basic auth. Make assertions more strict.
=> Update tests for auth

client_lib/pulp/client/commands/repo/cudl.py
fixes #4068
https://pulp.plan.io/issues/4068
=> Fix pulp-admin error when not running in tty

.travis/docs-builder.py, flake8.cfg, pulpcore/pulpcore/app/apps.py
It's causing failures, we need to fix them.
[noissue]
=> New Flake8 release has new formatting rules

docs/bugs-features.rst
here:
fix them and update your pull request.
Thank you so much for contributing to Pulp!
=> Add Test tracker to docs

pulpcore/pulpcore/app/models/publication.py
https://pulp.plan.io/issues/4045
=> Better support for auto-distribution.

server/pulp/server/db/migrations/lib/utils.py
re #4049
https://pulp.plan.io/issues/4049
=> Update progress with a custom number of processed items

plugin/pulpcore/plugin/stages/api.py, plugin/tests/unit/stages/test_stages.py
Yields a very significant performance improvement.
[noissue]
=> Change the default batch size to 50

plugin/pulpcore/plugin/stages/artifact_stages.py, plugin/pulpcore/plugin/stages/content_unit_stages.py, pulpcore/pulpcore/app/models/content.py
Solution: add a manager that provides a bulk_get_or_create() method
closes #4060
https://pulp.plan.io/issues/4060
=> Problem: bulk_create can fail with IntegrityError

docs/release-notes/plugin_api/0.1.z.rst, docs/release-notes/pulpcore/3.0.x.rst
=> Release notes for beta 14

docs/release-notes/plugin_api/0.1.z.rst, docs/release-notes/pulpcore/3.0.x.rst, plugin/setup.py, pulpcore/setup.py
=> Bumps version for beta 14

docs/user-guide/release-notes/2.18.x.rst, docs/user-guide/release-notes/index.rst
=> Add release notes for 2.18.0

pulpcore/tests/functional/api/using_plugin/test_crd_publications.py, pulpcore/tests/functional/api/utils.py
Closes PulpQE/pulp-smash#954
Related to https://pulp.plan.io/issues/3576
[noissue]
=> Test publications are ordered by create time in descending order

plugin/pulpcore/plugin/download/base.py
=> Fix type of MultiDict

docs/release-notes/plugin_api/0.1.z.rst, docs/release-notes/pulpcore/3.0.x.rst, plugin/setup.py, pulpcore/setup.py
=> Adds release notes and version bump for beta 15

plugin/pulpcore/plugin/stages/content_unit_stages.py, pulpcore/pulpcore/app/views/content.py
=> Formatting fixups

docs/release-notes/plugin_api/0.1.z.rst, docs/release-notes/pulpcore/3.0.x.rst, plugin/setup.py, pulpcore/setup.py
=> Bumps version, adds release notes for beta 16

docs/contributing/dev-setup/index.rst, docs/contributing/dev-setup/runtests.rst
=> Document how to run tests in the development setup

docs/user-guide/installation/fedora.rst, docs/user-guide/installation/rhel_centos.rst
closes #4228
https://pulp.plan.io/issues/4228
=> Add installation instructions for mongodb 3.x

plugin/pulpcore/plugin/storage.py, plugin/pulpcore/plugin/viewsets.py, pulpcore/pulpcore/app/models/storage.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/viewsets/__init__.py, pulpcore/pulpcore/app/viewsets/repository.py
https://pulp.plan.io/issues/4233
=> Add base serializer and viewset for content-guards.

pulpcore/app/viewsets/__init__.py
=> Expose RemoteFilter

docs/bugs-features.rst, docs/contributing/index.rst, docs/contributing/pull-request-walkthrough.rst, docs/index.rst, docs/plugins/index.rst, docs/workflows/index.rst
re: #4193
https://pulp.plan.io/issues/4193
=> Adds links to pulpcore-plugin docs

setup.py
=> Remove explicit dep on redis

pulpcore/app/views/status.py
Show version of pulpcore-plugin in status view
closes: #4235
https://pulp.plan.io/issues/4235
=> Show version of pulpcore-plugin

pulpcore/app/models/task.py, pulpcore/app/response.py, pulpcore/app/serializers/task.py, pulpcore/tasking/tasks.py, pulpcore/tasking/util.py, pulpcore/tasking/worker.py, pulpcore/tests/unit/models/test_task.py
fixes #3871
https://pulp.plan.io/issues/3871
=> Create a new Task field job_id to store rq job ids

pulpcore/etc/pulp/settings.py
https://pulp.plan.io/issues/4239
re #4239
=> Align default settings with new content app

docs/glossary.rst, docs/workflows/deferred-download.rst, docs/workflows/index.rst, docs/workflows/lazy-downloading.rst
https://pulp.plan.io/issues/4218
closes #4218
=> Add docs on lazy to the workflows section

pulpcore/app/models/content.py, pulpcore/app/models/fields.py
https://pulp.plan.io/issues/4272
closes #4272
=> Do not fail if file already moved to storage

.travis.yml
Travis only will deploy to pypi if the "on" setting is used to specify a
set of branches or if you set an option like "all_branches" or "tags".
[noissue]
here:
page for your pull request.  If there are failures, …
=> Fixing deployment code

docs/release-notes/pulpcore/3.0.x.rst, setup.py
=> Preparing release notes and bumping version for 3.0.0b18

pulpcore/content/handler.py, pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py, pulpcore/tests/functional/api/using_plugin/test_content_app.py
=> Enable streaming for PublishedArtifacts

pulpcore/app/models/__init__.py, pulpcore/app/models/content.py, pulpcore/app/models/publication.py, pulpcore/app/serializers/__init__.py, pulpcore/app/serializers/content.py, pulpcore/app/serializers/publication.py, pulpcore/app/serializers/repository.py, pulpcore/app/viewsets/__init__.py, pulpcore/app/viewsets/content.py, pulpcore/app/viewsets/publication.py, pulpcore/app/viewsets/repository.py
De-duplicate the `ContentGuard` classes and standardize the organization (modules) for _publication_ related classes.
=> Reorganization of publication related classes. [noissue]

pulpcore/content/handler.py
403 when `PermissionError` (or anything) is raised by the content guard.
Updated imports for consistency.
=> Fix handling of PermissionError raised by ContentGuard.

server/pulp/server/db/migrations/0029_applicability_schema_change.py
Not all MongoDB versions report a specific code whe index is not found.
closes #4225
https://pulp.plan.io/issues/4225
here:
fix them and update …
=> Don't fail migration in case there is no exception code

pulpcore/tasking/tasks.py
https://pulp.plan.io/issues/4331
I think keeping the `resources` parameter as `list` and not also support it also being a `str` as suggested in the issue, helps reduce API complexity.  It also seemed better to translate the user supplied `resources` list instead of mutating it. 
The `resources` could simply be a `collections.Iterable` to support passing `tuple` or `generators` but leaving this way for now.
=> Support resource URLs in enqueue_with_reservation().

.travis/install.sh, .travis/publish_docs.sh, docs/Makefile, docs/conf.py
=> Fixes doc building dependencies

pulpcore/app/viewsets/content.py
=> Remove dead code

docs/release-notes/pulpcore/3.0.x.rst, setup.py
=> Release notes and version bump for beta 20

docs/installation/configuration.rst, docs/installation/index.rst, docs/installation/storage.rst, pulpcore/app/models/fields.py, pulpcore/app/settings.py, pulpcore/content/handler.py
fixes #3900
https://pulp.plan.io/issues/3900
=> Add support for Amazon S3

docs/installation/instructions.rst
https://pulp.plan.io/issues/4390
closes #4390
=> Revise SELinux recommendation

docs/release-notes/pulpcore/3.0.x.rst, setup.py
=> Release notes and version bump for beta 21.

docs/release-notes/pulpcore/3.0.x.rst
fixes #4401
https://pulp.plan.io/issues/4401
=> Update release notes to use tags instead of dates

server/pulp/server/managers/consumer/applicability.py
closes #4373
https://pulp.plan.io/issues/4373
=> Handle non-existent repo case when checking types for applicability

pull_request_template.md
=> Shorten pull_request_template.md to just a link

pulpcore/content/handler.py
=> Fix missing _ in method name

docs/contributing/git.rst
=> Explain usage of noissue.

.coveragerc, .travis.yml, .travis/before_script.sh, .travis/script.sh, pulpcore/tests/functional/content_with_coverage.py
=> Combine test coverage

CODEOWNERS
More info about code owners: https://help.github.com/articles/about-code-owners/
=> Add QE as code owners of the functional tests

.travis/publish_docs.sh
fixes #4422
https://pulp.plan.io/issues/4422
=> Fix the publish nightly job

pulpcore/app/serializers/__init__.py, pulpcore/app/serializers/content.py, pulpcore/app/serializers/fields.py
Required PR: pulp/pulpcore-plugin#65
Required RP: pulp/pulp_file#166
re #4394
https://pulp.plan.io/issues/4394
=> Save ContentArtifacts in ContentSerializer

.travis/script.sh, docs/contributing/dev-setup/runtests.rst, docs/installation/instructions.rst, pulpcore/tasking/constants.py, pulpcore/tasking/services/manage_workers.py, pulpcore/tasking/services/worker_watcher.py, pulpcore/tasking/tasks.py, pulpcore/tasking/worker.py, pulpcore/tests/functional/api/test_workers.py
closes #4187
https://pulp.plan.io/issues/4187
=> Use hyphens for Pulp3' system units name.

.travis/2.18-release.yaml
=> 2.18.1 GA docs build. [noissue]

pulpcore/app/models/fields.py
closes #4382
https://pulp.plan.io/issues/4382
=> Refactor ArtifactFileField

server/pulp/server/db/manage.py, server/pulp/server/db/model/__init__.py
closes #4425
https://pulp.plan.io/issues/4425
=> Add unique index for login

pulpcore/app/serializers/repository.py
re #4449
https://pulp.plan.io/issues/4449
=> Sync in additive mode by default

pulpcore/app/serializers/fields.py
=> Allow validation of _artifacts field if empty
