pulp/pulp

client_lib/pulp/client/validators.py, client_lib/test/unit/test_validators.py, server/pulp/server/db/model/__init__.py
Adjust the regex to allow usernames to contain the at sign so that email
addresses can be valid usernames.
https://pulp.plan.io/issues/1728
=> Allow at sign in user ids

client_lib/pulp/client/commands/repo/sync_publish.py, client_lib/test/unit/client/commands/repo/test_sync_publish.py, docs/dev-guide/integration/rest-api/repo/cud.rst, docs/user-guide/release-notes/2.10.x.rst
closes #1982
https://pulp.plan.io/issues/1982
pulp.client.commands.repo.sync_publish.SyncPublishCommand
* Moved generate_override_config from RunPublishRepositoryCommand
* SyncPublishCommand now accepts override_config_options
* SyncPublishCommand now have new method generate_override_config
pulp.client.commands.repo.sync_publish.RunSyncRepositoryCommand
* Now accepts --force-full flag
=> 1982 - Added --force-full option to importer pulp-admin

docs/user-guide/installation/index.rst
This warning is no longer relevent with EL5 consumer support
being removed soon.
=> Removes python-qpid on EL5 docs warning

streamer/pulp/streamer/server.py
An importer has a configuration file in /etc/pulp/server/plugins.conf.d/
that can, among other things, configure the proxy used for the plugin.
Previously, the streamer was only using the importer configuration that
is present on the ``Importer`` module.
Although the most sensible thing to do is have the importer
configuration available on the Importer model object, this would require
a great deal of cleanup since importer/distributor models and
configuration are a mess of old and new, with the configuration spread
all over the place. This should be cleaned up as part plugin API work we
do for Pulp.
closes #2038
=> The pulp_streamer now uses the plugin-wide proxy config

docs/dev-guide/contributing/dev_setup.rst
All our development-related tools and scripts are moving to pulp/devel,
including things like our Vagrantfile. This updates the documentation to
reflect that.
It also removes the section on vagrant-cachier, which does not work
with dnf. Instead, it recommends the new method of caching packages.
=> Update the development guide to point users to pulp/devel

server/pulp/plugins/util/publish_step.py
This change is needed so that docker rsync distributor can use this method to create relative symlinks for tags.
=> Changes arguments for the make_link_unit 

server/pulp/server/managers/repo/unit_association_query.py, server/test/unit/server/managers/repo/test_unit_association_query.py
https://pulp.plan.io/issues/1894
The unit query needed to be the list of associated unit ids **AND** anything specified in the unit filter.
=> Fix unit query by criteria when unit filter contains ids.

server/pulp/plugins/rsync/publish.py, server/pulp/server/controllers/repository.py, server/pulp/server/db/model/repository.py, server/test/unit/server/controllers/test_repository.py
If a distributor has a predistributor_id configured, the publish is skipped when the
predistributor has not published since the last publish by the distributor. This includes
situations where the predistributor has not published at all.
re #1887
https://pulp.plan.io/issues/1887
=> Adds predistributor logic to the publish controller

server/pulp/plugins/rsync/publish.py, server/pulp/server/controllers/repository.py
Also removes extraneous code from rsync.
re #1887
https://pulp.plan.io/issues/1887
re #1963
https://pulp.plan.io/issues/1963
re #1759
https://pulp.plan.io/issues/1759
=> Fixes logic used to skip publishes based on predistributor.

pulp.spec
Adjusts the selinux_policyver macro in the pulp spec file
to not be an empty string. The new field value includes
both version and release of selinux-policy.
Also removes an unecessary if statement for F19 which is
not longer built.
https://pulp.plan.io/issues/2121
re #2121
=> Fixes selinux-policy spec file macro

docs/user-guide/release-notes/2.10.x.rst, server/pulp/plugins/migration/standard_storage_path.py, server/test/unit/plugins/migration/test_standard_storage_path.py
Removes the empty directory purge phase of the 2.8 migrations, which was taking
some users many hours when done over NFS.
Introduces multi-threaded concurrency for the bulk of the migration's work.
https://pulp.plan.io/issues/2118
fixes #2118
=> Speeds up the unit file path migrations

docs/dev-guide/contributing/dev_setup.rst, docs/user-guide/installation/f23-.rst, docs/user-guide/installation/f24+.rst
I sadly admit defeat. This removes references to COPR added in
yesterday's PR, but leaves in the changes that remove references
to using groupinstall.
this change partially reverts e00a852ef94f2d8d8737956ef130eb03b576091a
re #1993
https://pulp.plan.io/issues/1993
=> Remove references to copr

platform/pulp/platform/models/__init__.py, platform/pulp/platform/models/consumer.py, platform/pulp/platform/models/repository.py
https://pulp.plan.io/issues/2085
The following fields were not carried forward to 3.0.
Consumer:
- **capability**  *supported Agent but never used*
- **rsa_pub**  *supported Agent*
Binding:
- **binding_config**  *supported Nodes*
- **notify_agent**  *supported Agent*
- **consumer_actions** *supported Agent*
- **deleted** *supported Agent*
The applicability models are not included in anticipation that a strong relational model will support calculation on demand.  If this proves to be incorrect, we can add them later.
On consumer, I initially wrote `bind()` and `unbind()` convenience methods.  Then, after further consideration, I removed them because each of them contained a single line of code that the caller could also do.  Also, It seemed inappropriate for a model method to operation on …
=> Add consumer models.

server/pulp/server/webservices/compat_urls.py, server/pulp/server/webservices/settings.py, server/pulp/server/webservices/urls.py
Also adds a compat_urls.py file to support Django versions older than
1.6.
https://pulp.plan.io/issues/1766
reopened against 2.10-dev from: https://github.com/pulp/pulp/pull/2659
=> Update urls syntax for Django 1.10

server/pulp/server/webservices/middleware/exception.py
This header was removed in this commit:
8bf3c595f283d5072cfdce617c1e1623684132d8, but was acciddentally
reintroduced in this commit:
8ce699acdd65b4d2fd50c7a023bfa2a36b6387bc
The information is already present in the Content-Type headers, so the
offending line can simply be removed.
=> Remove invalid header from response

deps/external_deps.json, deps/python-kombu/2124.patch, deps/python-kombu/python-kombu.spec, rel-eng/packages/python-kombu
This fix is already in upstream Kombu so this ports
the important part of the fix to downstream
This commit bumps python-kombu to 3.0.33-6
https://pulp.plan.io/issues/2124
closes #2124
=> Fixes Qpid file descriptor leak

pulp.spec
This is the same fix as 8c152a68 except it correctly
escapes the %{version} and %{release} fields using
%%.
Now when you run:
`rpmspec -q pulp.spec --requires|grep selinux-policy` I get
the following output:
selinux-policy >= 3.13.1-158.21.fc23
https://pulp.plan.io/issues/2121
closes #2121
=> Fixes selinux-policy Requires statement

server/pulp/server/managers/status.py
Previously errors were caught and not logged. This makes
it very difficult to determine the root cause when an
error is experienced.
=> Adds logging for AMQP errors during /status/ API call

docs/dev-guide/integration/rest-api/repo/retrieval.rst, docs/user-guide/release-notes/2.11.x.rst, server/pulp/plugins/conduits/mixins.py, server/pulp/server/controllers/repository.py, server/pulp/server/db/migrations/0025_importer_schema_change.py, server/pulp/server/db/model/__init__.py, server/test/unit/plugins/conduits/test_mixins.py, server/test/unit/server/controllers/test_repository.py, server/test/unit/server/db/migrations/test_0025_importer_schema_change.py
Add full sync checks to the platform, where they can be used by all plugins.
closes #1983
https://pulp.plan.io/issues/1983
=> 1983 - Improve sync optimization to do a full sync after config file change or content removal

server/pulp/server/controllers/importer.py, server/pulp/server/controllers/repository.py, server/test/unit/server/controllers/test_importer.py
https://pulp.plan.io/issues/1977
Previous versions of Pulp allowed users to include their basic auth
information in the url. This is obviously less ideal than passing
this in the config, but in order to remain backwards compatibile, this
removes the auth info from the url and adds it to the importer config.
For importer configurations that were created before this change, we pass
the configuration through the same cleaner function as we do during
importer creation, so a temporary importer configuration includes the
basic auth information.
**Important note about testing:**
To test this, there are two things that need to be checked. First, a new importer feed should contain basic auth in the url. In this case, inspection of the importer config should show a feed without the basic auth, and …
=> Pull basic auth info out of feed url

docs/dev-guide/contributing/dev_setup.rst
SSHFS is an alternative to NFS when sharing directories between the host
and guest. This documents the approach in the "Advanced" section since
the package is not yet in Fedora and requires a COPR.
=> Add dev setup instructions for SSHFS

docs/user-guide/installation/f23-.rst, docs/user-guide/installation/index.rst, docs/user-guide/introduction.rst
I've placed this change in the introduction because I didn't see a better section and it seemed like a place most people would look, but I'm interested in other suggestions. 
I also considered adding something in there about the versions of Pulp itself we support (something like there's currently no LTS and the latest stable build is typically the only build to receive z streams). Does anyone have thoughts on that one way or the other?
=> Add a support policy section to the documentation

server/test/unit/plugins/migration/test_standard_storage_path.py
https://github.com/pulp/pulp/pull/2675 introduced several broken unit
tests by adding non-determinism to the call order.
=> Fix broken unit tests in storage path migration

server/pulp/server/controllers/distributor.py, server/test/unit/server/controllers/test_distributor.py
Fixed crash that arise when we try to remove an option from
distributor confing which was not before set. This ends up
in KeyError because this option was not in config dict.
This was fixed and also added TestCase for it.
Summary:
* Fixed pulp.server.controllers.distributor.update to ignore
missing options from distributor config
* Added TestCase for this behaviour
TestUpdate.test_remove_none_values_non_existing()
closes #2134
https://pulp.plan.io/issues/2134
Reopen of https://github.com/pulp/pulp/pull/2701
=> Fix crash from removing missing option from dist conf

docs/user-guide/deferred-download.rst
fixes #236
https://pulp.plan.io/issues/236
=> Adds docs for re-using files on disk when DB is lost

platform/pulp/platform/models/__init__.py, platform/pulp/platform/models/base.py, platform/pulp/platform/models/consumer.py, platform/pulp/platform/models/repository.py, platform/pulp/platform/tests/models/test_repository.py
https://pulp.plan.io/issues/2089
Not sold on `RepositoryContent.save()` and `RepositoryContent.delete()` managing the `last_content_added` and `last_content_removed`.  As a rule, we don't have one model update another.  *Maybe* it's okay in cases like this where the model is an *association* (join tables)?  Perhaps managing the `last_content_*` should be in the control layer?
Ignore the `Content` model (for now).
Anyone know if `RepositoryGroup.scratchpad` is need?  Used?
=> Add repository models.

server/selinux/server/pulp-celery.te
The rsync distributors needs to execute the rsync binary.
The call to rsync_exec allows the celery_t security context
to make that call.
https://pulp.plan.io/issues/2196
closes #2196
=> celery_t can now exec rsync_exec_t

platform/pulp/platform/models/README.md
Document pulp specific practices and procedures for pulp 3  modeling  intended to compliment the `db-translation-guide.md`.  Describes differences between pulp 2 and pulp 3 for each model (as needed).  This includes expected usage and extension by plugins.
=> Add models README.md

platform/pulp/platform/models/consumer.py, platform/pulp/platform/models/repository.py, platform/pulp/platform/tests/models/test_consumer.py, platform/pulp/platform/tests/models/test_repository.py
Add `natural_key()` to existing models.  Also, split repository tests and examples.
See: https://docs.djangoproject.com/en/1.8/topics/serialization/#serialization-of-natural-keys
=> add natural_key() to existing models.

platform/pulp/platform/models/__init__.py, platform/pulp/platform/models/content.py, platform/pulp/platform/models/repository.py, platform/pulp/platform/models/storage.py, platform/pulp/platform/settings.py, platform/pulp/platform/tests/models/test_content.py
https://pulp.plan.io/issues/2098
Okay folks, a few updated semantics to discuss.
The *Unit* part of `ContentUnit` although firmly entrenched in the pulp glossary, is a little awkward.  The term *unit* is synonymous with *item*, *thing*, *object* (and others) which makes it a bit redundant.  Consider it in another context - like a class named `RepositoryUnit` or `TaskObject`.  I believe that a class name of: `Content` and table name of `content` seems more appropriate. 
*"Repositories contain content."*
Another new concept is `Artifacts`.  *"Content has associated artifacts"*.  Each artifact represents a file.  I originally named this `ContentFile` but this quickly lead to odd semantics such as:
```
file = ContentFile(content=content)
file.content        # This is a reference to Content, …
```
=> add content models.

platform/etc/pulp/server.yaml, platform/pulp/platform/settings.py, platform/pulp/platform/tests/test_settings.py
In order to allow for easy configuration, this patch loads settings from
`/etc/pulp/server.yaml`, merges them with default settings for Pulp, and
then applies them to settings.py (which is in turn merged with the
global default settings).
fixes #2109
Reviewer note: Tests are incoming, but I wanted to see what people thought about a) switching to YAML and b) allowing users to set _any_ Django-supported setting
=> Add a new settings file for Django

platform/pulp/platform/fields.py, platform/pulp/platform/models/__init__.py, platform/pulp/platform/models/task.py
Add task models.
The tasking system is a pretty solid, well baked solution, so making too many changes at this time might not make sense.  I tried to make ones that made sense in relation to utilizing a relational database.
Utilized foreign keys where it appears to make sense, and converted some of the data types to utilize their natural data state in the database (mainly DateTimes)
There are four fields that will need more thought, but wanted to go ahead and put up the PR to start the conversation. These fields store complex data structures, that could potentially vary based on utilization.  
These are:
- Task.result
- Task.error
- ScheduledCalls.args
- ScheduledCalls.kwargs
My initial thought was to convert them into properties, so we can split up the internal representation (TextField) …
=> Add task models

platform/setup.py
Pulp's platform package depends on PyYAML, so it should declare it in
the setup.py.
fixes #2231
=> Add PyYAML to the dependency list for platform

platform/pulp/platform/models/base.py, platform/pulp/platform/models/generic.py
This was recently added, but I'm removing it per an IRC
convo. The thinking is that `__all__` supports an import
using * which should be avoided anyway per pep8 and pep20.
=> Removing __all__ usage from pulp.platform

platform/pulp/platform/models/content.py, platform/pulp/platform/models/storage.py, platform/pulp/platform/tests/models/test_content.py
This updates the Artifact model's `published_path` field to be
`relative_path` which I think is clearer. This also updates the
documenation for the field.
=> The Artifact `published_path` field is now `relative_path`

platform/pulp/platform/models/progress.py, platform/pulp/platform/tasks/task_system.py
This creates the pulp.platform.tasks.task_system package
and moves the get_current_task_id function into it.
=> Moves the get_current_task_id function

server/pulp/server/controllers/repository.py, server/pulp/server/managers/repo/unit_association.py, server/test/unit/server/managers/repo/test_unit_association.py
closes #2212
https://pulp.plan.io/issues/2212
=> Add units which did not pass signature filter to the task report.

docs/dev-guide/3.0-development/data-modeling.rst, platform/pulp/platform/models/__init__.py, platform/pulp/platform/models/consumer.py, platform/pulp/platform/models/repository.py, platform/pulp/platform/tests/models/test_consumer.py, platform/pulp/platform/tests/models/test_repository.py
Flattened importer and distributor models.
Renamed `Distributor` to `Publisher`.
Renamed `Plugin` to`ContentAdaptor`.  Never seemed quite right and took a stab at something better.
The natural key for an importer and publisher is `name` which requires it to be unique.  This puts *some* extra burden on the API user but I don't think it's unreasonable.
Updated the tests until we decide what direction we're going with on testing.
=> Consolidation of repository models.

app/pulp/app/models/__init__.py, app/pulp/app/models/catalog.py, app/pulp/app/models/content.py
Lazy sync has a LazyCatalogEntry collection Pulp 2. This covers the
LazyCatalogEntry functionality by relating a URL to an ``Artifacts``
and an ``Importer`` that contains the necessary download configuration
to access the URL (basic auth, client certificates, CA certificates,
etc).
closes #2088
=> Add a DownloadCatalog model to track Artifacts

docs/dev-guide/contributing/building.rst
This is based on an IRC discussion from earlier today, and captures the result of that discussion in the current pulp build instructions.
=> Update build docs to explicitly state when to update versions

app/pulp/app/models/repository.py
A trivial thing, but this espablishes better practice of explicitly
defining default related names for Models, alleviating issues related
to stemming and pluralization.
=> se default_related_nameinstead of relying on '%(class)ss'

server/pulp/plugins/conduits/repo_config.py, server/pulp/plugins/rsync/publish.py
The Q object used to find conflicts for relative url now restricts the search to distributor's of a
particular type. This is necesary to allow the same relative URLs for RPM and ISO content.
re: #2132
https://pulp.plan.io/issues/2132
=> Changes needed to support relative url for ISO repositories

app/pulp/app/settings.py
Use yaml.safe_load instead of yaml.load, as yaml.load is dangerous
Look at http://pyyaml.org/wiki/PyYAMLDocumentation#LoadingYAML for more
info
closes #[2290](https://pulp.plan.io/issues/2290)
=> Use yaml.safe_load instead of yaml.load

app/pulp/app/models/base.py, app/pulp/app/models/content.py, app/pulp/app/models/repository.py, app/pulp/app/tests/models/test_consumer.py, app/pulp/app/tests/models/test_content.py, app/pulp/app/tests/models/test_repository.py
The 'detail_model' field provided by MasterModel *is* the type field.
If we want to rename it from detail_model to 'type', I'm in favor of that.
=> Remove redundant 'type' fields.

pulp.spec, server/pulp/plugins/util/publish_step.py, server/selinux/server/pulp-celery.te, server/test/unit/plugins/util/test_publish_step.py
https://pulp.plan.io/issues/2277
Call `selinux.restorecon()` after moving published files.  The path passed to `restorecon()` cannot be unicode.
The `Requires: libselinux-python` needs to be added to the .spec file but I have no idea which one is actually being used.
=> Restore selinux context after published files are moved.

app/pulp/app/models/progress.py
The context manager now provides saving in all cases.
Also the docstrings have been updated to make this
behavior clear to the user.
Also the short form of `ProgressBar` was fixed
to create the 'pb' variable within the 'with'
section.
https://pulp.plan.io/issues/2092
re #2092
=> Updates saving behaviors of `ProgressReport`

docs/user-guide/release-notes/2.11.x.rst, server/pulp/server/async/scheduler.py, server/pulp/server/db/manage.py, server/test/unit/server/async/test_scheduler.py, server/test/unit/server/db/test_manage.py
Add close() method to celery scheduler for clean exit.
Catch ServerSelectionTimeoutError when mongo is down.
closes #2186
https://pulp.plan.io/issues/2186
=> Prompt user of running workers/tasks on migration

server/selinux/server/pulp-celery.te
https://pulp.plan.io/issues/2326
https://pulp.plan.io/issues/2277
While reproducing this issue, the relabeling during publishing was failing with permission denied.
Found this:
```
[jortel@f23s ~]$ sudo audit2allow -Ral
require {
type celery_t;
}
#============= celery_t ==============
selinux_set_enforce_mode(celery_t)
selinux_validate_context(celery_t)
```
After adding these 2 rules to the policy and installing, the publish succeeded and GET on files worked:
```
[jortel@f23s ~]$ sudo setenforce 1
[jortel@f23s ~]$ pulp-admin rpm repo sync run --repo-id=zoo 
+----------------------------------------------------------------------+
Synchronizing Repository [zoo]
+----------------------------------------------------------------------+
This command may be exited via ctrl+c without affecting …
```
=> Fix AVC denials while restoring SELinux context as part of publishing.

docs/user-guide/nodes.rst
The nodes install and quickstart was leaving out
an important step on the child node to configure
the server.conf on the child node.
https://pulp.plan.io/issues/1392
closes #1392
=> Updates the nodes install and quickstart

docs/dev-guide/contributing/building.rst
There are updates to the http://pulpproject.org/docs/
page that need to happen with different build types.
Those instructions are now added present.
=> Adds pulpproject.org updates as build steps

server/pulp/server/controllers/repository.py, server/test/unit/server/controllers/test_repository.py
closes #2328
https://pulp.plan.io/issues/2328
=> Repository syncs show all units updated even when there are no changes.

pulp.spec, server/test/unit/plugins/migration/test_standard_storage_path.py
Testing has been broken for a while on f24, and it's because of a difference between the f24 spec file in fedora downstream and our upstream spec. I'm still digging into what the "best" solution might be, but this gets tests running on f24 for 2.10 right now, by providing "python2-" prefixed versions of all the python-pulp-* packages in platform.
=> platform provides python2-pulp-* packages

app/pulp/app/serializers/fields.py, app/pulp/app/serializers/repository.py, app/pulp/app/viewsets/base.py
Without this, we had an inconsistency where a ViewSet, e.g. "TasksViewSet"
with endpoint_name "tasks" would still be registered with a base_name of
"task", so the section of the docs that say to use endpoint_name when
generating view_name arguments to serializer reference fields is a liar
without this change.
=> Explicitly set view_name when registering NamedModelViewSets

server/selinux/server/pulp-celery.te
re: #2277
https://pulp.plan.io/issues/2277
=> Removes extraneous permission from pulp-celery SELinux policy

app/pulp/app/serializers/__init__.py, app/pulp/app/serializers/base.py, app/pulp/app/serializers/fields.py, app/pulp/app/serializers/repository.py, app/pulp/app/viewsets/__init__.py, app/pulp/app/viewsets/base.py, app/pulp/app/viewsets/repository.py
This work allows objects that are related to repositories to have urls
that are nested within their related repository. For example, an
`rpm` importer named `zoo-importer` related to the `zoo` repository
will live in `repositories/zoo/importers/rpm/zoo-importer/`
=> Allow nested routing for objects related to repos

app/pulp/app/settings.py
We can revisit this if we want, but for the moment having this set
to `get_fqdn` breaks testing. In particular, it's impossible to use
RequestFactory to generate requests that can be used to test API
Serializers.
=> Set ALLOWED_HOSTS to allow all hosts by default

server/selinux/server/pulp-celery.te
On EL6, calling selinux.restorecon() requires changing the domain object id for the file
whose security context is being restored. This patch provides that permission for celery
on EL6.
closes #2387
https://pulp.plan.io/issues/2387
=>  SELinux permission for celery to change domain object id of files 

server/selinux/server/pulp-celery.te
EL6 requires very granular permissions for running restorecon. This patch grants celery_t those
permissions.
=> Adds more SELinux for EL6

pulp.spec, server/selinux/server/relabel.sh
RHEL 7.3 was experiencing an bug that was preventing the pulp-selinux RPM from using semodule -l to
figure out the installed version of pulp-selinux policies during upgrades.
The other change is in relabel.sh. This change fixed version comparison to account for the fact that
2.10.0 is greater than 2.2.0.
closes #2434
https://pulp.plan.io/issues/2424
=> Changes how pulp-selinux RPM decides when to run restorecon statements

docs/user-guide/troubleshooting.rst
Inform the reader that the log level will be adjusted only when Pulp processes
are restarted.
=> Update troubleshooting guide [2.10-dev]

docs/dev-guide/contributing/branching.rst, docs/dev-guide/contributing/merging.rst
Update the git commit message section in the docs to include a note about the keywords for referencing a Redmine issue and add some info about what constitutes a good commit message.
closes #103, #1321
https://pulp.plan.io/issues/103
https://pulp.plan.io/issues/1321
=> Update the git commit message section

app/pulp/app/models/task.py, plugin/pulp/plugin/__init__.py, plugin/pulp/plugin/tasking.py
The `TaskController` is basically a *procedural* approach and proposing an *object-oriented* alternative.  Appending non-fatal errors is a natural operation on the currently running task.  Proposing a *facade* object that represents the currently running task that supports these operations.
I also noticed the models.Task.non_fatal_errors is expected to be a json document with its root being a list.  But, the field did not have a default=[].  So I added it.  I think this makes sense?
I feel like the docstring could use a little more but not really sure what that needs to be yet.  After the entire plugin API is complete, we should make another pass over them to ensure it's crystal clear to the plugin writer how the API is to be used.
=> Replace task controller with facade object that represents the current running task.

app/pulp/app/models/content.py
Generator expression syntax looks a lot like tuple syntax, but the results are obviously quite different.
I threw in a typo fix as a bonus.
=> returning tuple as doc'd instead of a generator

app/pulp/app/serializers/base.py
PKOnlyOptimization prevents DetailRelatedFields from being able to know
their view_name because a PKOnlyObject does not have access to the full
object's Meta class.
=> Disable drf PKOnlyObject optimization for RetailRelatedFields

docs/dev-guide/contributing/features.rst
In addition to calling out the new etherpad, I tried to clarify the
sprint lifecycle, so as you follow the doc from top to bottom you
hopefully end up with a groomed sprint candidate for the next sprint
planning by the end of it.
fixes #2420
https://pulp.plan.io/issues/2420
=> Document story grooming process and related etherpad

tasking/pulp/tasking/base.py
The method previously being called does not exist.
=> calling the correct method name on task completion

app/pulp/app/db-reset.sh, app/pulp/app/management/commands/reset-admin-password.py, app/pulp/app/settings.py, docs/integration_guide/rest_api/index.rst
All API views now require authentication. The password for the 'admin' user can now be
set using the 'reset-admin-password'  django management command. The new command takes
an optional '--random' argument.
closes #2358
https://pulp.plan.io/issues/2358
=> Adds authentication to the REST API

app/pulp/app/models/task.py
It was given a default value recently, but that turned out to not be the best
option. There is no value in forcing this to be a list. Some tasks will return
other types, and some will only return None.
=> Task.result is allowed to be null

app/pulp/app/settings.py, tasking/pulp/__init__.py
- adds a missing __init__.py
- switches default to RabbitMQ temporarily until the
Qpid transport is Python 3.4 compatible
=> Small fixes for tasking

app/pulp/app/serializers/__init__.py, app/pulp/app/serializers/fields.py, app/pulp/app/serializers/repository.py, app/pulp/app/viewsets/base.py, app/pulp/app/viewsets/repository.py
This commit undoes some of the changes in
ff3a0a6404ed17620a0cd63be50c01e62a39b6a0. It removes the nested
routing, but keeps the `ImporerViewSet` and the `importers/` endpoint
in the RepositoryViewSet.
=> Remove URL nesting from ViewSet registration

server/pulp/plugins/util/publish_step.py
On EL7, restorecon calls out to lgetfilecon which raises an exception when
SELinux security context labels are not available.
https://www.gnu.org/software/gnulib/manual/html_node/lgetfilecon.html
=> Adds exception handling for when SELinux is disabled on EL7

server/selinux/server/relabel.sh
The new version comparison mechanism no longer handled an empty string being passed in.
As a result none of the restorecon statements were getting run at the end of pulp-selinux
installation.
closes #2436
https://pulp.plan.io/issues/2436
=> Fixes relabel.sh to handle empty string being passed in.

app/pulp/app/models/task.py, tasking/pulp/tasking/celery_instance.py, tasking/pulp/tasking/tasks.py
This PR introduces three fixes:
- Updates the Celery dedicated queue name to be 'C.dq2'.
This is a Celery backwards incompatible change so
Pulp3 is only compatible with Celery 4.0.
- Fixes a bug in the worker selection which was dispatching
work to non-dedicated workers.
- Resolves a traceback where a TaskStatus was being created
twice during normal reserved task execution.
https://pulp.plan.io/issues/2440
re #2440
=> Fixes the Pulp tasking system

docs/user-guide/authentication.rst, docs/user-guide/installation/index.rst, docs/user-guide/release-notes/2.11.x.rst
2.11 is the last release supporting EL6. This commit adds
a release note for that.
=> Adds release note about EL6 for 2.11

docs/user-guide/release-notes/2.11.x.rst, docs/user-guide/troubleshooting.rst
closes #2468
https://pulp.plan.io/issues/2468
=> Update release notes about migration caveat

docs/dev-guide/debugging.rst, docs/user-guide/release-notes/2.12.x.rst, docs/user-guide/release-notes/index.rst, server/etc/pulp/server.conf, server/pulp/server/async/tasks.py, server/pulp/server/config.py
Adds the ability to turn on cProfiles of individual Pulp tasks
and dumping of the tasks into a directory. This can have an impact
on performance. The trade off is that users could investigate
individual tasks or provide these cProfiles to developers to help
detect anomalies or systematic issues.
=> Fixes #1939: Enable cProfile of tasks

docs/user-guide/nodes.rst, docs/user-guide/release-notes/2.12.x.rst, nodes/child/pulp_node/handlers/handler.py, nodes/child/pulp_node/handlers/model.py, nodes/child/pulp_node/importers/http/importer.py, nodes/common/pulp_node/error.py, nodes/extensions/admin/pulp_node/extensions/admin/commands.py, nodes/extensions/admin/pulp_node/extensions/admin/sync_schedules.py, nodes/extensions/consumer/pulp_node/extensions/consumer/commands.py, nodes/parent/pulp_node/distributors/http/distributor.py, nodes/test/nodes_tests/test_admin_extensions.py
Update the documentation and release notes to indicate that nodes are
deprecated. Also, add warnings in the parent/child tasks and CLI commands.
fixes #1488
https://pulp.plan.io/issues/1488
=> Deprecate Pulp nodes

client_lib/setup.py, pulp.spec
The okaara 1.0.36 release is incompatible with Python
2.7. This Pins the versions to 1.0.32 <= okaara <=
1.0.35 which are compatible with Pulp. This range limit
is made in the spec file and the setup.py requirements.
https://pulp.plan.io/issues/2464
closes #2464
=> Pins okaara dependency versions

app/pulp/app/models/progress.py
The external link was not formatted correctly.
https://pulp.plan.io/issues/2319
=> re #2319: Fixes 3.0-dev docs error

docs/user-guide/release-notes/2.11.x.rst
The upgrade notes added also include stopping and
starting pulp_streamer.
This commit is based off of the 'pulp-2.11.0-0.5.rc'.
This allows us to merge it into the 2.11 GA release
at build time, and also merge it into 2.11-dev
and forward using our normal PR process.
https://pulp.plan.io/issues/2485
closes #2485
=> Adds upgrade notes to 2.11

client_lib/pulp/client/commands/unit.py, docs/dev-guide/integration/rest-api/content/orphan.rst, docs/user-guide/admin-client/orphan.rst, server/pulp/server/managers/content/orphan.py, server/test/unit/server/managers/content/test_orphan.py
Track the counts of units being deleted when orphan remove all is executed and
store the result indexed by content type id on the task.
fixes #1268
https://pulp.plan.io/issues/1268
=> As a user, orphan content delete reports how many units were deleted

server/pulp/plugins/util/publish_step.py, server/test/unit/plugins/util/test_publish_step.py
https://pulp.plan.io/issues/2136
The issue proposes to catch and log the exception raised in the `try:` but this exception is most likely the root cause.  The code in `finally:` *should* just clean up resources.  Allowing an exception out of the `finally:` results in exceptions raised in the `try:` to be *swallowed*.
This seemed like a more appropriate solution and results in the root cause being reported as desired by the reporter.
=> Prevent exceptions raised in finally:

docs/dev-guide/contributing/building.rst
The build docs were missing the setting of the
LATEST variable which caused new GA releases to
not be published at the root of docs.pulpproject.org
While in there, I tried to improve the clarity and ensure
each line is not over 100 characters.
I built the docs locally and proofed them also.
=> Updates build steps related to docs

server/pulp/server/async/app.py, server/pulp/server/async/scheduler.py, server/pulp/server/async/tasks.py, server/test/unit/server/async/test_app.py, server/test/unit/server/async/test_scheduler.py, server/test/unit/server/async/test_tasks.py
This fix ensures that workers (including resource_manager) and the
scheduler properly clean up their database records when gracefully
shutdown.
fixes #2491
https://pulp.plan.io/issues/2491
Note: This diff is a bit easier to view if you turn off white space checking:
https://github.com/pulp/pulp/pull/2901/files?w=0
=> Fix status API to not show stopped workers and scheduler

server/pulp/server/content/web/settings.py
django's normal behavior is to log at WARNING when it issues a 404 response to
a client. That is not the behavior Pulp wants, because it does not indicate a
failure in Pulp.
https://pulp.plan.io/issues/2510
fixes #2510
=> django.request log level changed to ERROR

common/pulp/common/constants.py, docs/user-guide/release-notes/2.12.x.rst, docs/user-guide/server.rst, server/etc/default/upstart_pulp_resource_manager, server/etc/default/upstart_pulp_workers, server/pulp/server/async/app.py, server/pulp/server/async/manage_workers.py, server/pulp/server/async/scheduler.py, server/pulp/server/async/tasks.py, server/pulp/server/async/worker_watcher.py, server/pulp/server/db/model/__init__.py, server/test/unit/server/async/test_app.py, server/test/unit/server/async/test_scheduler.py, server/test/unit/server/db/test_model.py, server/usr/lib/systemd/system/pulp_resource_manager.service
Similified and reduced the timings so that all failure detection occurs within 30 seconds. Changed resource_manager to use a timestamp-based locking mechanism.
closes #2509
https://pulp.plan.io/issues/2509
=> Reduce and simplify timings so that failover occurs within 30 seconds

docs/user-guide/release-notes/2.12.x.rst
Forgot to update the 2.12 release notes with new docker tag feature.
=> Added release note for docker tag command

docs/dev-guide/debugging.rst, server/etc/pulp/server.conf, server/pulp/server/async/tasks.py
This feature was introduced in 2.12, and is being fixed prior to the
release of 2.12.0. This fix includes:
* Updates the server.conf which used `enable` instead of `enabled`
* Updates the config file checking which treated received a str when it
expected a boolean.
* Provides automatic directory creation.
* Documentation updates and fix for blockquote sections which did not
render correctly.
https://pulp.plan.io/issues/1939
closes #1939
=> Fixes the cProfile Feature

docs/user-guide/release-notes/2.13.x.rst, docs/user-guide/troubleshooting.rst, server/pulp/server/logs.py, server/test/unit/server/test_logs.py
Appending a 8 character task id to log output if there is a relevant
task id.
fixes #2324
https://pulp.plan.io/issues/2324
TODO
=> Appending 8 character task id to log output

server/pulp/server/async/tasks.py, server/pulp/server/db/model/__init__.py, server/pulp/server/db/querysets.py, server/pulp/server/managers/status.py, server/test/unit/server/async/test_tasks.py, server/test/unit/server/db/test_model.py, server/test/unit/server/managers/test_status.py
Solution: A custom queryset for the Worker model allows filtering out
worker records which have not been updated in more than 25 seconds.
This queryset is used in two places:
- Status API
- Resource manager code that looks for available workers
closes #2496
https://pulp.plan.io/issues/2496
=> Problem: Stale worker documents present in the db

server/pulp/server/content/web/views.py, server/test/unit/server/content/web/test_views.py
mod_xsendfile intentionally drops the Content-Encoding header[0] when
responding to a request, but `mimetypes.guess_type` returns a tuple of
`('Content-Type', 'Content-Encoding')`. We were already ignoring the
encoding component of this tuple, so if `mimetypes.guess_type` *does* guess
that a non-`None` encoding value should be returned, all `x_send` would use
was the type component, resulting in the incorrect type being used in
the response.
For example: By default, `mimetypes.guess_type` returns `('text/xml',
'gzip')` for a file name like 'metadata.xml.gz', so xsendfile's response
incorrectly responds with the 'text/xml' Content-Type header. This
change makes mimetypes return `('application/gzip', None)` instead,
hopefully resulting in a happy client.
[0]: https://tn123.org/mod_xsendfile …
=> Don't guess encoding for xsendfile, only content type

server/pulp/server/db/manage.py
Call `datetime.utcnow()` to get the current time because the
`last_heartbeat` is stored on database on UTC timezone.
Fix #2545
=> Fix time_from_last_worker calculation

docs/user-guide/release-notes/2.13.x.rst, docs/user-guide/release-notes/index.rst, docs/user-guide/troubleshooting.rst, server/etc/default/upstart_pulp_resource_manager, server/etc/default/upstart_pulp_workers, server/pulp/server/async/app.py, server/pulp/server/async/manage_workers.py, server/pulp/server/async/scheduler.py, server/pulp/server/async/worker_watcher.py, server/test/unit/server/async/test_app.py, server/test/unit/server/async/test_scheduler.py, server/test/unit/server/async/test_worker_watcher.py, server/usr/lib/systemd/system/pulp_resource_manager.service
All workers will write their own records to the database
instead of relying on pulp_celerybeat to do so for them
using celery heartbeats.
This patch makes use of the Consumer blueprint that celery
runs at the start time of a worker. An extra boot step has
been added which sets a timer to periodically update the
worker record in the database.
http://docs.celeryproject.org/en/master/userguide/extending.html
https://groups.google.com/d/msg/celery-users/3fs0ocREYqw/C7U1lCAp56sJ
closes #2519
https://pulp.plan.io/issues/2519
closes #2516
https://pulp.plan.io/issues/2516
=> Workers write their own hearbeat records to database.

server/pulp/server/controllers/repository.py
Only update the last_publish field is the publish was a success and not
canceled.
fixes #2263
https://pulp.plan.io/issues/2263
=> Only update last_publish if success and not canceled

docs/user-guide/release-notes/2.12.x.rst
Solution: Add a note about Python wheel support to the release notes
re #2537
https://pulp.plan.io/issues/2537
=> Problem: Python wheel support omitted from the release notes

server/pulp/plugins/rsync/publish.py
Fixing a bug where we were filtering predistributor publish results by predistributor id instead of distributor_id.
fixes #2550
https://pulp.plan.io/issues/2550
=> Filtering predistributor results by distributor_id

pulp-dev.py
Create symbolic links so that the dev environment
upstart and systemd unit files both point to the 
development ones.
closes #2524
https://pulp.plan.io/issues/2524
=> Symlink systemd unit files to the source

pulp.spec
This requires a corresponding change to our build system to allow us to
continue building and testing el6 packages nightly, but it seems best
to have the committed spec file reflect the current support policy.
I wasn't actually sure that the change would be this simple, so I did
a test build with the change in place, here's what got built for el6:
- pulp-agent
- pulp-consumer-client
- python-pulp-agent-lib
- python-pulp-bindings
- python-pulp-client
- python-pulp-common
- python-pulp-devel
re #2576
https://pulp.plan.io/issues/2576
=> Stop building unsupported packages for el6

streamer/pulp/streamer/__init__.py, streamer/pulp/streamer/server.py, streamer/test/unit/streamer/test_server.py
https://pulp.plan.io/issues/2542
The streamer needed to try all available catalog entries.  This ensures that invalid entries don't prevent successful downloading when valid entries exist.  And, more robust in cases where there are multiple importers that can download a content unit and one (or more of them) pull from a remote repository that is temporarily unavailable.
I really tried not to rewrite the streamer but the flow needs to be very different.  Also, a few of the methods were doing too much and needed to be refactored.
=> Streamer tries all catalog entries.

pulp.spec
This prevents the pulp_streamer.service from being inappropriately
included in the pulp-server package.
closes #2518
https://pulp.plan.io/issues/2518
=> Explicitly install pulp-server service files

AUTHORS, docs/dev-guide/contributing/dev_setup.rst
This should bring the developer vagrant docs up
to date and provide some more useful insight.
I tested this on Fedora 24 and was able to get
running.
=> Update developer docs

streamer/pulp/streamer/server.py
Fix:
```
16:15:47 ./streamer/pulp/streamer/server.py:240:39: W291 trailing whitespace
```
causing jenkins to fail.
=> Fix flake8 warning.

server/pulp/server/managers/content/orphan.py
On a busy system a cursor for iterating over all units
in a collection could be timed out during orphan removal.
The batch size is set to 100 to make sure cursor is active,
it also should not introduce any noticable performance impact.
closes #2584
https://pulp.plan.io/issues/2584
=> Set batch_size for the cursor in orphan removal tasks

.mention-bot
This will allow mentionbot to include *active* developers instead.
=> mentionbot: stop recommending jcline.

pulp.spec
When https://github.com/pulp/devel/blob/master/ansible/library/pulp_facts.py is ran
in vagrant, it  to failes to gather the dependencies for pulp with the error:
"can't parse, unknown tag" for %{selinux_policyver}.
Updating the selinux_policyver tag to global resolves this issue.
Fedora packaging guidelines also state a preference for %global over %define
https://fedoraproject.org/wiki/PackagingDrafts/global_preferred_over_define
re #2497
https://pulp.plan.io/issues/2497
=> Update spec file

server/pulp/server/controllers/repository.py, server/test/unit/server/controllers/test_repository.py
It will force subsequent publish to be from scratch.
Before that publish could be incremental and in some cases, like
upload of the RPM with same NEVRA, resulted in duplicated
or outdated metadata in the published repository.
closes #1389
https://pulp.plan.io/issues/1389
=> Update last_unit_removed when unit is disassociated

server/pulp/server/webservices/views/repositories.py, server/pulp/server/webservices/views/serializers/__init__.py, server/pulp/server/webservices/views/serializers/content.py, server/test/unit/server/webservices/views/serializers/test_content.py
In order to fix an RPM bug, an opportunity presented itself to slightly
improve this interface, effectively renaming
`remap_fields_with_serializer` to `serialize_unit_with_serializer`, and 
exposing a new "serialize" method on `ModelSerializer` that can be
overridden in subclasses as desired to help with serializing "exotic"
field types, such as BLObs and other things not easily handled with our 
custom JSON encoder.
closes #2620
https://pulp.plan.io/issues/2620
=> Replace remap_fields with serialize_unit

docs/user-guide/installation/f23-.rst
Since the current pulp stable repo does not support rhel6.
=> Updated the repo for pulp rhel6 installs

docs/user-guide/installation/extra_configuration.rst, docs/user-guide/troubleshooting.rst, server/etc/pulp/server.conf, server/pulp/server/config.py, server/pulp/server/logs.py, server/test/unit/server/test_logs.py
This is related to https://pulp.plan.io/issues/2548
This will allow for more logging options for pulp
especially when /dev/log isn't available as is the
case in most containers.
=> Add console logger option for pulp.server.

tasking/pulp/tasking/tasks.py
Celery's Task.apply_async is expecting args and kwargs as keyword arguments.
If we want to pass any kwargs to the task, it has to be in the kwarg kwarg:
`apply_async(args, kwargs=mykwargs)`
With this PR we also assume that any args being passed in to apply_async will be passed directly to the task. Alternatively we could make this explicit and require any task args to be passed with the  `args` keyword. I am not sure which approach is more correct so any feedback is welcome.
=> Fix the arguments being passed to celery.apply_async

server/pulp/server/async/scheduler.py
Celery 4.x changes a number of implentation details which
breaks our assumptions about how the scheduling system
works. Therefore, we want to check for the celery version
and take actions to trigger the desired behavior depending
on that celery version.
closes #2615
https://pulp.plan.io/issues/2615
=> Fixes scheduled calls with Celery 4.x.

docs/user-guide/release-notes/2.13.x.rst, server/pulp/server/logs.py, server/test/unit/server/test_logs.py
* A release note for the console feature was added.
* Removal of some code handling a case that will never occur.
* Test fix because of ^
* Small flake8 fixes I saw when running tests locally
closes #2548
https://pulp.plan.io/issues/2548
=> Adds release note for console feature + misc fixes

docs/user-guide/installation/f23-.rst, docs/user-guide/installation/f24+.rst, docs/user-guide/nodes.rst, pulp-dev.py, pulp.spec, server/bin/pulp-gen-ca-certificate, server/bin/pulp-gen-key-pair, server/bin/pulp-setup
https://pulp.plan.io/issues/2013
**Server:**
Moved the RSA key pair generation out of the _%post_ of the pulp.spec into a new script named: `pulp-gen-key-par` and removed call to `pulp-gen-ca-certificate`.  Updated the *installation* documentation and added steps to run these (2) scripts.  
I added another script named: `pulp-setup` that is intended to consolidate things.  I'm on the fence about this.  On on hand, it seems valuable to automate and encapsulate the post-install steps into a single script.  This makes it easier for users (run one thing) and hopefully supports future refactoring and/or additions without impacting the user (and documentation).  If we like this, we'll need to change the documentation to instruct the user to run `pulp-setup` instead.  On the other hand, the …
=> RSA key pair and SSL CA certificate generation removed from pulp.spec.

.travis.yml, app/pulp/app/db-reset.sh, app/pulp/app/models/base.py, app/pulp/app/models/content.py, app/pulp/app/models/repository.py, app/pulp/app/serializers/__init__.py, app/pulp/app/serializers/base.py, app/pulp/app/serializers/fields.py, app/pulp/app/serializers/repository.py, app/pulp/app/settings.py, app/pulp/app/viewsets/repository.py, plugin/pulp/plugin/__init__.py, plugin/pulp/plugin/models/__init__.py, plugin/pulp/plugin/models/importer.py, plugin/pulp/plugin/models/publisher.py
This reorganizes the plugin API a little bit, and exposes all the pieces needed to create a basic pulp plugin. I also added some "quality of life" stuff I ran into while working on this, including:
- friendlier implementation of `__str__` in model base classes so running str/repr on a pulp model should give you sane behavior by default (it was't)
- the "one importer per-repo" constraint is now enforced in the data model
I also implemented a 'pulp.plugin' entrypoint in its own commit. If desired, I can split that off into a later PR and work it in another issue, or we can leave what's here in and improve it later if needed.
re #2454
https://pulp.plan.io/issues/2454
=>  Update plugin API and base classes for plugins

pulp.spec
python-okaara recently upgraded their fedora rawhide package to 1.0.37[0]. Pulp on F27 currently has broken dependencies since we're specifying `python-okaara >= 1.0.32,python-okaara < 1.0.36` in our spec file.
Previously we had an issue with python-okaara 1.0.36 because it was incompatible with python runtime 2.7 [1]. This has been fixed for 1.0.37. okaara 1.0.36 is not present in EPEL[0] and PyPI[2], so this spec file version change would not break any of our releases.
[0] https://apps.fedoraproject.org/packages/python-okaara
[1] https://github.com/jdob/okaara/issues/16
[2] https://pypi.python.org/pypi/okaara
=> Removed python-okaara<1.0.36 version restriction

server/pulp/server/managers/repo/unit_association.py, server/test/unit/server/managers/repo/test_unit_association.py
re #2577
https://pulp.plan.io/issues/2577
(cherry picked from commit 0005b1375f02d9cbe29bf23b892fa5ec7af343b8)
The cherry-picked commit was accidentally reverted on 2.12-dev in
commit c0ea5ee4bf8898d80d72c481fbc116fc548b8eeb. The original PR
containing this change was https://github.com/pulp/pulp/pull/2949
closes #2688
https://pulp.plan.io/issues/2688
=> update last_unit_added when units are copied

server/pulp/server/async/app.py
Starts Pulp worker heartbeat reporting when the Celery
consumer starts rather than when the Celery worker starts,
so that worker heartbeat reporting is resumed after a
disconnection and subsequent reconnection from the broker.
closes #2613
https://pulp.plan.io/issues/2613
=> Fixes issue w/ worker heartbeats on broker failure

app/pulp/app/models/repository.py, app/pulp/app/serializers/repository.py
The max_download_bandwidth and max_concurrent_downloads fields were not
expected to be on the model. These features are not included in the
MVP. This PR removes those fields from the model along with their
serializers.
There isn't an issue tracking this change. It is too small.
=> Removes two unexpected Importer fields

server/pulp/plugins/rsync/publish.py
closes #2687
https://pulp.plan.io/issues/2687
I tried to make the title to fit the 80 characters, but not sure if it still makes sense.
=> Use rsync's -K to preserve symlinks on publish with rsync distributor

server/pulp/plugins/rsync/publish.py
closes #2689
https://pulp.plan.io/issues/2689
I removed -S as well since it is the location of a control socket for connection sharing( which we are removing in this PR)
=> Don't use ssh connection sharing in rsync distributor.

platform/pulp/app/serializers/repository.py
It was previously a MultipleChoiceField, which caused problems. It should only
ever have one value.
=> The importer serializer's download_policy field should be a ChoiceField.

platform/pulp/app/db-reset.sh
This change needs to be merged before https://github.com/pulp/devel/pull/53
The new path is only used if an extra arg is passed, so this will not have an effect until that PR is merged.
=> Option to migrate from a virtual environment

docs/requirements.txt
This is a temporary solution until the following issue is fixed:
https://github.com/sphinx-doc/sphinx/issues/3779
=> Use sphinx<1.6.1 until ImportError in sphinx is fixed

docs/requirements.txt
The issue which did not allow us to use the latest sphinx is fixed in 1.6.2
sphinx-doc/sphinx#3779
=> Use the latest Sphinx version

platform/pulp/app/serializers/task.py
Solution: update the serializer for Task model by renaming 'result' field to 'error'
closes #2787
=> Problem: tasks API ommits error field in response

platform/pulp/tasking/tasks.py
Now one should be able to tell what is passing to where.
closes #2658
https://pulp.plan.io/issues/2658
=> Update apply_async and apply_async_with_reservations signatures

pulp.spec
The Source0 currently does not lead to the correct source file.
This updates the spec file and renames the source to what would be
the expected source name.
ref #2784
https://pulp.plan.io/issues/2784
=> Update spec files Source0

platform/pulpcore/app/settings.py
pulp-manager command needs full path to wsgi
in order to run from anywhere
closes #2707
https://pulp.plan.io/issues/2707
=> Update path to wsgi for pulp-manager command

common/pulp/common/error_codes.py, server/pulp/plugins/conduits/profiler.py, server/pulp/plugins/loader/manager.py, server/pulp/server/db/manage.py, server/pulp/server/db/migrations/lib/utils.py, server/pulp/server/managers/content/orphan.py
The following was added:
- load of auxiliary models
- post-delete method during orphan removal
- serialization in profiler to have all the data
in a proper shape for applicability calculation
re #2681
https://pulp.plan.io/issues/2681
=> Support for storing units in multiple collections

docs/contributing/3.0-development/index.rst, docs/contributing/style_guide.rst
https://pulp.plan.io/issues/2347
=> Add note to convert ported docstrings

platform/pulpcore/app/models/__init__.py, platform/pulpcore/app/models/content.py, platform/pulpcore/app/models/repository.py, platform/pulpcore/app/models/storage.py, platform/pulpcore/app/serializers/__init__.py, platform/pulpcore/app/serializers/fields.py, platform/pulpcore/app/serializers/repository.py, platform/pulpcore/app/settings.py, platform/pulpcore/app/tests/models/test_repository.py
https://pulp.plan.io/issues/2455
Files stored in: `/var/lib/pulp/tls/`
The `StoragePath` needed to be more specific so renamed using `location` semantics as `ArtifactLocation` and `TLSLocation`.  Still need to update the serializer.
The `FileSystem._save()` *storage* also needed to change to use the django `File` appropriately as a stream.  This meant it could not use shutil.copy() (which was not providing much anyway).
Took a stab at serializer changes.  Since certificates are passed by-value we need a way to set the value of `FileField` with content instead of a *file-like* object opened to an actual file.
=> Store importer TLS keys and certificates on the filesystem.

server/pulp/plugins/rsync/publish.py
Corrects the rsync distributor fast-forward logic so that it
uses the proper date range to determine which units to include.
This fixes an issue where units were not being published if the
association, predistributor publish and rsync publish occurred
in a certain order.
closes #2532
https://pulp.plan.io/issues/2532
=> Fix rsync distributor skipping units

docs/contributing/plugin_api/changeset.rst, docs/contributing/plugin_api/download.rst, docs/contributing/plugin_api/index.rst, platform/pulpcore/app/models/catalog.py, platform/pulpcore/download/__init__.py, platform/pulpcore/download/batch.py, platform/pulpcore/download/delegation.py, platform/pulpcore/download/error.py, platform/pulpcore/download/file.py, platform/pulpcore/download/ftp.py, platform/pulpcore/download/http.py, platform/pulpcore/download/settings.py, platform/pulpcore/download/single.py, platform/pulpcore/download/validation.py, platform/pulpcore/download/writer.py, plugin/pulpcore/plugin/changeset/__init__.py, plugin/pulpcore/plugin/changeset/iterator.py, plugin/pulpcore/plugin/changeset/main.py, plugin/pulpcore/plugin/changeset/model.py, plugin/pulpcore/plugin/changeset/report.py, plugin/pulpcore/plugin/download/__init__.py, plugin/pulpcore/plugin/download/factory.py, plugin/pulpcore/plugin/models/__init__.py, plugin/pulpcore/plugin/models/importer.py
Introduction
============
This proposal attempts to provide tooling intended to reduce the effort required for plugin writers to contribute a plugin.  
It focus narrowly on:
* File downloading.
* Creating content and artifacts.
* Content association with a repository.
* Deferred (Lazy) downloading *for-free* on minimal burden to plugin writer.
* Support the streamer.
* Twisted integration.
* Support validation when streaming the bits.
* Each download is autonomous and provides protocol independent interface.
* Keeping the plugin API lean-and-mean.
The proposed solution is layered.
Layer 1
-------
**Concurrent Downloading.**
Plugin writers are free to use any lib they want to download files.  However, I don't know of any that support concurrency and validation. The proposed solution is an …
=> Download package and plugin API - ChangeSet 

server/pulp/plugins/rsync/publish.py
Fixes an issue with rsync logic where some units which have 
not yet been published by the predistributor are included
with rsync publishes.
closes #2791
https://pulp.plan.io/issues/2791
=> Fix rsync distributor publishing units not published by predistributor

docs/conf.py, docs/requirements.txt
Building the docs should not require pulp python package to be installed.
=> Add Pulp package path to sphinx build config

platform/setup.py
1.11 was tested and it is the latest one at the moment.
=> Allow any Django >=1.8,<2

server/pulp/server/event/http.py, server/test/unit/server/event/test_http.py
Stop creating a thread for http notifier
closes #[2903](https://pulp.plan.io/issues/2903)
=> Stop creating a thread for http notifier

bindings/pulp/bindings/server.py
Fixes https://pulp.plan.io/issues/2825
* Use `base64.b64encode()` instead of `base64.encodestring()` for
encoding Basic Auth informations
=> Fixes pulp-admin improper base64 encoding for (very long) user basic auth credentials

platform/pulpcore/app/views/status.py
pep8speaks throws E722 for bare exceptions. From [the Python docs](https://docs.python.org/2/howto/doanddont.html):
> Because `except:` catches all exceptions, including SystemExit, KeyboardInterrupt, and GeneratorExit (which is not an error and should not normally be caught by user code), using a bare `except:` is almost never a good idea. In situations where you need to catch all “normal” errors, such as in a framework that runs callbacks, you can catch the base class for all normal exceptions, Exception.
=> Fixing bare exceptions in Status view

nodes/common/bin/pulp-gen-nodes-certificate, server/bin/pulp-gen-ca-certificate, server/pulp/server/managers/auth/cert/cert_generator.py
SHA1 certificates are deprecated and should be phased out. While most serious deployments will use their own certificates, the default install should at least be sane.
=> Sign certificates with sha256

.travis.yml, bindings/test/unit/test_tasks.py, client_lib/pulp/client/commands/consumer/query.py, common/pulp/common/config.py, devel/pulp/devel/dummy_plugins.py, server/pulp/plugins/rsync/configuration.py, server/pulp/plugins/rsync/publish.py, server/pulp/server/async/celery_instance.py, server/pulp/server/db/model/__init__.py, server/pulp/server/event/notifiers.py, server/pulp/server/managers/auth/permission/cud.py, server/pulp/server/managers/consumer/applicability.py, server/pulp/server/webservices/urls.py, server/pulp/server/webservices/views/serializers/content.py, server/test/unit/server/db/migrations/test_0015_load_content_types.py, server/test/unit/server/managers/auth/cert/test_cert_generator.py
Having flake8 run against diffs won't pick up things like unused imports
if the import line wasn't touched. Therefore, we should run flake8
against the entire codebase for each PR.
Also, fixing a bunch of breakages.
=> Run flake8 against entire codebase for PRs

docs/requirements.txt
The pulp/docs requirements.py should include everything necessary to run 'make html'
Since we are calling 'import django; django.setup()' in the sphinx conf.py
every dependency used by pulp needs to be installed (and not mocked).
Usually this is not a problem if the docs are being built on the same machine pulp is
installed on, but in cases where only doc building is done, only one requirements.txt
should need to be instatlled.
=> Add dependencies to pulp/docs requirements

platform/pulpcore/app/models/content.py, platform/pulpcore/app/models/storage.py, platform/pulpcore/app/serializers/content.py, platform/pulpcore/app/settings.py, platform/pulpcore/app/upload.py, platform/pulpcore/app/viewsets/__init__.py, platform/pulpcore/app/viewsets/base.py, platform/pulpcore/app/viewsets/content.py
Solution: add a viewset for Artifacts
The REST API user can now POST to /api/v3/artifacts endpoint with a file,
size, and any number of checksums. During the upload of the file, each
possible checksum is calculated. If user provides size or any checksums,
they are verified after the upload finishes. If one of the values does not
match a ValidationError is raised.
The user can also list all the the Artifacts by performing a GET request
to /api/v3/artifacts. An Artifact can be deleted by making a DELETE
request to /api/v3/artifacts/<pk>.
The user can not update Artifacts via REST API after one is created.
The 'django.core.files.uploadhandler.MemoryFileUploadHandler' is disabled so
all uploads are handled by 'pulpcore.app.upload.PulpFileUploadHandler' and
are written to '/var/lib/pulp/tmp' …
=> Problem: Artifacts can't be created via REST API

.travis.yml
Due to the fact that using setup.py for installation is no longer
suggested practice in the python community. We start using
`pip install -e .` instead of `python setup.py develop`.
=> Start using pip to install pulp in travis builds

platform/pulpcore/app/apps.py, platform/pulpcore/app/models/__init__.py, platform/pulpcore/app/models/content.py, platform/pulpcore/app/serializers/content.py, platform/pulpcore/app/serializers/fields.py, platform/pulpcore/app/signals.py, platform/pulpcore/app/viewsets/__init__.py, platform/pulpcore/app/viewsets/base.py, platform/pulpcore/app/viewsets/content.py, plugin/pulpcore/plugin/models/__init__.py
Solution: Add viewset and serializers to serve Content creation API
This change also introduces a DeferredArtifact that will be used by importers that
want to support deferred download policies.
closes #2872
https://pulp.plan.io/issues/2872
=> Problem: Content can not be created using REST API

platform/pulpcore/tasking/celery_instance.py
Turn on task_reject_on_worker_lost (aka CELERY_REJECT_ON_WORKER_LOST) to prevent the loss of tasks when a worker dies.
fixes #2958
https://pulp.plan.io/issues/2958
=> Turn on task_reject_on_worker_lost to prevent lost tasks

docs/plugins/plugin-api/changeset.rst, platform/pulpcore/app/models/content.py, platform/pulpcore/download/validation.py, plugin/pulpcore/plugin/changeset/__init__.py, plugin/pulpcore/plugin/changeset/iterator.py, plugin/pulpcore/plugin/changeset/main.py, plugin/pulpcore/plugin/changeset/model.py, plugin/pulpcore/plugin/download/__init__.py, plugin/pulpcore/plugin/download/factory.py, plugin/pulpcore/plugin/download/monitor.py
https://pulp.plan.io/issues/2942
File plugin counterpart: https://github.com/pulp/pulp_file/pull/9
Update the _changeset_ package to align with changes to the content/artifact model.
With `Artifact` being shared, the changeset needed to find and reuse artifacts much like it does for de-duplicating content.  It also needs to manage the `ContentArtifact`.  This effort revealed a few opportunities for better division of responsibilities.  But, the changeset paradigm remains the same.  A plugin writer will only need to deal with `Content` and `Artifact` DB models.
This effort also revealed opportunities for minor improvements in API clarity.  It's possible that the `DeferredArtifact` DB model could be renamed to something like `RemoteArtifact` which would be confusing to plugin writers.  With …
=> Update changeset for change in content/artifact models.

platform/pulpcore/app/models/repository.py, platform/pulpcore/app/tasks/importer.py, plugin/pulpcore/plugin/changeset/main.py
Determination of "is_deferred" moves to the Importer model.
Accounting of content add/remove moves to ChangeSet.
Sync task logs repo and importer names at start.
=> moves minor behaviors from FilePlugin to pulpcore

platform/pulpcore/download/context.py, platform/pulpcore/download/http.py, platform/pulpcore/download/single.py
Mitigates issues in python-requests and urlib3.  Here is the pulp2 issue:  https://pulp.plan.io/issues/2677
The `Cache` class copied almost exactly from pulp2 but moved to context.py.  The `Context` class just moved from single.py to context.py.
=> Port pulp2 caching of python-requests sessions.

platform/pulpcore/app/models/__init__.py, platform/pulpcore/app/models/publication.py, platform/pulpcore/app/models/repository.py, platform/pulpcore/app/models/storage.py, platform/pulpcore/app/serializers/repository.py, platform/pulpcore/app/tasks/publisher.py, platform/pulpcore/app/urls.py, platform/pulpcore/app/views/__init__.py, platform/pulpcore/app/views/content.py, plugin/pulpcore/plugin/models/__init__.py
https://pulp.plan.io/issues/2893
https://pulp.plan.io/issues/2895
Add publication models and test using file plugin.
This PR currently includes (2) files for the content app.  May split out into separate PR before merging.
Testing requires creating a `Distribution` in the DB with `psql`.
=> Add publication models.

platform/pulpcore/app/apps.py, platform/pulpcore/app/models/publication.py, platform/pulpcore/app/serializers/__init__.py, platform/pulpcore/app/serializers/base.py, platform/pulpcore/app/serializers/repository.py, platform/pulpcore/app/settings.py, platform/pulpcore/app/urls.py, platform/pulpcore/app/viewsets/__init__.py, platform/pulpcore/app/viewsets/base.py, platform/pulpcore/app/viewsets/repository.py
This was based off of a @jortel branch. It will need to be rebased, cleaned up and tested, but demonstrates the POC for Nested Serialization.
This PR does a few things, which I plan to clean up into separate commits.
1. Allows nested serializers to populate a field that represents an objects "url parent". For example, the publisher created at repositories/r1/publishers/file/p1/ should obviously use r1 as its repository.
2. Allow doubly nested viewsets to be registered with the router in the correct order. 
3. Create a Distribution ViewSet and Serializer.
This (at least right now) seems like the best approach, because it avoids creating lots of Mixins that handle the url creation. It also avoids needing to use `reverse` or url manipulation.
There are a lot more comments necessary to …
=> 2916 add distribution viewset and serializer

deps/external_deps.json, deps/python-kombu/python-kombu.spec
Disabling %check for python-kombu
Fedora's python-kombu doesn't have this enabled, and it's causing build
failures for rhel7 for python-six version requirements.
=> Disabling %check for python-kombu

common/pulp/common/config.py, server/pulp/plugins/rsync/publish.py, server/pulp/server/async/app.py, server/pulp/server/webservices/urls.py
Mitigates an issue where workers can be left in a broken
state if they are restarted while processing a task.
Fixes only the SIGTERM shutdown case, the most common one.
re #2835
https://pulp.plan.io/issues/2835
=> Fix issue causing worker to be left in a broken state

platform/pulpcore/app/serializers/__init__.py, platform/pulpcore/app/serializers/base.py, platform/pulpcore/app/serializers/fields.py, platform/pulpcore/app/serializers/repository.py
The parent repo will now be determined by the url instead of by
request parameters.
closes #2985
https://pulp.plan.io/issues/2985
=> Set the href_writable on RepositoryRelatedFields

.pep8speaks.yml, flake8.cfg
PEP8 seems to handle empty files just fine with regards to W391.
=> Stop ignoring PEP8 W391

platform/pulpcore/app/models/repository.py, platform/pulpcore/app/serializers/repository.py, plugin/pulpcore/plugin/download/futures/factory.py
closes #2818
re #2817
closes #2816
This commit aligns the Importer model and serializer with the MVP
document for Pulp 3. The model docstrings are redundant with the
serializer help_text. The help_text will eventually become the
documentation, so removing using it exclusively will be the best way to
keep the code, comments, and documentation up to date.
=> Align importer models and serializers with MVP

docs/plugins/plugin-api/asyncio.rst, docs/plugins/plugin-api/index.rst, platform/pulpcore/tasking/tasks.py, plugin/pulpcore/plugin/download/asyncio/__init__.py, plugin/pulpcore/plugin/download/asyncio/base.py, plugin/pulpcore/plugin/download/asyncio/exceptions.py, plugin/pulpcore/plugin/download/asyncio/factory.py, plugin/pulpcore/plugin/download/asyncio/file.py, plugin/pulpcore/plugin/download/asyncio/group.py, plugin/pulpcore/plugin/download/asyncio/http.py, plugin/pulpcore/plugin/models/importer.py, plugin/setup.py
Adds a HttpDownloader
- handles both synchronous and asynchronous downloads
- designed for subclassing to make custom downloader
- size validation works
- digest validation works
- has a well defined return interface DownloadResult
Reworks the Factory
- Updates the Factory to use HttpDownloader
- Fully configures HttpDownloader with all importer settings including:
ssl client and server options, basic auth, proxy, proxy_auth
- Can be reused with custom downloaders
Adds a GroupDownloader
- Downloads files in parallel but only return back to the use when any
group of files are fully downloaded.
- Drivable with or with generators
- Constrains in-memory objects through generator use
General Updates
- Updates the importer to use the Factory
- Updates the docs to use docs from the new code …
=> Introducing asyncio downloaders

plugin/pulpcore/plugin/download/asyncio/base.py, plugin/pulpcore/plugin/download/asyncio/file.py, plugin/pulpcore/plugin/download/asyncio/http.py
- reworks the file-object creation to be simpler
- adds finalize()
- switches FileDownloader, HttpDownloader to use it
- adds docs
https://pulp.plan.io/issues/2951
re #2951
=> Adds finalize() to BaseDownloader

docs/plugins/plugin-api/asyncio.rst, plugin/pulpcore/plugin/download/asyncio/group.py
The GroupDownloader was not correctly setting the expected_size and
expected_digests even though it could. This fixes the GroupDownloader so
that it sets those expected values causing validation to happen
correctly.
https://pulp.plan.io/issues/2951
re #2951
=> GroupDownloader now validates

docs/installation/instructions.rst
Changes:
- Made section header names more consistent
- Moved the SELinux permissive mode step, since it applies to all installation types, not just Ansible
- Added the command for setting SELinux to permissive mode
- Clarified that the python version (major *and* minor) found by virtualenv influences the path where the ```server.yaml``` file will be located.  It will be different on Fedora 25 and Fedora 26 because F26 uses Python 3.6, and the python version number becomes a component in the path name
- Added a command to exit the postgres user shell after setting up the database
- Added a reminder for the user to add the real location of ```server.yaml``` to the ```Environment``` variable in the systemd unit files
=> Made some changes to the installation docs for clarity

docs/installation/instructions.rst
The reST specification states that inline code must be identified by
double backticks. Triple backticks have no special meaning.
Triple backticks are used to denote `<pre>` blocks in various markdown
derivatives, such as CommonMark and GitHub-flavored Markdown.
=> Fix syntax error in documentation

plugin/pulpcore/plugin/download/futures/settings.py
https://pulp.plan.io/issues/3015
Masking the password is better than omitting it all together because it provides more information for troubleshooting.  Manly, that a password was specified vs. left blank.
=> Mask logged password.

platform/pulpcore/app/models/progress.py
https://pulp.plan.io/issues/3003
The `_last_save_time` was being updated even when not actually saved.  Calling save() repeatedly within 500 ms resulted the progress never actually getting saved.
=> Fix progress save() throttling.

platform/pulpcore/app/models/content.py, plugin/pulpcore/plugin/changeset/iterator.py, plugin/pulpcore/plugin/changeset/main.py, plugin/pulpcore/plugin/changeset/model.py
https://pulp.plan.io/issues/3017
Mainly separated the _pending_ and _stored_ models:  `PendingArtifact._model` and `PendingArtifact_stored_model`.
=> Remote artifact created with correct digests.

plugin/pulpcore/plugin/download/asyncio/group.py
Solution: process all finished downloads before checking if any Group is done
closes #3021
https://pulp.plan.io/issues/3021
=> Problem: GroupDownloader skips some downloads

server/pulp/server/db/model/__init__.py, server/test/unit/server/db/test_model.py
This is an additional fix needed in Pulp apart from
https://github.com/pulp/nectar/pull/63, since Pulp writes
out the SSL certs to a different path than nectar
closes #2960
=> UnicodeEncodeError in comments provided with SSL cert/key/CA

plugin/pulpcore/plugin/download/asyncio/file.py, plugin/pulpcore/plugin/download/asyncio/group.py, plugin/pulpcore/plugin/download/asyncio/http.py
The chunk size is a lot bigger, and increasing the default count of
downloaders in parallel for the group downloader.
=> Increase asyncio parallelization

platform/pulpcore/tasking/tasks.py
We need to be using a queryset for ReservedResources, not "get()".
closes #3056
https://pulp.plan.io/issues/3056
=> Fix traceback on rapid dispatch of multiple syncs

docs/contributing/platform_api/app/auth.rst, docs/contributing/platform_api/app/index.rst, docs/installation/configuration-files.rst, docs/integration_guide/rest_api/authentication.rst, docs/integration_guide/rest_api/index.rst, platform/pulpcore/app/auth/jwt_auth.py, platform/pulpcore/app/auth/jwt_utils.py, platform/pulpcore/app/models/auth.py, platform/pulpcore/app/serializers/user.py, platform/pulpcore/app/settings.py, platform/pulpcore/app/urls.py, platform/pulpcore/etc/pulp/server.yaml, platform/setup.py
closes #2359
https://pulp.plan.io/issues/2359
=> Add JWT token auth

platform/pulpcore/app/urls.py
The issue was that we were mapping all `/api/v3/*` routes to the api schema which meant that all routes that didn't match another route displayed the api schema. 
It also caused some weird behaviors where we saw some 406s instead of 404. 
I also needed to move the route above the other routers because they assigned `/api/v3/` to a route which returns a list of resources.
fixes #3063
https://pulp.plan.io/issues/3063
=> Fix the api schema route

platform/pulpcore/app/models/auth.py, platform/pulpcore/app/serializers/consumer.py, platform/pulpcore/app/serializers/repository.py, platform/pulpcore/app/serializers/user.py
Move username regex validator from model to serializer, since the model validation
does not run automatically on model save:
https://docs.djangoproject.com/en/dev/ref/validators/#how-validators-are-run
closes #2984
https://pulp.plan.io/issues/2984
=> Add uniquenessand length validators to serializer fields.

server/pulp/server/agent/direct/pulpagent.py
Fix NotFound exception if consumer is deleted when
its queue is gone.
closes #3069
https://pulp.plan.io/issues/3069
=> Fix exception when deleting consumer

docs/installation/instructions.rst
Update all install instructions to use venv (instead of virtualenv) for consistency
closes #3071
https://pulp.plan.io/issues/3071
=> Add Pulp3 source install instructions

server/pulp/server/db/manage.py, server/pulp/server/db/migrate/models.py, server/test/unit/server/db/test_manage.py
I threw this together to help someone who is testing how long the migrations take for various upgrades, and it appears useful enough to benefit others.
=> adds duration to the log message for completion of each migration

docs/integration_guide/rest_api/authentication.rst, platform/pulpcore/app/models/auth.py, platform/pulpcore/app/serializers/user.py, platform/pulpcore/app/viewsets/user.py
Creating a new endpoint for resetting jwts instead of having a field on
user to reset them. This also fixes user creation which is currently
broken.
fixes #3075
https://pulp.plan.io/issues/3075
=> Create a new jwt reset endpoint instead of a user field

pulpcore/pulpcore/app/serializers/fields.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/tests/viewsets/test_base.py, pulpcore/pulpcore/app/viewsets/repository.py
Solution: use repository id in the URL instead of name
This patch switches repository URI from `/api/v3/repositories/<name>/` to
`/api/v3/repositories/<pk>/`.
closes #3101
https://pulp.plan.io/issues/3101
=> Problem: repository URI is mutable

pulpcore/pulpcore/app/tasks/importer.py, pulpcore/pulpcore/app/tasks/publisher.py, pulpcore/pulpcore/app/viewsets/repository.py
https://pulp.plan.io/issues/3138?next_issue_id=3137
Changes:
- Aligns task arguments with calls from viewsets.
- Passes task arguments as kwargs for consistency and readability.
- Update task arguments to be based on PKs.  More will be needed when importer/publisher URLs concerted to PKs.
=> Fix importer update and sync; publisher update and publish.

docs/conf.py, docs/contributing/3.0-development/rest-api.rst, docs/integration_guide/rest_api/index.rst, docs/plugins/plugin-writer/basics.rst, docs/requirements.txt, pulpcore/doc_requirements.txt, pulpcore/pulpcore/apidocs/views.py, pulpcore/pulpcore/app/settings.py, pulpcore/pulpcore/app/urls.py
~~drf_openapi new PyPI release with ^ fixes~~ <- done with optional dep
~~update jjb jobs to separate pulp3 and pulp2 doc builds~~ <- do after merge to avoid building all the doc builder scaffolding 
~~update jjb jobs to separate pulp3 and pulp2 pr-doc builds~~
=> Add REST API autodocs

server/selinux/server/pulp-celery.te
closes #3159
https://pulp.plan.io/issues/3159
Compiled and installed without errors on f26, f27 and rhel7.
Resolves selinux denials on f27.
=> Update selinux definitions for celery so it runs on f27

pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/serializers/base.py, pulpcore/pulpcore/app/serializers/fields.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/viewsets/repository.py
closes https://pulp.plan.io/issues/3160
=> Move nested urls to flat structure

pulpcore/pulpcore/app/apps.py, pulpcore/pulpcore/app/tasks/__init__.py, pulpcore/pulpcore/app/tasks/base.py, pulpcore/pulpcore/app/tasks/importer.py, pulpcore/pulpcore/app/tasks/publisher.py, pulpcore/pulpcore/app/viewsets/__init__.py, pulpcore/pulpcore/app/viewsets/base.py, pulpcore/pulpcore/app/viewsets/repository.py
Solution: add general update and delete tasks and viewsets
This patch creates two new tasks that are used by both the publisher viewset and the importer viewset.
This patch also introduces a new base viewset. Both the importer and publisher viewset inherit from it.
closes #3038
https://pulp.plan.io/issues/3038
=> Problem: async update and delete code is duplicated

server/pulp/server/db/model/consumer.py
Search by repo_id is used to queue applicability tasks.
If there are many consumer profiles in a collection, cursor may timeout.
closes #3133
https://pulp.plan.io/issues/3133
=> Add repo_id index to applicability collection

docs/dev-guide/contributing/branching.rst
closes #3252
https://pulp.plan.io/issues/3245
=> Fix broken link to protected-branches.py

pulpcore/pulpcore/app/serializers/task.py
Using the model's serializer rather than reverse allows us to generate
hrefs for objects that use any set of url parameters.
closes #3276
https://pulp.plan.io/issues/3276
=> Make CreatedResource serialize any resource

pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/serializers/fields.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/settings.py, pulpcore/pulpcore/app/urls.py, pulpcore/pulpcore/etc/pulp/server.yaml
Solution: Add 'base_url' field to the Distribution resource
This patch adds a read only 'base_url' field to the Distribution resource. It's value is derived
from a new 'hostname' config in server.yaml and the 'base_path' of the Distribution.
for the base_url field of the Distribution resource.
closes #3185
https://pulp.plan.io/issues/3185
=> Problem: Distribution lacks a base URL

docs/integration_guide/rest_api/authentication.rst
The most recent FF does not support the add-on currently listed here.
This updates it to an equivalent plugin that is currently supported.
=> Switch to a supported Firefox addon

docs/contributing/platform_api/tasking.rst, docs/plugins/index.rst, docs/plugins/plugin-api/asyncio.rst, docs/plugins/plugin-api/futures.rst, docs/plugins/plugin-api/index.rst, docs/plugins/plugin-writer/first-plugin.rst, docs/plugins/plugin-writer/index.rst, plugin/pulpcore/plugin/changeset/model.py, plugin/pulpcore/plugin/models/__init__.py, pulpcore/pulpcore/app/models/content.py, pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/urls.py
Sphinx in 1.6.6 fixed a regression that would allow doc build warnings to
pass unnoticed[1].  Thus having updated Sphinx would have broken one's
Pulp docs build.
This patch addresses the doc build warnings as well as fixes a broken link
here and there.
[1] https://github.com/sphinx-doc/sphinx/issues/3919
closes: #3275
https://pulp.plan.io/issues/3275
=> Fix doc build (warning) errors

common/pulp/common/constants.py, docs/user-guide/release-notes/2.16.x.rst, docs/user-guide/release-notes/index.rst, server/etc/pulp/server.conf, server/pulp/server/async/app.py, server/pulp/server/async/scheduler.py, server/pulp/server/async/worker_watcher.py, server/pulp/server/config.py, server/pulp/server/constants.py, server/pulp/server/db/querysets.py, server/test/unit/server/async/test_app.py, server/test/unit/server/async/test_scheduler.py, server/test/unit/server/async/test_worker_watcher.py
refs #3135
https://pulp.plan.io/issues/3135
=> Add warning and config variables for heartbeat timeout/interval

pulpcore/pulpcore/app/viewsets/repository.py
Doc builder was failing with: more than one target found for cross-reference
'OperationPostponedResponse': pulpcore.plugin.viewsets.OperationPostponedResponse,
pulpcore.app.response.OperationPostponedResponse
=> Specify which OperationPostponedResponse in docstring

pulpcore/pulpcore/app/serializers/fields.py
The `_latest_version_href` field on repos can point to repo versions where complete is False.
=> Last version href erroneously returns incomplete versions

pulpcore/pulpcore/app/views/status.py, pulpcore/pulpcore/app/viewsets/content.py, pulpcore/pulpcore/app/viewsets/repository.py
The docstring in our views and viewsets is exposed to users through our
REST API schema documentation. This updates our docstring to be more
user friendly. For more info see:
http://www.django-rest-framework.org/api-guide/schemas/#schemas-as-documentation
=> Update views docstring to not expose internal details

pulpcore/pulpcore/app/serializers/content.py
Issue 3316 is cause because hashlib.algorithms_guaranteed contains shake_128 and shake_256 in python 3.6. These have variable length digests and need a length value passed in. 
Since the user shouldn't be passing in any algorithms not stored on the artifact model, only check those hashes.
fixes #3316
https://pulp.plan.io/issues/3316
=> Only validate hash algorithms that the user can upload on the model.

plugin/pulpcore/plugin/tasking.py, pulpcore/pulpcore/tasking/services/storage.py
Updated the `__enter__()` to create the directory.  I think this is more appropriate since the physical directory's lifespan coincides with the duration of the context.  Since the directory is deleted when exiting the context I liked the symmetry of it being created when entering the context.  The create method is more appropriate as an instance method.
Minor class refactoring.
File plugin pr: https://github.com/pulp/pulp_file/pull/31
=> WorkingDirectory refactored.

server/pulp/server/async/tasks.py, server/test/unit/server/async/test_tasks.py
Fixes an issue where workers would crash when
attempting to revoke() a previously running task
on startup. If the user sends SIGKILL to the
worker while running a task, the worker will
attempt to mark the task as stale when restarted.
This causes a hang for yet-unknown reasons. Calling
revoke() is not necessary when a dead worker is being
cleaned up because all work goes through dedicated
queues which disappear when the worker does. We
leave revoke() active only when a task is being
cancelled outside of worker cleanup.
closes #2835
https://pulp.plan.io/issues/2835
=> Fixes workers crashing on restart edge case

server/pulp/plugins/rsync/publish.py
Commit c981b94de498 ("As user I want to be able to provide custom
rsync arguments to rsync distributor") missed to add the rsync extra
args to the rsync call in remote_mkdir().
=> Actually use rsync_extra_args for all rsync calls

server/selinux/server/pulp-celery.te, server/selinux/server/pulp-server.te
closes #3314
https://pulp.plan.io/issues/3314
=> Update pulp puppet selinux policies

pulpcore/pulpcore/app/models/repository.py
`RepositoryVersions` is sometimes queried solely by (complete=True).  Adding an index to prevent full table scan.
=> RepositoryVersion.complete should be indexed.

pulpcore/pulpcore/app/viewsets/repository.py
Looks like add_content_units and remove_content_units parameters are
strings. This splits them up.
=> Fix adding/removing content units to a version

server/pulp/server/db/model/__init__.py
The queue suffix is dependent on celery version. Celery 4 uses ".dq2"
so we need to handle that case when we recreate the queue name as
part of the detail view.
=> Fix incorrect queue name suffix with Celery 4

server/pulp/server/db/model/__init__.py
The queue_name property does not handle the case where the worker name
is None.
=> Fix case where queue_name property returns None.dq

pulpcore/pulpcore/app/models/base.py, pulpcore/pulpcore/app/models/publication.py, pulpcore/pulpcore/app/models/repository.py
Related to https://pulp.plan.io/issues/3337, the FileContent needed to be ordered by a `created` field.  This seemed generally useful for other plugins for the same reason.  Then, considered that a `created` timestamp would be useful on most models.  So, why not add it to `Model`.  Along the same line of thinking, why not add `last_updated` while we're at it.  Should be generally useful for filtering/search and troubleshooting.
There are some concerns within the django community regarding *auto_now* and *auto_now_add* but I suggest we make this change independently of that.  We should be revisited and fix on all models as needed.
=> Fields: created & last_updated moved to Model.

pulpcore/pulpcore/app/models/content.py
Many Python Package file names are longer than 64 characters, for example:
`scipy-1.0.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl`
=> Lengthen relative path for content artifacts

pulpcore/pulpcore/app/models/repository.py
Prevent users/plugins from adding content to a repo version if that content would otherwise already exist for that repo version.
Added validation to the viewset so we don't kick off a task and a nice user error gets return if the content addition/removal isn't allowed. Also added validation to the model mostly for the benefit of plugins who might call these methods directly.
closes #3304
https://pulp.plan.io/issues/3304
=> Prevent duplicate content

docs/installation/instructions.rst
The Pypi installation instructions missed the makemigrations step.
Fixes #3362
https://pulp.plan.io/issues/3362
=> Add the missing makemigrations Pypi install step

pulpcore/pulpcore/app/viewsets/base.py, pulpcore/pulpcore/app/viewsets/repository.py
The multi-resource locking change used version to lock on when creating
repository versions but of course there's no version. It should lock on
repository.
=> Fixing error for repository version create

docs/dev-guide/contributing/branching.rst
With the acceptance of PUP3, branching and merging has significantly
changed.  This is to update the docs to reflect the new state of the
development work flow.
closes #[3246](https://pulp.plan.io/issues/3246)
https://pulp.plan.io/issues/3246
=> Update branching guide to a post-PUP3 world

plugin/pulpcore/plugin/models/publisher.py
re: #3221
https://pulp.plan.io/issues/3221
=> Remove vestigial model-based publish code from the plugin API

.travis.yml, docs/installation/instructions.rst, pulpcore/pulpcore/app/settings.py, pulpcore/pulpcore/etc/pulp/server.yaml
This commit updates the database docs to identify sqlite3 as the default
database and recommend that users use Postgresql in production. It also
links to the Django docs for more info on the settings.
Additionally, it updates the source and pypi install instructions in the
following ways:
* fixes some errors
* renames {venv} to pulpvenv for clarity
* adds a helper 1-liner to generate the SECRET_KEY line
* updates the PULP_SETTINGS to use python3.6 instead of {python_version}
https://pulp.plan.io/issues/3359
re #3359
=> Sqlite3 and some install fixes

pulpcore/pulpcore/app/settings.py, pulpcore/pulpcore/etc/pulp/server.yaml
Since Pulp still won't run with vanilla qpid broker[1] it seems reasonable
to refer to the RabbitMQ as the default broker instead.
Fixes #3366
https://pulp.plan.io/issues/3366
[1] https://github.com/celery/kombu/pull/810
=> Refer to RabbitMQ as the default broker

docs/installation/instructions.rst
The Ansible installer docs are being temporarily removed so that a new,
unified Ansible installer can be re-introduced later.
This commit also makes the install docs slightly for cross platform.
https://pulp.plan.io/issues/3437
closes #3437
=> Remove Ansible docs from installer

.travis/before_script.sh, pulpcore/pulpcore/app/settings.py, pulpcore/pulpcore/etc/pulp/server.yaml, pulpcore/pulpcore/tasking/celery_app.py
fixes #3406
https://pulp.plan.io/issues/3406
=> Using /var/lib/pulp/tmp instead of /var/cache/pulp

.travis/server.sqlite.yaml, pulpcore/pulpcore/app/settings.py, pulpcore/pulpcore/etc/pulp/server.yaml
https://pulp.plan.io/issues/3456
We can't specify it in settings.py because it is a database-specific option.  Therefore it needs to be specified in the server.yaml file.  Unfortunately this means that server.yaml will be providing some settings even on a default installation.
=> Set a 20 second timeout for sqlite

pulpcore/pulpcore/app/serializers/user.py
The 'six' module is intended to make writing code that works on both
Python 2 and 3 easier. Without Python 2 support, it just makes our code
more opaque.
Also removed some superflous logic.
=> Remove usage of the Django 'six' module

pulpcore/pulpcore/app/serializers/user.py
It's not currently being used for anything, so we shouldn't expose it.
closes #3141
https://pulp.plan.io/issues/3141
=> Remove the 'is_superuser' field from user-facing API

pulpcore/pulpcore/app/serializers/base.py
Looks like django requires certain features of hostnames like a "." so
using `get_host()` was not a good idea. Using a known valid hostname
instead.
fixes #3476
https://pulp.plan.io/issues/3476
=> Fixing problems with bad hostnames

pulpcore/pulpcore/app/viewsets/content.py
Remove ability to delete a content unit used by a
repo version
You should not be able to delete a unit of content that is used by a
repo version so that ability has been removed.
fixes #3418
https://pulp.plan.io/issues/3418
=> Remove ability to delete a content unit used by a repo version

pulpcore/pulpcore/app/viewsets/repository.py
If content is not passed in, the filter still gets run with a blank
string for some reason. Extending Filter instead of CharFilter seems to
fix this.
fixes #3502
https://pulp.plan.io/issues/3502
=> Fix defaulting of value to blank string when not specified

docs/extensions/napoleon_django/docstring.py, pulpcore/pulpcore/app/apps.py, pulpcore/pulpcore/app/models/base.py, pulpcore/pulpcore/app/models/fields.py, pulpcore/pulpcore/app/models/progress.py, pulpcore/pulpcore/app/response.py, pulpcore/pulpcore/app/serializers/base.py, pulpcore/pulpcore/app/viewsets/content.py, pulpcore/pulpcore/exceptions/base.py, pulpcore/pulpcore/exceptions/http.py, pulpcore/pulpcore/exceptions/plugin.py, pulpcore/pulpcore/tasking/tasks.py
Specifying ```super(ClassName, self)``` is not necessary in Python 3
=> Use Python3-style 'super()' instead of Python2-style

pulpcore/pulpcore/app/models/task.py, pulpcore/pulpcore/app/serializers/task.py, pulpcore/pulpcore/tasking/celery_app.py, pulpcore/pulpcore/tasking/constants.py, pulpcore/pulpcore/tasking/services/worker_watcher.py
closes #3121
https://pulp.plan.io/issues/3121
=> Simplify worker 'online' state tracking

.travis.yml, .travis/install.sh, pulpcore/pulpcore/app/fields.py, pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/models/task.py, pulpcore/pulpcore/app/tests/fields/test_jsonfield.py, pulpcore/setup.py
Fix a few issues which prevented Pulp from working with Django 2.0
* Changed requirement string
* Added ```on_delete``` behavior on all ForeignKey field types, required by Django 2 (needs to be double checked)
* Removed reference to ```six```
closes #3453
https://pulp.plan.io/issues/3453
=> Make compatible with Django 2.0

docs/contributing/dev-setup/source.rst
The guide made no mention of a working branch and now provides those for
each repository mentioned.
fixes #3506
https://pulp.plan.io/issues/3506
=> "Get the Source" Instructions Omit Working Branch

pulpcore/pulpcore/app/models/task.py, pulpcore/pulpcore/app/serializers/status.py, pulpcore/pulpcore/app/serializers/task.py, pulpcore/pulpcore/app/views/status.py, pulpcore/pulpcore/tasking/services/worker_watcher.py
* Don't serialize the 'gracefully_shutdown' field
* Create a new 'missing' property and serialize it
* In the status API, list both online and missing workers
=> Change how workers are represented

pulpcore/pulpcore/app/apps.py, pulpcore/pulpcore/app/viewsets/__init__.py, pulpcore/pulpcore/app/viewsets/base.py, pulpcore/pulpcore/app/viewsets/content.py
closes #3445
https://pulp.plan.io/issues/3445
=> Remove ability to delete content units

pulpcore/pulpcore/app/settings.py
This is no longer applicable because 
A) Importers are now totally unchained from repositories
B) I checked our models, and we are not using unique=True with any ForeignKeyFields
=> Remove non-applicable silenced warning

docs/contributing/index.rst, docs/contributing/unit_tests.rst
This policy is a starting point based feedback via pulp-dev. The
language adopted was shared via pulp-dev for comment.
=> Add basic unit tests policy

plugin/pulpcore/plugin/changeset/iterator.py
This resolves an issue where sqlite was emitting 'Too Many SQL
Variables' error when mirroring parts of Galaxy.
re #3499
https://pulp.plan.io/issues/3499
=> Uses smaller Changeset batches

plugin/pulpcore/plugin/changeset/iterator.py, plugin/pulpcore/plugin/changeset/model.py
https://pulp.plan.io/issues/3524
An empty `Q` object passed to `Model.objects.filter()` results in matching everything.  The PK will never be NULL so initializing the `Q(pk=None)` assures that when nothing else is added to the query, it will match nothing.  For the `Artifact` query, it means that when none of the digests are added to the query, it won't match everything.  Same for `Content` to be safe.
=> Prevent query matching all content/artifact when not criteria included.

pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/serializers/repository.py
closes: #3545
https://pulp.plan.io/issues/3545
=> Remote auto_publish field from Publisher

docs/plugins/plugin-api/download.rst, plugin/pulpcore/plugin/download/base.py, plugin/pulpcore/plugin/download/http.py, plugin/setup.py
All retry support is provided by the 'backoff' library which also
provides an asyncio compatible interface.
This updates the docs and docstrings to call out the new retry
functionality.
https://pulp.plan.io/issues/3421
closes #3421
=> Adds 429 Retry Support

docs/arch_and_scale/index.rst, docs/arch_and_scale/webserver.rst, docs/index.rst
This creates an Architecture and Scaling top level section of the docs.
It also explains for each component how it can be scaled which mostly
involves documenting how the WSGI application is laid out.
https://pulp.plan.io/issues/3132
closes #3132
=> Adds WSGI and Architecture Docs

.travis/install.sh, pulpcore/pulpcore/app/response.py, pulpcore/pulpcore/app/views/orphans.py, pulpcore/pulpcore/app/viewsets/base.py, pulpcore/pulpcore/app/viewsets/repository.py
fixes #3166
https://pulp.plan.io/issues/3166
Requires PR: PulpQE/pulp-smash#948
Requires PR: pulp/pulp_file#67
=> Return a single task for task operations

pulpcore/pulpcore/app/viewsets/task.py
Kersom found a bug in the behavior of composite filtering using the "online" or "missing" fields in conjunction with other filters.
=> Fix a worker filtering bug

pulpcore/pulpcore/app/apps.py, pulpcore/pulpcore/app/urls.py
If plugins define a urls.py, register it. This allows the plugin writer
to register views at arbitrary endpoints, allowing them to implement a
Live API.
fixes #3560
https://pulp.plan.io/issues/3560
To demonstrate how this is used, this PR is a proof of concept.
https://github.com/pulp/pulp_file/pull/66
=> Register plugin provided urls.py

pulpcore/pulpcore/app/serializers/base.py, pulpcore/pulpcore/app/serializers/progress.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/serializers/task.py, pulpcore/pulpcore/app/viewsets/repository.py, pulpcore/pulpcore/app/viewsets/task.py
closes: 3576
https://pulp.plan.io/issues/3576
=> Order list views where applicable

pulpcore/pulpcore/app/serializers/base.py
Default message provided by Django's URLValidator is simply:
"Enter a valid URL"
fixes #3475
https://pulp.plan.io/issues/3475
=> Provide more informative invalid base path error

pulpcore/pulpcore/app/viewsets/base.py
We should ignore other kwargs since pk should uniquely identify the
resource. The problem we were experiencing in pulp_ansible is that we
had a pk and a role_pk. The conversion from role_pk to role_id only
happens inside the else block and so we're getting a FieldError because
role_pk doesn't exist on the model. Instead, I think we should just use
the pk kwarg and ignore the rest.
=> Have get_resource() use pk and only pk if pk is provided

pulpcore/pulpcore/app/serializers/repository.py
The basic ModelSerializer fields such as 'created' were omitted from
RepositoryVersionSerializer
=> Add 'created' to repo version serializer

pulpcore/pulpcore/app/models/publication.py
https://pulp.plan.io/issues/3605
I would have added as: `PublishedFile.Meta.unique_together = (publication, relative_path)` but django does not deal with it properly.  This seems to be a know flaw[1] in django.
I would have mentioned the _new_ restriction in the plugin writer's docs but did not find an appropriate place.
[1] https://code.djangoproject.com/ticket/16732
=> Prevent duplicate relateive paths within a publication.

server/pulp/server/db/model/__init__.py
Writing SSL certs/key to file that contain non-ascii characters
raises a UnicodeDecodeError in Pulp, since Python 2 by default
decodes objects as 'ascii'.
closes #3253
https://pulp.plan.io/issues/3253
=> UnicodeDecodeError in comments provided with SSL cert/key

pulpcore/pulpcore/app/serializers/repository.py
The problem is you can create distributions without publications but you can't unset a publication on a distribution once it is set.
fixes #3671
https://pulp.plan.io/issues/3671
=> Allowing publication to be unset on distributions

docs/installation/instructions.rst, docs/overview/components/index.rst, docs/overview/components/webserver.rst, pulpcore/pulpcore/etc/pulp/server.yaml
This adds static content configuration docs, and adds it as a component
in the architecture list. It adds a single step to the installer which
refers to the more detailes docs.
It also adds the 'DEBUG: False' as the default to settings.yaml which
was missing. It was needed because these docs mention configuring it
there.
It also makes a few formatting improvements.
https://pulp.plan.io/issues/3620
closes #3620
=> Adds static content docs

repoauth/test/test_repo_cert_utils.py
We're waiting on an m2crypto bug but it might take a while to fix/package/release:
https://gitlab.com/m2crypto/m2crypto/issues/217
Skip the failing test for now.
ref #3689
https://pulp.plan.io/issues/3689
=> Temporarily skip failing test until m2crypto issue is resolved

server/pulp/server/util.py, server/test/unit/server/test_util.py
In some builds of Python, a usedforsecurity flag is available to declare that md5 is not being used for security purposes. We're using md5 for checksums so set this flag if it's available. This is required for FIPS environments.
=> FIPS: Setting the usedforsecurity flag to False if available

.travis/server.yaml, docs/installation/configuration-files.rst, docs/installation/instructions.rst, pulpcore/pulpcore/app/serializers/fields.py, pulpcore/pulpcore/app/settings.py, pulpcore/pulpcore/app/views/content.py, pulpcore/pulpcore/etc/pulp/server.yaml, pulpcore/pulpcore/tasking/connection.py, pulpcore/pulpcore/tasking/services/storage.py, pulpcore/tests/test_settings.py
The naming convention for yaml is lowercase snake.
We had some all-uppercase names mixed in, now made consistent.
fixes #3589
https://pulp.plan.io/issues/3589
=> Consistent names in server.yaml

pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/serializers/fields.py, pulpcore/pulpcore/app/serializers/repository.py
serializer.fields.FileField currently does not work since models.FileContent
was removed. This PR removes this custom field, and starts using
drf's FileField serializer.
=> Remove pulp's custom FileField serializer

.travis.yml
The installation required a custom commit from sphinx_rtd_theme
git+https://github.com/snide/sphinx_rtd_theme.git@abfa98539a2bfc44198a9ca8c2f16efe84cc4d26
The pip however started to get issues pulling that in:
```
$ pip install flake8 sphinx sphinxcontrib-swaggerdoc celery sphinxcontrib-swaggerdoc 'django<2' git+https://github.com/snide/sphinx_rtd_theme.git@abfa98539a2bfc44198a9ca8c2f16efe84cc4d26 pyyaml
Collecting git+https://github.com/snide/sphinx_rtd_theme.git@abfa98539a2bfc44198a9ca8c2f16efe84cc4d26
Cloning https://github.com/snide/sphinx_rtd_theme.git (to abfa98539a2bfc44198a9ca8c2f16efe84cc4d26) to /tmp/pip-drCLVI-build
Could not find a tag or branch 'abfa98539a2bfc44198a9ca8c2f16efe84cc4d26', assuming commit.
error: Your local changes to the following files would be overwritten by …
```
=> Fix docs/make.bat pip&git induced coflict

plugin/setup.py, pulpcore/setup.py
pulpcore is currently at 3.0.0b4, pulpcore-plugin requires 3.0.0b3,
so the editable installation fails and it falls back to installing from
PyPI. So the developer installation will not actually be a developer
installation.
=> Fix dependencies for source installation

pulpcore/pulpcore/app/tasks/base.py
I could not find any asnyc updates that breaks with this change.
Smash also passes cleanly. I suspect breakage might have occured
when we had more complex nested relationships.
closes #3705
https://pulp.plan.io/issues/3705
=> Stop creating QueryDict for async update data

docs/user-guide/release-notes/2.16.x.rst, server/pulp/server/webservices/views/serializers/__init__.py
This commit resolvs CVE-2018-1090 by redacting all data from
last_override_config. It does not modify what is saved in the database.
It also adds a release note for the 2.16.2 release.
https://pulp.plan.io/issues/3521
closes #3521
=> Redact last_override_config

server/bin/pulp-gen-ca-certificate
FIPS does not support 4096 bit length keys
https://pulp.plan.io/issues/3646
=> Use a shorter CA key in FIPS environments

server/pulp/server/managers/consumer/applicability.py
closes #3745
https://pulp.plan.io/issues/3745
=> Ignore missing consumer profile during applicability regeneration

pulpcore/pulpcore/app/viewsets/content.py
Uploading files cannot be done using JSON, this
disable support for the application/json media_type,
Because a file upload is required to create an artifact.
This does not need to be done for Remotes, because
files on a remote is optional.
closes #3622
https://pulp.plan.io/issues/3622
=> Set parsers explicitly for Artifact Viewset

pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/serializers/base.py, pulpcore/pulpcore/app/serializers/content.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/tests/serializers/test_base.py, pulpcore/tests/serializers/test_repository.py
refs: https://pulp.plan.io/issues/2970
=> Raise a ValidationError when undefined attributes are passed to an endpoint.

pulpcore/pulpcore/app/serializers/content.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/serializers/status.py, pulpcore/pulpcore/app/serializers/user.py
Added allow_blank=True to all CharField serializers that are
not required.
fixes #3755
https://pulp.plan.io/issues/3755
=> allow_blank for optional fields

docs/plugins/plugin-api/download.rst
The interface to get a downloader was renamed from
`get_asyncio_downloader()` to `get_downloader()` at some point.
You can see the correct name is `get_downloader` from the current HEAD
of master [0].
[0]: https://github.com/pulp/pulp/blob/82e03f89c6cd2abb446e25f6af02184a9cacae5c/plugin/pulpcore/plugin/models/remote.py#L45
=> Fix incorrect docs in the downloaders

pulpcore/pulpcore/app/viewsets/repository.py
Our live docs were not showing correct schema for content,
added_content, and removed_content, but now are correct.
fixes #3762
https://pulp.plan.io/issues/3762
=> Show correct schema under repository versions

plugin/pulpcore/plugin/serializers.py, pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/serializers/base.py, pulpcore/pulpcore/app/viewsets/base.py, pulpcore/pulpcore/app/viewsets/repository.py
closes #3668
https://pulp.plan.io/issues/3668
=> Fix OpenAPI schema for async responses

plugin/pulpcore/plugin/changeset/main.py, pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/tasks/repository.py
fixes #3814
https://pulp.plan.io/issues/3814
=> Using querysets for add/remove_content methods

pulpcore/pulpcore/app/files.py, pulpcore/pulpcore/app/models/content.py, pulpcore/pulpcore/app/models/fields.py, pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/serializers/base.py, pulpcore/pulpcore/app/serializers/task.py, pulpcore/pulpcore/app/viewsets/base.py, pulpcore/pulpcore/app/viewsets/repository.py, pulpcore/pulpcore/app/viewsets/task.py, pulpcore/setup.py, pulpcore/tests/viewsets/test_base.py
Certain models, such as {RPM|Python|Ansible}Content or Task, have a lot of very verbose information that the user doesn't care much about.  We would like to provide some way for a user to filter out the less-useful information so that responses can be easily human-readable.
e.g.
```
[vagrant@pulp3 ~]$ http GET http://localhost:8000/pulp/api/v3/tasks/edbe9ad0-9787-4d76-97df-1411ff097fa6/?pretty=True
HTTP/1.1 200 OK
...
{
"_href": "http://localhost:8000/pulp/api/v3/tasks/edbe9ad0-9787-4d76-97df-1411ff097fa6/",
"created": "2018-06-28T16:13:54.241649Z",
"finished_at": "2018-06-28T16:13:55.467281Z",
"id": "edbe9ad0-9787-4d76-97df-1411ff097fa6",
"parent": null,
"started_at": "2018-06-28T16:13:54.312332Z",
"state": "completed",
"worker": …
```
=>  Use a query param approach for multiple serializers

docs/contributing/dev-setup/quickstart.rst
Development environments can be deployed in Docker.
Update the quickstart guide to reflect this.
=> Add Docker quickstart

pulpcore/pulpcore/tasking/worker.py
Make sure the REDIS connection string present in server.yaml is inherited by workers and resource_manager.
fixes #3861
https://pulp.plan.io/issues/3861
=> Makes the Redis string connection in server.yaml prevails for resource_manager and workers

.travis.yml, pulpcore/pulpcore/tasking/tasks.py, pulpcore/setup.py
RQ changed an argument name from 'async' to 'is_async' because
the former is now a reserved keyword.
=> Fix Pulp on Python 3.7

pulpcore/pulpcore/app/viewsets/base.py
Description of the range filters now look like this "Filter results where number is between two comma separated values"
closes #3826
https://pulp.plan.io/issues/3826
=> Improves description of the range filters

plugin/pulpcore/plugin/stages/artifact_stages.py
The downloaders created by DeclarativeVersion didn't specify any digest
or size information to use for validation even if it was available. I've
tested this code and it worked for me.
https://pulp.plan.io/issues/3844
re #3844
=> Have DeclarativeVersion validate download digests

docs/user-guide/installation/extra_configuration.rst, docs/user-guide/troubleshooting.rst
This adds:
* An extra configuration section
* A troubleshooting section with symptom descriptions
https://pulp.plan.io/issues/3887
closes #3887
=> Add docs on maintenance jobs

pulpcore/tests/functional/api/test_api_docs.py, pulpcore/tests/functional/api/test_auth.py, pulpcore/tests/functional/api/test_crud_distributions.py, pulpcore/tests/functional/api/test_crud_repos.py, pulpcore/tests/functional/api/test_crud_users.py, pulpcore/tests/functional/api/test_workers.py, pulpcore/tests/functional/api/using_plugin/test_repo_version.py, pulpcore/tests/functional/api/using_plugin/test_unlinking_repo.py
Now that Smash tests are in the same repo as the code under test, we no
longer need to look to an external source (Redmine) to determine whether
an issue should be tested.
When adding a new test for funtionality which does not exist or is broken, decorate the test or test class with @unittest.skip("https://pulp.plan.io/issue/..."), and the patch which adds or fixes this functionality should remove the skip decorator to re-enable the test.
This has several benefits - it means the PR test runner will always run
the tests for the functionality being added/fixed so long as the
developer has properly re-enabled the test. It should also make the
tests faster by a small degree, and less reliant on external connections.
=> Remove usages of selectors.bug_is_fixed()

pulpcore/pulpcore/app/models/storage.py
https://pulp.plan.io/issues/3878
With integer IDs the PK is not yet assigned (and no longer unique across tables).
=> Fix storage path for published metadata.

pulpcore/pulpcore/app/viewsets/custom_filters.py, pulpcore/pulpcore/app/viewsets/repository.py, pulpcore/pulpcore/app/viewsets/task.py
closes #3825
https://pulp.plan.io/issues/3825
=> Adds description of the date filters format

pulpcore/pulpcore/app/openapigenerator.py, pulpcore/pulpcore/app/urls.py
Solution: Create a custom OpenAPI generator that refers to resources by their URI. 
To see the Docs generated with this change, point the browser to http://<pulphostname>:8000/pulp/api/v3/docs/
The JSON schema that can be used to generate bindings can be downloaded at http://localhost:8000/pulp/api/v3/docs/api?format=openapi
=> Problem: OpenAPI schema doesn't use URIs to identify resources

server/test/unit/server/db/model/test_dispatch.py
The test uses a list of various objects as invalid inputs for a Task status. One of the objects is a dict
which mongoengine does not support as a value because it's not hashable. This patch removes the dict from
the list of possible bad inputs.
closes: #3955
https://pulp.plan.io/issues/3955
=> Fixes broken unit test around TaskStatus model

pulpcore/pulpcore/app/serializers/progress.py
Solution: set allow_blank=True in the serializer
closes: #3964
https://pulp.plan.io/issues/3964
=> Problem: suffix field is required in the serializer, but can be ''

pulpcore/pulpcore/app/viewsets/content.py
Solution: provide a custom view inspector for ArtifactViewset
The custom inspector generates responses for multipart form uploads. As a result
the generated OpenAPI 2.0 schema has responses for Artifact GET and POST.
closes: #3962
https://pulp.plan.io/issues/3962
=> Problem: drf_yasg does not generate a response schema for Artifact

plugin/pulpcore/plugin/stages/declarative_version.py, pulpcore/pulpcore/app/serializers/repository.py
re # 3494
https://pulp.plan.io/issues/3494
closes #3944
https://pulp.plan.io/issues/3944
=> Adds doc string and validation for mirror parameter

docs/integration-guide/rest-api/authentication.rst
It's good to provide a snippet because everyone won't have to look it
up, and then users won't be inclined to put their password into
https://www.base64encode.org/
=> Small usability improvement in docs

pulpcore/pulpcore/app/serializers/task.py
Solution: remove the non-existing fields from the serializer
closes: #3965
https://pulp.plan.io/issues/3965
=> Problem: OpenAPI schema for created resource contains fields

pulpcore/pulpcore/app/serializers/__init__.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/viewsets/repository.py
Solution: Create separate serializers for 'create' operation
The problem was that we had a single serializer for both GET and POST. DRF was able to
distinguish which fields were to be used for accepting POST body params and which fields to 
use when serializing for a GET response. DRF knows this because some fields are 'write_only'.
However, the drf_yasg library we use for generating OpenAPI schema does not take into account
the 'write_only' attribute of a field. As a result when it was using the serializer to
generate a schema for the GET response it was including the 'write_only' fields.
This patch introduces a new serializer that is only used for the 'create' operation of the
RepositoryVersion ViewSet. This serializer is only used to inspect the inbound data in the POST
body. It is not …
=> Problem: OpenAPI schema for RepositoryVersion 'retrieve' is wrong

docs/plugins/plugin-api/stages.rst, plugin/pulpcore/plugin/stages/content_unit_stages.py
Adds pre_save() and post_save() handlers to ContentUnitSaver that plugin
writers can override on subclasses.
https://pulp.plan.io/issues/3953
closes #3953
=> Add better support for related model saving

pulpcore/pulpcore/app/viewsets/content.py
Solution: remove ArtifactSchema object and use SwaggerAutoSchema
A recent change in drf-yasg fixed a bug that this code was working around.
https://github.com/axnsan12/drf-yasg/commit/41b1ca44837abbac992d963c39b9b215a14390aa
=> Problem: ArtifactSchema is exactly the same as SwaggerAutoSchema

.travis/check_commit.sh, .travis/script.sh, .travis/validate_commit_message.py, docs/contributing/git.rst
Created a script to validate commit messages. This first pass checks for issues in the commit message and makes sure they're in the correct state.
fixes #3930
https://pulp.plan.io/issues/3930
=> Have Travis validate commit messages

docs/conf.py, pulpcore/tests/functional/api/using_plugin/constants.py, pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py, pulpcore/tests/functional/api/using_plugin/test_pagination.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py, pulpcore/tests/functional/api/using_plugin/test_tasking.py, pulpcore/tests/functional/api/using_plugin/utils.py
re #4000
https://pulp.plan.io/issues/4000
fixes #4005
https://pulp.plan.io/issues/4005
=> Fixing tests after pulp_file change and sphinx options

plugin/pulpcore/plugin/stages/artifact_stages.py
There is no need to continue searching for Artifacts, once we have found a
matching digest. The first match should be as good as the last one.
=> Break loop if artifact found by digest

CODE_OF_CONDUCT.md, CONTRIBUTING.md, pull_request_template.md
Github community standards expect a Code of Conduct, Contributing
guidelines, and a pull request template which have now been added.
fixes #3599
https://pulp.plan.io/issues/3599
=> Adhering to Github Community Standards

.travis/validate_commit_message.py, docs/contributing/git.rst
Editing commit messages in vim causes lines starting with # to be
ignored so #noissue was not a good choice as a keyword. Use [noissue]
instead.
=> Changing the syntax for no-issue commits to [noissue]

server/pulp/server/util.py, server/test/unit/server/test_util.py
This fixes the error:
PLP1005: The checksum type 'sha512' is unknown.
reported also in https://github.com/NVIDIA/nvidia-docker/issues/811
=> Add support for sha512

.travis.yml, .travis/publish_docs.sh
The Travis config for the various stages of testing and deployment has been updated. This change
should fix the nightly doc building and publishing to docs.pulpproject.org.
re: #3963
https://pulp.plan.io/issues/3963
=> Fix nightly docs

pulpcore/pulpcore/app/settings.py, pulpcore/pulpcore/app/templates/rest_framework/api.html, pulpcore/pulpcore/app/templatetags/pulp_urls.py
Solution: add a filter that makes links out of href
This patch adds a copy of the rest_framework api template to this repository. This was necesary in order to use
the new custom "urlize_quoted_links" filter. The filter turns any string that starts with '/pulp/api/v3' into a
anchor tag with that value.
closes #3987
https://pulp.plan.io/issues/3987
=> Problem: href values in browsable API are not clickable

pulpcore/tests/functional/api/using_plugin/constants.py, pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py, pulpcore/tests/functional/api/using_plugin/test_pagination.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py, pulpcore/tests/functional/api/using_plugin/test_tasking.py, pulpcore/tests/functional/api/using_plugin/utils.py
This reverts commit 23f9b5f5e71850973d3b0f57adc0101c4aaabbb5.
ref #4017
https://pulp.plan.io/issues/4017
here:
fix them and update your pull …
=> Update tests after manifest field removed from remotes

server/pulp/server/managers/repo/unit_association.py, server/test/unit/server/managers/repo/test_unit_association.py
To avoid mistake sin counting removed units, especially in the cases
when there are dependant units which are removed as well.
re #3985
https://pulp.plan.io/issues/3985
=> Rebuild content unit counts after unassociating units from a repo.

plugin/pulpcore/plugin/stages/artifact_stages.py, pulpcore/pulpcore/app/models/fields.py
Solution: Add a check to see if the source file is already in artifact storage
Prior to this patch it was possible to break an existing artifact by passing a path to it's file
as the file for a new Artifact.
This patch also removes extraneous code in the ArtifactSaver stage. The code was present because
an assumption was made that bulk_save() on Artifacts would not call the presave handler on the
ArtifactFileField. However, this is not the case and the pre_save handler is getting called.
closes: #3915
https://pulp.plan.io/issues/3915
=> Problem: ArtifactFileField can delete an existing artifact's file

pulpcore/pulpcore/app/serializers/task.py, pulpcore/pulpcore/tasking/tasks.py
The enqueue_with_reservation method needs to be task-aware such that it
saves the `parent` FK relationship when a task is being dispatched
within a task.
https://pulp.plan.io/issues/4032
closes #4032
=> Fixes spawned_tasks and parent

pulpcore/pulpcore/app/models/publication.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/app/views/content.py
https://pulp.plan.io/issues/4020
Adds support for pass-through publications.  
Publishers would still use the `Publication` _context_ and may (optionally) set pass-through=True. In combination with this, the publisher can (optionally) add `PublishedMeta` and possibly `PublishedArtifacts` to customize how the publication is composed.
I still need to run EXMPLAIN to see what django has translated the content-artifact query to be sure it's efficient and using the indexes.
I'm not sure where/how to update the docs.  I'm inclined to capture pass-through in planned more comprehensive docs rewrite stores.
=> Add support for pass-through publications.

plugin/pulpcore/plugin/stages/artifact_stages.py, plugin/tests/unit/stages/test_artifactdownloader.py
The ArtifactDownloader had two locations where it could block: dequeue from
the upstream stage queue and waiting for downloads to finish.
When downloads were ongoing, no new work could be accepted (even when below
the limit of concurrent downloads).
Fix this by waiting on both upstream content units and downloads at the same
time.  Additionally, refactor the huge method into a "run" class with state.
This allows to split up the functionality into smaller methods without
passing a large set of parameters around.
Restructure the tasks: Tasks are handling one content instance in the form
of a single coroutine now.  The coroutine computes the artifacts to
download, downloads them and updates the content instance.  The overall limit
on the number of concurrent downloads is restricted by a …
=> Implement single blocking asyncio.wait for ArtifactDownloader

docs/conf.py
=> Fix parameter name for autodoc defaults in Sphinx < 1.8

doc_requirements.txt
Related to this commit also:
https://github.com/pulp/pulp/commit/6dde2e11fee849822554c1c8dbb9fb221f3588d0
[noissue]
=> Pin version of sphinx to 1.7.9 while 1.8 has a bug

pulpcore/pulpcore/app/response.py, pulpcore/tests/functional/api/test_tasks.py
Required PR: PulpQE/pulp-smash#1137
closes #3978
https://pulp.plan.io/issues/3978
=> Reduction of information in response to operation postponed

pulpcore/pulpcore/app/models/publication.py
Set `publisher` field at `Publication` model nullable.
fixes #4038
=> Make publisher for publications optional

pulpcore/tests/functional/api/using_plugin/constants.py, pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
Add tests to verify that `base_version` can be used to create another
repository version. Using the same repository, and a different one.
Besides that, add a test to assure that an HTTP exception is raised when using
a non-exitent `base_version`.
closes: #4035
https://pulp.plan.io/issues/4035
=> Add tests for base_version and repository versions

plugin/pulpcore/plugin/models/__init__.py, pulpcore/pulpcore/app/models/__init__.py, pulpcore/pulpcore/app/models/publication.py
Solution: Add a BaseDistribution for plugin writers to use
This patch adds an abstract BaseDistribution model to the plugin api.
re: 3991
https://pulp.plan.io/issues/3991
=> Problem: Distribution is not available as an abstract model

pulpcore/pulpcore/app/wsgi.py
In development, wsgi is always launched using the manage.py, so the dynaconf imports there are fine. For non-development environments, wsgi might run by a systemd unit file directly.
=> Move imports so wsgi uses dynaconf settings

pulpcore/tests/functional/api/test_crud_distributions.py, pulpcore/tests/functional/api/test_crud_repos.py, pulpcore/tests/functional/api/test_crud_users.py, pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
Add test to assert that error should be raised when passing invalid extraneous parameters to CRUD APIs.
closes PulpQE/pulp-smash#1085
[noissue]
=> Add test to assert that error should be raised when passing invalid parameters to CRUD API

pulpcore/tests/functional/api/test_crud_distributions.py, pulpcore/tests/functional/api/test_crud_repos.py, pulpcore/tests/functional/api/test_crud_users.py, pulpcore/tests/functional/api/test_tasks.py, pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
Tests to ensure specified fields as in `endpoint?fields=id,other,another` are strictly returned from the APIs
closes PulpQE/pulp-smash#1124
[noissue]
=> Add test to ensure specific fields are returned from API

plugin/pulpcore/plugin/download/factory.py, plugin/pulpcore/plugin/stages/artifact_stages.py, plugin/tests/unit/stages/test_artifactdownloader.py, pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/serializers/repository.py
Use aiohttp's `limit` option to limit a total number of TCP connections,
instead of using `asyncio.Semaphore` directly.
closes #4040
https://pulp.plan.io/issues/4040
=> Add connection_limit to a Remote

pulpcore/tests/functional/api/test_crud_repos.py, pulpcore/tests/functional/api/test_crud_users.py, pulpcore/tests/functional/api/utils.py
Add a test to verify messages when attempting to create a user with a long
`username` and `username` with invalid characters.
Besides that, refactor the test for create repos with the same name.
See: https://github.com/PulpQE/pulp-smash/issues/882
'[noissue]'
=> Add tests for creating resources using invalid data 

pulpcore/pulpcore/app/serializers/task.py
Solution: strongly type created resources as an array of strings
This patch changes the CreatedResource serializer to inherit from the RelatedField serializer. This lets the
OpenAPI schema generator know that created resources are URI strings.
closes: #4053
https://pulp.plan.io/issues/4053
=> Problem: created resources OpenAPI schema is not specific enough

pulpcore/tests/functional/api/test_crd_artifacts.py, pulpcore/tests/functional/api/using_plugin/test_orphans.py
Update the use of sudo for cli client. Use new idiom added to Pulp-Smash.
See: https://github.com/PulpQE/pulp-smash/pull/1134
'[noissue]'
=> Update the use of sudo for cli client

plugin/pulpcore/plugin/download/file.py, plugin/pulpcore/plugin/download/http.py, plugin/pulpcore/plugin/stages/artifact_stages.py, plugin/tests/unit/stages/test_artifactdownloader.py
Note: I'm not sure what the intended use of
DeclarativeArtifact.extra_data, so I am not sure if this goes outside
the intended scope.
Use Case: During Docker sync, certain requests need specific headers
that are not shared with the entire session. Since Artifact downloads
happen in pulpcore rather than the plugin, there is no way to pass extra
arguments to downloader.run(). I suspect that this problem would exist
for any plugin that needs specially formed request to download Artifacts.
This pattern would allow Artifact downloaders to:
1. Add arbitrary headers to certain requests (like Docker V1 vs V2
artifact downloads)
2. Add arbitrary query parameters
3. dynamically set http verbs
1 is my use case, though 2 and 3 are hypothetical.
[noissue]
=> Pass DeclarativeArtifact.extra_data to downloader

docs/plugins/plugin-api/download.rst, plugin/pulpcore/plugin/download/__init__.py, plugin/pulpcore/plugin/download/base.py, plugin/pulpcore/plugin/serializers.py, pulpcore/pulpcore/app/models/content.py, pulpcore/pulpcore/exceptions/__init__.py, pulpcore/pulpcore/exceptions/validation.py
Adds the Artifact.create_and_validate staticmethod that creates an
in-memory, unsaved Artifact from a PulpTemporaryUploadedFile. Uploaded
files to Pulp show up with that type so that is convenient for plugin
writers. Also as the file is received by Django it auto-computes all of
the digest types.
This PR also moves SizeValidationError and DigestValidation error to
pulpcore.exceptions instead of living in pulpcore.plugin.downloads.
The ArtifactSerializer is also exposed via the plugin API with this
change also.
https://pulp.plan.io/issues/4072
closes #4072
=> Make an Artifact from a PulpTemporaryUploadedFile

docs/overview/components/webserver.rst
fixes #3866
https://pulp.plan.io/issues/3866
=> Documenting how to serve http and https content

server/etc/pulp/server.conf, server/pulp/server/config.py, server/test/unit/server/content/web/test_views.py
this allows to use the host from the incoming request for the redirect
closes #4092
=> default redirect_host to None

pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
Update assertions for base_version. Sort items per `_href` before any
assertion.
'[noissue]'
=> Update assertions for base_version test

pulpcore/pulpcore/app/management/commands/reset-admin-password.py, pulpcore/pulpcore/app/serializers/user.py, pulpcore/pulpcore/app/viewsets/user.py
In case of custom user model used, PasswordSerializer fails
because it relies on builtin into Django user model.
This patch add dynamic user model resolving.
closes #4077
=> Fix user serializer for custom user model

docs/plugins/plugin-api/download.rst, plugin/pulpcore/plugin/download/http.py
The close() method is a coroutine so it needs to be awaited but it was
not. This was discovered during some testing of the HttpDownloader I was
doing outside of Pulp.
It also fixes some of the examples which used the wrong class name and
an await example that would have errored if run.
[noissue]
=> Close HttpDownloader connections properly

pulpcore/tests/functional/api/test_workers.py
closes PulpQE/pulp-smash#877
> Pulp3 to not show offline workers in the status endpoint
> Filter offline workers in workers endpoint
Requires: https://github.com/PulpQE/pulp-smash/pull/1146
[noissue]
=> Add tests for Offline workers in status and worker APIs

plugin/pulpcore/plugin/download/base.py, plugin/pulpcore/plugin/download/factory.py, plugin/pulpcore/plugin/download/file.py, plugin/pulpcore/plugin/download/http.py, pulpcore/pulpcore/app/models/repository.py
Use force_close and concurrency restriction
The use of force_close was inspired by:
https://github.com/aio-libs/aiohttp/issues/2867#issuecomment-375278533
- Causes Factory and Downloaders to use force_close which causes the TCP
connection to close with each request.
- Ups the default concurrency to 20
- Moves the concurrency restriction feature to the Downloaders and
updates HttpDownloader and FileDownloader to use it.
- Stops using aiohttp for concurrency restriction because it's done in
the downloaders.
- The Factory now configures the concurrency restriction using the value
on the remote.
- creates a _run() method that subclassed Downloaders now need to
implement instead of run().
https://pulp.plan.io/issues/4036
https://pulp.plan.io/issues/4075
closes #4036
closes #4075
=> Use force_close and concurrency restriction

plugin/pulpcore/plugin/download/base.py, plugin/pulpcore/plugin/download/file.py, plugin/pulpcore/plugin/download/http.py
Solution: Add response header to the DownloadResult
The HttpDownloader now adds the response headers to the DownloadResult.
closes #4061
https://pulp.plan.io/issues/4061
=> Problem: DownloadResult is missing response headers

plugin/pulpcore/plugin/download/factory.py
https://pulp.plan.io/issues/4062
Corrected passing the certificate and key arguments when building the ssl_context.
The `Remote.ssl_validation` documentation indicates that it controls whether or not the sever (peer) certificate is verified by the downloader.  Discovered this was not implemented correctly in the factory during testing and corrected.
=> Fix SSL error and correct handling of Remote.ssl_validation.

docs/installation/configuration.rst
Point to correct django settings secret key docs
Link in docs was broken.
=> Fix Incorrect Django Documentation Link

server/pulp/server/controllers/repository.py
A change was made in #4092 to allow users to use the server request
hostname as the redirect_host for on-demand repos by leaving host in the
lazy config as blank. However, the defered_download code doesn't have a
server request and therefore should default to socket.getfqdn() if
redirect_host is unset.
fixes #4120
https://pulp.plan.io/issues/4120
=> Fixing missing hostname for deferred downloads

docs/installation/instructions.rst
Added ansible installer link to
pulp 3 docs.
closes #4098
https://pulp.plan.io/issues/4098
=> Ansible installer link to docs

pulpcore/setup.py
This is due to a new redis version being available and RQ not being
compatible with it. RQ has not yet released a fix so Travis is broken.
Once https://github.com/rq/rq/pull/1015/files is merged we can stop
carrying this.
[noissue]
=> Temporarily limit redis version

plugin/pulpcore/plugin/download/base.py
Plugin writers should override `_run`, not `run`.
[noissue]
=> NotImplemented str change

plugin/pulpcore/plugin/download/__init__.py
This is necessary for plugins that define their own Downloader.
[noissue]
=> Add http_giveup to Plugin API

plugin/pulpcore/plugin/download/base.py
This is necessary if the overrides of this function have other kwargs
that need to be passed.
[noissue]
=> Pass extra_data as kwarg

plugin/pulpcore/plugin/stages/content_unit_stages.py
I'm pretty sure this is probably not the right fix. @gmbnomis or @bmbouter, hoping you can suggest what to do.
fixes #4165
https://pulp.plan.io/issues/4165
=> Filtering the batch based on model type

pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py, pulpcore/tests/functional/api/using_plugin/test_crd_publications.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py, pulpcore/tests/functional/api/using_plugin/test_unlinking_repo.py, pulpcore/tests/functional/api/using_plugin/utils.py
The function `gen_file_publisher` is useless so removing it in favor of `gen_publisher` which does the same.
[noissue]
=> Removing gen_file_publisher

plugin/pulpcore/plugin/stages/artifact_stages.py, plugin/pulpcore/plugin/stages/content_unit_stages.py
Solution: Update Declarative Artifacts with Artifacts returned by bulk_get_or_create()
[noissue]
=> Problem: Artifact Saver fails to associate existing Artifacts

plugin/pulpcore/plugin/stages/content_unit_stages.py, pulpcore/pulpcore/app/models/content.py
Solution: fix the content unit saver stage
This patch addresses 2 problems:
1) Error because an exception was being caught during a transaction
2) The q() method did not provide the correct query for Content objects
closes #4170
https://pulp.plan.io/issues/4170
=> Problem: duplicate content can't by synced

pulpcore/tests/functional/api/using_plugin/test_content_promotion.py
Do the following:
1. Create a repository that has at least one repository version.
2. Create a publisher, and publication.
3. Create 2 distributions - using the same publication. Those
distributions will have different ``base_path``.
4. Assert that distributions have the same publication.
5. Select a content unit. Download that content unit from Pulp using
the two different distributions.
Assert that content unit has the same checksum when fetched from
different distributions.
closes#4186
https://pulp.plan.io/issues/4186
=> Add test to content promotion

pulpcore/pulpcore/app/models/content.py
A failed bulk_create might have already iterated into the generator for
desired objects. This can be prevented by casting into a list first.
[noissue]
=> Prevent failing bulk_create to consume objects from generator

docs/installation/configuration.rst
I don't believe python will complain about this but it doesn't look right. I tried searching different python standards and couldn't find anything about semicolons. So I am taking it out.
[noissue]
=> Docs: Remove Semicolon From Secret Example

docs/plugins/plugin-api/download.rst, plugin/pulpcore/plugin/download/base.py, plugin/pulpcore/plugin/download/file.py, plugin/pulpcore/plugin/download/http.py, plugin/pulpcore/plugin/models/remote.py, plugin/pulpcore/plugin/stages/artifact_stages.py, plugin/pulpcore/plugin/stages/declarative_version.py, pulpcore/pulpcore/app/models/repository.py, pulpcore/pulpcore/app/serializers/repository.py, pulpcore/pulpcore/constants.py
Required PR: https://github.com/pulp/pulp_file/pull/132
This includes a serializer that validates input correctly.
https://pulp.plan.io/issues/3763
closes #3763
=> Adds 'policy' to Remote

server/pulp/server/db/migrations/0029_applicability_schema_change.py
Not all MongoDB versions report a specific code when index is not found.
closes #4225
https://pulp.plan.io/issues/4225
=> Don't fail migration in case there is no exception code

setup.py
We're requiring rq >= 0.12 and redis < 3.0 but the new release of rq (0.13.0) requires redis >= 3.0 so our package requirements raise a conflict. I suggest we unpin the redis requirement and let pip install the right version of redis based on what rq needs.
=> Unpin the redis requirement

pulpcore/app/models/repository.py, pulpcore/app/serializers/__init__.py, pulpcore/app/serializers/base.py, pulpcore/app/serializers/repository.py, pulpcore/app/serializers/task.py, pulpcore/app/util.py, pulpcore/app/viewsets/__init__.py, pulpcore/app/viewsets/content.py, pulpcore/app/viewsets/custom_filters.py, pulpcore/app/viewsets/repository.py, pulpcore/tasking/util.py, pulpcore/tests/functional/api/using_plugin/constants.py, pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py, pulpcore/tests/functional/api/using_plugin/test_content_promotion.py, pulpcore/tests/functional/api/using_plugin/test_orphans.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py, pulpcore/tests/functional/api/using_plugin/test_tasking.py, pulpcore/tests/functional/api/using_plugin/test_unlinking_repo.py, pulpcore/tests/unit/serializers/test_base.py, pulpcore/tests/unit/test_util.py
These are the API changes from the single-table-content work that were discussed.
=> API Changes

pulpcore/app/serializers/repository.py
If the plugin writer doesn't provide a viewset where we can access this
content, there's no way to reverse the URL for it. They can see it in
the content summaries, though.
The Docker and Ansible plugins are currently like this.
[noissue]
=> Skip over url generation for content types without a viewset

pulpcore/content/__init__.py
The 'content' module needs to be auto-imported when the content app
starts so that loading is added to its startup sequence with this PR.
Importing is all we have to do and aiohttp's registration mechanisms
take over.
https://pulp.plan.io/issues/4273
re #4273
=> Adds importing of the 'content' module

pulpcore/app/models/repository.py, pulpcore/app/serializers/repository.py
Rename the 'connection_limit' to 'download_concurrency'
throughout the codebase and comments in the codebase to
variable name to be more understandable.
re: #4114
https://pulp.plan.io/issues/4114
=> Rename connection_limit to download_concurrency

pulpcore/app/models/base.py, pulpcore/tests/functional/api/using_plugin/constants.py
closes #4185
https://pulp.plan.io/issues/4185
Required PR: pulp/pulp_file#150
=> Prepend type for master/detail models with a plugin app label 

pulpcore/app/serializers/repository.py
And also tasks by association, via CreatedResource, which apparently
serializes the RepositoryVersion also.
closes #4283
https://pulp.plan.io/issues/4283
=> Fix bad pause when serializing repository versions

docs/components.rst, docs/installation/instructions.rst, pulpcore/app/settings.py, setup.py
Solution: collect static files before releasing to PyPI
This patch adds the 'whitenoise' middleware that serves static content for Pulp. 'whitenoise' is configured
to serve static content found in pulpcore/app/static directory. This means that after installing pulp, the user
will need to run the 'pulp-manager collectstatic' command to get all the static content into the directory.
closes #4180
https://pulp.plan.io/issues/4180
=> Problem: static files are not available on user installs

docs/contributing/dev-setup/index.rst
Instructs the developer to setup their environment with Pulplift
re #4234
https://pulp.plan.io/issues/4234
=> Updating Developer Setup Guide to use Pulplift

pulpcore/app/viewsets/user.py, pulpcore/tests/functional/api/test_crud_users.py
One admin user will exist until the full support for user
management is added
closes #4313
https://pulp.plan.io/issues/4313
=> Disallow user creation/update

pulpcore/app/settings.py
When running the whitenoise command it was writing to the python path
which it should not be able to do.
https://pulp.plan.io/issues/4180
closes #4180
=> Whitenoise should not write to python dir

docs/Makefile, docs/concepts.rst, docs/diagrams_src/concept-add-repo.dot, docs/diagrams_src/concept-content.dot, docs/diagrams_src/concept-publish.dot, docs/diagrams_src/concept-remote.dot, docs/diagrams_src/concept-repository.dot
Diagrams that illustrates all
of the concepts on the Concepts and Terminology page.
closes: #4100
https://pulp.plan.io/issues/4100
=> Add diagrams to Concepts and Terminology

.travis/docs-builder.py, doc_requirements.txt
To diagrams to be shown we need to call
'make diagrams' too.
closes: #4100
https://pulp.plan.io/issues/4100
=> Make diagrams via doc builder script

pulpcore/content/handler.py
The Content app would raise an exception if there were multiple
RemoteArtifacts. It also would not try additional ones if the first ones
failed.
https://pulp.plan.io/issues/2507
closes #2507
=> Content app tries all RemoteArtifacts

pulpcore/tasking/tasks.py, pulpcore/tests/functional/api/using_plugin/test_crd_publications.py, pulpcore/tests/functional/api/using_plugin/test_pagination.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py, pulpcore/tests/functional/api/using_plugin/test_tasking.py, pulpcore/tests/functional/api/using_plugin/test_unlinking_repo.py
The enqueue_with_reservation is included in the pulpcore-plugin package
and its docstring in the docs. When building the pulpcore-plugin docs it
complains saying:
docstring of pulpcore.plugin.tasking.enqueue_with_reservation
:19:Unexpected indentation.
[noissue]
=> Fix indention that Shinx complains about

pulpcore/tasking/tasks.py
[noissue]
Problem:
`Warning, treated as error:
/home/vagrant/devel/pulpcore-plugin/pulpcore/plugin/tasking.py:docstring of pulpcore.plugin.tasking.enqueue_with_reservation:19:Unexpected indentation.
make: *** [Makefile:53: html] Error 2
For some reason, I couldn't build the docs for https://github.com/pulp/pulpcore-plugin/pull/37 without this patch.
`
=> Indent docstring for building docs

pulpcore/app/serializers/__init__.py, pulpcore/app/serializers/content.py, pulpcore/app/serializers/fields.py, pulpcore/app/viewsets/content.py, pulpcore/tests/functional/api/using_plugin/test_orphans.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py, pulpcore/tests/unit/content/test_handler.py
Remove boilerplate from the plugins. Plugins must define a
"multiple_artifacts_per_content" attribute on their Serializer subclass
Meta class, and core will look at that to decide which to use.
re: 4340
https://pulp.plan.io/issues/4340
=> Let core decide whether to use "_artifact" or "_artifacts"

.travis/before_script.sh, docs/contributing/dev-setup/index.rst, pulpcore/app/viewsets/base.py, pulpcore/tests/functional/api/using_plugin/constants.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
closes #4279
https://pulp.plan.io/issues/4279
=> Namespace plugin endpoints with Django app label

docs/contributing/dev-setup/index.rst
In order to avoid duplicated (and partially outdated) documentation, the
details of how to utilize pulplift should be written down at pulplift
and only referenced elsewhere.
[noissue]
=> Defer the setup instructions for pulplift

pulpcore/tests/unit/content/test_handler.py
closes #4355
https://pulp.plan.io/issues/4355
=> Remove pulp_file dependency from unit tests

docs/installation/instructions.rst
Both PyPI and source ones.
closes #4356
https://pulp.plan.io/issues/4356
=> Update installation instructions

pulpcore/tests/functional/api/using_plugin/test_pagination.py
Make the `test_content` from pagination test case synchronous. Thus
avoiding occasional test failures. Test will be a bit slower, but
less error prone. Later on, if necessary an alternative can
be evaluated.
'[noissue]'
=> Remove threading from pagination test_content

pulpcore/tests/functional/api/using_plugin/utils.py
Modify `response_handler` used by populate_pulp to be `page_handler`.
For Pulp 3 `page_handler` should be the prefered one.
See: https://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.api.html?highlight=page_handler#pulp_smash.api.page_handler
'[noissue]'
=> Modify response_handler for populate_pulp function

pulpcore/app/serializers/publication.py
This hides the pass_through option when serializing Publications.
re #4421
https://pulp.plan.io/issues/4421
=> Mark pass_through write_only on Serializer

pulpcore/app/urls.py
fixes #4323
https://pulp.plan.io/issues/4323
This fixes the problem by dropping the requirement for an authed user. However, there's also [an unreleased fix in DRF](https://github.com/encode/django-rest-framework/pull/6429) that solves the 500 issue.
=> Fix 500 error when accessing /pulp/api/v3/ as unauthed user

setup.py
=> Pins redis client to version less than 3.2.0

pulpcore/tests/functional/api/test_auth.py
User endpoints will be removed. Adjust test to use another endpoint
that requires auth to be accessed.
https://pulp.plan.io/issues/4398
ref: #4398
=> Modify endpoint used by AuthTestCase

pulpcore/tests/functional/api/using_plugin/test_pagination.py
Make pagination sync to avoid threding problems as for now
timing is not an issue for this test case.
The asyncIO version is only twice fast as sync.
https://github.com/pulp/pulp/pull/3887
[noissue]
=> Remove Threads from pagination test case

pulpcore/tests/functional/api/using_plugin/test_content_path.py
Add test to verify how pulp handles sync/publish of content already on
filesystem and database.
https://pulp.plan.io/issues/4442
closes: #4442
=> Add test to verify sync/publish content already in pulp

pulpcore/tests/functional/api/test_workers.py
The PR https://github.com/pulp/pulp/pull/3882 changed worker
unit names to use hyphens so test worker needs this update.
[noissue]
=> Use hyphen on test worker

pulpcore/app/openapigenerator.py
Solution: update the schema generator to account for _id introduced as part of https://pulp.plan.io/issues/4206
closes: #4447
https://pulp.plan.io/issues/4447
=> Problem: wrong OpenAPI schema of repo version list, create APIs
